### ISSUE TITLE
Cannot publish Post Purchase extension through Shopify CLI

### ISSUE THREAD

**Issue by I-K-devit** [Shopify/shopify-cli#1033]
# Issue summary

I have a Shopify CLI installed on Ubuntu, and when i create Checkout Post Purchase extension, register and pushing it to the app it's generates broken link

## Expected behavior

After running 'shopify push' it must give a working link (manage_extensions/post_purchase/2141947) where you publish your extension

## Actual behavior

After running 'shopify push' it gives a broken link (extensions/post_purchase/2141947):

Command line:

![image](https://user-images.githubusercontent.com/74594096/104750356-a6160200-575c-11eb-982e-f8e29bfca2fb.png)

Page view:

![image](https://user-images.githubusercontent.com/74594096/104747783-95b05800-5759-11eb-8912-6a212843067f.png)

Also want to mention that if you type manage_extensions it will redirect you to 'temporarily unavailable' page:

![image](https://user-images.githubusercontent.com/74594096/104747886-b9739e00-5759-11eb-9807-7a7a3c4f956f.png)

## Steps to reproduce the problem

You can try it by running this commands:

> shopify create extension
// select 'Checkout Post Purchase'
> cd my-cool-checkout-extension
> shopify register
// authenticate yourself
// selected one of your dev apps
> shopify push

Then your extension link will be generated

## Specifications

- App type: Public
- Operating System: Ubuntu 20.04.1 LTS
- Shell: Terminal

**Comment by thecodepixi** [comment]
Hey 👋🏻  This issue appears to be stale/outdated, so I'm going to go ahead and close it. However, if you're still experiencing issues/errors with the CLI, feel free to open another issue.
