### ISSUE TITLE
[Proposal] Replace ngrok tunnel with CloudFlare

### ISSUE THREAD

**Issue by paulomarg** [Shopify/shopify-cli#1070]
It's been pointed out [in this post](https://blog.abuiles.com/blog/2021/02/07/speeding-up-your-shopify-app-development-workflow/) that [CloudFlare](https://developers.cloudflare.com/argo-tunnel/) might be a better alternative to ngrok for creating tunnels as it is allegedly quicker and allows custom domain names for free accounts, which has been requested before.

We should investigate whether it is indeed a safe / better alternative.

**Comment by wnm** [comment]
I just followed this tutorial: https://developers.cloudflare.com/cloudflare-one/tutorials/share-new-site

It was pretty straight forward, and in a couple of minutes I was able to setup a custom subdomain to my domain to tunnel traffic to my local server (over https as well).

So far, everything works just as well as ngrok... I'm not sure if its quicker, but yes, a permenant url for free is quite nice for Shopify app development!

Not sure about the security aspects of it. I initially thought I would expose a dns record to the public and expose my local server to it, but so far it hasn't shown up via `nslookup`... I'm not sure if Cloudflare is somehow able to hide argo tunnel dns entries?

**Comment by wnm** [comment]
I came here through Google. Any reason this issue isn't opened over at [Shopify/shopify_app](https://github.com/Shopify/shopify_app)

**Comment by paulomarg** [comment]
Hey @wnm, thank you for sharing your thoughts, they're very helpful!

The `shopify_app` already gem works with either of the tunnel options, so no gem changes would be required to replace ngrok there. The CLI, however, handles creating tunnels automatically, which is why it would take some code changes for it to start using CloudFlare.

**Comment by mysticaltech** [comment]
I regret seeing this only today as I just paid $10 to ngrok to grab their premium version as I was tired of having to change the URL everywhere every time I wanted to start coding. Definitely will switch ASAP! Great idea.

**Comment by shotor** [comment]
It would be nice to disable ngrok. For instance if the HOST env variable hostname isn't ngrok.com. Or with an extra env variable: NGROK_DISABLE?

Now I introduced an extra env variable to set in `Shopify.Context.initialize`. But shopify cli keeps asking me to update the app url every time I start it up.

**Comment by towfiqi** [comment]
Why not replace it with localtunnel? It lets you use custom subdomains and doesn't have the annoying time limit like ngrok.

**Comment by wnm** [comment]
Is it possible to setup ssl with localtunnel?

**Comment by towfiqi** [comment]
@wnm Actually I just tried the cloudflare tunnel with my own subdomain and its way faster than localtunnel and ngrok. So I think cloudflare OPs proposal makes sense.

**Comment by towfiqi** [comment]
@wnm And to answer your question, All the created localtunnel routes already are https, so no setup needed.
