### ISSUE TITLE
shopify serve on installed rails app throws error '`require': cannot load such file -- nokogiri/nokogiri (LoadError)'

### ISSUE THREAD

**Issue by michi-z** [Shopify/shopify-cli#1081]
# Issue summary

When i install the rails app with the 
shopify-app-cli the serve command fails.

## Expected behavior

When i run the serve command there should be no errors

## Actual behavior

Error:

```
.gem/ruby/2.6.3/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
┃ 	from /Volumes/User-Data/michiz/.gem/ruby/2.6.3/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
```

only the first two lines

## Steps to reproduce the problem

1. create rails app with `shopify create`
2. run `shopify serve`
3. get error

## Specifications

- App type: Rails
- Operating System: Macosx 10.15.7
- Shell: zsh
- Ruby version (ruby -v): 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19

**Comment by andyw8** [comment]
@michi-z which version of Rails ?

**Comment by michi-z** [comment]
in the gem.lock file 'nokogiri' ist listed.

**Comment by michi-z** [comment]
I @andyw8 i created the app again and seen that the error is already in the install:

```
┃ Bundle complete! 16 Gemfile dependencies, 74 gems now installed.
┃ Use `bundle info [gemname]` to see where a bundled gem is installed.
┃          run  bundle binstubs bundler
┃        rails  webpacker:install
┃ rails aborted!
┃ LoadError: cannot load such file -- nokogiri/nokogiri
```

**Comment by mkevinosullivan** [comment]
@michi-z can you run `shopify system` from inside your app directory and post the results here, please?

**Comment by michi-z** [comment]
@mkevinosullivan Here

`Shopify App CLI
               ROOT = /usr/local/Cellar/shopify-cli/1.5.0/src

Ruby (via RbConfig)
  /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
  x86_64-apple-darwin14.5.0 - RbConfig["host"]
  ruby-2.6.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar

In a Rails project directory
  ✓ gem, /usr/bin/gem, version 3.0.3
This command ran with ID: 83955
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	26: from /usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify:32:in `<main>'
	25: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	24: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	23: from /usr/local/Cellar/shopify-cli/1.5.0/src/bin/shopify:33:in `block in <main>'
	22: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/entry_point.rb:42:in `call'
	21: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/monorail.rb:20:in `log'
	20: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	19: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/core/executor.rb:15:in `call'
	18: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	17: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	16: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	15: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	14: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	13: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	12: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	11: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	10: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
	 9: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	 8: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 7: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	 6: from /usr/local/Cellar/shopify-cli/1.5.0/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	 5: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/command.rb:25:in `call'
	 4: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/system.rb:25:in `call'
	 3: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/system.rb:100:in `display_project_commands'
	 2: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/system.rb:106:in `display_project'
	 1: from /usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/system.rb:106:in `each'
/usr/local/Cellar/shopify-cli/1.5.0/src/lib/shopify-cli/commands/system.rb:110:in `block in display_project': undefined method `[]' for nil:NilClass (NoMethodError)`

**Comment by thecodepixi** [comment]
This issue seems to be stale, as there hasn't been any discussion here for a bit, so I'm going to go ahead and close this for now. If the issue persists after trying Kevin's proposed solution above, please feel free to open a new issue and we'll be happy to help!

**Comment by t-kelly** [comment]
Encountering this as well when running `shopify rails create` -- tried deleting the `arm64` of nokogiri and it resulted in a `'require': cannot load such file -- nokogiri` error

**Comment by r34ctor** [comment]
I have tried removing the `arm64` directory, but that did not solve the issue. 
I also thought that since I had an existing version of the CLI and had upgraded a bunch of times, that may have had unintended side effects, but reinstalling the CLI altogether didn't help either.

**Comment by pepibumur** [comment]
Thanks for the context @r34ctor. For some reason, your system's Ruby is trying to use the `gems` directory of the CLI for Nokogiri, and in the binary, there is an `arm64` binary that is not compatible with your architecture. The question is how we ended up there? Could you share the output of the following commands with me:

- `echo $GEM_HOME`
- `which ruby`
- `ruby -v`

**Comment by pepibumur** [comment]
Based on your logs it seems you are using the system's Ruby version. I recommend using a managed version of Ruby instead due to the issues [documented in this blog post](https://www.freecodecamp.org/news/do-not-use-mac-system-ruby-do-this-instead/). You can use a tool like [chruby](https://github.com/postmodern/chruby) for that. It'll install Ruby in a different directory and allow you to switch it in the future. After installing `chruby`, [install a Ruby version](https://github.com/postmodern/chruby#ruby-install), for example 2.7.2, and choose it to be the default, `chruby ruby-2.7.2`. After that if you do `which ruby`, the directory should be `/opt/rubies/2.7.2/bin/ruby` instead. Then try to run `gem install nokogiri`.

**Comment by pepibumur** [comment]
> Based on your logs it seems you are using the system's Ruby version. I recommend using a managed version of Ruby instead due to the issues documented in this blog post. You can use a tool like chruby for that. It'll install Ruby in a different directory and allow you to switch it in the future. After installing chruby, install a Ruby version, for example 2.7.2, and choose it to be the default, chruby ruby-2.7.2. After that if you do which ruby, the directory should be /opt/rubies/2.7.2/bin/ruby instead. Then try to run gem install nokogiri.

My bad. This would be an answer for someone outside of the org. Would you mind cloning the `shopify-cli` repo and running it from there:

```
dev clone shopify-cli
dev up
bin/shopify
```
Let me know if that works.
