### ISSUE TITLE
Can't seem to authenticate to create an app after installing cli

### ISSUE THREAD

**Issue by Matt-Wilson-Dev-Ops** [Shopify/shopify-cli#1116]
# Issue summary

Write a short description of the issue here ↓

Everything seems fine, I installed everything as per the tutorial, ruby, git and the rest, installed the CLI and the API.
I can check and see the version for the cli is 1.6.0, the api is 9.4.0 but after I try to use create and select ruby, add the name and then receive the url, the browser says authentication successful but then I receive an error and have to shopify logout to try again.

Sorry if I have missed anything below I am learning haha

## Expected behavior

I have watched tutorials on youtube and it should be prompting me to select the store right?

## Actual behavior

This command ran with ID: 37872
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        51: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:32:in `<main>'
        50: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        49: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        48: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:33:in `block in <main>'
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/executor.rb:15:in `call'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/commands/create.rb:8:in `call'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/command.rb:25:in `call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/commands/create.rb:25:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/sub_command.rb:12:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/rails/commands/create.rb:27:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/form.rb:13:in `ask'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/rails/forms/create.rb:25:in `ask'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/task.rb:7:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:48:in `query'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:26:in `query'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:69:in `request'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:46:in `block in request'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:96:in `default_headers'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/api.rb:91:in `current_sha'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:24:in `sha'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/git.rb:112:in `exec'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/context.rb:404:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)

## Steps to reproduce the problem

1. 
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: 
- Operating System: Windows 10
- Shell: CMD with ruby
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by andyw8** [comment]
Hi @Matt-Wilson-Dev-Ops,

The final line of the output seems to indicate this is related to your git install. Can you share the output of running `git -v` ?

**Comment by Matt-Wilson-Dev-Ops** [comment]
Hey mate,

I receive:

C:\Users\Lamb>git -v
unknown option: -v
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

if i used git --version:

C:\Users\Lamb>git --version
git version 2.30.2.windows.1

**Comment by Matt-Wilson-Dev-Ops** [comment]
Ok so it must have been something to do with Shopify's authentication last night because it's progressing past all of that now and allowing me to select my database. However once I do I get this error:

Database Type mysql
√ node v14.16.0
√ yarn 1.22.10
\ Installing rails gem...
X System call failed: gem install rails -v <6.1

These are my versions: 
C:\Users\Lamb>gem --version
3.2.14

C:\Users\Lamb>rails --version
Rails 6.1.3

/cry

**Comment by thecodepixi** [comment]
Hey 👋🏻  Since it's been some time since we've had a response from you, I'll be closing this issue as stale. If you are still experiencing problems with the CLI, please feel free to open a new issue!
