### ISSUE TITLE
Cannot use arrow keys in selector when using iTerm in cli version 1.7.0

### ISSUE THREAD

**Issue by henrytao-me** [Shopify/shopify-cli#1128]
# Issue summary

I cannot use arrow keys in selector when using iTerm for both short and long list. Note that: cli version 1.5.0 works fine with iTerm.

https://user-images.githubusercontent.com/5274722/111355371-b152b480-865d-11eb-9c19-0f7c85f59c5c.mov

## Expected behavior

Able to use arrow keys to select different options in the selector.

## Actual behavior

Show `Interrupt` and just cancel the command.

## Steps to reproduce the problem

1. Open iTerm
1. Run `shopify create extension`
1. Follow the flow and try to select an app

## Specifications

- App type: N/A
- Operating System: MacOS
- Shell: `shopify create extension`
- App version (ruby -v): `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`
- Shopify app cli version: 1.7.0

**Comment by andyw8** [comment]
Note from @henrytao-me : Works fine the default Mac terminal app.

**Comment by egenerat** [comment]
I can reproduce the same issue with shopify-cli 2.9.0 and iTerm2 3.4.14.
