### ISSUE TITLE
Add billing generation to Rails

### ISSUE THREAD

**Issue by tylerball** [Shopify/shopify-cli#115]
We need to hook up the Rails project type to the generate billing command. It might be a bit more complicated, I think the standard way to do this would be to generate an [`inline AfterAuthenticateJob`](https://github.com/Shopify/shopify_app#afterauthenticate-job) and insert a call to the Billing API inside the body of that job.

**Comment by derrickrc** [comment]
Any update on this as of September 2020? Thank you.
