### ISSUE TITLE
Why is the code foapollo client setup removed in server/server.js(backend) with latest cli

### ISSUE THREAD

**Issue by tommy921092** [Shopify/shopify-cli#1178]
![Screenshot 2021-04-22 at 6 50 38 PM](https://user-images.githubusercontent.com/41218788/115702526-a21d0000-a39b-11eb-864c-e117b6ce4101.png)
![Screenshot 2021-04-22 at 6 50 55 PM](https://user-images.githubusercontent.com/41218788/115702574-ad702b80-a39b-11eb-80a9-4ac1a634d200.png)

Noticed that the line 
server.context.client = await handlers.createClient(shop, accessToken);
is removed in the file server/server.js for app generated by the cli
but the handlers/clients.js(create apollo) and mutations folder still generated in the cli
so its a bit confusing as the "@shopify/shopify-api" provide admin api client access with Rest/Graphql
Please explain. Thanks!

![Screenshot 2021-04-22 at 7 01 35 PM](https://user-images.githubusercontent.com/41218788/115703844-2a4fd500-a39d-11eb-8099-77b86529c20a.png)

![Screenshot 2021-04-22 at 7 01 03 PM](https://user-images.githubusercontent.com/41218788/115703776-186e3200-a39d-11eb-906a-6384a86dd6c3.png)

**Comment by paulomarg** [comment]
You're right @tommy921092, thank you for pointing this out! These files were overlooked when we migrated over to the new library. We'll look into replacing those calls with the new client, if that code is still being used.
