### ISSUE TITLE
Fetch returns error about "example.com" when trying to develop locally

### ISSUE THREAD

**Issue by johnathanweidman** [Shopify/shopify-cli#1179]
# Issue summary

When working locally with an argo app using the serve command any attempt to fetch from a url that is not exmaple.com results in  an error:

## Expected behavior

I would expect to be able to make fetch calls to develop API calls to my app for the argo extension

## Actual behavior

I get a console error about not being able to fetch anywhere but "example.com"

<details> Error: The URL you're calling is not allowed. Fetch calls can only come from example.com </details>

## Steps to reproduce the problem

1.Start up a local Argo Extension 
2. Make a cors fetch request to the application server it is tied to 

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Node
- Operating System: OSX

**Comment by mkevinosullivan** [comment]
Hi @johnathanweidman, please provide the sequence of commands you use to reproduce?

**Comment by mkevinosullivan** [comment]
👋🏻 As there has not been any update to this issue for over three months, I'm going to close it.  If this continues to be an issue, please open a new issue.
