### ISSUE TITLE
shopify-cli create rails fail with System call failed: rails new --skip-spring --database=sqlite3

### ISSUE THREAD

**Issue by williambsb** [Shopify/shopify-cli#1192]
# Issue summary

Write a short description of the issue here ↓
Working on macOS  Catalina, 10.15.7  and Shopify-Cli 1.8.0  create rails scaffold fails with :
/Users/william/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.0.2.1/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)

My system have ruby 3.0.0 and Rails 6.0.2.1 

Fails are trigged on rails new command :

`create  config/locales/en.yml
┃       create  config/master.key
┃       append  .gitignore
┃ /Users/william/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.0.2.1/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
┃ 	from /Users/william/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.0.2.1/lib/active_support/message_encryptor.rb:175:in `_encrypt'`

The same behavior if I try with Postgresql database 

## Expected behavior

What do you think should happen?

Rails Application created . 

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.just try to create a rails app scaffold  with : shopify create rails 
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).
shopify create rails 

## Specifications

- App type: rails
- Operating System: macOS 
- Shell: zsh 
- Ruby version (ruby -v): 3.0.0

**Comment by mkevinosullivan** [comment]
Hi @williambsb, can you provide the full stack track of the output from `shopify create rails`, please?

**Comment by mkevinosullivan** [comment]
👋🏻 As there has not been any update to this issue for three months, I'm going to close it.  Note that the CLI has been updated quite a bit since this issue was opened, to version `2.1.0`.

If this continues to be a problem, please open a new issue.
