### ISSUE TITLE
Inconsistent use of periods vs ellipses in messages

### ISSUE THREAD

**Issue by tatheerf02** [Shopify/shopify-cli#1194]
# Issue summary

Some messages in the CLI use `...` while others use `…` and this should be consistent throughout.
@gfscott Which should it be?

**Comment by gfscott** [comment]
👍🏻 Let's go with the single-character ellipsis! `…`

**Comment by sharvy** [comment]
@tatheerf02 & @gfscott If anyone is not working on this issue, can I grab it?

**Comment by tatheerf02** [comment]
> If anyone is not working on this issue, can I grab it?

@sharvy I'm not working on it, so I think it should be fine :)
