### ISSUE TITLE
Add "host" parameter to generated ngrok authentication url for compatibility with app-bridge v2

### ISSUE THREAD

**Issue by nicolas-cusan** [Shopify/shopify-cli#1231]
# Issue summary

As of v2.x `@shopify/app-bridge`/`@shopify/app-bridge-react`  [requires a `host` option](https://www.npmjs.com/package/@shopify/app-bridge-react) to work properly. Previously (in v1) this option was named `shopOrigin` and used the `shop` parameter from the iframe embed url. 

As i learned from this [issue](https://github.com/Shopify/shopify-app-bridge/issues/38), it is possible to just get the `host` parameter from the iframe url to make `app-bridge` work in the Shopify admin.

But the authentication link generated when using `shopify serve` lacks the `host` parameter. The link no longer redirects to the app in the Shopify admin as the `host` parameter is not present (or so I assume), instead it leads to unexpected redirects for me.

## Expected behavior

When using `shopify serve` a link including the `host` parameter should be generated:

```
https://<RANDOM_CODE>.ngrok.io/auth?shop=<SHOP_NAME>&host=<HOST_CODE>
```

When used it should go through the authentication and redirect to the app inside the Shopify admin.

INFO: `host` seems to be the shop name encoded as base64 string. (can't link to the code because it is not open source but I checked in the `node_modules` of my current project).

## Actual behavior

The generated authentication link looks like this:

```
https://<RANDOM_CODE>.ngrok.io/auth?shop=<SHOP_NAME>
```

I get redirected to the password page of my development store.

## Steps to reproduce the problem

1. Create a new node.js/next app using `shopify create`
2. Update all npm modules to the latest version so that `@shopify/app-bridge`/`@shopify/app-bridge-react` use v2 
3. Serve your app with `shopify serve`
4. Visit the genrated ngrok auth link

## Specifications

- App type: node.js/next 
- Operating System: macOS 10.15
- Shell: zsh
- Ruby version (ruby -v): -

**Comment by paulomarg** [comment]
Hey @nicolas-cusan, thanks for raising this. We are working on adding app bridge v2 support to our app, but for now I believe you can work around this by:
1. Getting the `host` parameter from the URL in `MyApp.getInitialProps` in `_app.js` and using that to set up the `<Provider>`
2. As you said, change the `afterOAuth` callback in your server to pass the `host` parameter from `ctx.query` when redirecting 

I believe you should be able to work with app bridge v2 with those changes, but please do let us know if you still have any issues after that!

**Comment by nicolas-cusan** [comment]
Hey @paulomarg thank you for getting back to me. Good to know that v2 ist not implemented yet (I was usure if the problem was only on my side).

As you described in 1. I managed to get the app running by getting `host` from `ctx.query` in `getInitialProps ` in `_app.js`. I am unsure how to implement 2. but I will experiment on it.

For better context I will update the title of the issue to include `app-bridge` v2.

**Comment by liqueflies** [comment]
Hello @nicolas-cusan, how did you managed to see host into ctx.quert from `getInitialProps`? I can only see `shop` param.

Thank you,
L.

**Comment by Tyler-Magebinary** [comment]
Hi guys, 
I faced the same issue with the latest version (2.0.5),
I sorted it by overriding the **getInitialProps** method, you can pass the shopOrigin to the result also.
Hope this one can save your day :)

![image](https://user-images.githubusercontent.com/65339073/140907452-7ddb4467-d939-42c1-af51-47baafc89721.png)
