### ISSUE TITLE
shopify serve command is hanging frequently..

### ISSUE THREAD

**Issue by awd** [Shopify/shopify-cli#1259]
# Issue summary

Running `shopify serve` hangs with no output or logs to diagnose. 

## Expected behavior

`shopify serve` should not hang, it should fail with an error, or timeout if waiting on a network call.

## Actual behavior

Running `shopify serve` will sometimes hang - forever, without any errors or indication something is wrong. This is impossible to diagnose. This can stop a dev dead in their tracks. Is this ngrok related, or shopify related?

## Steps to reproduce the problem

1. run `shopify serve`, if it hangs, welcome to the club.

## Specifications

- App type: rails
- Operating System: osx
- Shell: iterm
- Ruby version (ruby -v): 2.7.3 and 2.7.2

**Comment by liqueflies** [comment]
Thank you @awd !

How to solve that?
I am not able to start the project :(

**Comment by lhincapie0** [comment]
+1

**Comment by Borahm** [comment]
It should work again!

**Comment by awd** [comment]
Thx @Borahm - any insight to the root cause? 

Would be 👍 if the cli could just report back something was throwing unexpected error to signal an outage at least.

**Comment by szapata-work** [comment]
+1

**Comment by rsalimans47** [comment]
Yep, for me it's hanging too atm. Very annoying when you have deadlines and you need to test your app

**Comment by Waqar-Ul-Khaf** [comment]
+1

**Comment by Borahm** [comment]
Looking into it! Sorry for the trouble

**Comment by awd** [comment]
Thank you @jacobsteves
