### ISSUE TITLE
HMR on server files?

### ISSUE THREAD

**Issue by zloz** [Shopify/shopify-cli#1263]
# Issue summary

Hi, am i missing something, shouldn't there be HMR (Hot module reloading) available on server files. its really tiring to keep restarting the server, even nodemon watch doesn't help as it restarts the whole server after each save, my expected behaviour is server watching my changes in the whole app (server plus frontend) and injecting them to the live build on each save. are there any plugins(webpack) or config i should be using to achieve this. any help would be very useful to dev community.

## Specifications

- App type: 1.12

**Comment by mkevinosullivan** [comment]
👋🏻 @zloz What are the commands you are using?  I'm guessing (but want to confirm) that you're referring to the creation of a node app?
