### ISSUE TITLE
Next.js boiler plate app stuck in a full reload loop

### ISSUE THREAD

**Issue by rsalimans47** [Shopify/shopify-cli#1264]
# Issue summary
Whenever I create a new nextjs/node app using the 'shopify create' app and install it on my test store, it keeps doing a full reload on repeat (the reload starts 2 seconds after the app is fully displayed in the browser). I'm using the new v1.12 of the Shopify CLI. It's also suddenly happening to the apps which I was already developing and it doesn't matter whether I'm on Chrome or Safari.

Whenever a full reload is started, the content of the app disappears until the reload is completed.

## Expected behavior

What do you think should happen?

Not doing a full reload every 2 seconds for no reason (without any change to the code whatsoever)

## Actual behavior

What actually happens?

A full reload is performed every 2 seconds in an infinite loop

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. make a new app with the shopify create command
2. Install the app on your test store
3. serve the app with 'shopify serve'
4. open the app

Here's also a screenshot of the exact error message I'm getting
<img width="1440" alt="Screenshot 2021-06-01 at 19 54 28" src="https://user-images.githubusercontent.com/69542143/120369822-20ae7b00-c314-11eb-8e4b-71a62e039e63.png">

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: 1.12
- Operating System: macOS 11 (BigSur) with M1 chip
- Shell: Bash
- Ruby version (ruby -v): ruby 3.0.0p0 (2020-12-25 revision 95aff21468)

**Comment by rsalimans47** [comment]
By the way: This behaviour only started showing this Monday when I started working. Last Friday, when I closed my computer for the weekend, I had never seen this behaviour before.

**Comment by rsalimans47** [comment]
Did anyone take a look at this yet? It's a huge problem that is blocking me from doing any front-end work

**Comment by mllemango** [comment]
Hey @rsalimans47, sorry for the late reply. I wasn't able to reproduce this issue on my end. To clarify, what do you mean when you say "a full reload is started"?

**Comment by rsalimans47** [comment]
Hi @mllemango , thanks for your reply! 

Here is a screen recording so you can see what I mean:
https://user-images.githubusercontent.com/69542143/120776262-5164ff00-c524-11eb-945d-63ce143d5887.mov

This goes on in an infinite loop: it starts up, couple of seconds pass by, and it starts completely reloading the app. This is on a local server, by the way.

The same thing happens for me when I create a new Nextjs/Node boilerplate Shopify app with the Shopify CLI. This was not the case a week ago.

Also, if I go back to commits from 1-2 weeks ago, this behaviour happens as well, whereas back then I did not have any problem. It started last Monday for me.

Have you ever encountered this before and how can I fix it?

**Comment by brandonironbirdlabscom** [comment]
Hi @mllemango - I believe I may be facing a similar (or identical) issue. Earlier this week I noticed that my app was loading very strangely. Specifically, the app would take an extremely long time to load, and then the content would suddenly disappear (similar to the video that @rsalimans47 posted).

When I tried rolling my app back to previous versions, I was able to get the content to display without disappearing, but it would still take an extremely long time to load (i.e. more than 60 seconds in cases).

I am able to replicate this problem even in a fresh Node app using the `shopify create` command.

Your previous comment indicates that we should try rolling back to a previous version of the CLI. Are you able to share some documentation on how to do that (I installed the Shopify CLI with homebrew).

**Comment by mllemango** [comment]
@brandonironbirdlabscom Hey! Good to have a second voice in this issue. 
The extremely long load times sounds like our recent issue communicating with the partners API https://github.com/Shopify/shopify-app-cli/issues/1259. 
As for rolling back, I think the easiest way is to use `gem` to install an older version with `gem install shopify-cli -v 1.9.0`, I'll be honest that's a total shot in the dark though. Appreciate y'all patience with this one!

**Comment by rsalimans47** [comment]
@mllemango I downgraded to Shopify-cli -v 1.9.0 according to your instructions and it works like a charm. So it might be a problem with the CLI after all then :) Let me know if I can help you resolve the problem (in case you'd like me to try some stuff out, for example). Thanks for your help!

@brandonironbirdlabscom run brew uninstall shopify-cli to remove your current install before running the command @mllemango recommended

**Comment by gitrlk** [comment]
Have the same issue with an npx create-next-app boilerplate, super frustrating and it was working fine until suddenly it started doing it. Had to switch computer to start the project I was working on from scratch
