### ISSUE TITLE
Shopify CLI: Failed to authenticate with Shopify. Please try again later.

### ISSUE THREAD

**Issue by 8maxxam8** [Shopify/shopify-cli#1285]
# Issue summary
I try to start my development server. From one moment to the next I was not able to run "shopify serve" anymore. First the console didn't do anything. Now the console gives me the error: 
**Failed to authenticate with Shopify. Please try again later.** 

I have updated the Shopify CLI to the current version 1.13.1, but the error still appears.

**Comment by mikeeus** [comment]
I'm getting the same issue too on version 1.13.1.
Running `shopify logout` and `shopify serve` again asks me to login, I do and it says logged in successfuly, then immediately sais `✗ Failed to authenticate with Shopify. Please try again later.`

**Comment by evilzebra-labs** [comment]
it worked for me after running the shopify CLI with SUDO

**Comment by chl03ks** [comment]
Same issue here I wonder if there's is a easy easy to downgrade the version using`brew`

**Comment by fitzmode** [comment]
Seems related to issue #1271 , no solid tangible resolution there.

**Comment by chl03ks** [comment]
> it worked for me after running the Shopify CLI with SUDO...
> 
> UPDATE:
> I've restarted the computer and when trying to log in back again it keeps saying the same "Failed to authenticate with Shopify" error

it didn't work for me, I'm using macOS Big Sur 11.2.3

**Comment by arfanliaqat** [comment]
was having a hard time with this myself for last few hours, without any upgrade or anything it stopped working,

@evilzebra-labs solutions worked in my case though

**Comment by evilzebra-labs** [comment]
> was having a hard time with this myself for last few hours, without any upgrade or anything it stopped working,
> 
> @evilzebra-labs solutions worked in my case though

it's not working for me anymore haha

**Comment by arfanliaqat** [comment]
It didn't work for me either... (it showed more progress then usual like installing ngrok, updating env etc, like its gonna work but at the end same error, i was so excited i didn't waited for it to finish before posting success... :neutral_face: )

@evilzebra-labs we are in same boat for now :laughing:

**Comment by arfanliaqat** [comment]
I think this will be helpful from somone from shopify I'm using chrome btw

```
This command ran with ID: 12453
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        41: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/bin/shopify:32:in `<main>'
        40: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        39: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        38: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/bin/shopify:33:in `block in <main>'
        37: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        36: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        35: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        34: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/core/executor.rb:15:in `call'
        33: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        32: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        31: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        30: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        29: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        28: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        27: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        26: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        25: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        24: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        23: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        22: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        21: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        20: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/commands/connect.rb:9:in `call'
        19: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/command.rb:25:in `call'
        18: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/commands/connect.rb:28:in `call'
        17: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/sub_command.rb:12:in `call'
        16: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/project_types/node/commands/connect.rb:10:in `call'
        15: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/commands/connect.rb:44:in `default_connect'
        14: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/task.rb:7:in `call'
        13: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/tasks/ensure_env.rb:17:in `call'
        12: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/tasks/ensure_env.rb:28:in `fetch_org'
        11: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api/organizations.rb:22:in `fetch_with_app'
        10: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:48:in `query'
         9: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:65:in `authenticated_req'
         8: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         7: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:49:in `block in query'
         6: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:77:in `api_client'
         5: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:83:in `access_token'
         4: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/db.rb:87:in `get'
         3: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:84:in `block in access_token'
         2: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/partners_api.rb:96:in `authenticate'
         1: from /var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/oauth.rb:42:in `authenticate'
/var/lib/gems/2.5.0/gems/shopify-cli-1.13.1/lib/shopify-cli/oauth.rb:97:in `receive_access_code': Timed out while waiting for response from Shopify (ShopifyCli::OAuth::Error)
```

**Comment by atiqueahmedziad** [comment]
I was running Shopify Cli version 1.13.0 comfortably. But after updating the Cli to version 1.13.1, I am getting this - **Failed to authenticate with Shopify. Please try again later.** error. I removed the version 1.13.1 and re-install the version 1.13.0 again, but still getting the same error. 
Finally, I rolled back to version 1.12.0, and it's working fine now.

**Comment by kyletov** [comment]
I ran into this issue too, it didn't work when I tried running `shopify logout` and `shopify serve`, but it worked when I ran `shopify tunnel stop` then `shopify serve`

**Comment by chl03ks** [comment]
@kyletov solutions worked in my case.

**Comment by arfanliaqat** [comment]
@kyletov solutions worked for me too! Cheers

**Comment by shubhamsoni2617** [comment]
> Hey folks, thank you for reporting this. It seems that this issue does not depend on the CLI version, but it is intermittently happening when the CLI is authenticating with the Shopify servers.
> 
> We apologize for the inconvenience, and we're working internally with the authentication team on a solution. We will keep you posted on our findings!

Any update paulomarg ? it would be very helpful to know when we can start working using cli

**Comment by designifyer** [comment]
> Hey folks, thank you for reporting this. It seems that this issue does not depend on the CLI version, but it is intermittently happening when the CLI is authenticating with the Shopify servers.
> 
> We apologize for the inconvenience, and we're working internally with the authentication team on a solution. We will keep you posted on our findings!

Hey @paulomarg, thank you for looking into this. The issue still exists

**Comment by arfanliaqat** [comment]
@shubhamsoni2617 did you tried the work around provided above in @kyletov comment?

**Comment by ldelafuente** [comment]
Hi @paulomarg shopify serve doesn't run and can't test or run our project. We are in a tight schedule and this issue is going to make us lose revenue. Do you have any update on this?

**Comment by ldelafuente** [comment]
Hi @paulomarg shopify serve doesn't run and can't test or run our app. We are in a tight schedule and this issue is going to make us lose revenue. Do you have any update on this?

**Comment by shubhamsoni2617** [comment]
Hi @ldelafuente , I tried all the possible solutions mentioned above, like @stiegi mentioned none of them is working. :(

**Comment by ldelafuente** [comment]
> Hi @ldelafuente , I tried all the possible solutions mentioned above, like @stiegi mentioned none of them is working. :(

I also tried everything and I'm still unable to run our project!

**Comment by arfanliaqat** [comment]
That is very unfortunate, however my setup got working and it still is working,

I am not working over weekend but for you guys i just ran it again - AND IT IS NOT WORKING - :fearful: 

Tried usual debug method
```
shopify tunnel stop
shopify logout
shopify serve
```
and it worked again :relieved: this epside just happend so i just you try similar if it helps?

In short it means that workaround is possible may give a real hard look to your shopify configs (store, api secret key etc) so that they are correct

**Comment by shubhamsoni2617** [comment]
I noticed that sometimes, if there is an instance of app running on browser and you close `shopify serve` then serving again is throwing `Failed to authenticate` error

**Comment by grallc** [comment]
> @arfanliaqat your solution didn't work for me. I logged out and logged back in and the browser indicated that I was authenticated successfully. My CLI on the other hand says otherwise.... I give up.
> 
> ![image](https://user-images.githubusercontent.com/28389950/123612454-39bf2480-d80b-11eb-912d-ecc7e8e82bee.png)

Same issue here.
I think this time the problem is coming from Shopify's side, since my CLI was working 30 minutes ago and I basically didn't change anything

**Comment by shubhamsoni2617** [comment]
> > @arfanliaqat your solution didn't work for me. I logged out and logged back in and the browser indicated that I was authenticated successfully. My CLI on the other hand says otherwise.... I give up.
> > ![image](https://user-images.githubusercontent.com/28389950/123612454-39bf2480-d80b-11eb-912d-ecc7e8e82bee.png)
> 
> Same issue here.
> I think this time the problem is coming from Shopify's side, since my CLI was working 30 minutes ago and I basically didn't change anything

+1

**Comment by shubhamsoni2617** [comment]
@grallc +1

**Comment by ldelafuente** [comment]
shopify serve keeps running intermittently and now onces it correcly starts the service the app doesn't authenticate and it keeps looping in the auth call

**Comment by ldelafuente** [comment]
`shopify serve` keeps running intermittently, and now, onces it correcly starts the service, the app doesn't authenticate and it keeps looping in the auth call.
I've tried using differents VPNs, browsers and even internet connections and the problem with authentication on Shopify's serves persist.

@paulomarg  this is a critical roadblock to keep developing on your platform. It's been incredibly difficult and frustrating trying to make some progress on our project because of this.

**Comment by ldelafuente** [comment]
`shopify serve` keeps running intermittently, and now, onces it correcly starts the service, the app doesn't authenticate and it keeps looping in the auth call.
I've tried using differents VPNs, browsers and even internet connections and the problem with Shopify's authentication servers persist.

@paulomarg  this is a critical issue and is a roadblock to us to keep developing on your platform. It's been incredibly difficult and frustrating trying to make some progress on our project because of this.

**Comment by djkgamc** [comment]
I just progressively tried every version of shopify-cli downward from 2.0.1 to 1.13.1 on an entirely new Partner account I created just to see if there was one version that worked as a workaround.

The command I ran was: 
_shopify logout_
_shopify node create_ or _shopify login_

Every version of shopify-cli produced the error: 
✗ Failed to authenticate with Shopify. Please try again later.

In newer versions of shopify-cli, it also passed this error or similar:
`www-authenticate: Bearer realm="271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6",error="invalid_token",error_description="The access token provided is expired, revoked, malformed, or invalid for other reasons."
x-request-id: 054348e4cd040f09b9469a4e97d7551f`

This is on MacOS Catalina. 
The browser I used to login was a Safari 14.1 browser with all cookies cleared.

This is preventing us from releasing our product subscription extension app.

**Comment by Jgobeille** [comment]
I am having this issue now. I updated to Shopify 2.0.1 to be able to use new shopify theme features. I guess this issue has still not been resolved?

**Comment by ldelafuente** [comment]
It keeps happening... I Sincerily don't understand how is that a company of your scale let this happen. Do you know that by not answering to the developers for weeks and not fixing this issues, you are basically taking hostage our salaries? We can't make any progress with your tooling not working. We can't event tell our clients the right reason why our projects keep getting delayed.

**Comment by aaronkantrowitz** [comment]
I'm experiencing this issue as well with a new proejct. Hoping this gets resolved soon!

**Comment by VladimirCatrici** [comment]
Same here, worked fine yesterday and stopped today without any changes from my side.

**Comment by Aeyzaz** [comment]
Testing a very critical part on my app and this happened, it was working fine a few hours ago.

**Comment by designifyer** [comment]
It's working again on my side without any command run other than shopify node serve --host=https://example.ngrok.io

**Comment by mkevinosullivan** [comment]
👋🏻 Hi folks, I appreciate that this is extraordinarily frustrating for those impacted.  Because of the intermittent nature of the issue, it's proving elusive to track down the root cause, especially when multiple interconnected modules are involved.

Some progress was made yesterday in identifying the potential cause in an internal service module.  More logging is required to confirm the issue and formulate a solution.

Thank you for your patience and support in helping track down the problem.

**Comment by markitics** [comment]
# My problem
I was stuck in this loop. The browser would open, I'd log in and get a success message in the browser like "you're logged in; you you close this browser and return to the cli".
But then back in the terminal, it would show an error.
```
✗ npm run dev

> my-shopify.app@1.0.0 dev
> shopify app dev

✔ Dependencies installed

To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser

━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━

    Error validating auth session

    What to try:
    We've cleared the current session, please try again

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```    

# My solution
This worked.
1. run `npm run dev` 
2. Browser opened accounts.shopify.com – it remembered which accounts I have, but instead of selecting an account, I cleared cookies:
3. I have "Edit this cookie" browser plugin. https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg/reviews I cleared all cookies on accounts.shopify.com

Then I went through the flow again. This time when accounts.shopify.com opened, I had to type my email and password. 
This time when I returned to the CLI I was successfully logged in.
```
To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
✔ Logged in.
```

**Comment by dronalabsinc** [comment]
This worked for me:

1. Cleared all shopify and app.shopify related cookies and content from my browser cache.
2. run npm run dev / yarn dev
