### ISSUE TITLE
Manually Enable Cookie Popup Endless Loop

### ISSUE THREAD

**Issue by eddy-reynoso** [Shopify/shopify-cli#1297]
# Issue summary
Using the Shopify CLI version 2.0.0 to create a Node app. When Creating a new page and adding a navigation link to that page, I am not able to go to that new page using the app bridge. Instead I get a Cookie Popup Endless loop. I have tried many things including clearing cookies, cache, local storage, restarting my machine, creating a new app, killing ngrok.

## Expected behavior

Should allow me to use the app without the Enable Cookie popup and should navigate to correct page.

## Actual behavior

What actually happens?
Cookie Popup runs every time I try to navigate to a new page even though I am using the Shopify boilerplate out of the box.

## Steps to reproduce the problem

1. Run Shopify Create Node and create a new app
2. Create new page in pages directory in addition to index.js
3. Add new page as Navigation Link in Partner Dashboard under App Setup > Embedded App > Manage.
4. Ensure that server is running with Shopify Serve Node
5. On browser try to click new navigation link.

## Error Code
https://github.com/eddy-reynoso/cookies-popup-error
## Error Demo
https://user-images.githubusercontent.com/47189260/123738538-f7c9c900-d872-11eb-95fa-7d6678e3c2dc.mov

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Node
- Operating System: macOS
- Shell: bash
- Ruby version (ruby -v): 2.6
- Node Version: 16.2.0
- NPM Version: 7.13.0

**Comment by tbeseda** [comment]
I used the same steps and was able to recreate a similar issue, but the cookie notice is when opening the app after initial boot. I don't see the cookie notice unless the server restarts.

https://user-images.githubusercontent.com/15697/124040104-85b3ca00-d9c1-11eb-8ee5-81b4341e8e32.mp4

When I checked the diff between my app and the original poster, it's just these routes

```diff
    ctx.res.statusCode = 200;
  };

-   router.get("/", async (ctx) => {
-    const shop = ctx.query.shop;
-
-    // This shop hasn't been seen yet, go through OAuth to create a session
-    if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
-      ctx.redirect(`/auth?shop=${shop}`);
-    } else {
-      await handleRequest(ctx);
-    }
-  });

  router.post("/webhooks", async (ctx) => {
    try {
      await Shopify.Webhooks.Registry.process(ctx.req, ctx.res);

...

  router.get("(/_next/static/.*)", handleRequest); // Static content is clear
  router.get("/_next/webpack-hmr", handleRequest); // Webpack content is clear
  router.get("(.*)", verifyRequest(), handleRequest); // Everything else must have sessions
+  router.get("(.*)", async (ctx) => {
+    const shop = ctx.query.shop;
+
+    // This shop hasn't been seen yet, go through OAuth to create a session
+    if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
+      ctx.redirect(`/auth?shop=${shop}`);
+    } else {
+      await handleRequest(ctx);
+    }
+  });

  server.use(router.allowedMethods());
  server.use(router.routes());
```

- Shopify CLI 2.0.1
- Node.js 14.16.1
- npm 7.16.0

**Comment by avibz1987** [comment]
Hey, we have the same issue, and it seems that we can't get approval since Shopify not allowing cookies using to embed apps anymore... what shall we do??? Thanks

**Comment by tbeseda** [comment]
Following up with a note from the `koa-shopify-auth` repo https://github.com/Shopify/koa-shopify-auth/issues/81#issuecomment-816656683 -- in my case, the "Enable Cookies" view flashing is intended to let the browser detect and set if cookies (needed for auth) are allowed.

I think there's still some more testing I need to do with adding a "real" session/token storage database and how the AppBridge navigates. There's probably a couple ways to improve the docs here too.

WIP :)

**Comment by smamessier** [comment]
Any update on this frustrating issue?
