### ISSUE TITLE
Changing terminal width while running `serve` causes visual progress bar bug

### ISSUE THREAD

**Issue by tmharryfrancis** [Shopify/shopify-cli#1299]
# Issue summary

Write a short description of the issue here ↓

If you change the terminal width while running `shopify theme serve`, each increment of the progress bar is displayed on a new line. It looks kind of cool but is a bit annoying!

Visual bug only.

![Screenshot 2021-06-29 at 14 24 17](https://user-images.githubusercontent.com/73337049/123806366-c4c11d00-d8e6-11eb-8c3d-8b1fc3acf86a.png)

(You can do some cool art with it!)

![Screenshot 2021-06-29 at 14 40 39](https://user-images.githubusercontent.com/73337049/123808327-8d537000-d8e8-11eb-846d-ebf54a0bec98.png)

ANYWAY!

## Expected behavior

What do you think should happen?

The progress bar should load as it does when you don't change the terminal width.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

The progress bar gets redrawn on a new line for each increment.

## Steps to reproduce the problem

1. Run `shopify theme serve`
2. Change terminal width

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

I don't think it's necessary here.

## Specifications

- App type:
- Operating System: macOS Catalina
- Shell: zsh
- Ruby version (ruby -v): 2.7.2

**Comment by mllemango** [comment]
That art _is_ cool
We can investigate this, but I think this might be from our cli interface we use https://github.com/Shopify/cli-ui

**Comment by efekurnaz** [comment]
very cool art!

Would be great to have a flag to disable the UI, with just plain simple text. 

I've just created a parallel grid with https://github.com/embarklabs/neo-blessed. Shopify Cli UI is buggy in there as well.

![CleanShot 2021-07-01 at 23 25 35](https://user-images.githubusercontent.com/10762792/124185568-d4498d00-dac3-11eb-81aa-0fc44435ead7.png)

**Comment by tmharryfrancis** [comment]
This issue is still present.
