### ISSUE TITLE
shopify login was not found

### ISSUE THREAD

**Issue by thagxt** [Shopify/shopify-cli#1306]
# Issue summary

Write a short description of the issue here ↓
I'm trying to connect to my development store to test the new features but I'm stuck on [step #3](https://shopify.dev/themes/getting-started/create#step-3-authenticate-with-shopify-cli) because I get error: `shopify login was not found`.

## Expected behavior

I expect it to let me login and continue. 

## Actual behavior

I get an error stating that the command `shopify login` was not found.

```
Command not found 
shopify login was not found

Did you mean?
shopify logout
 ```

## Steps to reproduce the problem

1. run  `shopify login --store devstore-url.myshopify.com`

## Specifications

- App type: Terminal
- Operating System: MacOS Mojave
- Shell
- Ruby version (ruby -v): ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by mkevinosullivan** [comment]
Have you installed the latest version of the CLI?  Login is only available with `v2` of the CLI.

**Comment by thagxt** [comment]
I've tried but it keeps installing v1.5.0

when I run `brew upgrade shopify-cli` it returns:

```
Error: 
  homebrew-core is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
This command may take a few minutes to run due to the large size of the repository.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
Warning: shopify/shopify/shopify-cli 1.5.0 already installed
```

**Comment by thagxt** [comment]
It was because of Brew. I had to run `git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow` to be able to update everything. Now it works.
