### ISSUE TITLE
shopify login returns an SSL error

### ISSUE THREAD

**Issue by dhruveonmars** [Shopify/shopify-cli#1307]
# Issue summary

When I run the command `shopify login --store=<storeurl>` I get an error in my command line on macOS that seems to be related to Ruby and an SSL certificate issue.

## Expected behavior

It should prompt to authenticate me.

## Actual behavior

I get the following error message in the command line:

<details>
This command ran with ID: 86836
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/net/http.rb:621:in `start'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/commands/login.rb:61:in `shop_to_permanent_domain'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/commands/login.rb:45:in `validate_shop'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/commands/login.rb:18:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/command.rb:25:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/monorail.rb:32:in `log'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
</details>

## Steps to reproduce the problem

1. Install Shopify CLI using Homebrew as documented on [https://shopify.dev/themes/tools/cli/installation](https://shopify.dev/themes/tools/cli/installation).
2. Verified installation by running `shopify version` which gave back 2.0.1.
3. Cloned [https://github.com/Shopify/dawn](https://github.com/Shopify/dawn), and `cd` into that directory in the command line. Then ran the `shopify login --store=<storeurl>`, which gave the response above.

## Specifications

- App type: NA
- Operating System: macOS 11.3.1
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

**Comment by kellyvaughn** [comment]
Running into the same issue. I didn't run into it on my MBP but did on my M1 Mac Mini (both running macOS 11.4, ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]).

**Comment by mkevinosullivan** [comment]
@dhruveonmars What's the output of `shopify system all`?

@kellyvaughn Are you able to show the output of `shopify system all` before and after you changed Ruby via RVM?

**Comment by mkevinosullivan** [comment]
Thanks @dhruveonmars - I'm not sure why the RVM change would make a difference, since the Ruby used by the CLI in both cases above is the same (`/usr/local/Cellar/ruby/3.0.1/bin/ruby`), which is the expected one for a `brew` installation, and not the one from RVM.

**Comment by NitishDeshpande** [comment]
I'm facing the same issue, Shopify-cli 2.1.0 and Ruby 3.0.2, Can someone help me here?

```
Environment
  TERM              = xterm-256color
  SHELL             = /bin/bash
  PATH              = /usr/local/opt/ruby/bin:/Users/nitish/.pyenv/shims:/Users/nitish/.pyenv/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nitish/software/android-sdk-macosx/tools:/Users/nitish/software/android-sdk-macosx/platform-tools
  LANG              = en_US.UTF-8

Shopify CLI
               ROOT = /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0
  PROJECT_TYPES_DIR = /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/project_types
           TEMP_DIR = /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/.tmp
          CACHE_DIR = /Users/nitish/.cache/shopify
   TOOL_CONFIG_PATH = /Users/nitish/.config/shopify
           LOG_FILE = /Users/nitish/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /Users/nitish/.config/shopify/logs/debug.log

Current Shop
  No store found. Please run shopify login --store=STORE to login to a specific store

Ruby (via RbConfig)
  /usr/local/Cellar/ruby/3.0.2/bin/ruby
  x86_64-apple-darwin17     - RbConfig["host"]
  ruby-3.0.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
```

### Error log

```
$ shopify login
This command ran with ID: 89693
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/identity_auth.rb:218:in `post_request'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/identity_auth.rb:208:in `post_token_request'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/identity_auth.rb:132:in `request_access_token'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/identity_auth.rb:65:in `authenticate'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/commands/login.rb:33:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/command.rb:25:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/monorail.rb:32:in `log'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
```

**Comment by corazzi** [comment]
I was having this issue, too.

My default certificate was missing from where Ruby expected to find it.

If you run `ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'` you should get something similar to this:

`"/usr/local/etc/openssl@1.1/cert.pem"`

When I tried to look into that file, though, it didn't exist.

Running the following downloaded the pem certificate file and fixed the issue for me:

```bash
curl -fsSL curl.haxx.se/ca/cacert.pem -o "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
```

**Comment by boothkittson** [comment]
So after a lot of back and forth it seems that Shopify has acknowledged there's an issue.  See this github post:  https://github.com/Shopify/shopify-cli/issues/1309

There is some rigmarole about logging in and logging out and some other rigmarole that it's sequence dependent.  A newly posted ["Caution" on the dev page](https://shopify.dev/themes/tools/cli/getting-started) for Shopify CLI also states you must be the store owner or staff account (which does not work BTW).

All of which I tried on a fresh install of Ruby and Shopify CLI and a fresh dev store, all to no avail.  I nagged the Shopify support staff about the non-working workaround.

Will post progress here.

**Comment by boothkittson** [comment]
Finally found a potential solution.  

The issue is that when you first use the **shopify theme serve** command within VSCode's Powershell, an error occurs.  You may get an error message similar to this:
 
> Error 
> You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.
> If you're the store owner, then you need to log in to the store directly using the store URL at least once (for example, using freedom-for-quilty.myshopify.com.myshopify.com/admin) before you log in using Shopify CLI. Logging in to the Shopify admin directly connects the development store with your Shopify login.

The bug is that Shopify CLI doesn't recognize the store owner, even if you're logged in.
To remedy this Shopify recommends logging into the new dev store.
    _Simply re-logging into your new store won't work_.  Shopify's solution is incomplete.  This is what I did.

- Get a fresh browser without any Shopify cookies, cache, or whatever.
    I just made a new Chrome profile and this worked

- type in the URL of your new store's admin
  Should ask you to login, with your email address.  Go ahead and log in with your store password (not your partner/dev password).  
 Should ask you to input the verification code Shopify sends to your email.  Go ahead and input this.
- Shopify should then ask you to associate the email with your partner/dev account
  Should send the verification code to your phone (either text or auto phone call depending on your settings)
  Go ahead and enter this.

- Go back to VSCode Powershell and run the shopify login command, e.g.
  `shopify login --store example-store.myshopify.com`
do this even if you're logged in or think you're logged in.
-   run the shopify them serve command
 `shopify theme serve`

Somewhere in the resulting message you should see the URL for the live preview.  You should be good to go.  All of this assumes you're running Shopify version 2.17, at this writing the latest.
