### ISSUE TITLE
[Post Unite] Add more context on the steps required to run an app

### ISSUE THREAD

**Issue by davekilljoy** [Shopify/shopify-cli#131]
# Issue summary

<img width="505" alt="Screen Shot 2019-06-17 at 10 53 14 AM" src="https://user-images.githubusercontent.com/1523373/59614423-baac9700-90ee-11e9-91a3-1da6b556252e.png">

When running the `shopify serve` command for the first time, theres a couple things that were missing from the `success` summary.

1. I need to update the whitelist URL's in the App
2. I need to hit `Control-T` to actually open the app, its listed as a tip but thats also the only way to do it (maybe)
3. `[wait] compiling...` is confusing as I thought I had to wait longer for something to complete before visiting the URL

**Comment by neil-rubens** [comment]
I had the same problem.  This what happened to work for me.

execute `shopify serve`  see the link to ngrok:

> ✓ ngrok tunnel running at https://<YOUR_HASH>.ngrok.io

you need to open it in your browser

you may see a message:
> "Expected a valid shop query parameter"  

You can fix that by: https://stackoverflow.com/a/61470140/2705777

p.s. copy of: https://github.com/Shopify/shopify-app-cli/issues/483#issuecomment-620259356
