### ISSUE TITLE
Image errors on "shopify theme pull"

### ISSUE THREAD

**Issue by Artz0ne** [Shopify/shopify-cli#1315]
# Issue summary

When attempting to pull a theme that has images (jpg or png) in the assets folder, errors are generated and the image files aren't pulled correctly. They're all downloaded at zero bytes.

## Expected behavior

Images should be downloaded.

## Actual behavior

What actually happens?

Images are flagged as errors as in the following examples....
<img width="586" alt="Screenshot 2021-06-30 at 16 25 16" src="https://user-images.githubusercontent.com/10516342/123990888-1c808680-d9c2-11eb-9960-b6c27a0d2b30.png">

<details>
<code>
┃ ERROR get assets/password-page-background.jpg: "\xFF" from ASCII-8BIT to UTF-8
┃ ERROR get assets/site-background.jpg: "\xFF" from ASCII-8BIT to UTF-8
</code>
</details>

## Steps to reproduce the problem

Use "shopify theme pull" command on a theme that has an image in the assets folder

## Specifications

- Operating System: Mac OS 11.4
- Shell: zsh
- Ruby version (ruby -v): 3.0.1

**Comment by alquezajanmaverick** [comment]
I applied double-splat operator on the argument (file.rb) to avoid deprecation warnings while pulling.
