### ISSUE TITLE
Repeated URL parameter keys get overridden

### ISSUE THREAD

**Issue by tyleralsbury** [Shopify/shopify-cli#1323]
# Issue summary

When you have multiple parameters in the URL that have the same key, only the last one is taken, which can cause issues.

## Actual behavior

An example using the new faceted filtering API:

`http://127.0.0.1:9292/collections/all?filter.v.option.size=s&filter.v.option.size=m&filter.v.option.size=l` - notice that `filter.v.option.size` is the key for all 3 parameters.  When the page renders, though, it's as though only `filter.v.option.size=l` is considered.

<img width="1412" alt="Screen Shot 2021-06-30 at 4 01 48 PM" src="https://user-images.githubusercontent.com/60230011/124023880-7ed68880-d9bc-11eb-94f7-1a135e2c815c.png">

## Expected behavior

By comparison, a similar URL on a production environment:

`/collections/all?filter.v.option.size=s&filter.v.option.size=m&filter.v.option.size=l`

All 3 filters are active and the count is correct on selected filters:

<img width="853" alt="Screen Shot 2021-06-30 at 4 03 32 PM" src="https://user-images.githubusercontent.com/60230011/124024091-bd6c4300-d9bc-11eb-8b83-eb90790e0f7e.png">

## Steps to reproduce the problem / test case

1.  On a fresh copy of Dawn, go to a collection page with filters enabled
2. Select a few filters from the same group, example: size
3. Note that the only filter being considered is the last parameter in the URL, this affects the active filters and rendered grid
4. Refresh the page.  Note the same thing.
5. Reopen the filter you used in step 2
6. Note that only the last option is checked

## Specifications

- App type: Theme - Dawn
- Operating System: Mac OS
- Browser: Chrome

**Comment by macournoyer** [comment]
Issue is that we convert the query string params to a Hash: https://github.com/Shopify/shopify-cli/blob/main/lib/shopify-cli/theme/dev_server/proxy.rb#L42. Removing dups.

Thanks for reporting Tyler!
