### ISSUE TITLE
Registering app extension fails

### ISSUE THREAD

**Issue by pratiknikam** [Shopify/shopify-cli#1325]
# Issue summary

Following [theme app extensions getting started tutorial](https://shopify.dev/apps/online-store/theme-app-extensions/getting-started#scaffold-and-register-a-theme-app-extension) in existing app. When I try to push or register extension, I get following error:

```
You cannot register theme-app-extension because this app already has the maximum number of 1 registration allowed for this extension type.
```

This is first time I'm doing this so I def don't have any other extension registered under same app.

## Expected behavior

Should be able to register or push newly created extension.

## Actual behavior

```
You cannot register theme-app-extension because this app already has the maximum number of 1 registration allowed for this extension type.
```

## Steps to reproduce the problem

1. Upgrade shopify-cli to latest version
2. `shopify extension create --type=THEME_APP_EXTENSION --getting-started`
3. `cd theme-app-extension`
4. `shopify extension register`

```
> shopify extension register
┏━━ Registering Extension 
┃ You can only create one Theme App Extension extension per app, which can’t be undone.
┃ ? Would you like to register this extension? (y/n) (You chose: yes)
┃ Registering with Shopify...                                                                                                                                                                                                 
✗ You cannot register theme-app-extension because this app already has the maximum number of 1 registration allowed for this extension type.
```

Here's how theme app extensions setting looks on partner side.

![image](https://user-images.githubusercontent.com/2853953/124040032-227e6380-d9d2-11eb-988b-1df7341b8955.png)

## Specifications

- App type: Embedded app
- Operating System: MacOS
- Shell: Bash
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by monting** [comment]
I'm encountering a different error, when running `shopify extension register`

```
This command ran with ID: 40063
Please include this information in any issues/report along with relevant logs
/opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/project_types/extension/extension_project.rb:99:in `property_present?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/project_types/extension/extension_project.rb:49:in `registered?'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/project_types/extension/commands/register.rb:10:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/project_types/extension/commands/register.rb:9:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/sub_command.rb:13:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/command.rb:19:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/executor.rb:15:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/monorail.rb:20:in `log'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:33:in `block in <top (required)>'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /opt/homebrew/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:32:in `<top (required)>'
	from /opt/homebrew/bin/shopify:6:in `load'
	from /opt/homebrew/bin/shopify:6:in `<main>'
```

**Comment by catlee** [comment]
Can you try running `shopify extension connect` instead? That should connect your local project to your existing extension.

**Comment by pratiknikam** [comment]
@catlee so I connected my extension to my dev/local version of app where I've completed all my development and testing. Now it's time I need to connect this extension to my live app so that I can push and create versions for merchants to use. How do we go about this?

Couldn't find any documentation around such scenario.

**Comment by catlee** [comment]
@pratiknikam could you please create a new issue for your feature request? It's easier to keep track of where discussions are happening.

This specific issue regarding registration has been resolved.

**Comment by pratiknikam** [comment]
Makes sense @catlee . I've created https://github.com/Shopify/shopify-cli/issues/1387

**Comment by pratikwebkul** [comment]
I face same issue but the above solution is not working for me i am getting some other errors please refer

pratik@pratik:~/Desktop/shopify-cli/akram-store-4/theme-app-extension$ shopify extension connect
[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- readline.so
Did you mean?  readline
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

Loading your extensions…
This command ran with ID: 49225
Please include this information in any issues/report along with relevant logs
/usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:85:in `rescue in block in request': Timeout (ShopifyCli::API::APIRequestTimeoutError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:49:in `block in request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:86:in `request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:36:in `query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api.rb:49:in `block in query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api.rb:50:in `query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api/organizations.rb:31:in `fetch_with_extensions'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/tasks/get_extensions.rb:8:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/task.rb:7:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:38:in `load_registrations'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:22:in `prompt_for_registration'
	from <internal:kernel>:90:in `tap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:16:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/method_object.rb:56:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:416:in `block in wrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/method_object.rb:56:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:416:in `block in wrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:173:in `then'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/connect.rb:23:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/form.rb:13:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/commands/connect.rb:28:in `with_connect_form'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/commands/connect.rb:8:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/sub_command.rb:13:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/monorail.rb:20:in `log'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/bin/shopify:33:in `block in <main>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/bin/shopify:32:in `<main>'
/usr/local/lib/ruby/3.0.0/net/protocol.rb:219:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
	from /usr/local/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
	from /usr/local/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
	from /usr/local/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
	from /usr/local/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1521:in `request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1514:in `block in request'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:960:in `start'
	from /usr/local/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/http_request.rb:39:in `request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/http_request.rb:9:in `post'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:58:in `block in request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:86:in `request'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/api.rb:36:in `query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api.rb:49:in `block in query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api.rb:50:in `query'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/partners_api/organizations.rb:31:in `fetch_with_extensions'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/tasks/get_extensions.rb:8:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/task.rb:7:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:38:in `load_registrations'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:22:in `prompt_for_registration'
	from <internal:kernel>:90:in `tap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/questions/ask_registration.rb:16:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/method_object.rb:56:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:416:in `block in wrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/method_object.rb:56:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:416:in `block in wrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/result.rb:173:in `then'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/forms/connect.rb:23:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/form.rb:13:in `ask'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/commands/connect.rb:28:in `with_connect_form'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/project_types/extension/commands/connect.rb:8:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/sub_command.rb:13:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/monorail.rb:20:in `log'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/bin/shopify:33:in `block in <main>'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.2/bin/shopify:32:in `<main>'

**Comment by yaizudamashii** [comment]
> Can you try running `shopify extension connect` instead? That should connect your local project to your existing extension.

@catlee I would like to how to run the same command with Shopify CLI 3.x
