### ISSUE TITLE
`theme serve` not working with password protected shop signing-in as staff

### ISSUE THREAD

**Issue by davecyen** [Shopify/shopify-cli#1333]
# Issue summary

Write a short description of the issue here ↓

I'm following the Getting Started tutorial on https://shopify.dev/themes/getting-started/create.

When I run `shopify theme serve` in the CLI, the URL address provided (http://127.0.0.1:9292) prompts me to enter the store password or login as store owner. Then, when I attempt to login as store owner and submit my credentials, I receive an error page (`We'll be back soon`).

![image](https://user-images.githubusercontent.com/1930455/124291875-08a06600-db23-11eb-9af5-b0839edc0c0b.png)

I was able to successfully workaround this and access the page when I entered the password, but since I was following the getting started tutorial I had to log in via the admin and change the password first.

Specifications
App type: Theme, CLI
Operating System: macOS 11.4
Shell: /bin/zsh
Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580)

**Comment by rgie** [comment]
This happens to me as well. Here's what I did.
1.  Change Shopify store password
2. visit my storename.myshopify.com to enter the new password
3. visit http://127.0.0.1:9292 and enter the new password when asked

Hope this helps.

**Comment by davecyen** [comment]
Yup that worked for me too! Just wanted to flag this as a non blocking
issue. Thanks.
