### ISSUE TITLE
Shopify theme serve error running command

### ISSUE THREAD

**Issue by ok3dotdev** [Shopify/shopify-cli#1334]
# Issue summary

Issue using the shopify-CLI command `Shopify theme serve`

Write a short description of the issue here ↓

Following the documentation to get started with Shopify theme development.  Shopify init should initialize and pull in DAWN theme files into local directory and Shopify init should upload the files to the Shopify store and provide links to view and edit the theme in the theme editor. 

## Expected behavior
The command should create a local dev environment and push the theme as a dev theme to the Shopify store.

## Actual behavior

What actually happens?
On running the command `Shopify theme serve` the cli tries to sync the theme out output errors about json files to the console and provides link to view the theme but the links don't work.  creating a new dev store bypasses this but with a new 404 error in console. 

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
`<details>
 ERROR update DAWNBFCM/layout/password.liquid:
┃   404
┃ ERROR update DAWNBFCM/layout/theme.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/apps.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/announcement-bar.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/cart-icon-bubble.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/cart-live-region-text.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/cart-notification-button.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/cart-notification-product.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/collection-list.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/collage.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/contact-form.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/custom-liquid.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/featured-collection.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/featured-blog.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/header.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/image-banner.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/image-with-text.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/footer.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-404.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-article.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-blog.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-cart-footer.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-cart-items.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-collection-banner.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-collection-product-grid.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-list-collections.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-password-footer.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-password-header.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-page.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-product.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/main-search.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/multicolumn.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/newsletter.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/page.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/product-recommendations.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/pickup-availability.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/article-card.liquid:
┃   404
┃ ERROR update DAWNBFCM/sections/rich-text.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/cart-notification.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-3d-model.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-account.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-accordion.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-caret.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-arrow.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-cart.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-cart-empty.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-checkmark.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-clipboard.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-close-small.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-close.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-discount.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-error.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-facebook.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-filter.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-instagram.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-hamburger.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-minus.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-padlock.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-pinterest.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-play.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-plus.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-remove.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-snapchat.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-share.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-success.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-tick.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-tumblr.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-tiktok.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-unavailable.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-twitter.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-youtube.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-vimeo.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/icon-zoom.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/meta-tags.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/pagination.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/price.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/product-card.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/product-card-placeholder.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/product-thumbnail.liquid:
┃   404
┃ ERROR update DAWNBFCM/snippets/social-sharing.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/account.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/activate_account.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/addresses.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/login.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/order.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/register.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/customers/reset_password.liquid:
┃   404
┃ ERROR update DAWNBFCM/templates/gift_card.liquid:
┃   404
┃ ERROR update DAWNBFCM/config/settings_data.json:
┃   404
┃ ERROR update DAWNBFCM/config/settings_schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/bg-BG.json:
┃   404
┃ ERROR update DAWNBFCM/locales/cs.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/da.json:
┃   404
┃ ERROR update DAWNBFCM/locales/cs.json:
┃   404
┃ ERROR update DAWNBFCM/locales/da.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/de.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/el.json:
┃   404
┃ ERROR update DAWNBFCM/locales/en.default.json:
┃   404
┃ ERROR update DAWNBFCM/locales/de.json:
┃   404
┃ ERROR update DAWNBFCM/locales/en.default.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/es.json:
┃   404
┃ ERROR update DAWNBFCM/locales/es.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/fi.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/fr.json:
┃   404
┃ ERROR update DAWNBFCM/locales/fr.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/hr-HR.json:
┃   404
┃ ERROR update DAWNBFCM/locales/hu.json:
┃   404
┃ ERROR update DAWNBFCM/locales/id.json:
┃   404
┃ ERROR update DAWNBFCM/locales/it.json:
┃   404
┃ ERROR update DAWNBFCM/locales/it.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ja.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ja.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ko.json:
┃   404
┃ ERROR update DAWNBFCM/locales/fi.json:
┃   404
┃ ERROR update DAWNBFCM/locales/lt-LT.json:
┃   404
┃ ERROR update DAWNBFCM/locales/nb.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ko.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/nl.json:
┃   404
┃ ERROR update DAWNBFCM/locales/nl.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/nb.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pl.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pt-BR.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pt-BR.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pt-PT.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pt-PT.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ro-RO.json:
┃   404
┃ ERROR update DAWNBFCM/locales/pl.json:
┃   404
┃ ERROR update DAWNBFCM/locales/ru.json:
┃   404
┃ ERROR update DAWNBFCM/locales/sk-SK.json:
┃   404
┃ ERROR update DAWNBFCM/locales/sl-SI.json:
┃   404
┃ ERROR update DAWNBFCM/locales/sv.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/th.json:
┃   404
┃ ERROR update DAWNBFCM/locales/sv.json:
┃   404
┃ ERROR update DAWNBFCM/locales/tr.json:
┃   404
┃ ERROR update DAWNBFCM/locales/tr.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/vi.json:
┃   404
┃ ERROR update DAWNBFCM/locales/vi.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/zh-CN.json:
┃   404
┃ ERROR update DAWNBFCM/locales/zh-CN.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/zh-TW.json:
┃   404
┃ ERROR update DAWNBFCM/locales/zh-TW.schema.json:
┃   404
┃ ERROR update DAWNBFCM/locales/th.schema.json:
┃   404
┃ ERROR update DAWNBFCM/templates/article.json:
┃   404
┃ ERROR update DAWNBFCM/templates/blog.json:
┃   404
┃ ERROR update DAWNBFCM/templates/cart.json:
┃   404
┃ ERROR update DAWNBFCM/templates/404.json:
┃   404
┃ ERROR update DAWNBFCM/templates/index.json:
┃   404
┃ ERROR update DAWNBFCM/templates/collection.json:
┃   404
┃ ERROR update DAWNBFCM/templates/page.contact.json:
┃   404
┃ ERROR update DAWNBFCM/templates/page.json:
┃   404
┃ ERROR update DAWNBFCM/templates/list-collections.json:
┃   404
┃ ERROR update DAWNBFCM/templates/product.json:
┃   404
┃ ERROR update DAWNBFCM/templates/search.json:
┃   404
┃ ERROR update config/settings_schema.json: No such file or directory @ rb_sysopen - config/settings_schema.json
┃ ERROR update config/settings_data.json: No such file or directory @ rb_sysopen - config/settings_data.json
┃ ERROR update DAWNBFCM/templates/password.json:
┃   404
┃ 
</details>`

## Steps to reproduce the problem

1.Shopify login
2. Shopify init
3. Shopify theme serve

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Shopify-CLI
- Operating System: macOS Big Sur V11.2.3
- Shell: Terminal
- Ruby version (ruby -v):ruby 2.7.3p183
<img width="827" alt="Screen Shot 2021-06-29 at 9 18 14 PM" src="https://user-images.githubusercontent.com/53154228/124332933-c4cc5180-db60-11eb-9595-8cf0788da228.png">
<img width="908" alt="Screen Shot 2021-06-29 at 9 03 42 PM" src="https://user-images.githubusercontent.com/53154228/124332952-d6adf480-db60-11eb-9387-8bb647e42bd8.png">

**Comment by sickerman** [comment]
similar issue already opened

**Comment by sickerman** [comment]
You need to sign out of all shopify accounts from your browser.
Create a new development store to support online store 2.0 features and repeat the steps from `shopify init`. Let me know if this helps
