### ISSUE TITLE
Unable to login through CLI if Partner account is part of other organizations

### ISSUE THREAD

**Issue by alvserr** [Shopify/shopify-cli#1335]
# Issue summary

It fails when I try to login using `shopify login` with a Partner account that is also part of other organizations.

Just for testing purposes, I created a new Partner account and when I try logging in with this new account, it logins without problems.

On both accounts I see the same success message in the browser after submitting login credentials: "Authenticated successfully. You may now close this page."

But it fails on the CLI when I try to login with the Partner account that is part of other organizations.

I already tried `shopify logout` and it doesn't fix the issue.

## Expected behavior

The CLI should respond with the next message: `Logged into partner organization [organization_name]`

## Actual behavior

CLI responds with the next message:

```
X An unexpected error occurred on Shopify.
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.
```

If I run `shopify whoami` it shows the same message.

This gives me problems to create apps. At this point if I run `shopify node create`, it shows the next error:

`X Failed to authenticate with Shopify. Please try again later.`

If I provide the organization ID to `shopify node create`, it will create the app, but will fail if I run `shopify node serve` and will say `Couldn't verify your store [store_name]`

## Steps to reproduce the problem

1. Run `shopify login`
2. Login with Partner account that is part of other organizations.

## Specifications

- Operating System: Windows 10
- Shell: PowerShell 5.1.19041.1023
- Ruby version (ruby -v): ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x64-mingw32]
- Shopify CLI version: 2.0.1

**Comment by cupelapps** [comment]
Hi,
For me too, same problem
Regards
Muthu

**Comment by KeiMitchell** [comment]
Hi alvserr.
I have the same problem too....

**Comment by mkevinosullivan** [comment]
👋🏻 Please run the command with `DEBUG=1` in front of it, e.g.,
```
# Linux/MacOS
$ DEBUG=1 shopify login

# Windows CMD
C:\> set DEBUG="1"
C:\> shopify login

# Windows PowerShell
PS C:\> $env:DEBUG="1"
PS C:\> shopify login
```
and share the output.

**Comment by alvserr** [comment]
Hello @mkevinosullivan, thanks for reaching out.

The output was 2 tokens for "storefront_renderer_production_exchange_token" and "partners_exchange_token"

Then an HTML document that renders like this:

![error](https://user-images.githubusercontent.com/79106418/124661441-7cb97180-de75-11eb-917e-cea7dee1843c.png)

And finally the "shopify whoami" response message:

```
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.
```

**Comment by mkevinosullivan** [comment]
👋🏻 @alvserr, is this happening consistently every time or is it intermittent?   If it's intermittent, it might be related to #1285, which is being looked at.

**Comment by alvserr** [comment]
@mkevinosullivan Thanks for keeping looking at it.

It is happening every time. I also updated the CLI to the new version (2.0.2) and the problem persists. Also tried to uninstall shopify-cli and install it again and still the same problem.

I'm not sure if at some point it fails when it tries to look for my organization, because my account is also part of others. As counter part, the new Shopify Partners account that I created (and isn't part of any other organization) logins without any problems.

**Comment by noelsyoung** [comment]
@mkevinosullivan I am getting this same error. FWIW, I am a member of one partner organization, but no others. Additionally, when I try to log in, I see the authentication confirmation in the browser, but running the command in the terminal using DEBUG=1 gives me the same result as @alvserr . If I log into a store via the CLI, `whoami` returns `Logged into store <STORENAME>.myshopify.com as staff (no partner organizations available for this login)`.

**Comment by aisflat439** [comment]
This has been a problem for me and is fixed as of 7est

**Comment by Kenstreak** [comment]
DEBUG {"data"=>{"organizations"=>{"nodes"=>[{"id"=>"xxxxxxx", "businessName"=>"myName", "website"=>"[https://](https://streak.hk/)myApp", "stores"=>{"nodes"=>[{"shopId"=>"xxxxxxxxxx", "link"=>"[http://](http://partners.shopify.com/1785626/stores/58882490575)myApp", "shopDomain"=>"myApp", "shopName"=>"myApp", "transferDisabled"=>false, "convertableToPartnerTest"=>true}]]}

✗ Couldn't verify your store

just following the quickstart and unexpected error occurs

**Comment by liambolling** [comment]
This still happens for me

**Comment by jchenaud** [comment]
Hey ! 
I find something working for me.
First of all I normally use google chrome on mac OS
.But I got some problems on Shopify like connexions loops in front. 
I switch to Firefox as default  and my cli  working nowHey! I find something working for me.First of all I normally use google chrome on mac OS.But I got some problems on Shopify like connexions loops in front. I switch to Firefox as default  and my cli  working now

**Comment by jclarkdev** [comment]
**Update:** When attempting to run certain commands, like `shopify theme push` for example, I get this error message with lots of context. This will hopefully the Shopify team the context they need.

`This command ran with ID: 59776
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/api.rb:72:in `block in request': 403 (ShopifyCli::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/api.rb:86:in `request'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/admin_api.rb:95:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/theme/theme.rb:166:in `all'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/forms/select.rb:20:in `themes'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/forms/select.rb:9:in `block in ask'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:188:in `ask_interactive'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/forms/select.rb:8:in `ask'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/form.rb:13:in `ask'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/project_types/theme/commands/push.rb:40:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/sub_command.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/monorail.rb:32:in `log'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.4.0/gems/shopify-cli-2.4.0/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'`

**Comment by jclarkdev** [comment]
Thanks for the workaround @meuschke I think I've seen this mentioned once before as well. Happy to try it out on my end just to be able to get something published on the marketplace once and for all.

I think I also saw an accompanying explanation before as to _why_ this isn't working with multiple orgz, but I feel I need to emphasize to the Shopify team *how inconvenient it is to have to use this workaround when working in an agency or freelance environment and switching between multiple organizations every day...

Looking fwd to an update on this issue in the future 😇

**Comment by leocxy** [comment]
Hello, I have the same error message. But I think my case is slightly different from your issues.
My account is associate with two organizations. It will show the there is an unexpected error

```
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: 4a2208e2-12fb-4876-bca4-1b2ae9a84ec0
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: 4a2208e2-12fb-4876-bca4-1b2ae9a84ec0
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: 4a2208e2-12fb-4876-bca4-1b2ae9a84ec0
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: 4a2208e2-12fb-4876-bca4-1b2ae9a84ec0
✗ An unexpected error occurred on Shopify.
```

Here is the cli version
```
~ » DEBUG=1 shopify version                                                                                                                                                             
2.6.3
```

**Comment by notrealdev** [comment]
Same issue here:
Just try to log in on local via: http://127.0.0.1:9292/admin

![image](https://user-images.githubusercontent.com/79106418/124661441-7cb97180-de75-11eb-917e-cea7dee1843c.png)

**Comment by Magicking** [comment]
Ended up with the same issue, with the same error where I could not login with a partner account while it was working fine a bit before.

Solved using this recipe:
1. Logout of CLI
2. Logout of web interface
3. Login with CLI
4. Login with web interface with password using "select another account"
5. Worked \o/

Most probably a local token permission not updated.

**Comment by puppycodes** [comment]
ugh this issue is really ruining my week... +1 all day

**Comment by Dzheky** [comment]
Same problem, all the fixes that were suggested didn't work for me, always gives authorization error

**Comment by thedesignersdeveloper** [comment]
Same problem and non of the fixes work. So i've just spent months building a site for a client, i hand it over through the partner portal and now i can't edit it at all.

Shopify you need to make this No1 Priority to fix it.

**Comment by pepicrft** [comment]
I'm closing this one in favor of https://github.com/Shopify/shopify-cli/issues/1694, please, share any authentication-related issues that you encounter there.
