### ISSUE TITLE
shopify extension serve - No available ports found to run extension

### ISSUE THREAD

**Issue by muthusomasundaram** [Shopify/shopify-cli#1336]
# Issue summary
when running the command 'shopify extension serve', i am getting this error 
`X No available ports found to run extension`
Write a short description of the issue here ↓

## Expected behavior
Extension should run

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. shopify extension serve

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Post purchase Checkout Extension
- Operating System: Windows 8.1
- Shell: command prompt
- Ruby version (ruby -v): 2.7.3

**Comment by sandeshpaudyal** [comment]
I also got the same error while tryin serve the Shopify extension with command : "shopify extension serve"

**Comment by justCatalyst** [comment]
same problem here. Any solution?

**Comment by dani-sanomads** [comment]
Thanks
