### ISSUE TITLE
Online Store 2.0 - Set store url in config file

### ISSUE THREAD

**Issue by lorenzorivosecchi** [Shopify/shopify-cli#1340]
I am wondering if there is a way to have the CLI get the active store url from a config file (.env or whatever).

With Theme Kit i used to define the store url and other variables through a yaml file.
What's the equivalent for Online Store 2.0?

**Comment by macournoyer** [comment]
The equivalent now is to use one of:

- `shopify login --store STORE.myshopify.com`
- `SHOPIFY_STORE=STORE.myshopify.com shopify login`

There is no config file anymore.

**Comment by lorenzorivosecchi** [comment]
That's too bad
