### ISSUE TITLE
Syntax and extensions Errors when serve or push theme to the store 

### ISSUE THREAD

**Issue by PedroCampana** [Shopify/shopify-cli#1345]
Errors on multiple file extensions when push or serve dawn cloned theme. 

I have loged and init a dawn theme, when i try to serve in to shopify i receive Syntax errors.

1: theme init cloned the repository without problems. 
2: when i try theme serve i recieve 

ERROR update config/settings_data.json: No such file or directory @ rb_sysopen - config/settings_data.json
ERROR update config/settings_schema.json: No such file or directory @ rb_sysopen - config/settings_schema.json

3: I tried to theme push --nodelete i receive:

┃ ERROR update sections/apps.liquid:                                                                                                                                            
┃   Liquid syntax error (line 3): Syntax error in tag 'render' - Template name must be a quoted string                                                                          
┃ ERROR update sections/main-product.liquid:
┃   Liquid syntax error (line 74): Syntax error in tag 'render' - Template name must be a quoted string
┃ ERROR update templates/404.json:
┃   File extension is not valid for file templates/404.json
┃ ERROR update templates/blog.json:
┃   File extension is not valid for file templates/blog.json
┃ ERROR update templates/article.json:
┃   File extension is not valid for file templates/article.json
┃ ERROR update templates/cart.json:
┃   File extension is not valid for file templates/cart.json
┃ ERROR update templates/collection.json:
┃   File extension is not valid for file templates/collection.json
┃ ERROR update templates/index.json:
┃   File extension is not valid for file templates/index.json
┃ ERROR update templates/page.contact.json:
┃   File extension is not valid for file templates/page.contact.json
┃ ERROR update templates/list-collections.json:
┃   File extension is not valid for file templates/list-collections.json
┃ ERROR update templates/page.json:
┃   File extension is not valid for file templates/page.json
┃ ERROR update templates/password.json:
┃   File extension is not valid for file templates/password.json
┃ ERROR update templates/product.json:
┃   File extension is not valid for file templates/product.json
┃   Section type 'main-product' does not refer to an existing section file
┃ ERROR update templates/search.json:
┃   File extension is not valid for file templates/search.json

## Steps to reproduce the problem

1. Shopify theme login 
2. Shopify theme init
3. Shopify theme serve

<img width="1771" alt="Captura de Pantalla 2021-07-06 a la(s) 14 11 41" src="https://user-images.githubusercontent.com/86965463/124667076-e8eba380-de7c-11eb-9d04-e4dbc2a96afc.png">

- Operating System: macOS 10.15.7 
- Shell: Terminal
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by lorenzorivosecchi** [comment]
Same thing on

MacOS 11.4
Shell: zsh
Ruby: 2.7.2
Shopify-CLI: 2.0.1

**Comment by dabrorius** [comment]
I have the exact same problem:

MacOS 11.4
Ruby 2.7.4
Shopify-CLI 2.1.0

**Comment by macournoyer** [comment]
The root cause seem to have been that your store wasn't yet migrated to Online Store 2.0 https://help.shopify.com/en/manual/online-store/themes/os20/.

All stores should now have been migrated for a while. Please reopen if it happens again!

**Comment by shinyatentree** [comment]
For me it was working fine for the first time then when I re-create the same environment I start having this same problem. I tired to log out and login to the store but the problem is still there.

**Comment by Chewbacca222222** [comment]
I get the exact same issue when cloning Dawn (2.0 theme) and trying to upload that, any suggestions?

**Comment by asmerkin** [comment]
I'm not running it wrong. I'm using the latest CLI, and I see that the config/settings_data.json or config/settings_schema.json are completely ignored. 

```
DEBUG ignore config/settings_data.json
DEBUG ignore config/settings_data.json
DEBUG ignore config/settings_data.json
DEBUG ignore config/settings_data.json
DEBUG ignore config/settings_data.json
DEBUG ignore config/settings_data.json
```

if I go ahead and paste the content using the online editor, it works.
