### ISSUE TITLE
Shopify Theme Serve command renders no images or styles from local directory

### ISSUE THREAD

**Issue by whileymai** [Shopify/shopify-cli#1348]
# Issue summary

Write a short description of the issue here ↓

When running the command shopify theme serve to sync local theme, no local assets including css and js stored from local assets folder are rendered when previeiwing the site. Instead files are replaced with //cdn.shopify.com/shopifycloud/shopify CDN.

## Expected behavior

What do you think should happen?

Shopify theme serve should be able to link to files stored in local folders within the folder the command is run.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

<details>
All assets are replaced with '//cdn.shopify.com/shopifycloud/shopify' this is just part of the URL, causing no cs js files to be linked when previweing the site, i am using themekit aswell to sync changes to look at the complete site.
</details>

## Steps to reproduce the problem

1. run shopify theme serve
1. view preview site
1. Identify if assets from local directory are being linked too

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by martincarvalho** [comment]
Same here, all images are broken except .svg's loaded as <img> tags for some reason. 
If I access the generated IMG URL's I get a: "Transformation failed" error message
