### ISSUE TITLE
Cannot pull theme. Dozens of errors with image assets.

### ISSUE THREAD

**Issue by trev-dev** [Shopify/shopify-cli#1360]
Write a short description of the issue here ↓

I'm making multiple attempts to pull an existing theme from shopify and shopify-cli `shopify theme pull -i 12463859322` keeps throwing errors

Shopify Cli Version 2.0.2 installed via Ruby Gems 3.2.21

```bash
➜  general git:(master) ✗ shopify theme pull -i 1234567891011
┏━━ Pulling theme files from Swatch Debug Jul 8 (#1234567891011) on store.myshopify.com ━━━━━━━━━━━
┃                                                                                                         100%
┃ ERROR get assets/adobe-w-undyed.png: wrong number of arguments (given 4, expected 2..3)
┃ // About 50 more lines of this error for various image assets for the theme.
┃ ERROR get assets/white.png: wrong number of arguments (given 4, expected 2..3)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (72.51s) ━━
✓ Theme pulled successfully (Nope!)
```

**Comment by adrianocr** [comment]
I'm also having similar errors: 

```console
┃ ERROR get assets/0.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/6.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/favicon.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Clean.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/flex-icon.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/flex-icon.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Keto.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Gluten-Free.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/minus.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/minus1.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Non-GMO.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Paleo.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/password-page-background.jpg: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/plus.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/slick-theme.less: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/ssw-fontello.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/testimonial-icon.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Vegan.png: wrong number of arguments (given 4, expected 2..3)
```

**Comment by nitannn** [comment]
Getting the same error as well 👆🏽

**Comment by dgtlmonk** [comment]
It seems like this error doesn't appear if your theme is Online Store 2.0 compatible (dawn)

**Comment by DistantMemory** [comment]
+1

**Comment by lesterdefreitas** [comment]
+1

**Comment by dspeake** [comment]
+1

┃ ERROR get assets/editorial-new-regular.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/editorial-new-regular.woff2: wrong number of arguments (given 4, expected 2..3)

**Comment by EmbarkJosh** [comment]
+1

``` ShellSession
┃ ERROR get assets/algolia_dependency_fontawesome-webfont.eot: wrong number of arguments (given 4, expected 2..3)       
┃ ERROR get assets/algolia_dependency_fontawesome-webfont-ie-fix.eot: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/algolia_dependency_fontawesome-webfont.ttf: wrong number of arguments (given 4, expected 2..3)       
┃ ERROR get assets/algolia_dependency_fontawesome-webfont.woff: wrong number of arguments (given 4, expected 2..3)      
┃ ERROR get assets/big_noodle_titling.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/algolia_dependency_fontawesome-webfont.woff2: wrong number of arguments (given 4, expected 2..3)     
┃ ERROR get assets/black.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/dark-brown.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/favicon.png: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/flex-icon.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/flex-icon.woff: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/password-page-background.jpg: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Rubik-Bold.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Rubik-Italic.ttf: wrong number of arguments (given 4, expected 2..3)
┃ ERROR get assets/Rubik.ttf: wrong number of arguments (given 4, expected 2..3)
```
Expanded error details:
``` ShellSession
? ERROR get assets/algolia_dependency_fontawesome-webfont.eot: wrong number of arguments (given 4, expected 2..3)       
given : The term 'given' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is   
At line:1 char:91
+ ... ncy_fontawesome-webfont.eot: wrong number of arguments (given 4, expe ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (given:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by martinstonis** [comment]
+1 similar issue
Shopify CLI version 2.1.0

>┃ ERROR get assets/whitsunday-blue.png: wrong number of arguments (given 4, expected 2..3)
>┃ ERROR get assets/wild-watermelon.png: wrong number of arguments (given 4, expected 2..3)
>┃ ERROR get assets/yellow.png: wrong number of arguments (given 4, expected 2..3)

**Comment by martinstonis** [comment]
+1

**Comment by monaounagi** [comment]
+1
```
┃ ERROR get assets/password.jpg: wrong number of arguments (given 4, expected 2..3)
```

**Comment by lesterdefreitas** [comment]
> It seems like this error doesn't appear if your theme is Online Store 2.0 compatible (dawn)

Oh that's interesting, thanks for the observation. I hope that doesn't mean that Shopify will give this a low priority though. Working with non Online Store 2.0 themes is still going to be a part of the workflow for developers for a long time. Heck we even have some clients with themes so old they don't even use sections at all!

It would be frustrating to have to switch between themekit and cli for these different scenarios.

**Comment by dspeake** [comment]
It appears to be related to the files themselves. For the store I have an issue with, I just uploaded Dawn and pulled the theme successfully. When I uploaded password.jpg to that same theme though, the error returns for that file.

[This is the image.](https://cdn.shopify.com/s/files/1/0512/2080/7832/t/7/assets/password.jpg)

**Comment by lesterdefreitas** [comment]
@fabiancpl [This solution](https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-891081572) does seem to work for now. It's not ideal of course but it seems to be the only way for now to deal with this problem when it arises.

**Comment by aodreman** [comment]
I am getting the same error with password.jpg, which is a file that comes with the theme, this is happening with the initial pull.

**Comment by AlternatePro** [comment]
I found another workaround.. but still testing it. Like many above, I could not do a pull request without a boatload of asset parameter issues.. I tried the various 'solutions' linked above but none resolved the problem.. So to get this working correctly I download the theme direct from Shopify using the theme export function and then unzipped the theme to my development folder and did a CLI push of the downloaded theme back up to Shopify. I can now do pull requests without the asset issues. However, if you add an app you may need to re-export the Shopify theme and do the process again to get this to work again and again.

**Comment by austinhutchison** [comment]
I have this issue as well for images and fonts in the assets folder

When trying the solution in [1361](https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-891081572) it stalled on 99% on the first attempt, and then on the second attempt gave the same error.

**Comment by lesterdefreitas** [comment]
> FWIW, I just upgraded shopify-cli from 2.2.2 to 2.3.0 and no longer see the previous errors I encountered. I can't say for sure this is what fixed it, though I hadn't done anything else so it seems to be the reason. YMMV, but it seems worth checking your version if you continue to see this issue.

@jgiordanoGG Oh that's awesome. My problem though is that I'm currently stuck on MacOS 10.13 and it doesn't look like I can update the cli to that version becuase it keeps throwing an error when trying to update one of the dependencies, openssl. By any chance does anyone have a solution for me on that one besides the obvious (getting a new computer)? 😅

**Comment by austinhutchison** [comment]
Updating to 2.3.0 worked for me! 

@lesterdefreitas  I can't say for sure but you could try updating 2.2.2 with the changes made in the PR here: https://github.com/Shopify/shopify-cli/pull/1319

**Comment by trev-dev** [comment]
I spent some time with shopify-cli 2.4 myself here and was also able to work without this issue. It's good to keep your gems up-to-date :)

Closing this for now.
