### ISSUE TITLE
Populate * not working

### ISSUE THREAD

**Issue by designifyer** [Shopify/shopify-cli#1363]
# Issue summary
Is anybody else experiencing this?
I get 404 error when I run `shopify populate [object]`

## Expected behavior

It should populate the store with the selected object (products, draft orders etc.)

## Actual behavior

I get this error:
<details>This command ran with ID: 50530
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        37: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/bin/shopify:32:in `<main>'
        36: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        35: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        34: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/bin/shopify:33:in `block in <main>'
        33: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/entry_point.rb:23:in `call'
        32: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/monorail.rb:32:in `log'
        31: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        30: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/core/executor.rb:15:in `call'
        29: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        28: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        27: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        26: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        25: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        24: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        23: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        22: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        21: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        20: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        19: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        18: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        17: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        16: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/command.rb:19:in `call'
        15: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
        14: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api/populate_resource_command.rb:33:in `call'
        13: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api/populate_resource_command.rb:102:in `input_options'
        12: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api/populate_resource_command.rb:113:in `schema'
        11: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api/schema.rb:10:in `get'
        10: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api.rb:43:in `query'
         9: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         8: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api.rb:42:in `block in query'
         7: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api.rb:117:in `api_client'
         6: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api.rb:143:in `fetch_api_version'
         5: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         4: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/admin_api.rb:136:in `block in fetch_api_version'
         3: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/api.rb:36:in `query'
         2: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/api.rb:86:in `request'
         1: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.0.2/lib/shopify-cli/api.rb:74:in `block in request': 404 (ShopifyCli::API::APIRequestNotFoundError)
{"errors":"Not Found"}</details>

## Steps to reproduce the problem

1.Run shopify populate command

## Reduced test case

None

## Specifications

- Operating System: macOS Catalina
- Ruby version (ruby -v): ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

**Comment by javimata** [comment]
update shopify-cli, if use another lang different to english in the version 2.0.1 have this error, need update to 2.0.2 or put language to english

**Comment by designifyer** [comment]
@javimata I have v 2.0.2 & the language is set to EN

**Comment by dailyfreshvending** [comment]
Any insights on this? Still not working
