### ISSUE TITLE
shopify-CLI shows two accounts on login

### ISSUE THREAD

**Issue by NikitaZanella** [Shopify/shopify-cli#1364]
# Issue summary

2 days ago I've noticed that my partner account got 2 account linked (with the same email address). I've contacted the Shopify Partner Support and they removed the unused account, but Shopify CLI shows both the accounts on "shopify login --store".

The Shopify Partner Support removed the unused account correctly. In fact, in the Shopify partner dashboard, when I click on the top right icon (profile), I don't see the second account anymore. Everything is fine.

## Expected behavior

The expected behavior is to see only the main account in the Shopify CLI login.

## Actual behavior

When I log into a shop with Shopify CLI, the terminal shows both the accounts as below:

Output after cleaning browser cache and cookie + shopify logout:

`
C:\Users\nikit\Desktop\jst>shopify logout
Successfully logged out of your account

C:\Users\nikit\Desktop\jst>shopify whoami 
It doesn't appear that you're logged in. You must log into a partner organization or a store staff 
account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.     

C:\Users\nikit\Desktop\jst>shopify login --store=jst-theme.myshopify.com
? Select partner organization (Navigate up with 'k' and down with 'j', press Enter to select, filter with 'f')
> 1. Nikita Zanella (XXXXXXX)
  2. NikitaZanella (YYYYYYY)
`

The second account is the one deleted from the Shopify Support.

## Specifications

- Operating System: Windows 10
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
- Shopify-cli version: 2.0.2

**Comment by fbnhyn** [comment]
Same here

**Comment by pilotmsteele** [comment]
me too, very confusing

**Comment by stephszeto** [comment]
Related: https://github.com/Shopify/shopify-cli/issues/1513
