### ISSUE TITLE
Rails create failed on Windows

### ISSUE THREAD

**Issue by molotow11** [Shopify/shopify-cli#1365]
# Issue summary

Hello, I am using Windows 10 and trying to create new rails app

## Expected behavior

Successfully created pp

## Actual behavior

Creation failed
This last messages I see:
`? What database type would you like to use? Please ensure the database is installed. (You chose: PostgreSQL)`
`Database Type postgresql   `                                                     
`√ node v12.14.0`
`√ yarn 1.22.5`
`\ Installing rails gem…`
`**X System call failed: gem install rails -v <6.1**`

## Steps to reproduce the problem

1. type `shopify rails create` in shell
2. go through parameters
3. have this issue

## Specifications

- App type: Rails
- Operating System: Windows 10
- Shell: Power Shell
- Ruby version (ruby -v): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]

**Comment by tobymurray** [comment]
i think this is a limitation of PowerShell - you can try manually installing Rails (e.g. `gem install rails "-v <6.1"`) then retry?
