### ISSUE TITLE
Hot reload not always seeing latest scss changes

### ISSUE THREAD

**Issue by lesterdefreitas** [Shopify/shopify-cli#1366]
# Issue summary

Write a short description of the issue here ↓

When saving chagnes to scss files, the development theme reloads but doesn't show the changes until I save again and let it reload a second time.

## Expected behavior

What do you think should happen?

Hot reload should reload and show the latest changes you have just made to scss files.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

You have to save twice so that the hot reload runs twice to see your changes.

## Steps to reproduce the problem

1. Run `shopify theme serve`
2. Make a change to an scss file stored locally and save.
3. Check the theme preview to see if the changes have reflected.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: N/A
- Operating System: Mac OS 10.13.6
- Shell: Terminal
- Ruby version (ruby -v): ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]

**Comment by macournoyer** [comment]
The `theme serve` command was designed to work with Online Store 2.0 themes. [Scss support has been deprecated](https://www.shopify.ca/partners/blog/deprecating-sass), and so will not be supported by this command.

You can still use [Theme Kit](https://shopify.dev/themes/tools/theme-kit) on older themes.
