### ISSUE TITLE
ignore_files in config.yml

### ISSUE THREAD

**Issue by adamclasic** [Shopify/shopify-cli#1367]
# Issue summary

Shopify CLI is unable to ignore files listed in config.yml both in `shopify theme` and `shopify extension` commands (`serve | pull | push `)

as for now only config/settings_data.json is being ignored by default

## Expected behavior

What do you think should happen?

files and directories should be ignored just like in Theme Kit

What actually happens?

 `<details>
ERROR update webpack/package.json:
┃   404
┃ ERROR update webpack/package-lock.json:
┃   404
</details>` 

## Specifications

- App type: node, theme extension and theme.
- Operating System: ubuntu 20.04
- Shell:
- Ruby version (ruby -v): 3.0.1

**Comment by knynkwl** [comment]
+1

**Comment by knynkwl** [comment]
btw maybe the title should be updated to reflect a closer-to-the-issue name? "Ignore Files/Folders option" just a thought

**Comment by bigskillet** [comment]
Shopify CLI uses `.shopifyignore` to exclude files:
https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli
