### ISSUE TITLE
Shopify Github Integration App not connecting

### ISSUE THREAD

**Issue by climbandfocus** [Shopify/shopify-cli#1371]
# Issue summary

Have tried to connect my development store to my Github account to load up the new Dawn theme, however keep getting this error (attached)

--Yes I am logged in as a staff member that I created by my Partner account
--Yes it has full account privileges
--Yes I have tried revoking and re-authorizing the connection 

Not sure what else to try.

![Annotation 2021-07-12 165039](https://user-images.githubusercontent.com/25091948/125365494-99502080-e331-11eb-8194-bffd7849d2ae.png)

**Comment by pilotmsteele** [comment]
same problem for me...

**Comment by timwf** [comment]
Me too!

**Comment by concordadams** [comment]
Same problem here. Happening on multiple stores in our partners account.

**Comment by climbandfocus** [comment]
Must have been hotfixed - it worked for me today.

**Comment by trenkwill** [comment]
Well I'm still having the issue on my side

**Comment by climbandfocus** [comment]
@trenkwill not sure, I did nothing different trying to establish the app connection besides waiting a few days.

**Comment by trenkwill** [comment]
Thanks for reopening the issue.
I've waited a couple of days and still can't connect with most of my stores..
It worked on one though!!

So not sure what's going on...
