### ISSUE TITLE
Hot Reload + Login Issues

### ISSUE THREAD

**Issue by Kcharle** [Shopify/shopify-cli#1392]
# Issue summary

Write a short description of the issue here ↓

- Shopify CLI hot reload stops working upon attempting customer login.
- Login redirects to login page even when using correct credentials

## Expected behavior

What do you think should happen?

After logging into a customer account when running `shopify theme serve` I should

- Be redirected to the value I have set on my hidden input with the name `return_url` which is `/accounts` therefore `127.0.0.1:9292/accounts`
- Hot reload on the `shopify theme serve` command should still detect new updates and reload my browser displaying the updates.

## Actual behaviour

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

After trying to login to a customer account when running `shopify theme serve` 

- I am redirected back to the login page without any errors, but not logged in, meaning I can't view my "Account" page.
- The hot reload functionality stops working completely, no further changes are reflected upon saving pages. The page appears to refresh but nothing visually changes (removing content, styling changes, etc)

## Steps to reproduce the problem

1. Run `shopify theme serve`
2. Try logging in to a customer account
3. Verify that you can or cannot see further changes to templates via Hot reload
4. Verify you are actually logged in to your customer account.

## Specifications

- App type: Dev Store
- Operating System: Windows 10 / WSL 2
- Shell: ZSH
- Ruby version (ruby -v): 2.6.6

**Comment by tommypepsi** [comment]
> I have to press F5 each time I make some changes.

Same here, just tested it out. It seem to be refreshing the page automatically but the changes don't appear until I manually refresh the page.

**Comment by macournoyer** [comment]
The customer login issue should be fixed in https://github.com/Shopify/shopify-cli/pull/1480. Can you try again with the latest version, and reopen if that doesn't work.
