### ISSUE TITLE
Shopify theme serve unpublished theme

### ISSUE THREAD

**Issue by james0r** [Shopify/shopify-cli#1394]
# Issue summary

Is serving an unpublished theme currently possible? Sometimes when i'm dev'ing I'm wanting to use an unpublished theme with different customizer data than that of the published theme.

## Expected behavior

`shopify theme serve [theme id]`

## Actual behavior

No parameter is allowed for this `shopify theme serve` and customizer data is pulled from the published theme.

## Steps to reproduce the problem

1. Duplicate Dawn
2. Change customizer data for duplicate
3. `shopify theme pull` and select duplicate theme.
4. `shopify theme serve`
5. Observe customizer data from published theme while working on a development theme of the unpublished theme.

**Comment by juanpasolano** [comment]
I like this, I don't really understand the flow for custom theme devs.
The coupling between data and structure seems weird and dangerous to me. If I forget to pull the theme then I'll override data. Also It seems weird to save data in your repo, what if you want the theme in diff prod and dev stores

**Comment by karreiro** [comment]
Thanks for reporting this, @james0r! I'd like to clarify the upcoming updates in the CLI (introduced by #2174).

In the next CLI version, the `shopify theme serve --theme-editor-sync` command will serve the local theme and synchronize changes from the Theme Editor automatically into the local theme files.

However, considering this scenario:
1. Run `shopify theme pull -t my_theme`
2. Run `shopify theme serve --theme-editor-sync`
2. Notice the CLI is serving theme with the sync features activated

All changes introduced in the second step are applied to your **Development Theme** - a particular theme that the CLI relies on for development when we run `theme serve`, it doesn't appear in your Theme Library but appears when you run `shopify theme list`.

If you'd like to apply your changes on `my_theme` (from the first step), you may run:

```
shopify theme push -t my_theme
```

We're planning enhancements into the CLI UX to clarify the existence of this **Development Theme**. But, I hope this comment clarifies things a bit for now.

Please let me know if you have any questions or comments about that :)

**Comment by karreiro** [comment]
Hi @bakura10,

I have an update about the` --theme/-t` parameter; there's a PR introducing it in the `theme serve` command: https://github.com/Shopify/shopify-cli/pull/2336

We may expect that flag in the following CLI releases.

**Comment by bakura10** [comment]
Hi @karreiro ,

The shopifyignore was indeed the missing piece!

We are _nearly_ ready to delete ThemeKit, our only missing use case is the following: during theme development, our design team has one store for each demo store. When I push, I have a ThemeKit comment to push the code to three different stores. For now, I don't see how this could be done in Shopify Kit (this would require three different command that would each switch the theme.

I would like to be able to do that:

"shopify theme push --store store1.myshopify.com --theme=ID --store store2.myshopify.com --theme=ID"

Is there a workaround for this use case?

**Comment by bakura10** [comment]
But still, what is really missing to Shopify CLI is a proper support for env file. Being able to do that:

```
dev:
  store: foo.myshopify.com
  theme_id: 123

demo-store-1:
   store:demostore.myshopify.com
   theme_id: 345
```

And being able to launch a command for different env:

```
shopify theme serve --env=dev
shopify theme push // By default push to every store in the ".env", unless --env is set explicitly
```

The fact that I had to use an extra node library (dotenv) to manage env variables really does not satisfy me tbh :D

**Comment by bakura10** [comment]
Hi @karreiro,

Sorry to ping you about that again, but @dsnvs from my team is facing an issue. It seems that while the serve command does not synchronize the files specified in the .shopifyignore on update, it, however, ignores the file entirely when the command is run the first time.

We are using the following command:

```
shopify theme serve ./dist --theme=THEME_ID
```

Where THEME_ID is the ID of an unpublished theme.

Our .shopifyignore file is set as follow:

```
templates/*
config/*
```

To reproduce the issue:

1) Change global settings so that the config/settings_data.json changes
2) Launch the serve command
3) The setttings_/data.json is restored to whatever you have in your file

This unfortunately defeats the whole purpose of the .shopifyignore, as our content is constantly removed whenever we launch the command every morning :/. Is this expected @karreiro ?

**Comment by karreiro** [comment]
Thanks a lot for sharing these details, @bakura10.

I've tried to reproduce the issue with the latest version of the CLI, and it seems to work:

https://user-images.githubusercontent.com/1079279/183116820-c60ac83d-c277-4a92-bf5c-7533e2f10b35.mov

I'm not sure if I'm missing something in the steps to reproduce tho. Please let me know if I am :)

**Comment by bakura10** [comment]
Thanks, I will check with my co-worker. But when I tried, the issue was actually on the store (in your video you do not seem to check the actual store). @dsnvs can you check here if your issue is solved?

**Comment by dsnvs** [comment]
@karreiro I am not sure what/how, but a few days after I mentioned this problem to @bakura10, the issue was solved. It was fixed without updating the CLI (it was still 2.20.1 when I noticed the fix) so I am not sure what happened.

**Comment by bakura10** [comment]
I do not seem to be able to reproduce it neither, strange...

**Comment by karreiro** [comment]
@dsnvs @bakura10 np! If you ever notice that issue again, feel free to leave a comment here :)
