### ISSUE TITLE
Could not find a valid gem 'shopify-cli' (= 2.1.0), here is why

### ISSUE THREAD

**Issue by haunguyen1989** [Shopify/shopify-cli#1400]
# Issue summary

Write a short description of the issue here ↓
- Environment: Ubuntu 20.04 LTS
- Ruly: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
- We followed the shopify-cli installation instructions from https://shopify.dev/apps/tools/cli/installation.
`sudo apt install /path/to/download/shopify-cli-x.y.z.deb
`

## Expected behavior

What do you think should happen?
Install success

## Actual behavior

What actually happens?
ERROR:  Could not find a valid gem 'shopify-cli' (= 2.1.0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)
dpkg: error processing archive /home/hau/Downloads/shopify-cli-2.1.0.deb (--unpack):
 new shopify-cli package pre-installation script subprocess returned error exit status 2
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Open terminal run: gem install shopify-cli or sudo apt install ./shopify-cli-2.1.0.deb
2. Error:  Could not find a valid gem 'shopify-cli' (= 2.1.0), here is why:
![2021-07-21_11-29](https://user-images.githubusercontent.com/44774202/126433258-65583b9c-4c52-4bfe-8801-94aacb6e1aa3.png)

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by mkevinosullivan** [comment]
👋🏻 This looks like a timeout error with https://rubygems.org, from where `shopify-cli` is downloaded.  Have you tried again since?

**Comment by Xardasus** [comment]
rubygems.org can't be reached via IPv6 for some reason.
Try disabling IPv6 and try again.
