### ISSUE TITLE
Asset images break on theme push

### ISSUE THREAD

**Issue by gwhitcher** [Shopify/shopify-cli#1401]
# Issue summary
Asset images break on theme push.   

## Expected behavior
Images should upload through the CLI and work.  They are being corrupted.  If I do it through the Shopify web UI it works.  But as soon as I pull then push again it gets corrupted.

## Actual behavior
Asset mages break on upload from the CLI.  

## Steps to reproduce the problem
1. Add jpg image to the assets directory.
1. Run shopify theme push
1. View image on website or in asset directory and it will say "Transformation failed".

## Specifications
- App type: theme
- Operating System: Windows
- Shell: 2.1.0
- Ruby version (ruby -v): ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x64-mingw32]

**Comment by sergejcodes** [comment]
The CLI encodes all binary files (`jpg`, `png`, `woff` etc.) to Base64 before uploading them to the remote store. This is defined in [syncer.rb](https://github.com/Shopify/shopify-cli/blob/main/lib/shopify-cli/theme/syncer.rb#L225) 

If you upload e.g. a `jpg` file through the remote Shopify code editor and then run `shopify theme pull` to pull all theme files, the image is correctly decoded.

Likely it's an issue with the remote decoding process of the Base64 data after it's being received from the CLI syncer.

**Comment by macournoyer** [comment]
Sorry for the delay on this. I can't reproduce on macOS. Is it possible everyone experiencing this issue is on Windows?

**Comment by abmenzel** [comment]
> Sorry for the delay on this. I can't reproduce on macOS. Is it possible everyone experiencing this issue is on Windows?

I believe so. This is the case for me at least.

**Comment by opium-opiumoo** [comment]
> Sorry for the delay on this. I can't reproduce on macOS. Is it possible everyone experiencing this issue is on Windows?

I'm on Windows and all of my colleagues who are experiencing this issue are also on Windows.

**Comment by ineptian** [comment]
+1 on windows.

**Comment by gwhitcher** [comment]
Yes, I am on Windows

> Sorry for the delay on this. I can't reproduce on macOS. Is it possible everyone experiencing this issue is on Windows?
