### ISSUE TITLE
You are not authorized to edit themes on...

### ISSUE THREAD

**Issue by Blend-Jordan** [Shopify/shopify-cli#1412]
# Issue summary

Write a short description of the issue here ↓
I am trying to login with the cli and it dont authorise.

Steps im taking are:
shopify login
shopify login --store=STOREURL
shopify theme serve

Error:
✗ You are not authorized to edit themes on STOREURL
Make sure you are a user of that store, and allowed to edit themes.

I have tried reinstalling the cli, reinstalling homebrew, restarting.

It works for one of our shops in the partner account but none of the others.

Any help appreciated
Thanks.

## Specifications

- Operating System: MacOS
- CLI version 2.1.0

**Comment by johnsfuller** [comment]
@Blend-Jordan So I figured out the issue (at least for me) and these are the steps to avoid the unauthorized error: 
1. I had to create a staff account with my email and give it theme permissions (I just gave it all permissions) per these ["Before You Start" instructions](https://shopify.dev/themes/getting-started/create#before-you-start)
2. run `shopify logout`
3. run `shopify login --store=<store-name>`
4. run `shopify theme serve`

It seems counter-intuitive to create a staff account when I'm logged in via a partner account that has admin permissions, but a staff account is necessary. I'm curious as to why @shopify-admins designed it this way.

**Comment by artyrcheek** [comment]
yeah @johnsfuller's solution worked for me.
Seems a bit annoying that we have to create a staff account though @shopify-admins ??

**Comment by jdunham2** [comment]
Just to add to this, if like me you have multiple partner accounts tied to a single sign-in on Shopify... make sure to try all the partner organizations from the cli and running the commands.

I found my newly created staff account got tied to a partner account I haven't used in about a year. Shopify wasn't able to remove the accounts last I checked with them (about a year ago again).

**Comment by jdunham2** [comment]
Im finding non of my accounts work for some stores... This looks like could be related to #1718 1718

**Comment by rhys-vdw** [comment]
I had this issue when I transferred the account over to the client. Even though I had full permissions I had to log out and log back in again for the CLI to permit me to serve the theme. Thanks for the tip @johnsfuller

**Comment by zubairahmed25** [comment]
This is how I got it solved

Ctrl+Shift+H on Mac -> Go to your local folder -> Ctrl+Shft+. (period) -> Look for .cache -> Delete shopify folder 

This will delete any cache from shopify-cli and you'd be able to log in.

**Comment by boothkittson** [comment]
Nope, doesn't work.  How the hell can I get working from the Shopify CLI?
