### ISSUE TITLE
shopify theme serve - infinite redirect

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/shopify-cli#1415]
# Issue summary

Write a short description of the issue here ↓
When trying to access the local URL that `shopify theme serve` gives you (`http://127.0.0.1:9292`) it puts you in an infinite redirect loop.

## Expected behavior

What do you think should happen?
It should allow me to access the site

## Actual behavior

What actually happens?

Infinite redirect loop
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/7152041/127496039-a19bcc6c-206e-491a-ac2a-57cdf86ab870.png">
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/7152041/127496404-5554c99b-0f66-4765-aa48-e2d5811e8be3.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/7152041/127496460-51935759-5d82-4327-8e75-9422ed541306.png">
<img width="548" alt="image" src="https://user-images.githubusercontent.com/7152041/127496479-6db3bfcd-69df-44d7-aefe-9e4b792a0983.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/7152041/127496497-ccb26a2c-793a-46d0-a292-d8c4a31f6ab3.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/7152041/127496530-612d8e3a-99e9-425b-a082-29939b3afc48.png">

## Steps to reproduce the problem

1. run `shopify theme serve` on any project
2. visit `http://127.0.0.1:9292`

**Comment by younessidbakkasse** [comment]
I have the same issue.

**Comment by younessidbakkasse** [comment]
I solved the issue by changing my organisation, it's probably due to access problems.

**Comment by macournoyer** [comment]
This might have something to do with the shop being password protected. Did you log in as staff prior to this happening by any change? Might be related to #1333.
