### ISSUE TITLE
CLI crashes if there is no program to handle the protocol on login

### ISSUE THREAD

**Issue by brett-uaudio** [Shopify/shopify-cli#1425]
# Issue summary

Write a short description of the issue here ↓

The CLI crashes on login if `xdg-open` can't find a suitable program to handle https(?)

## Expected behavior

What do you think should happen?

I should be able to login successfully on a remote machine when there is no suitable program available to `xdg-open` by pasting a URL that gets printed to the console  in a local machine's browser with a suitable tunnel or other way to get the localhost:3456 call back to the remote server with the running CLI. This is part of setting up a Bamboo CI plan. We successfully got this to work in a Docker container, probably because it didn't have `xdg-open` installed.

## Actual behavior

What actually happens?

The CLI crashes and prints the flow URL to the console. 

## Steps to reproduce the problem

1. Have a remote Linux machine with `xdg-open` installed but no programs to handle the protocol (I assume it's https, but I'm not sure).
2. Run `shopify login --shop=SHOP`.
3. The CLI will crash and print out the URL for the flow.

## Specifications

- App type:
- Operating System: Ubuntu 16.04.7 LTS
- Shell: GNU bash, version 4.3.48(1)-release
- Ruby version (ruby -v): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38)

**Comment by mkevinosullivan** [comment]
@brett-uaudio Please share the compete output from the CLI when it crashes.

**Comment by axis80** [comment]
I would also point out that Heroku handles this with a `--interactive` login switch.  So, when you specify this command, they will prompt for username and password at the command line:

`heroku login --interactive`

**Comment by dsychin** [comment]
I am facing the same issue where my development environment is running Linux on Windows with WSL. There is no browser inside WSL but I also can't use the link the error spits out because the callback url does not work since the command just exits immediately.

**Comment by axis80** [comment]
Wow, thanks @dsychin!  I uninstalled xdg-open from my Ubuntu machine using `sudo apt-get remove --auto-remove xdg-utils` and that restored the old behavior.  I am now able to use my clunky workaround (described above) to log in.

To be clear: it'd be ideal if the Shopify CLI team could add a `shopify login --interactive` login method.  In the meantime, though, at least there is some sort of workaround, as clunky as it may be.
