### ISSUE TITLE
Themes - Feature Request: Add flag for setting Theme's name

### ISSUE THREAD

**Issue by sdn90** [Shopify/shopify-cli#1431]
I'm interested in using the Theme CLI for creating development theme's for Pull Requests and need to be able to put an identifier for the Pull Request in the name so I don't have to store an ID somewhere.

I'm aware that this is possible to create through the unstable API but it would be great to simplify things and use the CLI for everything.

**Comment by dylansmith** [comment]
Agree, I also want to be able to push to a new unpublished theme within our CI pipeline, but there is no way to supply the new theme name via an argument.

**Comment by dylansmith** [comment]
@sdn90 @gideonb by the way, there is a workaround for CI scripting:

```sh
printf 'Your Theme v1.2.3' | shopify theme push -u
```
