### ISSUE TITLE
Local customized theme's data not being saved in settings_data.json

### ISSUE THREAD

**Issue by iRabi** [Shopify/shopify-cli#1434]
# Issue summary

We can view the development them in _http://127.0.0.1:9292/_ and changes made in _https://[sitename].myshopify.com/admin/themes/12345xxxxxx/editor_ are also reflected in http://127.0.0.1:9292/ once saved but the values are not being saved in settings_data.json

So, when 'shopify theme push' is executed in CLI no customized changes are uploaded in live theme.

## Expected behavior
All changes that are saved and reflected in _http://127.0.0.1:9292/_ must be saved in _settings_data.json_ and pushed to live site.

## Actual behavior
Customized changes from editor are not being saved in local _settings_data.json_ and when theme is pushed there is not any change visible in live site.

## Steps to reproduce the problem

1. Serve the theme in localhost (CLI > 'shopify theme serve')
2. Customize theme in editor 
3. Save, stop theme serve and push it in live (CLI > 'shopify theme push')

**Comment by princelauvaka** [comment]
After some investigation, it looks like the `shopify theme serve` is not really a 2 way sync.
So whatever gets saved in the customizer during your `shopify theme serve` is only saved online, this means you'll have to **pull** the theme to get the online changes to your local while your still in this serve.

Once you **stop** your serve, the online customizer data is gone,
but you'll have a copy of the online customize data if you have pulled it during the serve.

https://shopify.dev/themes/tools/cli/theme-commands#pull

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
This is a problem and needs to be addressed.

**Comment by opium-opiumoo** [comment]
+1 on Windows

**Comment by tomthatwebagency** [comment]
BUMP +1 this a million. After working on a theme it doesnt make sense to have to pull before you push, why cant local files stay in sync with remote?

**Comment by opium-opiumoo** [comment]
@macournoyer do you have any update on this?

**Comment by macournoyer** [comment]
`theme serve` is indeed a one way sync for now. It will only upload your local files to the Online Store.

To clarify, what you want is to pull the changes made to `config/settings_data.json` in https://[sitename].myshopify.com/admin/themes/12345xxxxxx/editor, and override the local copy on disk?

Would that cover everyone's use case here?

**Comment by tomthatwebagency** [comment]
@macournoyer definitely would! usual flow would be a combination of theme customizer and visual studio code to complete the theme, at the end if we forget and then push the code to store we override any customizer settings we did. 

i guess we either need to have an option to pull the settings data locally when finished or exclude that file from a push?

**Comment by iRabi** [comment]
@macournoyer, I agree, this option ll be better solution for now “i guess we either need to have an option to pull the settings data locally when finished or exclude that file from a push?”.

**Comment by iRabi** [comment]
@macournoyer, yes whatever we see in _http://127.0.0.1:9292/_ after customizing in _https://[sitename].myshopify.com/admin/themes/12345xxxxxx/editor [development (draft)]_ section should be saved or pulled in local _settings_data.json.

And as @tomthatwebagency's suggestion it ll be better if we can have an option to save/pull the _settings_data.json_ locally when finished and even better if some CLI command is provided to include/exclude that file to push into live theme.

**Comment by 1aurabrown** [comment]
I'm in the process of migrating my custom boilerplate theme to Online Store 2.0 for the first time, and I'm really not understanding how to develop a theme for a client, setting up all content for them as I build the site, and then hand over a store with a live theme, with all data in place. Every time I start up the development theme, I have to set up theme settings all over again. How can this be avoided? I'm still a little fuzzy on how all these new pieces of tooling fit together.

**Comment by abmenzel** [comment]
I had a similar problem, my approach was to pull the changed .json files whenever I terminate the local server (If I have modified the files in the customizer). I ignore every other file by using the `-x` flag.  In my own setup I have this saved as a script in my `package.json` to make it easy to run.

```
shopify theme pull --nodelete -x 'assets/*' -x 'layout/*' -x 'locales/*' -x 'sections/*' -x 'snippets/*' -x 'templates/*.liquid' -x 'config/settings_schema.json' 
```

**Comment by pablogiralt** [comment]
@abmenzel where do you save your package.json? I get a 404 error on serve after creating this file.  Do you add your package.json in a folder above the theme folder?

**Comment by pinguluk** [comment]
> I had a similar problem, my approach was to pull the changed .json files whenever I terminate the local server (If I have modified the files in the customizer). I ignore every other file by using the `-x` flag. In my own setup I have this saved as a script in my `package.json` to make it easy to run.
> 
> ```
> shopify theme pull --nodelete -x 'assets/*' -x 'layout/*' -x 'locales/*' -x 'sections/*' -x 'snippets/*' -x 'templates/*.liquid' -x 'config/settings_schema.json' 
> ```

Is the command automatically executed when the local server is terminated? How do you do that? Or do you manually execute it?

**Comment by abmenzel** [comment]
@pinguluk I manually execute it (and sometimes forget). I haven't looked into ways of automatically executing it when the local server is terminated. Maybe this discussion can help https://stackoverflow.com/questions/37571997/nodejs-run-command-when-script-is-terminated

**Comment by squadcar** [comment]
Has this gotten anywhere? Using the CLI for the first time, and while it's a fairly drastic improvement, losing a few hours worth of theme settings/data is a pretty horrible thing to find out the hard way. Obviously theme pull right before closing the session works, but given it's a non-recoverable sort of thing if you forget, it seems like this should be a bigger issue...

**Comment by mikez93** [comment]
@MaxDesignFR thanks for that detail. I think adding the "--development" theme name to the command is helpful so shopify CLI knows from which theme to pull the settings files. This solves the issue for me. It's not that hard to remember to run the above command prior to committing updates to Git.

1) set up shopify CLI
2) start "theme serve"
3) make local code changes
4) make settings changes via the temp settings UI - not local
5) pull changes from the temp theme on server (shopify labeled this theme as "development")
6) commit changed .json files to the local git repo
7) quit shopify local theme serve process (AFTER COMMITING pulled changes to Git)
8) push changes to GitHub 
9) all code changes made locally AND settings changes made via the UI are reflected in the connected them on shopify.

BTW - I have not verified that the above command will get every change made via the settings UI into your local code base so make sure to test it incrementally as you make changes.
