### ISSUE TITLE
Shopify cli Login and authenticate is not working

### ISSUE THREAD

**Issue by khaliluttara** [Shopify/shopify-cli#1437]
I am facing a little bit errors. Please help me .... ... I am using windows10 pro
![cliproblem](https://user-images.githubusercontent.com/19252183/128655567-0ca27c58-4621-4cb4-ac87-3528d87e0c24.PNG)

**Comment by evaldas-raisutis** [comment]
Interesting, mine is similar, but different. Windows 10 (with ruby dev stuff installed)

![image](https://user-images.githubusercontent.com/3714332/129905894-2ce8df80-96a3-4a66-a2a6-4b512bdbd879.png)

**Comment by yomnashaban** [comment]
same here, any help with that ?
