### ISSUE TITLE
shopify command line hangs on cygwin

### ISSUE THREAD

**Issue by jamesbeninger** [Shopify/shopify-cli#1438]
# Issue summary

Write a short description of the issue here ↓

When I run `shopify.bat version` or any other shopify command in a cygwin terminal, it hangs with no response.

**Fix**
I was able to get this running with the following edits:
**/Shopify CLI/vendor/deps/cli-ui/lib/cli/ui/os.rb**: Add "when /cygwin/" right below `when /mingw32/`

**/Shopify CLI/vendor/deps/cli-kit/lib/cli/kit/system.rb**: Add "return :windows if /cygwin/.match(RUBY_PLATFORM)" right below "return :windows if /mingw32/.match(RUBY_PLATFORM)"

## Expected behavior

What do you think should happen?
The command should run normally.

## Actual behavior

What actually happens?
It hangs.  When I run the gem manually with "ruby -I /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/ /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify", I get:

<details>
Traceback (most recent call last):
        20: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify:30:in `<main>'
        19: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify:30:in `require_relative'
        18: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/load_shopify.rb:18:in `<top (required)>'
        17: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify:9:in `require'
        16: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        15: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        14: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/lib/shopify_cli.rb:24:in `<top (required)>'
        13: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify:9:in `require'
        12: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        11: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        10: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui.rb:1:in `<top (required)>'
         9: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui.rb:2:in `<module:CLI>'
         8: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui.rb:19:in `<module:UI>'
         7: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/bin/shopify:9:in `require'
         6: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         5: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         4: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:4:in `<top (required)>'
         3: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:5:in `<module:CLI>'
         2: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:6:in `<module:UI>'
         1: from /cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:13:in `<module:Spinner>'
/cygdrive/c/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.2.0/vendor/deps/cli-ui/lib/cli/ui/os.rb:15:in `current': Could not determine OS from platform x86_64-cygwin (RuntimeError)
</details>

## Steps to reproduce the problem

1. run `shopify.bat version` in a cygwin terminal

## Specifications

- App type:  N/A
- Operating System: Windows 10
- Shell: cygwin
- Ruby version (ruby -v): 2.6.4

**Comment by gonzaloriestra** [comment]
I've tried to improve the support for Cygwin as part of https://github.com/Shopify/shopify-cli/pull/1983, but I've checked that `RUBY_PLATFORM` doesn't always return `cygwin`, and depending on the case, it could behave like Linux or Windows. It will require deeper research.
