### ISSUE TITLE
Shopify pulls non-existent css and scss files

### ISSUE THREAD

**Issue by opium-opiumoo** [Shopify/shopify-cli#1442]
# Issue summary

Write a short description of the issue here ↓

When I'm setting my theme Shopify pulls css and scss versions of my css.liquid and scss.liquid files which brakes the whole css of the shop and makes conflict in the log. Happens with js too. This has started when I integrated GitHub and started using Shopify CLI.

## Expected behavior

What do you think should happen?

All the .css and .scss files must be ignored and we should be able to pull only .css.liquid and .scss.liquid files.

## Actual behavior

What actually happens?

Additional css and scss (sometimes and js files) which break the css and scss.

## Steps to reproduce the problem

1. Extract a zip file of the theme
2. Create a new branch in your shop and paste all the theme files there
3. Try merging with your live theme
4. You have additional css and scss (possibly js too) that break your whole store

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Shopify CLI and GitHub Integration
- Operating System: Windows 10
- Shell: Git Bash
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by opium-opiumoo** [comment]
![Capture](https://user-images.githubusercontent.com/74781116/128831989-9d5846ad-e05d-4c1a-98e7-d583f20f557c.JPG)

As you can see there are two files that are not appearing in the Shopify Code Editor. I'm assuming Shopify generates them automatically from the .liquid ones and when I'm pushing my local theme it breaks the whole store.

**Comment by lesterdefreitas** [comment]
So glad to find someone else talking about this issue. I've been experiencing this too. Up until now I've had to just revert the commit that comes from the Shopify bot where the non-liquid files are generated. That seems to solve the problem going forward. But it is very annoying and should be fixed!
