### ISSUE TITLE
Create theme blank

### ISSUE THREAD

**Issue by Dev2637** [Shopify/shopify-cli#1446]
# Issue summary

I can't find a init theme blank command anywhere?

Is there a command to create a blank theme with required files and folders like themekit?

https://shopify.dev/themes/tools/cli/theme-commands

**Comment by macournoyer** [comment]
We don't offer a blank theme at the moment. Our current starting theme is [Dawn](https://github.com/Shopify/dawn).

But you can use any starter theme on Git you want using the `init` command:

```
shopify theme init --clone-url=GIT_URL
```
