### ISSUE TITLE
"Theme Pull" command adds new lines on Windows

### ISSUE THREAD

**Issue by ozanmeral** [Shopify/shopify-cli#1453]
# Issue summary

Simply trying to pull an existing theme and it adds new blank lines to some files.

![image](https://user-images.githubusercontent.com/27968849/129559201-c15de65e-adac-4f85-8843-29b7ad5cc21a.png)

## Specifications

- Operating System: Windows 10

**Comment by albjes** [comment]
Same problem in Windows 10

**Comment by stefano-tonanni** [comment]
Same problem here Windows 10.
Really annoying, makes the cli totally unusable with git

**Comment by karreiro** [comment]
Thank you for reporting this, @ozanmeral!

I'm trying to reproduce this issue locally, but I'm having a challenging time with that, as it seems to work here:

<img width="80%" alt="demo" src="https://user-images.githubusercontent.com/1079279/148922401-b9be7caf-6e56-422f-b99c-ce7d95180521.gif">

Am I missing something in the steps to reproduce? (in the Gif above, I'm using Windows 10 too).

Also, could you please share your `ruby`, `shopify`, and `git` versions (like the following image shows)?

<img width="80%" alt="version" src="https://user-images.githubusercontent.com/1079279/148922947-3e6e499f-35f2-4123-b043-097937ed682c.png">

@albjes, @wllmdeemer, @stefano-tonanni, please, feel free to share those versions as well - that would help a lot!

**Comment by vfxjohow** [comment]
I am having the same problem.

Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
Shopify CLI: 2.8.0
Git: git version 2.31.1.windows.1

**Comment by lesterdefreitas** [comment]
@karreiro is this issue now resolved though?

**Comment by karreiro** [comment]
Hi @lesterdefreitas! Thanks for reaching out!

Yes, it is [solved](https://github.com/Shopify/shopify-cli/pull/1937) now. Regarding your question:

> So in your case @karreiro it might be that the last push was from a Windows PC?

No, in the Gif I attached to the [PR solving this](https://github.com/Shopify/shopify-cli/pull/1937), the last push was from a Unix (macOS) system.

Also, while that PR is merged, the latest version of CLI doesn't include it. This fix will be available on the very next CLI release.

Regarding the fix itself, we're adopting an approach quite similar to the LF normalization you've mentioned (however, at CLI `pull`/`push` phases).

Finally, please, don't hesitate to report any issue or even leave a comment here if you notice anything odd in the CLI! :)
