### ISSUE TITLE
Shopify theme serve failing to process images from Assets folder

### ISSUE THREAD

**Issue by blindbeat** [Shopify/shopify-cli#1455]
It gives "transformation failed" instead of an image

my code is:
  img src="{{ 'palm-tree.png' | asset_img_url: '300x' }}" alt="Image of a Tree Palm"

On production i get normal image, but on localhost while developing all i have is this 
![image](https://user-images.githubusercontent.com/33102966/129630268-503f5389-f24a-4a73-89c8-ec3954665948.png)

## Specifications

- Operating System: Windows
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by opium-opiumoo** [comment]
Hello,

This is already being worked on. You can see more in this issue thread [https://github.com/Shopify/shopify-cli/issues/1401](url)
