### ISSUE TITLE
Credentials generated by Theme Kit Access App do not work

### ISSUE THREAD

**Issue by visnaut** [Shopify/shopify-cli#1456]
# Issue summary

When inputting a password generated by the Theme Kit Access app, using the `--password` flag or `SHOPIFY_PASSWORD` env variable in CI, the cli logs in successfully, but fails when performing any theme command.

Utilizing the CI-based login is useful for teams that have dockerized tooling, and Theme Kit Access is a great way of managing those credentials amongst a team.

## Expected behavior

The Shopify CLI is able to perform theme commands when utilizing credentials generated by Theme Kit Access.

## Actual behavior

When performing any theme command, after having authenticated with credentials provided by Theme Kit Access, shopify-cli returns the following error:
```bash
✗ Please login again with shopify login
```

## Steps to reproduce the problem

1. Create a development store
1. Install [Theme Kit Access](https://apps.shopify.com/theme-kit-access?shpxid=549cfbe2-6869-40C2-8F5A-3E706F10258C)
1. Generate new credentials
1. Logout of any existing sessions in Shopify CLI:
   - ```bash
     $ shopify logout
     ```
1. Login using CI mode:
   - ```bash
     $ export CI=1
     $ export SHOPIFY_SHOP=development-store.myshopify.com
     $ export SHOPIFY_PASSWORD=shptka_0123456789abcdef0123456789abcdef
     $ shopify login
     ```
1. Verify login status:
   - ```bash
     $ shopify whoami
     Logged into store development-store.myshopify.com as staff (no partner organizations available for this login)
     ```
1. Perform a theme command:
   - ```bash
     $ shopify theme serve
     ✗ Please login again with shopify login
     ```

## Specifications

- App type: `theme`
- Operating System: `x86_64-apple-darwin19`
- Shell: `fish`
- Ruby version (ruby -v): `ruby-3.0.0`

**Comment by attaboy** [comment]
Hi @visnaut. Passwords generated by Theme Kit Access are only compatible with [Theme Kit](https://github.com/Shopify/themekit), our legacy theme development tool. Shopify CLI uses a different authentication process, and it can't use Theme Kit passwords to login.
