### ISSUE TITLE
No ability to set a custom port for ngrok tunnel

### ISSUE THREAD

**Issue by kellyvaughn** [Shopify/shopify-cli#1459]
# Issue summary

There's currently no ability to set change the port from 8081 when running `shopify node serve`. As a result, there's no change in the ngrok URL that's generated, which may be in use by another app that's being locally developed.

## Expected behavior

Either by use of a `--port` flag or reading the `PORT` environment variable in the .env file, a different ngrok tunnel should be started based on the specified port (with perhaps a fallback to 8081).

## Actual behavior

What actually happens?

The port is hard coded to 8081 regardless of what is set in the .env file, which creates the same tunnel previously created. It (of course) crashes if you attempt to add a `--port` flag that doesn't exist.

## Steps to reproduce the problem

1. run `shopify node serve` without a specified port
2. ngrok starts up on port 8081 (or continues running on port 8081 if previously started)

## Specifications

- App type: `node`
- Shell: `zsh`
- Ruby version (ruby -v): `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]`

**Comment by molly-yu** [comment]
I noticed that other serve commands (e.g. rails serve) have the same issue, we will probably have to add the custom port for those as well.
