### ISSUE TITLE
Shopify login command shows inactive Partner Account

### ISSUE THREAD

**Issue by tallyecom** [Shopify/shopify-cli#1513]
# Issue summary
Shopify login command shows inactive Partner Account
Write a short description of the issue here ↓
by mistake, I'd created 2 Partner Accounts while playing around with Shopify, and it was giving troubles as I didn't want to use the extra 1, hence contacted partner support and got it duly deactivated, and it doesn't show on any of the browsers I use.

but CLI shows it up as soon as I log in with the Shopify login command for selection.

## Expected behaviour
the deactivated account should not show up in CLI

What do you think should happen?
Only Active Account should show up in the CLI

## Actual behaviour
both the account (active as well as inactive) shows up for selection
What actually happens?
both the account (active as well as inactive) shows up for selection 
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>
though this is an error, there is no error message to show
![shopifyclierror](https://user-images.githubusercontent.com/89682193/132617305-07bcb601-00bf-4c5e-95b2-b0884a993b1a.jpg)

</details>

## Steps to reproduce the problem
oh! 
1. a partner account with 2 or more partner organisations will be needed, 1 of which is deactivated
2. open CLI, and try to login

## Specifications
None
- App type: CLI
- Operating System: Windows 10 Pro
- Shell: CMD
- Ruby version (ruby -v):
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]

**Comment by hannachen** [comment]
Hi @tallyecom, thanks for logging this issue! Could you kindly help me understand the steps to reproduce the bug? In the description, you mentioned 2 separate Partners account, but the replication step mentioned an account with multiple organizations. Given that I don't think it's possible for a Partners account to be associated with multiple organizations, are you referring to the CLI's perspective where you previously logged into both accounts at some point?

**Comment by tallyecom** [comment]
as mentioned earlier, I'd created 2nd Partner Account while playing around with Shopify App Development, 
once I understood the error I duly got it deactivated by connecting with the Partner Support, 

now when I log in using a browser the 2nd Account does not get shown, but when I use Shopify CLI, both the accounts including the 1 deactivated shows up for selection.

to reproduce the issue we will need a partner account with 2 accounts 1 of which needs to be deactivated by Shopify, and then a simple login to Shopify using the command "Shopify login" should reproduce it.

**Comment by hannachen** [comment]
@tallyecom thank you for the clarification!

**Comment by tallyecom** [comment]
> 👋 Hi @tallyecom, we made some changes to attempt a fix, could you kindly verify whether this is fixed for you?

yes its resolved
