### ISSUE TITLE
When installing the app, "Error: write EPIPE ┃ at WriteWrap.onWriteComplete [as oncomplete] (internal / stream_base_commons.js: 94: 16) Error occurs.

### ISSUE THREAD

**Issue by atsuki-sakai** [Shopify/shopify-cli#1521]
# Issue summary
I created an app using Shopify Cli. I ran into this error when trying to install.

> 

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by kishanbharda** [comment]
What was the issue and how did you solve it can you please post it here?

**Comment by atsuki-sakai** [comment]
This issue is still unresolved. I even initialized my Mac, but the problem wasn't resolved.
