### ISSUE TITLE
I can't install apps created with Shopify CLi. #Error: write EPIPE ┃ at WriteWrap.onWriteComplete [as oncomplete] (internal / stream_base_commons.js: 94: 16) #

### ISSUE THREAD

**Issue by atsuki-sakai** [Shopify/shopify-cli#1522]
# Issue summary

I created an app using Shopify Cli. I ran into this error when trying to install.
I get the error "Error: write EPIPE" but the app was installed (checked on the dashboard).
At this time, http: // localhost: 8081 cannot be accessed either.
Open this URL in your browser.
"https://e596-101-142-101-38.ngrok.io/auth?shop=app-nodejs.myshopify.com" An error occurs after 60 to 120 seconds.

When I check the page that caused the error and remains blank with DevTool, such an error occurs. Open this URL in your browser.
_GET https://e596-101-142-101-38.ngrok.io/_next/static/chunks/pages/index.js?ts=1631355965053 net::ERR_HTTP2_PROTOCOL_ERROR 200_

# Terminal display
### 
_$ shopify_ node serve
`atsukisakai@sakaisensaenoMacBook-Pro node_app % shopify node serve
✓ ngrok tunnel running at https://e596-101-142-101-38.ngrok.io
⭑ This tunnel will timeout in 1 hours 32 minutes
⭑ To avoid tunnels that timeout, it is recommended to signup for a free ngrok
account at https://ngrok.com/signup. After you signup, install your
personalized authorization token using shopify [ node | rails ] tunnel auth <token>.
✓ .env saved to project root
✓ Whitelist URLS updated in Partners Dashboard

⭑ To install and start using your app, open this URL in your browser:
https://e596-101-142-101-38.ngrok.io/auth?shop=app-nodejs.myshopify.com

┏━━ Running server… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 
┃ > shopify-app-node@1.0.0 dev /Users/atsukisakai/Desktop/Shopify/node_app
┃ > cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
┃ 
┃ [nodemon] 2.0.6
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching path(s): server/index.js
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node ./server/index.js`
┃ Browserslist: caniuse-lite is outdated. Please run:
┃ npx browserslist@latest --update-db
┃ 
┃ Why you should do it regularly:
┃ https://github.com/browserslist/browserslist#browsers-data-updating
┃ Browserslist: caniuse-lite is outdated. Please run:
┃ npx browserslist@latest --update-db
┃ Loaded env from /Users/atsukisakai/Desktop/Shopify/node_app/.env
┃ Browserslist: caniuse-lite is outdated. Please run:
┃ npx browserslist@latest --update-db
┃ 
┃ Why you should do it regularly:
┃ https://github.com/browserslist/browserslist#browsers-data-updating
┃ event - compiled successfully
┃ > Ready on http://localhost:8081
┃ API Deprecation Notice: {
┃   message: 'https://help.shopify.com/api/getting-started/api-deprecations?locale=ja',
┃   path: 'https://app-nodejs.myshopify.com/admin/api/2020-10/graphql.json'
┃ }
┃ event - build page: /
┃ wait  - compiling...
┃ event - compiled successfully
┃ API Deprecation Notice: {
┃   message: 'https://help.shopify.com/api/getting-started/api-deprecations?locale=ja',
┃   path: 'https://app-nodejs.myshopify.com/admin/api/2020-10/graphql.json'
┃ }
┃ event - build page: /
┃ wait  - compiling...
┃ event - compiled successfully
┃ 
┃   Error: write EPIPE
┃       at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
┃ 
`

## Specifications
- OS: mac OS Big Sur 11.5.2
- Shopify: Cli 2.3.0
- Node js: v14.17.6
- npm: 6.14.15
- Shell: /bin/zsh
- Ruby version (ruby -v): ruby 2.7.4p191

**Comment by daniel-martin94** [comment]
Any updates on a fix? I also ran into this issue following the [shopify.dev documentation](https://shopify.dev/apps/getting-started/create). 

shopify version: 2.5.0

**Comment by atsuki-sakai** [comment]
shopify 2.6.3
Node 16.11.0

I updated it, but I'm getting the same error.
Is there a possible cause?
