### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by bigskillet** [Shopify/shopify-cli#1526]
# Issue summary

There's a console error when saving ignored files listed in `.shopifyignore`.

For example, I'm ignoring `src` files so the output to `assets` triggers the reload. When an ignored `src` file is saved, the output triggers a hot-reload, and I'm guessing the `src` throws the error after.

## Expected behavior

[HotReload] SSE Connected.

## Actual behavior

[HotReload] SSE Connected.
Uncaught TypeError: Cannot read properties of undefined (reading 'endsWith')
    at isCssFile ((index):396)
    at EventSource.handleUpdate ((index):385)

## Steps to reproduce the problem

1. Add file to `.shopifyignore`
2. Run `shopify theme serve`
3. Save ignored file

**Comment by pepibumur** [comment]
👋🏼 @bigskillet 
It's Pedro from Shopify. First of all, apologies for the inconvenience this might have caused.
I debugged the issue following the instructions that you shared and it's a legit bug. I opened a [PR](https://github.com/Shopify/shopify-cli/pull/1537) fixing it. Once merged, we'll release it in the next version of the CLI that will go out next Monday (September 20th).
