### ISSUE TITLE
Theme Serve Pulls Wrong Theme

### ISSUE THREAD

**Issue by catboxer** [Shopify/shopify-cli#1532]
I am getting all sorts of weird behaviors today. Not sure what misstep I am taking. Hoping someone can help me.
**Store I am the owner of:**
I login to my store as normal. I am the store owner. I am in my development store and I serve u the theme but instead of serving it up I get a mishmash of the active theme with development theme custom pages. I can only access the theme customizer. When I try to access the storefront I get a password protected page.

**Store I am the collaborator on:**
I was able to access this store yesterday without any issues. Today I login to the store. It says I'm synced and it's serving but I get the unable to access 'storename' sorry a login error occurred page. I am able to access the theme customizer from the CLI link.

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
"serve" doesnt pull any theme - is uses whatever theme files you have locally. Use "pull" to pull the theme files you want to serve.
