### ISSUE TITLE
Shopify hosted fonts don't load via the local preview url

### ISSUE THREAD

**Issue by tmharryfrancis** [Shopify/shopify-cli#1533]
# Issue summary

Write a short description of the issue here ↓

Font's loaded using the (font picker)[https://shopify.dev/themes/architecture/settings/input-settings#font_picker] cause a 406 error and don't load when viewing the site through the local preview url.

## Expected behavior

What do you think should happen?

The font's should load without erroring.

## Actual behavior

What actually happens?

The font request returns as error, example:

<details>GET https://fonts.shopifycdn.com/quicksand/quicksand_n4.d095c6a3084955552d078cb5ddbfcacb66ded7c7.woff2?&hmac=65eb56d90173fd41d0a86a889262dcca9d5f005a6c507ba94157cbd1f14a7cfa net::ERR_ABORTED 406</details>

## Steps to reproduce the problem

1. Load a font using the Shopify font picker 
2. Apply the font to some text in a theme
3. Serve the theme using the Shopify CLI
4. Observe the error via the console.

## Specifications

- App type: N/A
- Operating System: macOS Big Sur
- Shell: zsh
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]

**Comment by josialoos** [comment]
having the same problem. I believe this is a shopify cli bug. Please fix this soon, fonts are a major thing in webdev!

**Comment by anteksiler** [comment]
I'll bump this as well :)

Getting: Failed to load resource: the server responded with a status of 406 ()
harmoniasans_i4.ccbfea79fd847e76d49925a923aa89064359e629.woff2:1

**Comment by alaskanpuffin** [comment]
Also experiencing this same issue.

**Comment by pinguluk** [comment]
+1
