### ISSUE TITLE
ShopifyCli APIRequestClientError: A shop may only have 100 development themes

### ISSUE THREAD

**Issue by alfredojrm** [Shopify/shopify-cli#1541]
# Issue summary
**ShopifyCli::API::APIRequestClientError: A shop may only have 100 development themes**

I am currently in a development team with 3 people, we are developing a theme for a client store, the 3 developers have staff accounts with permissions to edit themes, the issue is that when using `shopify theme serve` to view our local development, it throws an error in console that does not allow us to work.

## Expected behavior

The `shopify theme serve` command works correctly and serves the theme locally.

## Actual behavior

The console throws an error and the local theme does not work.

What actually happens?

`This command ran with ID: 00666
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        32: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<main>'
        31: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        30: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        29: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <main>'
        28: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        27: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        26: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        25: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        24: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        23: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        22: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        21: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        20: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        19: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        18: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        17: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        16: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        15: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        14: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        13: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        12: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        11: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
        10: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
iMac-de-Imac:luneale-dev imac$ shopify theme serve
This command ran with ID: 07408
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        32: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<main>'
        31: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        30: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        29: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <main>'
        28: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        27: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        26: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        25: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        24: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        23: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        22: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        21: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        20: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        19: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        18: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        17: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        16: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        15: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        14: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        13: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        12: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        11: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
        10: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
         9: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/project_types/theme/commands/serve.rb:13:in `call'
         8: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/theme/dev_server.rb:36:in `start'
         7: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/theme/development_theme.rb:26:in `ensure_exists!'
         6: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/theme/theme.rb:104:in `create'
         5: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/admin_api.rb:95:in `rest_request'
         4: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         3: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/admin_api.rb:92:in `block in rest_request'
         2: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/api.rb:86:in `request'
         1: from /Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.3.0/lib/shopify-cli/api.rb:78:in `block in request': 422 (ShopifyCli::API::APIRequestClientError)
{"errors":{"base":["A shop may only have 100 development themes"]}}`

![Screenshot from 2021-09-16 17-23-17](https://user-images.githubusercontent.com/87659707/133697267-29e4572f-275a-44be-b831-826c12dfb5dd.png)
![Captura de Pantalla 2021-09-02 a la(s) 11 36 49 a  m](https://user-images.githubusercontent.com/87659707/133697300-86b4975f-1705-4b2d-9dfa-0997449198c8.png)

## Steps to reproduce the problem

1. Connect multiples shopify cli's to the same store 
2. Execute shopify theme serve

## Specifications

- App type: Theme (Shopify CLI for themes)
- Operating System: ubuntu 20.04, windows 10, macOS Big Sur version 11.0.1
- Shell: bash, cmd & powershell, bash
- Ruby version (ruby -v): ruby 2.7.0p0(ubuntu), ruby 2.6.0(windows), 2.6.3p62 (mac)

**Comment by pepibumur** [comment]
Hey @alfredojrm
Apologies for the inconvenience this might have caused. Looking at the error you seem to be hitting an API limit that only allows up to 100 development themes per store. If you are not actively using those 100 themes, I recommend removing the unused ones from your development store. If you log into the store and head to the "themes" section of the storefront, you'll notice there's a section with all the themes from where you can delete them:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/663605/133768771-cc551191-bdc0-49b6-a5f9-b26c59f73d89.png">

Please, let me know if this helps. In the future, we might provide an interface from the CLI to manage the themes directly from your terminal.

**Comment by macournoyer** [comment]
Hey @alfredojrm. Development themes don't appear on the Admin dashboard.

It might be caused by an issue in the `theme serve` command that ends up re-creating the development theme each time.

Can you tell me the output of running `hostname` on the same machine you run `theme serve`?

As a workaround, you can delete development themes using `shopify theme delete -a`, then select them one by one.
Or get all the IDs (the number in between the `[...]`) and run: `shopify theme delete ID1 ID2 ID3 ID3`. This will help you get bellow the 100 theme limit until we figure this out.

**Comment by michaelrshannon** [comment]
Just to say that we have also now seen this problem - similar setup - three devs working on a staging store, with less than 10 themes showing in the admin, but loads of `Development (be2add-4eff42311225)` themes when viewing the underlying list of themes.

Guessing this is some kind of issue where the CLI is not re-using the same theme when serve is called again from the same machine under a different session?

**Comment by macournoyer** [comment]
Are you by any chance using our https://github.com/Shopify/lighthouse-ci-action GitHub action?

There was an issue fixed recently that might have caused this: https://github.com/Shopify/lighthouse-ci-action/pull/19

**Comment by sharafciger** [comment]
I can confirm we use

**Comment by macournoyer** [comment]
Great! Updating to the latest version of https://github.com/Shopify/lighthouse-ci-action should fix it then!
