### ISSUE TITLE
Logging in to admin area on local url produces "Due to an unexpected technical problem, Shopify is temporarily unavailable."

### ISSUE THREAD

**Issue by aunruh** [Shopify/shopify-cli#1559]
# Issue summary

Write a short description of the issue here ↓

I do "shopify theme serve"
I get the local URL:
http://127.0.0.1:9292

I open it in Chrome. It works.
I go to http://127.0.0.1:9292/admin
Now I login and then I see:
"Due to an unexpected technical problem, Shopify is temporarily unavailable."

## Expected behavior

What do you think should happen?

I think I should be able to login to the admin area here. This way I could go to the theme editor and look at the changes of the section blocks that I just coded.

## Actual behavior

What actually happens?

I go to http://127.0.0.1:9292/admin
Now I login and then I see:
"Due to an unexpected technical problem, Shopify is temporarily unavailable."

## Steps to reproduce the problem

1. I do "shopify theme serve"
1. Go to http://127.0.0.1:9292/admin
1. login

## Specifications

- App type: shopify cli ??
- Operating System: MacOs BigSur 11.6
- Shell: /bin/zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
using latest shopify cli

**Comment by welectronic** [comment]
+2
