### ISSUE TITLE
PHP local server not working

### ISSUE THREAD

**Issue by amosmos** [Shopify/shopify-cli#1565]
# Issue summary

Write a short description of the issue here ↓
`shopify php serve` doesn't seem to work.
I do get:
`[Thu Sep 23 15:51:38 2021] PHP 8.0.10 Development Server (http://127.0.0.1:3000) started`
But when loading the ngrok URL in the browser I get an ngrok error:
`Failed to complete tunnel connection` and `The error encountered was: dial tcp [::1]:8081: connect: connection refused`.
Thanks in advance!

## Expected behavior

What do you think should happen?
Get to the app install page

## Actual behavior

What actually happens?
Described above :-)
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. install latest shopify-cli
2. create new php application
3. run shopify php serve

## Specifications

- App type: php
- Operating System: macos
- Shell: zsh
- Ruby version (ruby -v): 3.0

**Comment by mrniamster** [comment]
any fix for this?
![image](https://user-images.githubusercontent.com/52563039/145610829-03aaf962-eb8c-4419-a3c8-172984163641.png)
![image](https://user-images.githubusercontent.com/52563039/145610871-84143c3f-1303-4f1c-8e86-6bfc3ade671b.png)
