### ISSUE TITLE
Theme serve error: Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by andrebreia** [Shopify/shopify-cli#1576]
# Issue summary

Write a short description of the issue here ↓

Can't run `shopify theme serve` but all other commands seem to work fine.

## Expected behavior

What do you think should happen?

Sync theme and serve.

## Actual behavior

What actually happens?

Error when trying to run the command.

![Image of error message](https://user-images.githubusercontent.com/17434432/134887552-fa25c2cf-0f76-40fc-a6b9-a576acb88b0d.png)

## Steps to reproduce the problem

1. Run `shopify theme serve`

## Specifications

- App type: Theme
- Operating System: macOS Big Sur v11.5.2
- Shell: zsh
- Ruby version (ruby -v):  2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

**Comment by macournoyer** [comment]
Hi André!

This could possibly be caused by a weird character in your host name.

What does this command output in your terminal?
```
hostname
```

**Comment by andrebreia** [comment]
Hey @macournoyer!

Interesting. The output is `André’s MacBook Pro`.

Tried changing it and removed any special characters, but unfortunately didn't fix the issue.

**Comment by macournoyer** [comment]
Ah! Thanks for that. It's the accent for sure.

If you run `shopify logout` and `shopify login --shop ...`, and try again, it should work.

**Comment by andrebreia** [comment]
That worked. 😀

Thanks for your help @macournoyer!
