### ISSUE TITLE
undefined method `dig' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Bilal-Abbas-Gigalabs** [Shopify/shopify-cli#1577]
Is there anyone know about this error? 
![error](https://user-images.githubusercontent.com/72508641/134895443-169208cc-ba5e-4726-a580-6d036c1fb82f.png)
?

**Comment by Bilal-Abbas-Gigalabs** [comment]
Someone please ?

**Comment by catlee** [comment]
Can you post the exact command that you're running?
What kind of extension are you trying to push?
