### ISSUE TITLE
Discussion - Shopify CLI and Continuous Integration pipeline/tool

### ISSUE THREAD

**Issue by hehoo** [Shopify/shopify-cli#1582]
# Issue summary

First of all, it's not an issue but kind of a discussion or a wanted feature. There is no type of 'discuss' or 'feature' that I can choose when I tried to create an issue. 

In short I want to integrate the Shopify CLI with my Continuous Integration pipeline/tool, so that my app extension (post-purchase extension) can be pushed and published through by the CICD pipeline without manual interaction in the whole flow. But I couldn't find a way to authenticate the Shopify CLI in a silent way (e.g. by passing authentication credential directly), instead of the interactive way in browser. I've been gone through all the documentation and discussions, but couldn't find any clue for that. It seems like it is impossible to do it in the latest version **2.5.0** of Shopify CLI. 

Could anybody let me know if I am wrong and give me some tips about how to achieve it? If my guess is right, can this feature be put into the roadmap and get it released in future releases? 

Many Thanks!
Best Regards

**Comment by stephszeto** [comment]
Hi Minggang! Thanks for raising this - you're correct that we currently don't provide token-based authentication that'd allow you to use the CLI in your CI/CD workflow. This is indeed on our roadmap though and definitely something we'll be tackling in the very near future. 

For our own reference, what CI platform do you use?

**Comment by hehoo** [comment]
@stephszeto Thanks for the information.  Looking forward it :).  We are using [buildkite](https://buildkite.com/) as our CI platform.

**Comment by d-goldin** [comment]
We also would like this feature to use in our GCP Cloud Build pipelines.

**Comment by dylansmith** [comment]
I think I may have a theoretical workaround for this (though as yet properly tested).

When using the `shopify login` command, it's clear that the CLI starts an HTTP server on http://127.0.0.1:3456 to receive the OAuth callback. I looked in the source code to see where the CLI stores the access and refresh tokens it gets back from Shopify, and the answer is here: https://github.com/Shopify/shopify-cli/blob/0701e2820b74fe58e9df6ebcb322fb0f63bf39bc/lib/shopify_cli.rb#L136

Shopify CLI creates a `.db.pstore` file in a location which can be controlled via the `APPLOCALDATA` environment variable.
Once you have this file, you essentially have the tokens you need for authentication in CI without any OAuth handshake involving a browser. I am not sure what the expiry time is, but I've never seen the CLI re-authenticate via the browser in the time I've used it.

So, the potential solution is:

1. Run `export LOCALAPPDATA="/tmp" && shopify login` to create your token file
2. Securely create this file in CI somehow and set the `APPLOCALDATA` env var to the relevant location
3. Shopify CLI should now be authenticated

**Comment by hyldmo** [comment]
There's another workaround that Shopify uses internally that I've gotten to work as well. See https://github.com/Shopify/lighthouse-ci-action/blob/4dc7955cf2112084e1fea1b8ca903a081c6211ef/entrypoint.sh#L96
```bash
# Secret environment variable that turns shopify CLI into CI mode that accepts environment credentials
export CI=1
export SHOPIFY_SHOP="$SHOP_STORE"
export SHOPIFY_PASSWORD="$SHOP_APP_PASSWORD"
```
The app password is the same as you would use for themekit, i.e. a private app

**Comment by zhixiangyao** [comment]
> 

You are right! thx!

**Comment by TheApeMachine** [comment]
> There's another workaround that Shopify uses internally that I've gotten to work as well. See https://github.com/Shopify/lighthouse-ci-action/blob/4dc7955cf2112084e1fea1b8ca903a081c6211ef/entrypoint.sh#L96
> 
> ```shell
> # Secret environment variable that turns shopify CLI into CI mode that accepts environment credentials
> export CI=1
> export SHOPIFY_SHOP="$SHOP_STORE" # storename(.myshopify.com) exclude parentheses 
> export SHOPIFY_PASSWORD="$SHOP_APP_PASSWORD" # Same as you would use for themekit, i.e. a private app admin API password
> ```
> 
> If you set these 3 env vars `shopify login` will login automatically without requiring a browser.
> 
> In my opinion, if those just were documented I would regard this feature as implemented.

I found this in the code yes, with a nice remark that it is about to be deprecated?

commands/login.rb
```
# As password auth will soon be deprecated, we enable only in CI
if @ctx.ci? && (password = options.flags[:password] || @ctx.getenv("SHOPIFY_PASSWORD"))
  ShopifyCLI::DB.set(shopify_exchange_token: password)
else
...etc
```

**Comment by evaldas-raisutis** [comment]
How is this not supported yet 👀 we still use themekit for our CD pipelines and won't be upgrading until CLI can authenticate using token/password.

Yes, that includes OS 2.0 themes.

Bonkers.

**Comment by hehoo** [comment]
@stephszeto How is this CI/CD support going? When are you going to release this support officially?  Thanks!

**Comment by iamvishnusankar** [comment]
Any updates on this? We are testing our theme app extensions on multiple environments. Swapping credentials and building extensions for multiple environments is virtually impossible in local machine alone.

We are unable to push our extension without testing due to this and it's affecting our app's overall rating.

**Comment by stephszeto** [comment]
Thanks for your patience with this, folks! We've run into a few different unexpected issues as we've been getting this feature ready to ship - hoping to get this out to beta users in the next week or so!

**Comment by infn8** [comment]
I have some information I’d like to place here that could be a helpful workaround for some people.

Now before everybody makes a comment to me saying that this doesn’t solve the problem for them, I know. I’m not saying that it does.

But if you happen to be using GitHub to store your source control version of your Shopify theme, there is a Shopify created GitHub integration that is actually quite effective two way syncing tool between your source control and a theme on Shopify. 

https://shopify.dev/themes/tools/github

We started down the role of continuous integration with the CLI and gave up on it because of the issues above. Afterwards, we found this tool and it totally saved the day. I placed here in the hopes that it is helpful if it isn’t… Well, I don’t have a solve for that.

**Comment by iamvishnusankar** [comment]
@stephszeto Any updates on this?

**Comment by paulwhipps** [comment]
Also chasing an update. Attempting to implement some CICD and hitting roadblocks on this front.

**Comment by sstankov** [comment]
@stephszeto  anyway to get included in beta testing? We have set CI/CD pipelines all over our Shopify App, and we want to do it for this extension as well.

**Comment by iamvishnusankar** [comment]
@stephszeto Filled out the form. Still haven't received the access!

**Comment by sanjos30** [comment]
Looking forward for an update. I wonder how does so many app's perform CI/CD on their end?

**Comment by TheApeMachine** [comment]
@stephszeto actually, I recently found out (through some Youtube video) that you will deprecate the script tags API, so we decided to port the whole thing over to theme app extensions, which resulted in a much nicer deployment path. Basically the Docker file below does enough, and we can push it to various clusters representing the environments, which will be loaded once with products, which is manageable.

```
FROM node:16                                                                                                                                                                                                                                                                                                                                                                                                                     WORKDIR /app                                                                                                                                                                                                    COPY . .
COPY .env.prod .env
RUN npm install && npx next build
EXPOSE 3000
CMD npx next start
```

**Comment by stephszeto** [comment]
Looping back here with an update: the feature is now out! Check out [the shopify.dev changelog](https://shopify.dev/changelog/ci-cd-support-for-scripts-extensions) for details.

**Comment by mariatryta** [comment]
Seems like the update above solved the issue with extensions and scripts but not for themes themselves? Is that correct? Is there a plan to roll out a similar feature for themes as until then we are dependent on themekit...

**Comment by stephszeto** [comment]
Yes, it's correct that this feature doesn't support themes. We're looking into it, but supporting this token for themes is extra tricky relative to scripts and extensions, given that themes are associated with merchant stores (as opposed to Partner accounts), which makes mapping this across more challenging. Hope to have more to share soon on this!

**Comment by begemotik** [comment]
The issue prevents us from using `shopify CLI` in our Gitlab Pipeline. Are there any plans to make it work with themes as well?

**Comment by MurmeltierS** [comment]
Could you at least echo out the URL used to login?

**Comment by ZeoKnight** [comment]
any update on support for themes? our corporate repositories are on bitbucket so the github integration solution doesn't work for us...

**Comment by stephszeto** [comment]
CI/CD support for themes is on our radar and something we're planning on looking at imminently before the end of the year - thanks everyone for your patience!

**Comment by StewPoll** [comment]
Hey @stephszeto is there anywhere we can get updates to that specifically?

**Comment by stephszeto** [comment]
CI/CD for themes is now out as of today! [More details on how to set that up can be found here.](https://shopify.dev/themes/tools/cli/ci-cd)
