### ISSUE TITLE
Getting Started Node-React App Throwing Error "This app can’t load due to an issue with browser cookies."

### ISSUE THREAD

**Issue by banerjeejagan** [Shopify/shopify-cli#1583]
# Issue summary
Shopify Node React App, created using shopify CLI, running perfectly while serving from localhost using Ngrok or LocalTunnel.
I have uploaded this to an Ubuntu instance on AWS, it compiled successfully. 
But when I tried to access from my shopify store, it's throwing error.

## Expected behavior

The One I am talking about is just an hello world app, it should show Hello world , that's it.

## Actual behavior

What actually happens?

"The app couldn’t be loaded
This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser
, or contacting the developer to get support."

## Steps to reproduce the problem

1. Uploaded "getting started", "Hello world" App on Ubuntu Server, which runs perfectly from local. 
2. It's compiled too, but  when it tries to authenticate, throwing like above.

## Specifications

- App type: Shopify Node React Next Koa-Auth
- Operating System: Ubuntu
- Shell:
- Ruby version (ruby -v):

**Comment by jesalerno84** [comment]
👋 @banerjeejagan - Can you please take a look at this thread: https://github.com/Shopify/koa-shopify-auth/issues/61 and see if it addresses your issue?  If not I would recommend following up in that thread.
