### ISSUE TITLE
shopify-cli doesn't recognize non-development stores

### ISSUE THREAD

**Issue by dungle-scrubs** [Shopify/shopify-cli#1593]
More of a discussion to better understand how this tool is meant to be used.

When I run `shopify switch` I only see a list of development stores, no existing live client stores.

I'm wondering if this tool is specifically meant for Theme Store theme development? 

For example, if I am building a custom Online Store 2.0 compatible theme for a client - but not for theme sale, once their shop is transferred and goes live, will I be required to switch to Theme Kit and is Theme Kit able to work with the new theme framework?

**Comment by ADTC** [comment]
You can also use `shopify switch --store=your-live-store.myshopify.com` if you're already logged in.
