### ISSUE TITLE
Shopify Partners Dashboard CLI Schema

### ISSUE THREAD

**Issue by brwhaley** [Shopify/shopify-cli#1594]
# Issue summary

Is it possible to issue queries against the Shopify Partners Dashboard CLI Schema directly (without using the Shopify CLI)?  For example, is there a way to retrieve an app's Application Url or Redirect Urls programatically?  Thanks!

**Comment by ptiger10** [comment]
I've had a similar problem. The Partners API GraphQL endpoint does not support mutations, yet the CLI is able to run mutations within the Partners dashboard that update the Application Url and Redirect Urls. Is this undocumented functionality in the Partners API, or am I missing something?
