### ISSUE TITLE
Login to shopify from command line is impossible

### ISSUE THREAD

**Issue by tomjefferson** [Shopify/shopify-cli#1601]
# Issue summary

This command ran with ID: 27820
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<main>'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <main>'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:25:in `call'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/commands/login.rb:33:in `call'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:64:in `authenticate'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:131:in `request_access_token'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:207:in `post_token_request'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:217:in `post_request'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1483:in `request'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `open'
C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `initialize': A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "accounts.shopify.com" port 443 (Errno::ETIMEDOUT)
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:32:in `<main>'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/bin/shopify:33:in `block in <main>'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/monorail.rb:20:in `log'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/core/executor.rb:15:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/command.rb:25:in `call'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/commands/login.rb:33:in `call'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:64:in `authenticate'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:131:in `request_access_token'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:207:in `post_token_request'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.5.0/lib/shopify_cli/identity_auth.rb:217:in `post_request'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:1483:in `request'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:932:in `start'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `open'
C:/Ruby27-x64/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to accounts.shopify.com:443 (A connection attempt failed because the connected party did not properly respond after a
period of time, or established connection failed because connected host has failed to respond. - connect(2) for "accounts.shopify.com" port 443) (Errno::ETIMEDOUT)

## Steps to reproduce the problem

1. try **shopify login** 
2.  after the successful login the above error happen.

## Specifications

- App type: public
- Operating System: win 7
- Shell: powershell
- Ruby version (ruby -v): 2.7.4p91

**Comment by jesalerno84** [comment]
Hey @tomjefferson - are you still having an issue trying to login?
