### ISSUE TITLE
ShopifyCLI::AdminAPI requires the property token to be set error when running shopify extension serve

### ISSUE THREAD

**Issue by cecyc** [Shopify/shopify-cli#1604]
# Issue summary

When running `shopify extension serve` on a `checkout_ui` extension, an auth error appears if we are unable to get a token to call the AdminAPI.

```
ShopifyCLI::AdminAPI requires the property token to be set
```

## Expected behavior

* CLI should be able to fetch the necessary token
* Better error handling to surface instructions to end-user on how to resolve the error if it appears

## Actual behavior

What actually happens?

`ShopifyCLI::AdminAPI requires the property token to be set` error appears

## Steps to reproduce the problem

1. run `shopify logout`
1. run `shopify extension serve`

But this can happen if the user logged in via Partners and not their Dev store when logging in to the `shopify-cli`.

Current workaround:
* Log out of CLI
* Log out of Partners
* Log into dev store directly (not through partners)
* Log in to shopify CLI again `shopify login --store=STORE`

Can also bypass the call to the Admin API by providing a resourceUrl in the command
`shopify extension serve --resourceUrl=PRODUCT_ID:1` where `PRODUCT_ID` is the ID of a product that exists in the dev store the user is logged in as, or by adding `EXTENSION_RESOURCE_URL` to their `.env` file.

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by jarthorn** [comment]
Just confirming this is still a problem in CLI version 2.17.0.
