### ISSUE TITLE
issue in login

### ISSUE THREAD

**Issue by Anthony-david** [Shopify/shopify-cli#1637]
# Issue summary

Everything works perfect, but when i login its shows a error
![image](https://user-images.githubusercontent.com/52906642/136658198-cd493a24-1deb-48c4-9107-147b6af17930.png)

## Expected behavior

I am able to check the store and version by cmd, but when i login it shows error, after login error i run SHOPIFY logout its works

## Actual behavior

X An unexpected error occured.
        To ]8;;https://github.com/Shopify/shopify-cli/issues/new\submit an issue]8;;\ include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

## Specifications

- App type: theme
- Operating System: Windows
- Shell: Powersell
- Ruby version (ruby -v): 2.7

**Comment by Freelancer740** [comment]
I'm getting the same error while trying to log in with the Shopify login command.

**Comment by Freelancer740** [comment]
please help if anyone can help??

**Comment by jeejay19** [comment]
Hello! to fix the issue just install https://git-scm.com/download/win

**Comment by zuadulislam** [comment]
how can i fixed that issues @Freelancer740  help me

**Comment by uemura-zyplus** [comment]
@jeejay19 
I appreciate your kindness.
It worked fine!

**Comment by TombeDev** [comment]
Thanks @jericjamesdigital !
After completing your steps everything works fine now.

**Comment by Anthony-david** [comment]
Works like a charm @jeejay19 ,Really appreciate take you time.

Follow simple steps >#1637 (comment)

**Comment by remyoswalt** [comment]
@jericjamesdigital I am getting the same issue when I try to run the local development server, I am not able to solve the error, please help

**Comment by johncarter-** [comment]
Make sure you don't have subdirectories in your `assets` directory!! Just lost about an hour...

**Comment by remyoswalt** [comment]
I am still getting this error, please help anyone

**Comment by remyoswalt** [comment]
@johncarter-  Where is assets directory located, I can't find it, please help

**Comment by tahmidbintaslim** [comment]
Follow simple steps >#1637 (comment)

**Comment by tahmidbintaslim** [comment]
> Hello I have a similar error when I do " shopify extension push": (Only in this case) X An unexpected error occured. To submit an issue include the stack trace. To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1. But your process not work in my case, I followed it in detail, I had already installed the listed resources, so I updated them to the latest version. Anyone have any ideas? thanks ![Capture](https://user-images.githubusercontent.com/35004040/138554363-53cd164a-efb2-4631-88b9-60f6c151f074.PNG)

@marcosolito  Follow simple steps > [ #1637 (comment)](https://github.com/Shopify/shopify-cli/issues/1637#issuecomment-945745741)

**Comment by ahmedpowers** [comment]
The solution is to use Git Bash for windows as opposed to CMD or Powershell.

**Comment by ZyriabDsgn** [comment]
> The solution is to use Git Bash for windows as opposed to CMD or Powershell.

I applied everything in jericjamesdigital's guide but couldn't get it working (using CMD), your solution got it working for me.
I remember why I used to dev on Linux...

Thanks mate

**Comment by JawadUllah9T9** [comment]
**X An unexpected error occured.
        To submit an issue include the stack trace.**
only show this error please any one help?????

**Comment by ehsanajmal** [comment]
To submit an issue include the stack trace.
only show this error please any one help?????

**Comment by ehsanajmal** [comment]
Found a solution to solve this error "To submit an issue include the stack trace."

1) Log out of your shopify account in the browser
2) Log out through shopify CLI (if not already logged out) "shopify logout"
3) Log in to {shop}.myshopify.com/admin in the browser
4) Then log in through shopify CLI "shopify login --store {shop}.myshopify.com"

You should be able to run "shopify theme serve" after this. If not, make sure you log out of anywhere you're logged in to shopify and try again.

This worked for me and make sure you added ‘SHOPIFY_CLI_STACKTRACE=1’ in the environmental variable.

**Comment by serkanalabas** [comment]
> Found a solution to solve this error "To submit an issue include the stack trace."
> 
> 1. Log out of your shopify account in the browser
> 2. Log out through shopify CLI (if not already logged out) "shopify logout"
> 3. Log in to {shop}.myshopify.com/admin in the browser
> 4. Then log in through shopify CLI "shopify login --store {shop}.myshopify.com"
> 
> You should be able to run "shopify theme serve" after this. If not, make sure you log out of anywhere you're logged in to shopify and try again.
> 
> This worked for me and make sure you added ‘SHOPIFY_CLI_STACKTRACE=1’ in the environmental variable.

I made a login with github to thank you. thanks :)

**Comment by grantrlgus** [comment]
> Found a solution to solve this error "To submit an issue include the stack trace."
> 
> 1. Log out of your shopify account in the browser
> 2. Log out through shopify CLI (if not already logged out) "shopify logout"
> 3. Log in to {shop}.myshopify.com/admin in the browser
> 4. Then log in through shopify CLI "shopify login --store {shop}.myshopify.com"
> 
> You should be able to run "shopify theme serve" after this. If not, make sure you log out of anywhere you're logged in to shopify and try again.
> 
> This worked for me and make sure you added ‘SHOPIFY_CLI_STACKTRACE=1’ in the environmental variable.

It works! Thanks a lot!

**Comment by geongeorge** [comment]
Make sure your store has not hit the 100 theme limit.
