### ISSUE TITLE
login issue on a staff partner account

### ISSUE THREAD

**Issue by razvanmitre** [Shopify/shopify-cli#1638]
# Issue summary

I have an account (email: razvanmitre@gmail.com) which has access to 1 organization. This account is a staff account on this organization, not an owner. If I try to login though `shopify login` I receive: "It doesn't appear that you're logged in. You must log into a partner organization or a store staff account."

I also tried to login on one of the stores this organization has access to. That didn't work either.

## Expected behavior

Login to the organization with a staff account on that organization

## Actual behavior

Command  `DEBUG=1 shopify login` returns:
```
DEBUG storefront_renderer_production_exchange_token: _token_
DEBUG partners_exchange_token: _token_
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: a54b9b95-6b28-461d-acb3-b4c67f7f312b
DEBUG {"data"=>{"organizations"=>{"nodes"=>[]}
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.
```

So it seems that it does not see my organization.

When I try to login into a store on which my organization has access to I get this: 
`DEBUG=1 shopify login --store _store_id_`
```
DEBUG shopify_exchange_token: _token_
DEBUG storefront_renderer_production_exchange_token: _token_
DEBUG partners_exchange_token: _token_
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: 04a27ce8-21d1-4ca2-a07e-24df4676b1c4
DEBUG {"data"=>{"organizations"=>{"nodes"=>[]}
Logged into store _store_id_ as staff (no partner organizations available for this login)
```

But when I try to pull a theme I get:
`DEBUG=1 SHOPIFY_CLI_STACKTRACE=1 shopify theme pull`
```
DEBUG GET https://_store_id_/admin/api/unstable/themes.json with X-Request-Id: 799b19bc-4220-4882-8303-40d5378753c2

✗ An unexpected error occured.
        To submit an issue include the stack trace.

/Users/razvan/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
```

## Steps to reproduce the problem

1. Login in the CLI on a staff partner account 

## Specifications

- App type: Shopify CLI version 2.6.3
- Operating System: MacOS 11.6
- Shell: Terminal
- Ruby version (ruby -v): ruby 3.0.0p0

**Comment by Danishnaseer** [comment]
i am still facing the issue ,if i login through direct owner account its still give me error.
i have tried to create staff account to login but still facing the error



It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store STORE to log in.
