### ISSUE TITLE
An unexpected error occured

### ISSUE THREAD

**Issue by dfaulring** [Shopify/shopify-cli#1640]
# Issue summary

Unable to run `shopify theme serve`. I am logged in to the store. Was working previously but it stopped working after I was requested to login again which I did but after is when the problem was created. 

## Expected behavior

What do you think should happen?

Should launch a development server. 

## Actual behavior

What actually happens?

Get an error message saying
`
  ✗ An unexpected error occured.
  To submit an issue include the stack trace.
  To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
`

## Steps to reproduce the problem

1. Run `shopify theme serve`

## Specifications

- App type: Theme
- Operating System: M1 Macbook Air
- Shell: zsh
- Ruby version (ruby -v):  2.6.3p62

**Comment by jeejay19** [comment]
Hello! to fix the issue just install https://git-scm.com/download/win

**Comment by Jhongt796** [comment]
I've the same problem, only "theme serve" doesnt work, and it gives the following error:

```
PS C:\Users\User\Documents\GitHub\mystore> shopify theme serve
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ * Syncing theme #9999999999 on mystore.myshopify.com
┃                         0%  
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.14s) ━━━

X An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

Enviroment:
- Windows 10 Versión 21H1 ( SO 19043.1266 )
- gem 3.2.22 
- ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
- shopify-cli 2.6.3

**Comment by zulufucxs** [comment]
Same issue here. It started after upgrading to the newest version of Shopify CLI.

**Comment by Jhongt796** [comment]
> I'm also having this issue. @jeejay19 do you have a real solution?

could you share stack trace? (To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.)

**Comment by Jhongt796** [comment]
### I managed to fix the error.

First, I tried to delete my local repository where my store's theme was and then I cloned it again, however it still isn't working, (This theme is just a branch of my repository where being similar, each theme is a branch).

I tried with another theme (Another repository), specifically with the "Dawn" theme in order to rule out problems with the files, and this one worked correctly, so I added the environment variable "SHOPIFY_CLI_STACKTRACE" with the value "1", leaving me the following record of the error:

```
PS C:\Users\User\Documents\GitHub\master_theme_servicios_delivery> shopify theme serve
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ * Syncing theme #128052396274 on mystore.myshopify.com
┃                                                                           0%  
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.57s) ━━━

X An unexpected error occured.
        To submit an issue include the stack trace.

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/file.rb:23:in `read': Is a directory @ rb_sysopen - assets/fontawesome (Errno::EISDIR)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/file.rb:23:in `read'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/file.rb:23:in `read'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/file.rb:65:in `checksum'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:295:in `file_has_changed?'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:193:in `enqueue'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:42:in `block in enqueue_updates'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:42:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:42:in `enqueue_updates'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/syncer.rb:152:in `upload_theme!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `public_send'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/project_types/theme/ui/sync_progress_bar.rb:11:in `block in progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui/progress.rb:34:in `progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/project_types/theme/ui/sync_progress_bar.rb:10:in `progress'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/project_types/theme/commands/serve.rb:14:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/dev_server.rb:47:in `block in start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/theme/dev_server.rb:43:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/project_types/theme/commands/serve.rb:13:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/sub_command.rb:13:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/command.rb:19:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/monorail.rb:32:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/bin/shopify:37:in `block (2 levels) in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/bin/shopify:36:in `block in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.3/bin/shopify:47:in `<main>'
```

In the first line of this record it refers to a folder that cannot be read, within my repository "assets / fontawesome", due to limitations of the shopify CDN system, **"Assets" does not support sub directories**, so when removing it from my repository, shopify-cli was already working correctly.

This makes me think that the error is due to the fact that in this new version (2.6.3) some process that ignores when there is an error of this type is not taken into account, so it is likely that they can solve this error simply by checking the stack trace when executing the command.

**Enviroment:**
Windows 10 Versión 21H1 ( SO 19043.1266 )
gem 3.2.22
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
shopify-cli 2.6.3

**Comment by amjgbr** [comment]
@joshcawthorne nice find. This was driving me nuts. Thanks

**Comment by macournoyer** [comment]
Indeed this was caused by the subdirectory under `assets/`. We are pushing an update the docs to make it clearer that subdirectories are not supported. Sorry about the confusion!

**Comment by lilyfielding** [comment]
Yeah I'm still having this issue unfortunately, my `assets/` doesn't have any subfolders so that's not the issue here. Does anyone know where to add the `SHOPIFY_CLI_STACKTRACE=1` variable?

**Comment by joshcawthorne** [comment]
@lilyfielding this guide might help you 🙂 https://github.com/Shopify/shopify-cli/issues/1637#issuecomment-945745741

**Comment by remyoswalt** [comment]
@joshcawthorne where is assets directory located, whenever I try to run shopify node serve I got the same error
![Capture3](https://user-images.githubusercontent.com/92564290/141668996-a126760c-7e9c-40e3-b5cc-266dc14fb543.JPG)

**Comment by remyoswalt** [comment]
@macournoyer where is assets folder located, I am trying to create shopify app but getting this error when I run the command shopify node serve, please help

**Comment by catboxer** [comment]
No sub folder in assets folder so ran variable getting error Address already in use - bind(2) for 127.0.0.1:9292 (Errno::EADDRINUSE)
So I killed processes on 9292 and it fixed this issue for me. Hope this helps someone else.

**Comment by remyoswalt** [comment]
@catboxer Can you please explain the solution in simple words, its too hard to understand the solution, please help

**Comment by haroldao** [comment]
I'm also having this issue. | 2.7.2

**Comment by koki786** [comment]
i am creating new shopify app thus it giving me this error X An unexpected error occured.
        To submit an issue include the stack trace. i tried to login in  my shopify store again getting same error 
i also add environment variable nd system variable

**Comment by sagararora028** [comment]
I had the same issue. But when I changed the directory to the folder all the files are in, everything started working fine again. Have shared a video for that.

https://www.loom.com/share/1a9a0fd87d9048ab8393bb730a92c96d

**Comment by Jtzuya** [comment]
> I had the same issue. But when I changed the directory to the folder all the files are in, everything started working fine again. Have shared a video for that.
> 
> https://www.loom.com/share/1a9a0fd87d9048ab8393bb730a92c96d

Thanks man, this helps me sort this out

**Comment by jordihoven** [comment]
Make sure you cd into the correct directory.

**Comment by maelboulange** [comment]
Hello, 

I have the same error. I am in the correct directory and there is no folder in assets. Someone have an other solution ?

**Comment by maelboulange** [comment]
Shopify theme pull is working as usual

I don't have explication and I don't know why. I restart everything and it's working now. I think there is big issue on shipify cli with cache, cookie, and other thing ...

**Comment by b-mael** [comment]
I have the same error if I run "shopify them pull"

I can't explain, but if I am connect to my box it's not working. But if I put my phone at hotspot it's working ...

**Comment by jordihoven** [comment]
Try Shopify Whoami or Shopify theme whoami to see if you’re logged in correctly… weird.

**Comment by b-mael** [comment]
I solve my problem, I don't know how ... It's so weird ...

**Comment by Jtzuya** [comment]
Hi guys, here's how I fix this issue. 

Shopify Login --store=yourstore.myshopify.com



> What happens when you run “Shopify theme pull”? Does the folder get pulled in correctly then?
> […](#)
> Sent from my iPhone
> On 15 Jan 2022, at 16:14, maelboulange ***@***.***> wrote: ﻿ Hello, I have the same error. I am in the correct directory and there is no folder in assets. Someone have an other solution ? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.

Tried this earlier and the code that I didn't save "git add." were all gone. Always save it before doing "shopify theme pull"

**Comment by danniel917** [comment]
> Just to add to this - I also ran into this issue, and discovered it was because I had a sub-folder in my assets folder for fonts. Removing that resolved the error!

Thank you!

**Comment by BrandonLandgraffBranding** [comment]
Not sure why but this solved my issue:
1. Logged out of Shopify in terminal
2. Sent a staff invite to a different email address
3. Logged out of Shopify in the browser
4. Accepted the staff invite and logged in
5. Logged in to new staff account in terminal
6. Started "shopify theme serve" and it worked perfectly (: 

I spent all day and tried all sorts of solutions:
- Reinstalling homebrew, ruby, shopify cli
- Trying different themes
- Changing directories or even trying to delete the assets folder entirely 
- Making sure I was starting "shopify theme serve" in the right directory

SO! If you are having trouble - I'd give the above solution a shot!

**Comment by pratikmdhr** [comment]
> Not sure why but this solved my issue:
> 
>     1. Logged out of Shopify in terminal
> 
>     2. Sent a staff invite to a different email address
> 
>     3. Logged out of Shopify in the browser
> 
>     4. Accepted the staff invite and logged in
> 
>     5. Logged in to new staff account in terminal
> 
>     6. Started "shopify theme serve" and it worked perfectly (:
> 
> 
> I spent all day and tried all sorts of solutions:
> 
>     * Reinstalling homebrew, ruby, shopify cli
> 
>     * Trying different themes
> 
>     * Changing directories or even trying to delete the assets folder entirely
> 
>     * Making sure I was starting "shopify theme serve" in the right directory
> 
> 
> SO! If you are having trouble - I'd give the above solution a shot!

@BrandonLandgraffBranding this worked for me.. thanks!!

**Comment by pkiula** [comment]
Nothing to do with fonts subfolder etc in assets. The solution is to `cd` into the directory of the theme.

**Comment by BrendaMichelle** [comment]
I had this error, too. In my case, it was because port 9292 was already in use, so I killed the process. Here are the steps I took that you can try if you have a macbook:

1. Open your terminal
2. Type in `lsof -i. 9292` and hit enter. This will show a list of processes running on that port. See example below:
<img width="598" alt="Screen Shot 2022-08-13 at 6 54 25 PM" src="https://user-images.githubusercontent.com/8907035/184515932-aa4818f2-71e9-4d87-a6ec-18baa73086a3.png">

3. Locate the PID of the ruby command (note the `PID` column), which in my case is `2477` as shown in my screenshot above.
4. In the terminal type `kill -9 2477` REPLACING `2477` with whatever PID was output after steps 2 & 3 and hit enter.
5. In my case, I had to login anew, so the command for that is `shopify login --store johns-apparel.myshopify.com
` REPLACING the shop link with your shop.
6. Try to rerun `shopify theme serve` again 🤞

**Comment by DutchPrince** [comment]
I removed the .DS_Store file and it started working again.
```
$ ls -a
$ sudo rm .DS_Store
```
