### ISSUE TITLE
Partners Login Error

### ISSUE THREAD

**Issue by molly-yu** [Shopify/shopify-cli#1652]
# Issue summary

Write a short description of the issue here ↓

When logging into a store as a partner using `shopify login --store=STORE`, in the case where STORE is an actual store but not owned by or part of my partner organization, it incorrectly says that I have successfully logged into the store (doesn't actually log into the store). -> also appears when I run `shopify whoami`
## Expected behavior

What do you think should happen?

It should display a message of some sort saying that the store is not part of my partner organization.
`Shopify whoami` should also not show that I am logged into the store.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

It displays a message saying that I am logged into a store that isn't mine, even though it is not logged into the store. In the screenshot below, my partner organization does not own `teststore`, and yet it says I am logged in. In the following message where I try to create an app, I see that I am in my actual store.

<img width="788" alt="Screen Shot 2021-10-15 at 4 07 29 PM" src="https://user-images.githubusercontent.com/55213953/137931197-16f81888-344d-4291-ae89-dcde5d027abb.png">

## Steps to reproduce the problem

1. run `shopify login --store=STORE`, where STORE is an existing store not owned by your partner
2. run `shopify whoami`

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by stephszeto** [comment]
Whoa this is bad - good catch, Molly!
