### ISSUE TITLE
macOS installation and Nokogiri

### ISSUE THREAD

**Issue by pepicrft** [Shopify/shopify-cli#1658]
# Issue summary
When installing the CLI using `gem install` and the Ruby version that comes with macOS, the installer picks the wrong architecture for Nokogiri and that causes the installation to fail. Some users solve that by using a Ruby version management tool like `chruby` or `rbenv` to use a Ruby version other than the system's. 

## Expected behavior
Installation should work when using the system's Ruby. We can't ask users to change their Ruby version to be able to use the CLI.

## Actual behavior

The installation fails because it picks the wrong architecture of the Nokogiri gem.

## Steps to reproduce the problem

1. Switch to the system Ruby (macOS)
2. Run `gem install shopify-cli`

**Comment by gonzaloriestra** [comment]
Rubygems issue talking about this problem (not solved yet): https://github.com/rubygems/rubygems/issues/4234
