### ISSUE TITLE
SSLError: Certificate verify failed

### ISSUE THREAD

**Issue by ghost** [Shopify/shopify-cli#1673]
# Issue summary

Write a short description of the issue here ↓

When I try to do anything like ```shopify login``` or ```shopify theme serve```, I get an error about unable to find local issuer certificate. I am using the system Ruby for MacOS. I have also tried installing ```rvm``` and Ruby 3.0.0 like [another thread](https://github.com/Shopify/shopify-cli/issues/1307) said, and went through a bunch of troubleshooting steps with SSL issues, but the result was the same.

<details>➜  wee-ones-consumer git:(consumer) SHOPIFY_CLI_STACKTRACE=1 shopify theme serve
✗ An unexpected error occured.
	To submit an issue include the stack trace.

** [Bugsnag] 2021-10-22 08:08:37 -0400: Unable to send information to Bugsnag (https://notify.bugsnag.com), #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)>
** [Bugsnag] 2021-10-22 08:08:37 -0400: ["/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'", "/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'", "/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:1038:in `connect'", "/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:970:in `do_start'", "/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:959:in `start'", "/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:1512:in `request'", "/usr/local/Cellar/shopify-cli/2.6.5/gems/bugsnag-6.24.0/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/usr/local/Cellar/shopify-cli/2.6.5/gems/bugsnag-6.24.0/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/usr/local/Cellar/shopify-cli/2.6.5/gems/bugsnag-6.24.0/lib/bugsnag/delivery/thread_queue.rb:38:in `block in serialize_and_deliver'", "/usr/local/Cellar/shopify-cli/2.6.5/gems/bugsnag-6.24.0/lib/bugsnag/delivery/thread_queue.rb:55:in `block (2 levels) in start_once!'"]
/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:959:in `start'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/net/http.rb:1512:in `request'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/identity_auth.rb:217:in `post_request'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/identity_auth.rb:207:in `post_token_request'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/identity_auth.rb:131:in `request_access_token'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/identity_auth.rb:64:in `authenticate'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:110:in `authenticate'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:123:in `block in access_token'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/db.rb:87:in `get'
	from /usr/local/Cellar/ruby/3.0.2_1/lib/ruby/3.0.0/forwardable.rb:238:in `get'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:122:in `access_token'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:116:in `api_client'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/admin_api.rb:95:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/theme/development_theme.rb:46:in `exists?'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/theme/development_theme.rb:34:in `ensure_exists!'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/theme/dev_server.rb:36:in `start'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/project_types/theme/commands/serve.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/sub_command.rb:13:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/command.rb:19:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/monorail.rb:30:in `log'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/bin/shopify:37:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/bin/shopify:36:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/bin/shopify:47:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'</details>

## Expected behavior

What do you think should happen?

The shopify cli should serve the theme

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

The CLI loads a login page in Chrome. I click login and the browser says I am authenticated. Then, the error message above pops up in my terminal.

## Steps to reproduce the problem

1. Navigate to directory of Dawn theme
1. type in command ```shopify login``` or ```shopify theme serve```
1. Click Login in Chrome when the browser pops up

## Specifications

- App type: shopify-cli v2.6.5
- Operating System: MacOS Big Sur 11.6
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

## Other Details

Output from ```shopify system all```:

<details>Environment
  TERM              = xterm-256color
  SHELL             = /bin/zsh
  PATH              = /usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/openssl/bin:/usr/local/sbin:/usr/local/opt/openjdk@11/bin:/usr/local/opt/php@7.4/bin:/Users/beers/.nvm/versions/node/v12.4.0/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/apache-maven/bin:/Users/beers/.composer/vendor/bin:/opt/apache-maven/bin:/Users/beers/.rvm/bin:/Users/beers/.composer/vendor/bin:/opt/apache-maven/bin:/Users/beers/.rvm/bin:/Users/beers/.composer/vendor/bin:/opt/apache-maven/bin:/Users/beers/.rvm/bin:/Users/beers/.composer/vendor/bin:/opt/apache-maven/bin:/Users/beers/.rvm/bin:/Users/beers/.composer/vendor/bin:/opt/apache-maven/bin:/Users/beers/.rvm/bin
  LANG              = en_US.UTF-8

Shopify CLI
               ROOT = /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5
  PROJECT_TYPES_DIR = /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/lib/project_types
           TEMP_DIR = /usr/local/Cellar/shopify-cli/2.6.5/gems/shopify-cli-2.6.5/.tmp
          CACHE_DIR = /Users/beers/.cache/shopify
   TOOL_CONFIG_PATH = /Users/beers/.config/shopify
           LOG_FILE = /Users/beers/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /Users/beers/.config/shopify/logs/debug.log

Current Shop
  wee-ones-consumer.myshopify.com

Ruby (via RbConfig)
  /usr/local/Cellar/ruby/3.0.2_1/bin/ruby
  x86_64-apple-darwin20     - RbConfig["host"]
  ruby-3.0.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar</details>

**Comment by corazzi** [comment]
@nathanbeers I had the same issue as you, though with a slightly different environment.

If you run `ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'` you should get something similar to this:

`"/usr/local/etc/openssl@1.1/cert.pem"`

When I tried to look into that file, though, it didn't exist.

If you get the same result, try tunning this command to fetch the latest certificate authorities. It fixed it for me.

```bash
curl -fsSL curl.haxx.se/ca/cacert.pem -o "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
```
