### ISSUE TITLE
Shopify theme serve slow in css files replace

### ISSUE THREAD

**Issue by Sanj718** [Shopify/shopify-cli#1691]
# Issue summary

I'm using webpack to convert my sass files and push it to assets folder (min.css). So technically i'm compressing and replacing changed file to assets folder. For some reason Shopify theme serve takes much longer to detect those changes rather than directly changing it. 
 

## Expected behavior

I'm expecting to detect my css files changes in assets folder immediately as soon as i replace them, in development mode. 

## Actual behavior

It takes about 20 seconds or more to detect change and show it on local dev server via using theme serve. 
I feel like shopify theme servre is mainly detecting file save behaviour but i'm wondering if there is any way to (of config) to detect css file replace. 

## Steps to reproduce the problem

1. Making change in my Sass files. (common.scss)
2. Which is processed by webpack and replacing the existing file in assets folder (common.min.css)
3. Check for local dev url and nothing changes. Only after 20+ seconds i see my changes. 

The i tried to run shopify theme serve and manually replaced common.min.css file, and i see delay too. 
So, outcome, shopify theme serve has delay on replaced files, however it works great for existing file edits. 

NOTE:
It works immediately if i directly change/edit css files inside assets folder.

**Comment by EvgeniyMukhamedjanov** [comment]
I feel like the delay is happening with all the files if the root folder that is served by CLI contains files/folders that don't belong to Shopify: `package.json`, `src/`, etc. in my case. The `.shopifyignore` doesn't help. Once I shift all the Shopify folders into a dedicated folder and serve that folder by CLI — the delay disappear.
