### ISSUE TITLE
shopify php serve error 

### ISSUE THREAD

**Issue by yimincheah** [Shopify/shopify-cli#1704]
# Issue summary

Write a short description of the issue here ↓
Error goes when type shopify php serve in terminal

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<details>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┏━━ Running server… 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┗━━━━━━━                                                             (0.16s)
X An unexpected error occured.
        To submit an issue include the stack trace.

Traceback (most recent call last):
        32: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        31: from C:/Ruby27-x64/bin/shopify:23:in `load'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/bin/shopify:47:in `<top (required)>'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/bin/shopify:36:in `block in <top (required)>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort' 
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/bin/shopify:37:in `block (2 levels) in <top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/entry_point.rb:23:in `call'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/monorail.rb:30:in `log'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:15:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'        
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:16:in `block in call'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'      
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'       
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'     
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/command.rb:19:in `call'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/sub_command.rb:13:in `call'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/project_types/php/commands/serve.rb:28:in `call'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/project_types/php/commands/serve.rb:35:in `block in call'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/lib/shopify_cli/context.rb:428:in `system'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:219:in `resolve_path'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `which'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `fetch': key not found: "PATHEXT" (KeyError)
</details>

## Steps to reproduce the problem

1. shopify php create
2. shopify php serve

## Specifications

- App type: php public app
- Operating System: Windows 10
- Shell: 
- Ruby version (ruby -v): ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]

**Comment by amcaplan** [comment]
This should be fixed by #2005.
