### ISSUE TITLE
Intermittent theme push error: "can't add a new key into hash during iteration"

### ISSUE THREAD

**Issue by dylansmith** [Shopify/shopify-cli#1705]
# Issue summary

We have an automated workflow for pushing theme updates to our stores using the Shopify CLI. However, when using the `shopify theme push` command we intermittently (and fairly frequently) get one or more of the following errors in the console output:

```
ERROR update <filename.liquid>: can't add a new key into hash during iteration
```

To make matters worse the process ends with exit code 0, so we cannot reliably detect that sometime has gone wrong without parsing the console output for keywords. This seems to occur more frequently when pushing a new unpublished theme, or when there are a large number of files to sync.

This seems to be impacting other users, especially those using the `--json` flag to write to a file, as it results in invalid JSON. See #1353 and #1417.

Can you tell us what is causing these errors and whether this is something that Shopify is actively working to resolve?

## Expected behavior

If there are syncing errors, the CLI should retry the impacted files a reasonable number of times and fail with an exit code of 1 if the theme could not be wholly and reliably pushed to Shopify. It should not be possible for the CLI to push a partial (broken) theme update, particularly if you are pushing to the live, published theme.

## Actual behavior

The `shopify theme push` operation always ends with exit code 0 even if errors are reported, and we cannot be certain that the theme has been pushed correctly.

## Steps to reproduce the problem

1. Use the `shopify theme push -u` command to push a new unpublished theme
1. The errors appear intermittently, so you may need to try this a number of times

## Specifications

- App type: Theme
- Operating System: MacOS
- Shell: Bash
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

**Comment by juergengenser** [comment]
same here when uploading a bulk of asset files at once.
