### ISSUE TITLE
Hot Reload fails on CSS change 

### ISSUE THREAD

**Issue by cnscorpions** [Shopify/shopify-cli#1709]
# Issue summary

Write a short description of the issue here ↓
1. `shopify theme serve` run a local server
2. do some CSS changes in theme.css
3. page not refresh and changes will not be applied
4. reload page manually, and then CSS changes will be applied

## Expected behavior

What do you think should happen?
CSS changes applied as expected

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- App type: Theme Prestige
- Operating System: win10 Pro
- Shell: Powershell + Windows Terminal
- Ruby version (ruby -v): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]
- Shopify-cli Version: 2.6.5
- Chrome: Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by bigskillet** [comment]
Check out this thread: https://github.com/Shopify/shopify-cli/issues/1409

**Comment by cnscorpions** [comment]
@bigskillet thanks, I have checked it out. But same issue, `shopify theme serve --poll` does not work

**Comment by macournoyer** [comment]
Is it possible there were two CSS files defined on the same line in the Liquid file? Something like:

```
<link rel="stylesheet" href="{{ 'theme.css' | asset_url }}" /><link rel="stylesheet" href="{{ 'theme2.css' | asset_url }}" />
```

If, so it should be fixed by https://github.com/Shopify/shopify-cli/pull/1714

If not, can you paste the part of the Liquid file where `theme.css` is loaded.

**Comment by MaxDesignFR** [comment]
I encountered a similar issue today, this structure would cause "[HotReload] Could not find link for stylesheet..."

```
{%- capture script -%}header{% if section.settings.minified_files %}.min{% endif %}.js{%- endcapture -%}
{%- capture style -%}header{% if section.settings.minified_files %}.min{% endif %}.css{%- endcapture -%}
<link rel="stylesheet" href="{{ style | asset_url }}" type="text/css" media="print" onload="this.media='all'">
<script src="{{ script | asset_url }}" defer></script> 
```

Following previous comment I switched line orders and it somehow fixed this issue. I'm using Shopify CLI 2.23.0.
