### ISSUE TITLE
Unable to serve, push, or pull themes since v2.6.6

### ISSUE THREAD

**Issue by jasewarner** [Shopify/shopify-cli#1718]
# Issue summary

Having logged into a store, since upgrading to Shopify CLI 2.6.6, I am unable to `serve`, `push`, or `pull` themes.

## Expected behavior

I should be able to `serve`, `push`, and `pull` themes.

## Actual behavior

After running `shopify login --store=<store>`, I receive the following message: 

`Logged into store <store> in partner organization <organisation>`

However, when running a theme command, I receive an error message. 
For instance, when running `shopify theme serve`, I get the following error:

```
✗ You are not authorized to edit themes on <store>.
Make sure you are a user of that store, and allowed to edit themes.
```

I have tried logging out of the various stores as well as my partner account, and then logging back in again using `shopify login --store=<store>`, but to no avail. Incidentally, this problem would crop up every now and again in previous versions of Shopify CLI, but the aforementioned logging-out "fix" did the trick.

## Steps to reproduce the problem

1. Run `shopify login --store=<store>`
1. Then try `shopify theme serve`
1. Wait for the error message

## Specifications

- Operating System: macOS Big Sur 11.6
- Ruby version (ruby -v): 2.6.5p114

**Comment by GitYing** [comment]
in your cli logout of shopify
on your browser also log out of shopify
visit partners.shopify.com and login
find your store and login using your partner portal

go back to CLI and 
"shopify login"
Go and authorize it
"shopify switch --store=xx"

and now things should work

**Comment by jasewarner** [comment]
> in your cli logout of shopify on your browser also log out of shopify visit partners.shopify.com and login find your store and login using your partner portal
> 
> go back to CLI and "shopify login" Go and authorize it "shopify switch --store=xx"
> 
> and now things should work

@GitYing, thanks for your reply. As mentioned in my initial post, I tried this method but I am still getting the `✗ You are not authorized to edit themes…` error message. Whilst this "fix" worked in previous versions of Shopify CLI, it no longer seems to work in v2.6.6.

**Comment by GitYing** [comment]
> > in your cli logout of shopify on your browser also log out of shopify visit partners.shopify.com and login find your store and login using your partner portal
> > go back to CLI and "shopify login" Go and authorize it "shopify switch --store=xx"
> > and now things should work
> 
> @GitYing, thanks for your reply. As mentioned in my initial post, I tried this method but I am still getting the `✗ You are not authorized to edit themes…` error message. Whilst this "fix" worked in previous versions of Shopify CLI, it no longer seems to work in v2.6.6.

You're right, this used to work but not anymore.. I have since instead created a dedicated "Staff Account" for shopify cli use... its a pain but i log out of my partner accounts and just login using storeurl.com/admin then use my staff acc and then authenticate my cli

**Comment by monting** [comment]
Getting the same issue currently. This is making the tool an impediment. Please fix 🙏

**Comment by jdunham2** [comment]
Likewise having this issue. Only on some stores... Using theme kit as a fallback but would love if we can fix this with shopify cli.

**Comment by alex-digital-hawks** [comment]
When I was having this issue it was due to custom folders being added to the assets folder, the cli doesn’t tell you what the exact error was but stripping the team completely back to bare bones helped me to be able to serve push and pull again using the cli! 

Hope this helps someone as it’s absolutely frustrating

**Comment by jasewarner** [comment]
Any news on a fix for this? I'm still experiencing the problem in some stores (I have full permissions in all).

**Comment by curiouscrusher** [comment]
Just experienced this today, same issue where logging into a store via partner organization does not allow for theme editing.

**Comment by jdunham2** [comment]
I have noticed the permissions seem to get cached in the browser and, until
you clear them, cli will not update your permissions.

I’m doing this from memory so it might not be perfect but try the following:

From terminal run ‘shopify logout’
Next run ‘shopify login’
Then when the browser opens
open inspector and from the application tab clear the “application storage”
Rerun ‘shopify login’
