### ISSUE TITLE
Github integration and CLI, not pulling or watching changes to template JSON files

### ISSUE THREAD

**Issue by arqdesignstudio** [Shopify/shopify-cli#1719]
# Issue summary

Write a short description of the issue here ↓
CLI is not watching for changes from JSON templates made in the Customizer, where files are under the Templates folder. Everytime I make a customizer change to a template, I have to download the template files with a seperate window using Themekit to 'theme get templates' so it gets logged in GitHub.

If I forget to do this step, then I lose all my content when I push it to a published or unpublished theme. CLI and Github should be logging those changes for me without this extra step.

## Expected behavior

What do you think should happen?
When I am editing a development site locally, but using the development customizer, all changes made in the development site customizer should be watched by CLI and comitted to the GitHub connection so I can see and merge changes to those files in GitHub.

## Actual behavior

What actually happens?
Template files are not being watched or downloaded by GitHub.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

When using the comment Shopify theme serve, no changes made to the customizer are being logged in Github when connected to a branch

## Steps to reproduce the problem

https://www.loom.com/share/92ad0c0e3a34408f82b455a37390209c

## Specifications

- App type: Shopify CLI connected to Microsoft Visual Studio
- Operating System: Mac OS Catalina
- Shell: 
- Ruby version (ruby -v):ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by arqdesignstudio** [comment]
Not a small deal, it's a HUGE deal. If you don't use themekit to manually pull any config files or templates, you lose EVERYTHING all progress. Please fix ASAP, otherwise CLI is essentially useless without both setups and themekit has major conflicts with CLI if you muck it up or accidently run theme watch while connected to GitHub.

**Comment by joshuaiz** [comment]
It's still relevant. As a workaround I moved everything out of the Customizer which is a bit drastic but nothing else was working and it doesn't look like anyone at Shopify is concerned with this issue.

**Comment by arqdesignstudio** [comment]
This is still very relevant.

Not a single store connected to CLI will pull any files from the /templates
file with changes made inside the customizer into GitHub tracking changes.
The only way to pull any template changes is to use themekit download
commands in conjunction with CLI or else you will lose your work if you
close your code editor, or CLI logs out

Warmest Regards,
Lea Gucciardi

*Creative Director | Designer | Developer*Branding | Development |
eCommerce | Websites | Products

*www.arqdesign.studio*

Office Hours: T, W, T, F 10AM - 4PM EST
Sunday, Monday, Saturday Closed
E:  ***@***.*** ***@***.***>

**Comment by arqdesignstudio** [comment]
This is still very relevant.

Not a single store connected to CLI will pull any files from the /templates
file with changes made inside the customizer into GitHub tracking changes.
The only way to pull any template changes is to use themekit download
commands in conjunction with CLI or else you will lose your work if you
close your code editor, or CLI logs out

Or you have to make all changes to the .json file instead of the development customizer,
or continue to manually run theme pull /templates

**Comment by arqdesignstudio** [comment]
Video showcasing the issue

https://www.loom.com/share/81311999d07d48d88f0f41603cff0c72
