### ISSUE TITLE
cmd line unable to login using shopify login

### ISSUE THREAD

**Issue by lewissutton02** [Shopify/shopify-cli#1720]
# Issue summary

Write a short description of the issue here ↓
When using 'shopify login --store' it allows me to authenticate my account but then I get an 'unexpected error' in cmd line.

## Expected behavior

What do you think should happen?
When using shopify login --store, I should authenticate the account (which it lets me do) then my cmd line should state that I've logged in successfully.

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error
<X An unexpected error occured.
        To submit an issue include the stack trace.

C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - git (Errno::ENOENT)
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:102:in `popen3'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open3.rb:289:in `capture3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/context.rb:493:in `capture3'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/git.rb:142:in `exec'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/git.rb:148:in `rev_parse'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/git.rb:24:in `sha'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli.rb:178:in `sha'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/api.rb:113:in `default_headers'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/api.rb:57:in `block in request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/api.rb:89:in `request'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/api.rb:37:in `query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/partners_api.rb:39:in `block in query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/partners_api.rb:40:in `query'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/partners_api/organizations.rb:6:in `fetch_all'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/commands/login.rb:78:in `select_organization'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/commands/login.rb:34:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/command.rb:25:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/monorail.rb:30:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/bin/shopify:37:in `block (2 levels) in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/bin/shopify:36:in `block in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.6.6/bin/shopify:47:in `<top (required)>'
        from C:/Ruby30-x64/bin/shopify:23:in `load'
        from C:/Ruby30-x64/bin/shopify:23:in `<main>'>

## Steps to reproduce the problem

1.    Open Command Prompt
2.    Shopify login --store= " ... "
3.    Error message

## Specifications

- App type: Command Prompt
- Operating System: Windows 10
- Shell:
- Ruby version (ruby -v): 3.0.2

**Comment by DarwinSSV** [comment]
am also facing the same issue. It's annoying

**Comment by gonzaloriestra** [comment]
Do you have Git installed on your system? You can download it here: https://git-scm.com/download/win
