### ISSUE TITLE
Shopify theme serve function not updating local changes.

### ISSUE THREAD

**Issue by matthaighdj** [Shopify/shopify-cli#1740]
# Issue summary

Hi

The shopify theme serve function has not been working (showing changes locally) for over a week now.

I have to make the changes "blind" and push the theme to check on the live shopify site for updates.

Is this a known issue?

shopify-cli version is 2.6.6 as per screenshot.

Also shared a screenshot if the shopify serve command for current store.

Thanks

Matt

## Expected behavior

What do you think should happen?

Local environment should preview changes to theme files in realtime.

## Actual behavior

What actually happens?

Nothing, the local environment does not show/update any changes to theme files.

## Steps to reproduce the problem

1. Run shopify theme serve   
1. update a theme file.
1. preview theme on local enviroment (http://127.0.0.1:9292)

## Specifications

- App type: theme
- Operating System: macOS Big Sur (11.4) 
- Shell: Terminal
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

![Screenshot 2021-11-11 at 12 20 45](https://user-images.githubusercontent.com/49408460/141298557-a360485c-cc8c-451c-9327-ead095849862.png)
![Screenshot 2021-11-11 at 12 18 48](https://user-images.githubusercontent.com/49408460/141298594-39290e24-aff9-427c-9117-9351e23c18b2.png)

**Comment by nelsonvassalo** [comment]
Also experiencing this all of a sudden. On CLI 2.34.0

**Comment by havardjohansen** [comment]
Same here

**Comment by dev-goutham** [comment]
Same here, 2.15.5

Was working fine until a few hours ago. Stopped working when I started working on a new theme.
