### ISSUE TITLE
What is the correct way of sharing a theme link with a client?

### ISSUE THREAD

**Issue by chrish-d** [Shopify/shopify-cli#1741]
# Issue summary

Write a short description of the issue here ↓

I have a branch I'm working on with some changes I want to preview to a client (`branch-alpha`). I also have another branch I'm working on with another feature I want to share with the client (`branch-beta`).

Running `shopify theme serve` on `branch-alpha` gives me an option to "share this theme preview", but if I checkout to another branch (`branch-beta`) and run the same command, I get the same share link given again.

## Expected behavior

**What do you think should happen?**

The command should generate two unique theme IDs to allow me to share the separate changes with the client.

## Actual behavior

**What actually happens?**

The two branches share the same theme and override any changes made between branches, making it impossible to share two different branches as a preview link.

A way around this I found was to "add a theme" from Shopify's themes page via the GitHub connection, and then select the two branches there. This does become a bit cumbersome however when you've got multiple branches to preview, and adds additional admin deleting themes (branches) that have been merged.

**Comment by karreiro** [comment]
Closed by https://github.com/Shopify/shopify-cli/pull/2200.
