### ISSUE TITLE
Clean creation of new React App fails to make connection between store and server.

### ISSUE THREAD

**Issue by punkscience** [Shopify/shopify-cli#1775]
# Issue summary

Write a short description of the issue here ↓

Following the tutorial instructions and creating a fresh app using `shopify app create node`. 
Resulting app server compiles and runs successfully on the server side using ngrok.
Resulting app client installs successfully on my development store.
When I click on my app in the development store, nothing happens -- it seems to fail to connect. Error message on server side is:

ℹ ｢hot｣: WebSocket Client Connected
┃ ⚠ ｢hot｣: client socket error {"errno":-54,"code":"ECONNRESET","syscall":"read"}

## Expected behavior

What do you think should happen?

Default app, when clicked should show me something like "Shopify App using React!"

## Actual behavior

What actually happens?

When I click on my app in the development store, nothing happens -- it seems to fail to connect. Error message on server side is:
<details>
ℹ ｢hot｣: WebSocket Client Connected
┃ ⚠ ｢hot｣: client socket error {"errno":-54,"code":"ECONNRESET","syscall":"read"}
</details>

## Steps to reproduce the problem

1. Setup an ngrok account
2. Login to your shopify store
3. Setup ngrok key
4. shopify app create node
5. shopify serve
6. Install app in default development store.
7. Go to development store app list and click on the app to open it.

## Specifications

- App type: Node
- Operating System: MacOS
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by ayozemr** [comment]
nevermind, in my case I was missing a scope in .env... I still see that error in console, but app is loading
