### ISSUE TITLE
Ngrok installation fails on Windows

### ISSUE THREAD

**Issue by robcode222** [Shopify/shopify-cli#1776]
# Issue summary

I'm working on a Shopify app.  When I run the command "shopify app serve" from inside the app directory, it fails at installing ngrok.  It says "Something went wrong with ngrok installation, please make sure ngrok.exe exists within c:/Users/name/AppData/Local/shopify before trying again."

I have verified and ngrok is in that path.  In fact, the "shopify app serve" command continues to download ngrok, unzips it and then complains it can't find it when it downloaded it and unzipped it.  I have check the permissions and ngrok has full permissions.  

**Note that the directory path in the error error message uses forward slashes and windows uses backslashes.**    

## Expected behavior

What do you think should happen?
ngrok should execute and open up a tunnel.

## Actual behavior

What actually happens?

Error message basically saying it can't find ngrok.exe when it is in the directory it says to put it in.

## Steps to reproduce the problem

1.  shopify app serve

## Specifications

- App type: ngrok
- Operating System:  Windows10
- Shell:  command prompt
- Ruby version (ruby -v):  3.0.2p107

**Comment by robcode222** [comment]
I tried PowerShell since it can handle both types of file slashes '/' and '\'.  Still can't find the file that is there.

**Comment by Man-RP** [comment]
Same here

**Comment by zakariamofaddel** [comment]
Same, it fails every time at "Installing ngrok..."

**Comment by Man-RP** [comment]
> In your AppData\Local\shopify folder, check if ngrok.zip exists. If not, download from their website. Extract it here manually.
> 
> It should be like this ..AppData\Local\shopify \ngrok\ngrok.exe

not working dude..

**Comment by 90stareq** [comment]
Thanks @sarik-k .
Create a **folder** at this directory with the name **ngrok**: **..AppData\Local\shopify** --> **paste ngrok.exe here**
like: C:/Users/USER/AppData/Local/shopify/ngrok/ngrok.exe

**Comment by umar9871** [comment]
> copy ngrok.exe ngrok



> There's a regression bug on the version 2.7.1 affecting Windows environments. While we work on a new release to fix it, you can downgrade to version 2.7.0 or follow this workaround:
> cd %HOMEPATH%/AppData/Local/shopify
> copy ngrok.exe ngrok
> ```
> 
> Sorry for the inconvenience.

Not working this solution got some permission errors

**Comment by zakariamofaddel** [comment]
> > copy ngrok.exe ngrok
> 
> 
> 
> 
> 
> 
> 
> > There's a regression bug on the version 2.7.1 affecting Windows environments. While we work on a new release to fix it, you can downgrade to version 2.7.0 or follow this workaround:
> 
> > cd %HOMEPATH%/AppData/Local/shopify
> 
> > copy ngrok.exe ngrok
> 
> > ```
> 
> > 
> 
> > Sorry for the inconvenience.
> 
> 
> 
> Not working this solution got some permission errors

I would suggest just uninstalling the Shopify CLI (look at docs on which command to run), and install it again specifying the version @2.7.0.

It's the fastest and cleanest way to fix this issue while we wait for a fix 😄

**Comment by gonzaloriestra** [comment]
The fix has been included in the [latest release (2.7.2)](https://github.com/Shopify/shopify-cli/releases/tag/v2.7.2). Thanks for your patience!

**Comment by gonzaloriestra** [comment]
@dwight9339 yes, I'm afraid Git Bash is not fully compatible. But if you install it from CMD, then you will be able to use it from Git Bash (at least the tunneling part):
- `gem uninstall shopify-cli`
- `rmdir c:/Users/name/AppData/Local/shopify`
- `gem install shopify-cli`
- `shopify app tunnel start` (so that it installs Ngrok)

**Comment by dwight9339** [comment]
Got it. Thanks!
