### ISSUE TITLE
problems with ngrok installation when running "shopify app serve"

### ISSUE THREAD

**Issue by Man-RP** [Shopify/shopify-cli#1777]
# Issue summary

I'm working on a Shopify app. When I run the command "shopify app serve" from inside the app directory, it fails at installing ngrok. It says "Something went wrong with ngrok installation, please make sure ngrok.exe exists within c:/Users/<username>/AppData/Local/shopify before trying again."

## Expected behavior

ngrok should execute and open up a tunnel.

## Actual behavior

Error message basically saying it can't find ngrok.exe when it is in the directory it says to put it in.

## Specifications

App type: ngrok
Operating System: Windows10
Shell: command prompt
Ruby version (ruby -v): 3.2.22
node version: 16.13.0

**Comment by gonzaloriestra** [comment]
Duplicated of https://github.com/Shopify/shopify-cli/issues/1776
