### ISSUE TITLE
theme serve: warnings displayed when symlinks linking to project files exist

### ISSUE THREAD

**Issue by ettoredn** [Shopify/shopify-cli#1780]
# Issue summary
Thousands of warnings are displayed when a project file is symlinked inside the project (e.g. when using pnpm).

## Expected behavior
No warnings.

## Actual behavior

```
        Directory: /Users/ettore/Workspace/theme/node_modules/.pnpm/snapdragon@0.8.2/node_modules/base

        is already being watched through: /Users/ettore/Workspace/theme/node_modules/.pnpm/base@0.11.2/node_modules/base

        MORE INFO: https://github.com/guard/listen/blob/master/README.md
        ** ERROR: directory is already being watched! **
```

## Steps to reproduce the problem

1. use pnpm for managing javascript dependencies in a theme project
1. add `/node_modules/` in `.shopifyignore`
1. `shopify theme serve`

## Specifications

- App type: theme
- Operating System: macOS 10.15.5
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by karreiro** [comment]
Resolved by https://github.com/Shopify/shopify-cli/pull/2270.
