### ISSUE TITLE
Errno::ENOENT: No such file or directory - git

### ISSUE THREAD

**Issue by maoece** [Shopify/shopify-cli#1782]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

E:/Ruby/lib/ruby/3.0.0/open3.rb:221:in `spawn'
E:/Ruby/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
E:/Ruby/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
E:/Ruby/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
E:/Ruby/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by gonzaloriestra** [comment]
Do you have Git installed on your system? You can download it here: https://git-scm.com/download/win
