### ISSUE TITLE
NoMethodError: undefined method `split' for [""]:Array

### ISSUE THREAD

**Issue by sarik-k** [Shopify/shopify-cli#1783]
# Issue summary
Getting 'An unexpected error occured' when running `shopify app serve` after ngrok tunnel has been created. 

## Expected behavior
Server should run without errors. 

## Actual behavior
Getting 'An unexpected error occured' when running `shopify app serve` after ngrok tunnel has been created. 

## Steps to reproduce the problem

1. Run `shopify app serve`
2. Choose whether to update application url or not
3. Getting error after 'Running server...` shows up in terminal

## Stacktrace

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `which'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:219:in `resolve_path'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/context.rb:428:in `system'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/lib/shopify_cli/services/app/serve/php_service.rb:39:in `block in call'

## Specifications

- App type: Public
- Operating System: Windows 10
- Shell: git bash / powershell
- Ruby version (ruby -v): 2.7.4p191

**Comment by SalmanMalyk** [comment]
Simple, just go to C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.7.1/vendor/deps/cli-kit/lib/cli/kit and open "system.rb". On line 219 just remove ".split(';')" and run command again. It'll work 🗡️

**Comment by gonzaloriestra** [comment]
Related to https://github.com/Shopify/shopify-cli/issues/1828

**Comment by amcaplan** [comment]
This should be fixed by #2005.
