### ISSUE TITLE
Replace storage provider for Ngrok binaries

### ISSUE THREAD

**Issue by gonzaloriestra** [Shopify/shopify-cli#1784]
We are downloading ngrok from [Equinox URLs](https://github.com/Shopify/shopify-cli/blob/e18d552c8325b92bdd9468656b8fc4761023329e/lib/shopify_cli/tunnel.rb#L23:L25), but the service was apparently going to shut down on September 30th according to [this announcement](https://equinox.io/blog/shutting-down) (although it still works).

We should better store the binaries on our servers or any other place.

**Comment by stephszeto** [comment]
Going to close this in light of the new tunneling direction we're going in.
