### ISSUE TITLE
shopify-cli fails to find ruby on Mac

### ISSUE THREAD

**Issue by artooras** [Shopify/shopify-cli#1789]
# Issue summary

I followed the recommended steps to install `shopify-cli` on Mac via homebrew. When I want to verify the installation by running `shopify version`, I get an error.

## Expected behavior

`shopify version` to output the version

## Actual behavior

I get an error message below:

`/usr/local/bin/shopify: line 2: /opt/homebrew/Cellar/ruby/3.0.1/bin/ruby: No such file or directory`

## Specifications

- App type: Node
- Operating System: Mac OS
- Shell: zsh
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]

## Also

The contents of the file at `/usr/local/bin/shopify` are:

`#!/usr/bin/env bash`
`/opt/homebrew/Cellar/ruby/3.0.1/bin/ruby --disable=gems -I /opt/homebrew/lib/ruby/gems/3.0.0/gems/shopify-cli-1.13.1 /opt/homebrew/lib/ruby/gems/3.0.0/gems/shopify-cli-1.13.1/bin/shopify $@`

**Comment by Cam** [comment]
I've found none of the suggestions I could find worked, but eventually came up with [this workaround](https://github.com/Shopify/shopify-cli/issues/2057#issuecomment-1058877945).

**Comment by gonzaloriestra** [comment]
The release [2.13.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.13.0) should fix this issue. It now supports Ruby 3.1 and the brew formula has changed. Please, let us know if you still have problems.
