### ISSUE TITLE
Node.js 17.x not compatible with Shopify CLI "shopify app serve"

### ISSUE THREAD

**Issue by bethkellyshopify** [Shopify/shopify-cli#1808]
# Issue summary

The latest version of Node.js for Mac is currently 16.13.0 LTS and 17.2.0 Current.
Node.js 17.0.1 and 17.2.0 (tried both) do not work with the node.js installation that shopify cli puts into the local app.  When you run `shopify app serve` with either of these two versions, you get the error seen below and then the app crashes.

Installing Node.js 16.13.0 still runs with an error, but it runs.

Seems like something fundamentally changed between node versions.

## Expected behavior

What do you think should happen?

App should run and be useable at the URL given during the running of `shopify app serve`

## Actual behavior

What actually happens?

Server crashes and `shopify app serve` waits for a file change to retry
Because app crashed, the local host is not responding at the ngrok URL given in the script.

## Steps to reproduce the problem

1. follow the procedures here:  https://shopify.dev/apps/getting-started/create
2. When reviewing the requirement for "You've installed the latest version of Node.js.", assume that if the version you have is between the LTS version and the Current version, you should be OK.
3. get to step 4 and encounter the error in the stacktrace

## Stacktrace

> ┏━━ Running server… 
> ┃
> ┃ > shopify-app-node@1.0.0 dev
> ┃ > cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
> ┃
> ┃ [nodemon] 2.0.6
> ┃ [nodemon] to restart at any time, enter `rs`
> ┃ [nodemon] watching path(s): server/index.js
> ┃ [nodemon] watching extensions: js,mjs,json
> ┃ [nodemon] starting `node ./server/index.js`
> ┃ Browserslist: caniuse-lite is outdated. Please run:
> ┃ npx browserslist@latest --update-db
> ┃ node:internal/modules/cjs/loader:488
> ┃       throw e;
> ┃       ^
> ┃
> ┃ Error: Package subpath './lib/parser' is not defined by "exports" in /Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/node_modules/postcss/package.json
> ┃     at new NodeError (node:internal/errors:371:5)
> ┃     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
> ┃     at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
> ┃     at resolveExports (node:internal/modules/cjs/loader:482:36)
> ┃     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
> ┃     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
> ┃     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
> ┃     at Module.require (node:internal/modules/cjs/loader:999:19)
> ┃     at require (node:internal/modules/cjs/helpers:102:18)
> ┃     at Object.552 (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
> ┃     at __webpack_require__ (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
> ┃     at Object.560 (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
> ┃     at __webpack_require__ (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
> ┃     at Object.290 (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
> ┃     at __webpack_require__ (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
> ┃     at Object.632 (/Users/bethkelly/src/github.com/Shopify/bettythree/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
> ┃   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
> ┃ }
> ┃
> ┃ Node.js v17.2.0
> ┃ [nodemon] app crashed - waiting for file changes before starting...

## Specifications

- App type:  shopify-cli 2.7.1
- Operating System: Mac OS Monterey, version 12.0.1
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by eatfrog** [comment]
Seeing this on windows too

**Comment by lindaludovisi** [comment]
It is happening also for me. Any idea on how to solve this issue?

**Comment by martinezfran63** [comment]
I resolved this issue by changing the version of node used. In my case I installed nvm. Then I ran `nvm install --lts`. I was then able to run `shopify app serv` and create the server without any issues.

**Comment by ykhakshoor** [comment]
Had the same issue. Downgraded the versions of node and npm, now it works. Make sure to delete your old versions!

**Comment by Joshuaf91** [comment]
I'm also seeing this issue running node v17.

Thank you @martinezfran63 I resolved this using nvm as well.

**Comment by pepicrft** [comment]
👋🏼 First of all, apologies that you are running into this issue. I investigated it a bit, and it turns out there's an incompatibility between the dependency graph of the NextJS app that the shopify-cli generates and Node 17. 
Unfortunately, there's no straight solution that doesn't involve changing the `postcss` package so my advice until a fix is pushed upstream on that package is to downgrade to Node 16. We recommend installing [nvm](https://github.com/nvm-sh/nvm) in your environments to manage multiple Node installations.
I'll keep this issue until we can provide a proper solution for this. Please, if anyone finds a workable workaround for this, don't hesitate to post it here, or even better, open a PR on [this repository](https://github.com/Shopify/shopify-app-node).

**Comment by pepicrft** [comment]
[Once this PR gets merged](https://github.com/Shopify/app-bridge/pull/2116), we'll be able to update Next to the latest version in the template that we use, and that should bring the compatibility with Node 17

**Comment by pepicrft** [comment]
I created [a PR ](https://github.com/Shopify/shopify-app-node/pull/694) to update the template to the latest Next version which is compatible with Node 17. If you already have an app created with NextJS, you can update the following dependencies in your project to get it working:

```json
{
  "dependencies": {
    "@shopify/app-bridge-react": "^2.0.6",
    "@shopify/app-bridge-utils": "^2.0.6",
    "@shopify/koa-shopify-auth": "^4.1.4",
    "next": "^12.0.8",
    "next-env": "^1.1.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  }
}
```
