### ISSUE TITLE
Show the current live theme when users execute `theme push` without the `--allow-live` parameter

### ISSUE THREAD

**Issue by karreiro** [Shopify/shopify-cli#1809]
# Issue summary

When users execute `theme push`, they are prompted with the following message:

```
Are you sure you want to push to your live theme? (Choose with ↑ ↓ ⏎)
> 1. yes
  2. no
```

However they do not know which theme is being used as live.

## Expected behavior

What do you think should happen?

The message must include the live theme name and ID:

```
Are you sure you want to push to your live theme (Dawn #126557585430)? (Choose with ↑ ↓ ⏎)
> 1. yes
  2. no
```

## Actual behavior

The message does not include live theme name and ID:
```
Are you sure you want to push to your live theme? (Choose with ↑ ↓ ⏎)
> 1. yes
  2. no
```

**Comment by ADTC** [comment]
I thought the theme name would be on another line (before question). If we keep it in the same line as the question, does this question prompt still look good when the theme name is 50 characters long? (50 is the max allowed.)

**Comment by ADTC** [comment]
A suggestion, if it has to be on the same line:
```
Push to live theme (Dawn #126557585430)? (Choose with ↑ ↓ ⏎)
       (vs.)
Are you sure you want to push to your live theme (Dawn #126557585430)? (Choose with ↑ ↓ ⏎)
```

**Comment by ADTC** [comment]
What do you think of this shorter text? (At least for English). Will this be on another PR, if ever?

**Comment by karreiro** [comment]
@ADTC, yeah, we're planning to include these extra details (live theme name and ID) in a new PR.

Regarding the limit of 50 characters, I'm not sure if word wrap is a problem in this case. I'm looping in @MeredithCastile to get her thoughts about this :)

**Comment by ADTC** [comment]
Okay, sure. Anyway, I've updated the last comment to hopefully make it clearer. Please take a look again.

**Comment by karreiro** [comment]
Hi @ADTC,

I'm wondering about this direction:
<img width="60%" src="https://user-images.githubusercontent.com/1079279/145119644-46b94b71-761f-43cf-8ed7-baa7232de310.png" />

Because it's a bit similar to the UI when users are selecting a theme:
<img width="60%" src="https://user-images.githubusercontent.com/1079279/145119648-283a4c79-9c0c-4788-8477-6dd68e61cb89.gif" />

What do you think about it? I'm trying to keep the _"Are you sure you want to [...]"_ part, so we continue raising users' attention to the impact of this command.

**Comment by ADTC** [comment]
@karreiro that looks good! Could also be this, if it makes more sense to keep the keyboard instruction with the question:
```
Are you sure you want to push to your live theme? (Choose with ↑ ↓ ⏎)
Theme: Venture #126591205398 [live]
1. yes
2. no
```
In this case, the part `Theme:` should remain in white while the theme name itself is in the suggested color blue.

**Comment by karreiro** [comment]
Great 🚀 I will do that! Thanks, @ADTC :)
