### ISSUE TITLE
JSON errors in pages when merging

### ISSUE THREAD

**Issue by opium-opiumoo** [Shopify/shopify-cli#1816]
# Issue summary

I'm having JSON errors on merge which involves the JSON of the blocks when I merge a development theme (which is not live) with the live theme. None of the blocks are visible. The error in the "View Logs" panel says "invalid type of block" and this happens every time I merge something from a different theme. I want to clarify that all the JSON is generated by the customizer. I do not edit any of it before merging.

## Expected behavior

The section should display all the content properly and not make these kinds of errors as it breaks the whole page / section. It appears to be blank.

## Actual behavior

All the changes and the new files are migrated but the content is corrupted and it cannot be displayed

## Steps to reproduce the problem

1. Make a new page in the development theme.
2. Make a new section with blocks.
3. Add some content to the section and the blocks.
4. Merge your changes to another theme that is connected to Shopify (in our case all our branches are in Shopify)
5. Check the log of your updated theme with the merged section and view the content of the page.

## Specifications

- App type: Shopify
- Operating System: Windows 10
- Shell: powershell
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by boyan-borisov** [comment]
+1
