### ISSUE TITLE
Multiple Values Storefront Filtering doesn't work locally via Shopify CLI's Theme Serve

### ISSUE THREAD

**Issue by hunterruth** [Shopify/shopify-cli#1818]
# Issue summary

Following the documentation, you're allowed to combine filter values e.g: color: Red or Blue by using comma separated values. 

**Doesn't work**
http://127.0.0.1:9292/collections/all-products?filter.p.m.styles.color=Black,Red 

**Works**
https://[shopname].myshopify.com/collections/all-products?filter.p.m.styles.color=Black,Red

## Expected behavior

It should filter the products in a collection by both specified values on the local served environment, as well as the development site. 

## Actual behavior

It works on the development site, but doesn't work at all via Shopify's CLI theme serve command. With Metafields, it doesn't show any results if there is a comma separated value. It also does not properly parse the filter on refresh. No checkboxes are checked, even if you checked them before clicking apply (or updating the url manually). 

With product options, it properly updates the URL

e.g: http://127.0.0.1:9292/collections/all-products?filter.v.option.size=55%22x55%22&filter.v.option.size=60%22x120%22

However, it only parses the first value that is selected. The checkboxes don't correspond with the URL correctly. 

## Steps to reproduce the problem

1. Shopify theme serve
2. Navigate to collection page
3. Click multiple filter values
4. Click apply
5. See result. 

## Specifications

- Shopify CLI v: 2.7

**Comment by JulesLugus** [comment]
Same problem here ! 
Thanks for the report we got an headach figuring why we can't make it work following the documentation.

**Comment by yannlugus** [comment]
Yep, same problem reported here ! 
Looks weirds. Thanks for the report, that save me tons of time looking why it didn't work ;)

**Comment by stephszeto** [comment]
cc @karreiro (?)
