### ISSUE TITLE
shopify theme serve error - Cannot overwrite generated asset

### ISSUE THREAD

**Issue by BugShallNotPass** [Shopify/shopify-cli#1820]
# Issue summary

`shopify theme serve` command is working fine but always shows the following errors:

![2021-12-03_15-49-07](https://user-images.githubusercontent.com/80621721/144536724-d9d7bb05-9603-4224-917b-e53b5b5e1592.png)

**Comment by octipus** [comment]
Having the same issues.
The idea is that i have myfile.js and myfile.js.liquid
I need to use the .liquid one as the file uses liquid variables.
I have tried to delete the .js file but a new one does not get generated from .liduid when i run "shopify serve"
Any help is much appreciated.
