### ISSUE TITLE
Error while running "shopify app serve" for php app.

### ISSUE THREAD

**Issue by SalmanMalyk** [Shopify/shopify-cli#1828]
Whenever i try to serve my app it always return this error and the tunnel is stoped.

![image](https://user-images.githubusercontent.com/37849208/145022795-32b34b49-068b-45ec-aba7-561973237a75.png)

Here's the Stack trace:
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/system.rb:225:in `which': undefined method `split' for [""]:Array (NoMethodError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/system.rb:219:in `resolve_path'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/context.rb:437:in `system'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/services/app/serve/php_service.rb:39:in `block in call'        
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/services/app/serve/php_service.rb:32:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/services/base_service.rb:5:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/commands/app/serve.rb:31:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/command/sub_command.rb:14:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/command.rb:24:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'      
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'        
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/executor.rb:15:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/monorail.rb:30:in `log'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/bin/shopify:37:in `block (2 levels) in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/bin/shopify:36:in `block in <top (required)>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/bin/shopify:47:in `<top (required)>'
        from C:/Ruby30-x64/bin/shopify:23:in `load'
        from C:/Ruby30-x64/bin/shopify:23:in `<main>'

**Comment by mrniamster** [comment]
same. any fix?

**Comment by mrniamster** [comment]
i can't create my Shopify app after this, please i request add a fix to this.

**Comment by TheApeMachine** [comment]
Hmm, it's working for me, same cli version, different ruby version though. Could be Ruby 3 has a change that breaks the cli?

**Comment by mrniamster** [comment]
@TheApeMachine  mine is :
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

What's your please can you share

**Comment by SalmanMalyk** [comment]
Well i just fixed it by going to the ruby file `C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/system.rb`. On line 225 remove split function and run the command again. It's working fine now.

**Comment by kisuka** [comment]
Same issue, using ruby 3.0.3p157.

**Comment by SalmanMalyk** [comment]
> Well i just fixed it by going to the ruby file `C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.7.2/vendor/deps/cli-kit/lib/cli/kit/system.rb`. On line 225 remove split function and run the command again. It's working fine now.

This fix helped me to run command perfectly. Try this hopefully it'll work.
