### ISSUE TITLE
Can't use logical negation with the --ignore flag in push/pull commands

### ISSUE THREAD

**Issue by tmharryfrancis** [Shopify/shopify-cli#1829]
# Issue summary

Write a short description of the issue here ↓

Prefixing the ignore flag value with '!' doesn't ignore all files except those specified.

## Expected behavior

What do you think should happen?

When using the pull command with the ignore flag I'd expect prefixing the flag value with '!' to ignore all files except those specified. 

eg. `shopify theme pull --live --nodelete --ignore !config/**/*` should only pull down the settings files

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

The command pulls the entire set of theme files down

## Steps to reproduce the problem

1. Run `shopify theme pull --live --nodelete --ignore !config/**/*`
2. See all files have been replaced, not just the config files

## Specifications

- App type: theme
- Operating System: mac os
- Shell: zshell
- Ruby version (ruby -v): 3.0.2

**Comment by karreiro** [comment]
Closing in favor of https://github.com/Shopify/shopify-cli/issues/1558 :)
