### ISSUE TITLE
Bonkers Security

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-cli#1833]
# Issue summary

I created a development store in my Partner account. I wanted to hook up the Shopify CLI to it, and load it woth products for testing. Little did I know, I was logged into a different partner account. So when I used the command line shopify login --store=drunk-monkey, that it would do that. 

## Expected behavior

I would've expected this command to fail, as that store, drunk-monkey is not present in that partner account. I would've expected some kind of error informing me the store is not available, and to try logging in to a different partner account. I did not explore whether I could do any damage. 

## Actual behavior

shopify login --store=drunk-monkey
Logged into store drunk-monkey.myshopify.com in partner organization Not Me You inc.

## Steps to reproduce the problem

1. login to someone else's partner account
2. make a store in your own partner account
3. login to your store in someone else's partner account

**Comment by molly-yu** [comment]
Related: https://github.com/Shopify/shopify-cli/issues/1652
