### ISSUE TITLE
fix for shopify cli authentication error

### ISSUE THREAD

**Issue by b4thestorm** [Shopify/shopify-cli#1856]
# Issue summary

Write a short description of the issue here ↓
I was attempting to login to the Shopify cli interface with:
```ruby 
shopify login --store <domain here>
```

I would get a popup window that asks me to login. I go ahead and 
login and then immediately the terminal blows up with errors. 

I was getting a cryptic SSL error by some older version of Ruby.

## Expected behavior
I was expecting to see a list of partner organizations, connected to my account 
that I should be able to login to. After I successfully login using the cli.

## How to fix this issue
this issue is an issue with an older version of ruby/openssl. specifically ruby < 2.7.
To fix this, you have to make sure you are using a ruby package manager. 
I use rbenv, and the steps to fix this error with rbenv is: 

rbenv install 3.0.3 (or any newer version you prefer)
rbenv local 3.0.3 (make this your local ruby version)
rbenv rehash (this does magic - have to look this up)
gem install shopify-cli (this installs the shopify cli that respects your current ruby version)
shopify login --store <domain here>  (and thats it, this should work for you)

**Comment by alemens** [comment]
I do not have anywhere `ruby-3.0.0` do you know @amcaplan from where `shopify system all` return this `RbConfig["RUBY_VERSION_NAME"]`? 
```bash
Ruby (via RbConfig)
  /Users/stack/.rbenv/versions/3.0.3/bin/ruby
  x86_64-apple-darwin21     - RbConfig["host"]
  ruby-3.0.0                - RbConfig["RUBY_VERSION_NAME"]
```
