### ISSUE TITLE
Store login fails with "An unexpected error occured"

### ISSUE THREAD

**Issue by gskerry** [Shopify/shopify-cli#1865]
# Issue summary
After logging into partner account successfully, attempt to log into store owned by partner account and receive "An unexpected error occured"

## Expected behavior
Log into store

## Actual behavior
Per above.
![image](https://user-images.githubusercontent.com/8867156/146689485-bc598552-8e12-43cc-9d4b-28fea5627944.png)

`<details>✗ An unexpected error occured.</details>` 

## Steps to reproduce the problem
1. Login to partner account
1. Attempt `shopify theme pull` -> CLI complains "Please run `shopify login --store=STORE` "
1. Run `shopify login --store=STORE`; receive error

## Stacktrace
![image](https://user-images.githubusercontent.com/8867156/146689355-5d2f5477-5029-4a35-93d3-33e6f1b94c39.png)

## Specifications

- App type: CLI v2.7.3
- Operating System: Linux Mint Cinnamon
- Shell: bash
- Ruby version (ruby -v): ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by abdullah-shah-5** [comment]
Here are some things which I think might be helpful

!) try to set the environment variables of your pc.
just add SHOPIFY_CLI_STACKTRACE = 1 

2) try logging out and then login again

3) download git-scm 

4)update your shopify cli


I hope your problem gets solved soon.

**Comment by davoodfox** [comment]
Same issue here.

**Comment by jvlvl-z** [comment]
Same issue since v2.7.3...

**Comment by abdullah-shah-5** [comment]
> Same issue since v2.7.3...

I was facing it before but mine got solved after reinstalling ruby devkt
