### ISSUE TITLE
Feature Request: Get list of themes with their IDs

### ISSUE THREAD

**Issue by lesterdefreitas** [Shopify/shopify-cli#1867]
# Issue summary

There seems to be no straightforward way of getting a list of all themes on a connected store and their IDs.

## Expected behavior

It would be great if we could run a command like `shopify get themes` and get a list back of all the themes on the current store along with their IDs.

To add to this, it would be great if there was also a `shopify theme open` command which returned a list of themes which, when selected, will open up the selected theme in your browser.

## Actual behavior

The only way to get a list of themes is to run `shopify theme push` or `shopify theme pull` but even then you don't get their IDs.

**Comment by karreiro** [comment]
Thanks a lot for suggesting this feature, @lesterdefreitas!

A command for listing available themes is valuable indeed! However, as the in the CLI current follows the structure of `shopify [namespace] [command]`, I'm planning to:
