### ISSUE TITLE
NoMethodError: undefined method `split' for [""]:Array

### ISSUE THREAD

**Issue by SattyKaur** [Shopify/shopify-cli#1868]
# Issue summary

Hello, I am new to shopify apps and am having trouble serving my app. I have installed ngrok and ran shopify app tunnel auth <token>
I then serve my app which produces a unexpected error without any message to what went wrong. Can anyone help

`X An unexpected error occured.
        To ←]8;;https://github.com/Shopify/shopify-cli/issues/new?title=NoMethodError%3A+undefined+method+%60split%27+for+%5B%22%22%5D%3AArray&body=%23+Issue+summary%0A%0AWrite+a+short
+description+of+the+issue+here+%E2%86%93%0A%0A%0A%0A%23%23+Expected+behavior%0A%0AWhat+do+you+think+should+happen%3F%0A%0A%0A%0A%23%23+Actual+behavior%0A%0AWhat+actually+happens%3F%0A%
0ATip%3A+include+an+error+message+%28in+a+%60%3Cdetails%3E%3C%2Fdetails%3E%60+tag%29+if+your+issue+is+related+to+an+error%0A%0A%0A%0A%23%23+Steps+to+reproduce+the+problem%0A%0A1.%0A1.%
0A1.%0A%0A%0A%23%23+Stacktrace%0A%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.7.3%2Fvendor%2Fdeps%2Fcli-kit%2Flib%2Fcli%2Fkit%2Fsystem.rb%3A225%3Ain+%60which
%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.7.3%2Fvendor%2Fdeps%2Fcli-kit%2Flib%2Fcli%2Fkit%2Fsystem.rb%3A219%3Ain+%60resolve_path%27%0AC%3A%2FRuby27-x64
%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.7.3%2Fvendor%2Fdeps%2Fcli-kit%2Flib%2Fcli%2Fkit%2Fsystem.rb%3A126%3Ain+%60system%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%
2Fgems%2Fshopify-cli-2.7.3%2Flib%2Fshopify_cli%2Fcontext.rb%3A438%3Ain+%60system%27%0AC%3A%2FRuby27-x64%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.7.3%2Flib%2Fshopify_cli%2Fser
vices%2Fapp%2Fserve%2Fphp_service.rb%3A39%3Ain+%60block+in+call%27%0A%0A%0A%23%23+Specifications%0A%0A-+App+type%3A%0A-+Operating+System%3A%0A-+Shell%3A%0A-+Ruby+version+%28ruby+-v%29%
3A%0A&labels=type%3Abug←\submit an issue←]8;;←\ `

**Comment by mandeepsandhu91** [comment]
Hi, 
Did you fix this issue? I am facing this issue.

**Comment by devteamsit** [comment]
Facing the same issue while "Shopify app serve" for laravel app.
