### ISSUE TITLE
Urdu and English language

### ISSUE THREAD

**Issue by boubacarsbgmali** [Shopify/shopify-cli#1872]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by amcaplan** [comment]
Closing, as I'm not sure what this is about. Feel free to open another issue with some explanation of what you'd like to see.
