### ISSUE TITLE
Shopify CLI : Shopify login command not working on the live server

### ISSUE THREAD

**Issue by devteamsit** [Shopify/shopify-cli#1875]
Hello Team,

We are trying to create a theme app extension. For that, we have installed Shopify CLI or our shared hosting / live server.
When I run "Shopify login" it gives me the URL to run on the browser. 

Reference: https://prnt.sc/23yx1fa

After visiting this URL it shows up my Shopify accounts but when I select the account we land on an URL starting from "127.0.0.1"
and we get this issue.  

Reference: https://prnt.sc/23yxg77

This issue only occurs when I do this from my shared hosting, However, I have Shopify CLI in my windows 10, and when I do this for the local environment. It works like a charm. Kindly help me to solve this so that I can take up the Shopify CLI on the server.

**Comment by tingfungc** [comment]
Try port forwarding (3000 and 3456) to your server

**Comment by axis80** [comment]
Just copy that 127.0.0.1 URL to your clipboard, then load it from your CLI using the command `wget "https://127.0.0.1/url-goes-here"` .  Make sure to enclose the URL in double quotes.

**Comment by DevStackRahul** [comment]
Hi 
I am getting same issue is there any documentation or solution so I can check
I am using AWS server.
Please let me know the best solution for the same 
check video 
https://watch.screencastify.com/v/7mEDlLd5hrB1h9CgjGMK

**Comment by adornthemes** [comment]
I am also getting same issue in my window pc. IS there any solutions for this ?
