### ISSUE TITLE
Missing commands as mentioned on Getting started for building shopify themes.

### ISSUE THREAD

**Issue by Notive-BV** [Shopify/shopify-cli#1888]
# Issue summary

My current homebrew installation is missing al the basic required commands for creating an theme as mentioned here https://shopify.dev/themes/getting-started/create and in the shopify videos.

## Expected behavior

What do you think should happen?

I should be able to login my store and follow the tutorials in order to create and locally serve themes.

## Actual behavior

What actually happens?

![image](https://user-images.githubusercontent.com/11158817/148032162-b1631b77-d1fe-4f84-a289-9a6918bc3550.png)
I am missing all the basic commands. 

## Steps to reproduce the problem

1. Homebrew update and OS / Xcode update. 
1. Run brew install shopify-cli
1. Try running any of mentioned commands from official documentation. 

## Specifications

- App type: 
- Operating System: macOS montarey
- Shell: 
- Ruby version (ruby -v): ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

## Ive tried

Installing shopify-cli@2.6.6 as used in video. this was not found on homebrew.

**Comment by rayhvh** [comment]
I did uninstall shopify-cli with homebrew then installed shopify-cli using GEM.  gem install shopify-cli

```
type shopify
shopify is a shell function from /Users/***/.shopify-app-cli/shopify.sh
```

I disabled the following .sh file with comment using an IDE. then ran a new tab and ran 'shopify' again. 

now i am getting the commands as mentioned in tutorial and video.  ?
