### ISSUE TITLE
Apparent incompatibility with RVM "can't find gem shopify-cli"

### ISSUE THREAD

**Issue by gskerry** [Shopify/shopify-cli#1897]
# Issue summary
Utilizing [RVM](https://rvm.io/) and setting ruby version in shell causes shopify cli to fail with `can't find gem shopify-cli`

## Expected behavior
Shopify references currently linked ruby binary 

## Actual behavior
Appears to reference system binary. Missing gem

`<details>can't find gem shopify-cli</details>`

## Steps to reproduce the problem

1. install RVM
2. ensure login shell, per RVM requirements (e.g. `bash -l`)
2. Set ruby version e.g. `rvm use 3.0.3`
3. `ruby -v` -> `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
4. `shopify version` -> error

## Stacktrace
Traceback (most recent call last):
        2: from /usr/local/bin/shopify:23:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem shopify-cli (>= 0.a) with executable shopify (Gem::GemNotFoundException)

## Specifications

- App type: 2.8.0
- Operating System: Linux Mint Cinnamon
- Shell: bash
- Ruby version (ruby -v): 3.0.3 / 2.7.0 (*per above)

**Comment by amcaplan** [comment]
Hi @gskerry, did you install the CLI on one version and then `rvm use` another version? Anytime you switch versions, RVM will change your gem path so the gem won't be found. You'd need to install the gem once for every Ruby version you use.

If you'd like a global installation, you can try installing via Homebrew, per [the instructions on our docs site](https://shopify.dev/apps/tools/cli/installation#install-shopify-cli).

**Comment by gskerry** [comment]
As you mentioned, this doesn't appear to result in a global install, but does address the error within that shell session. Do you happen to know if the gem install persists for that RVM ruby version?

(i.e. `rvm use 3.0.3`; `gem install shopify-cli`; `rvm use 2.7.0`; [other activity]; `rvm use 3.0.3`... will the gem install from the first use of 3.0.3 persist?)

**Comment by amcaplan** [comment]
@gskerry to the best of my recollection, RVM changes the PATH every time you change versions. It's not uninstalling anything. So if you install on `3.0.3`, then switch to another version, then switch back to `3.0.3`, I believe you should have access to the CLI again.

Also, my apologies for missing that you're on Linux not Mac, so the Homebrew suggestion wouldn't be helpful 🤦

**Comment by amcaplan** [comment]
Glad we worked it out!
