### ISSUE TITLE
Whacked out extension issue

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-cli#1899]
# Issue summary

Sequence is clean: shopify logout, shopify login. Choose from one of eight organizations. fine. settle on number 8. 

In my terminal I am inside a theme_app_extension directory, in a project, with no .env file. It was previously registered using a different partner account, but that account is no longer relevant, so I want to re-register using this one. 

I tried **shopify extension register** thinking hey, register this extension for this partner account with this new App. That blew chunks and error'd out. 

So I tried a connect, wondering hey, if I connect this app extension maybe that will work? Nope. Now the interesting stuff. I was offered a list of 3 other App extensions. One is part of my partner account, and two belong to a different partner account. None are from the currently logged-in partner account. 

OK. So I suppose if this extension I am looking at, is not registered, then sure, a connect command could make some sense when the connect command is issued, to look through other Partner accounts. But, probably not.

But seriously? Why is this tool showing me extensions to connect to that belong to accounts I am not even logged into? Is that not super weird? 

## Expected behavior

If I ask to connect to an extension, and I am logged into a Partner account, then only show me extensions to connect to that belong to this partner account I am logged into? Does that not make sense? 

## Actual behavior

I get presented App Extensions belonging to other partner accounts, and other Apps, to connect to. Why? 

Shopify CLI Version 2.8.0

**Comment by axis80** [comment]
In addition to .env, there's also a `.shopify-cli.yml` file that gets saved within the theme app extension folder.  I'm not sure what it's for, but it might be the cause of your issue.

**Comment by resistorsoftware** [comment]
That file, .shopify-cli.yml contains nothing interesting. Zero data. So it cannot be an excuse for exposing non-essential or irrelevent data. 

My point is that till tooling remains hard to use, as it clearly has not taken into account boundaries, but instead surfs an entire network tree in search of interesting things.

**Comment by gonzaloriestra** [comment]
This has been fixed on version 2.16.0. From now on, only apps from the Partners account logged in will be listed. Thanks for the suggestion!
