### ISSUE TITLE
Theme serve not showing local changes

### ISSUE THREAD

**Issue by sebasreis** [Shopify/shopify-cli#1902]
# Issue summary

The theme serve command is not working as intended: the code changes I make locally are not being updated in the preview url (not even with manual refresh).

## Expected behavior

The local changes I make to theme files should be shown in theme serve preview url.

## Actual behavior

The theme serve preview url is not showing local changes to theme files.

## Steps to reproduce the problem

1. Run "shopify theme serve" 
2. Make changes to theme files
3. Preview theme locally (http://127.0.0.1:9292)

## Specifications

- App type: shopify cli (theme serve)
- Operating System: Running Ubuntu 18.04 with WSL2 on Windows 10 (I use WSL2/Ubuntu for cli commands and Windows Chrome browser to preview theme)
- Shell: Bash
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by ZUNZET17** [comment]
Having the exact same issue using the same as op.

**Comment by AlexanderParker** [comment]
Can confirm the same issue. It was working perfectly on Windows 10, WSL1. 

I upgraded to WSL2 this past weekend, and after reinstalling Ubuntu and shopify CLI (and it's dependencies), theme serve is no longer updating on change requiring the process to be terminated and restarted in order to force updates to synchronise to the store.

OS - Ubuntu 20.04.3 LTS, WSL2
Ruby - 3.1.0, then 3.0.0 (neither work)
rbenv - 1.2.0
npm - 8.3.1
node - 16.14.0

**Comment by brunoagcorreia** [comment]
I am having the same issue. Lots of editing, but nothing shows up on the live version on Shopify

**Comment by colin-article** [comment]
+1

**Comment by memetican** [comment]
Same. Even if I delete 100% of the content in local files like theme.liquid, and even if I stop and restart the theme server, I am not seeing the changes locally.

**Comment by dashy2021** [comment]
Shopify theme serve which generates local IP address not working. 
Showing error page with message "Due to an unexpected technical problem, Shopify is temporarily
unavailable. Please check back in a few minutes - we' be uo and
running in no time!"

**Comment by Geedo713** [comment]
All facts, i been trying to get started with shopify theme devving, i made some little small changes to the .json file just to see if any changes are rendered and when i use the shopify  theme serve command, i see nothing taking place!

**Comment by skdevelopers** [comment]
I'm having the same issue my online store and local store is not updating any new code i written I run serveral times shopify theme dev 
terminate the process and regenerate it but nothing happend after few days back once I update or re run theme dev will update new changes on online and local ? 
SK Developers., Faisalabad.

**Comment by origindesign** [comment]
Also seeing a similar issue, sometimes it sees changes to files quite quickly, then other times theres a few mintues delay, other times, have to stop and restart with shopify theme dev. Im on windows 11.

This becomes extremely frustrating when deving, i end up having to push my files and preview the theme on the live store. not efficient at all. Please help us Shopify!
