### ISSUE TITLE
ShopifyCLI::API::APIRequestForbiddenError: 403{"errors":"Unauthorized Access"}

### ISSUE THREAD

**Issue by huyhuanhg** [Shopify/shopify-cli#1907]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/var/lib/gems/2.7.0/gems/shopify-cli-2.7.4/lib/shopify_cli/api.rb:74:in `block in request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.4/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.4/lib/shopify_cli/api.rb:89:in `request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.4/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.7.4/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by pepicrft** [comment]
This is a [platform limitation](https://github.com/Shopify/shopify-cli/issues/1309#issuecomment-1112351597) that the team will soon work on fixing. Until them, we recommend following the workaround in that comment. I'll close this issue to continue the discussion there.
