### ISSUE TITLE
Homebrew installation shopify-cli

### ISSUE THREAD

**Issue by b-mael** [Shopify/shopify-cli#1908]
Hello

I try to install shopify-cli thanks to homebrew.
I already enter the command : brew tap shopify/shopify

The next command to install shopify-cli is "brew install shopify-cli" according to the shopify documentation

But I have this error : 

 No available formula with the name "ruby" (dependency of shopify/shopify/shopify-cli).

Someone could help me plase ?

**Comment by Elliottmeija** [comment]
I had the same issue, it's likely your ruby installation that is causing the problem. You may need to edit your shell file.
1. What ruby version are you using? `ruby --version`
2. What OS and hardware are you using?
3. What do you have ruby wise in your shell file? (zsh, bash, etc)

**Comment by amcaplan** [comment]
It looks like this issue has been solved.

@t-kelly please make sure to run `brew tap shopify/shopify` before `brew install shopify-cli`.

I'm closing under the assumption that there isn't much more to do here, but feel free to open another issue if something needs more discussion.
