### ISSUE TITLE
Unable to run Shopify 'Theme Serve Command'

### ISSUE THREAD

**Issue by Jzabierek** [Shopify/shopify-cli#1914]
# Issue summary

Unable to run Shopify Theme Serve from Git Bash Terminal; attempts to run met with 'TypeError: no implicit conversion of String into Integer'. Uninstall/Reinstall different versions of Shopify CLI (2.6.6 -> 2.8), Ruby, and Git with no success. 

## Expected behavior

Running 'Theme Serve' should sync local theme to dev. store, opens local host and online Store Editor and preview theme

## Actual behavior

Running 'Theme Serve' sync is started and dies @ .92 - .99 sec. 'An unexpected error occured' is displayed with a link to post to the Shopify CLI github

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. cd into directory
1. log into Partners' dev store via command 'shopify login --store=<insertStoreName>'
1. run command 'shopify theme serve'

## Stacktrace

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/theme/file.rb:113:in `[]='
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/theme/file.rb:113:in `visit_value'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/theme/file.rb:106:in `block in visit_hash'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/theme/file.rb:105:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.8.0/lib/shopify_cli/theme/file.rb:105:in `visit_hash'

## Specifications

- App type:
- Operating System: Windows 10 Home Version	10.0.19042 Build 19042
- Shell: Git Bash
- Ruby version (ruby -v): Ruby 2.7.5p203 (2021-11-24 revision f69aeb8314 [x64-mingw32]

**Comment by khadija-ouakkaha** [comment]
So no one has actually got to the bottom of this?
