### ISSUE TITLE
App blocks: Invalid tag 'schema' : settings: is invalid

### ISSUE THREAD

**Issue by MaxDesignFR** [Shopify/shopify-cli#1927]
# Issue summary

`Shopify extension push` returns `Invalid tag 'schema' : settings: is invalid` when using 7 times or more the same attribute in schema settings.

## Expected behavior

This should be working as expected. The max block limit is 25 according to https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework#file-and-content-size-limits, so that's not it.

## Actual behavior

 Terminal returns `Invalid tag 'schema' : settings: is invalid`, the app block is therefore not published.

![eJTEOdQaUU](https://user-images.githubusercontent.com/46461193/149386360-53edde69-580e-4154-a05b-5898d8d8b2ca.png)

## Steps to reproduce the problem

1. Create theme app extension: https://shopify.dev/apps/online-store/theme-app-extensions/getting-started
1. In your app block, try shema settings such as:
```
{% schema %}
{
  "name": "My app block",
  "target": "section",
  "settings": [
    {
      "type": "paragraph",
      "content": "test 1"
    },
    {
      "type": "paragraph",
      "content": "test 2"
    },
    {
      "type": "paragraph",
      "content": "test 3"
    },
    {
      "type": "paragraph",
      "content": "test 4"
    },
    {
      "type": "paragraph",
      "content": "test 5"
    },
    {
      "type": "paragraph",
      "content": "test 6"
    },
    {
      "type": "paragraph",
      "content": "test 7"
    }
  ]
}
{% endschema %}
```
3. Shopify extension push

## Specifications

- App type: Theme app extension - app block
- Operating System: Windows 11 64 bit
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by awd** [comment]
This error is confusing as there are no indicators what is invalid, and what steps to take for correction. Generally blocking when building app-embed / app-block integrations.

@t6d @molly-yu @lopert @pepicrft @karreiro @gonzaloriestra - Can someone internal pass this along to the right team/PL?

**Comment by stephszeto** [comment]
cc @catlee

**Comment by awd** [comment]
Hi @catlee + @stephszeto - has anyone been able to take a look at this? This is still a blocking bug when building app embeds / app blocks.

**Comment by catlee** [comment]
Hi,

The current limit for non-interactive settings is a maximum of 6 per block. I'll look into why we're not returning a more helpful error message.
