### ISSUE TITLE
Shopify sections should be uploaded before templates.

### ISSUE THREAD

**Issue by craigdg** [Shopify/shopify-cli#1933]
# Issue summary
If a Shopify template refers to a section that has not yet been uploaded to the Shopify environment, the `shopify theme serve` command throws the following error...

`Section type 'foo' does not refer to an existing section file`

## Expected behavior

The sections should be uploaded before the template files, so that the error doesn't get thrown.

## Actual behavior

The sections are uploaded after the templates, causing the error.

## Steps to reproduce the problem

1. Create a new section, such as `test.liquid`.
2. Create a basic template json file.

```
{
  "sections": {
      "test": {
          "type": "test"
      }
  },
  "order": [
      "test"
  ]
}
```

3. Run the `shopify theme serve` command.

## Specifications

- Operating System: Windows 10 (10.0.19041) Build 19041
- Shell: PowerShell 7.1.5
- Ruby version (ruby -v): 3.0.3p157

**Comment by andyxmas** [comment]
I find this error a lot when swtiching git branches when `shopify serve` running
