### ISSUE TITLE
Shopify Login on Windows 10

### ISSUE THREAD

**Issue by mohamedrafea** [Shopify/shopify-cli#1935]
# Issue summary

Write a short description of the issue here ↓
Cannot use shopify login to connect to partner account

## Expected behavior

When I type shopify login, default browser should open and the cmd waits for the call back

## Actual behavior
Following error appear:
X System call failed: start "" "https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=b8680104f6a2dc5b983c09a713d5b62e1540dbc671f4b5c53e35f4087801&response_type=code&code_challenge=Ub39RbR9GuFDWRl-gA7ymMvt8lh1YiSWuC4IRcEKGmQ&code_challenge_method=S256"

## Specifications

- App type: shopify version 2.8.0
- Operating System: windows 10 home
- Shell: cmd prompt or powershell
- Ruby version (ruby -v): ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

**Comment by lesterdefreitas** [comment]
I'm having issues logging in on Windows as well, but my error message is a bit different:

![image](https://user-images.githubusercontent.com/12233287/150081708-1e3828a0-3516-43a4-839f-bdaf242ea71c.png)

The store URL is definitely valid. We keep the shopify login command with the store url stored in the readme file in our theme repos, and I am copying and pasting what I have always used.

The store does not belong to our partner organization, but this was never a problem before. We are using a direct user login that has access to themes. Or has something weird changed in this regard now?

**Comment by ettoredn** [comment]
Same on my side using 2.9.0 from homebrew/macOS.

**Comment by Elliottmeija** [comment]
Same on my side. I'm fairly annoyed as the shopify browser text editor is about as useable as a french press made of chicken wire.

Can we please get an update on this by a dev? It's apparently been a known issue for a while.

**Comment by ettoredn** [comment]
@andrewhassan ?

**Comment by amnkhan** [comment]
I am new to using Shopify CLI, Just installed it on my WINDOWS 10 machine. 

When I use the command `shopify login` 

It takes me to the login page. But when I click login it's showing `{"code":"MethodNotAllowed","message":"GET is not allowed"}` 

Is there anything I am missing?

**Comment by ettoredn** [comment]
Never experienced such issue. Try open a new issue .
