### ISSUE TITLE
`shopify app create` failing for both `node` and `rails`

### ISSUE THREAD

**Issue by hannachen** [Shopify/shopify-cli#1940]
Should be fixed by this PR by @amcaplan 
Possibly only impacting M1 machines

https://github.com/Shopify/shopify-cli/pull/1922

### Cause
- Mismatched versions of **Ruby** and **Rails**
    Version of `webpacker` used in the generated app depends on the version of **Rails** on the machine (`rails -v`)
    **Rails Rails 6.1.4.4** will install `webpacker ~5`, lower versions may install `webpacker 4` or none at all
- Unsupported version of **Node**
    M1 uses **Node 17** by default, generated projects use **Node 16**
- Shopify `dev` tool sometimes change the version of **Ruby** and **Node** when a command is executed from a project folder (probably reads `dev.yml`)

### What works
- Ruby `3.0.3`
- Node `16`
- Rails `6.1.4.4`
- Install `shopify-cli` via **Ruby gem** instead of **Homebrew**

### Workaround
- Using `ruby-install` (`brew install ruby-install`), update system **Ruby** version to the latest `3.0.3`: `ruby-install 3.0.3`
- Using `chruby` install `3.0.3` and set it as default by adding `chruby 3.0.3` in your bash profile (i.e. `~/.zshrc`)
- Using `nvm`, install and set node version to `16` by adding the path to your bash profile:
    `export PATH="$NVM_DIR/versions/node/v16.13.2/bin:$PATH"`
- Install **Rails** version `6.1.4.1`: `gem install rails -v 6.1.4.1`
- Ensure Shopify CLI is installed via **Ruby gems** and not **Homebrew** (`gem install shopify-cli` and not `brew install shopify`, verify with `which shopify` and it should match ruby version: `/.gem/ruby/3.0.3/bin/shopify`)

#### Optional - if error message includes openssl
- Using Homebrew, install **openssl**
- Update shell profile to use the latest version of **Ruby** and **openssl**

**Comment by gonzaloriestra** [comment]
Closing here, as this should be fixed.
