### ISSUE TITLE
Authentication issues with CLI

### ISSUE THREAD

**Issue by Chewbacca222222** [Shopify/shopify-cli#1947]
# Issue summary

For some reason I randomly get ```17:28:25 ERROR  » update locales/en.default.json: X Please login again with shopify login``` after running ```shopify theme serve``` from the command line. If I just ignore it then check the front end (http://127.0.0.1) I get the following error message:
`Internal Server Error
storefront_renderer_production_exchange_token missing
WEBrick/1.7.0 (Ruby/3.0.3/2021-11-24) at 127.0.0.1:9292`

If I try and logout using ```shopify logout``` then log back in again my browser says the authentication was successful but the CLI then reports:
`X error: Your account was not found. Please sign up at https://partners.shopify.com/signup
For authentication issues, run shopify logout to clear invalid credentials
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.
If trying to log into a store staff account, please use shopify login --store=STORE to log in.`

Currently this is an annoyance as I can still refresh the front end (twice) and it will load back as normal but it's starting to become a real blocker.

## Expected behavior

CLI should login and logout correctly.

## Actual behavior

What actually happens?

CLI reports a login failure even though the front end works (after some refreshes) and the login technical "succeedes".

## Steps to reproduce the problem

1. Run ```shopify theme serve```
2. Get error
3. Stop process
4. Try ```shopify logout``` then ```shopify login```
5. Still fails

## Specifications

- Operating System: Windows 11
- Shell: Git bash
- Ruby version (ruby -v): ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- CLI version: 2.9.0

**Comment by Chewbacca222222** [comment]
Just to note, I've read through [this bug report](https://github.com/Shopify/shopify-cli/issues/1694) and tried creating a separate staff account with a new email address and that didn't work either. Exact same issue!

**Comment by ettoredn** [comment]
Same on my side using 2.9.0 from homebrew/macOS.

**Comment by Elliottmeija** [comment]
Same here. This happened immediately after upgrading to 2.9.0.

**Comment by ettoredn** [comment]
@andrewhassan ?

**Comment by hannachen** [comment]
Hi there, is this happening only with the latest CLI update `2.9.0`? If so, the issue may expected behaviour resulting from a bug fix: https://github.com/Shopify/shopify-cli/issues/1944#issuecomment-1018907046

**Comment by Coenmathijssen** [comment]
The issue is still persisting in version 2.16.1. When saving code during development, I also get this error every 15 minutes or so.

**Comment by cocomonier** [comment]
I have also been getting this issue coming up very often. I didn't have it at all until the a few versions ago (maybe 2.15) but it is now a pretty frustrating bug. Logging in and out doesn't seem to fix it. I usually reload a few times and eventually the page will load.
