### ISSUE TITLE
Roll back to a previous Shopify CLI version

### ISSUE THREAD

**Issue by willypark22** [Shopify/shopify-cli#1949]
# Issue summary

Can you downgrade or roll back to a previous Shopify CLI version? If so what is the command, or the steps to do so? I'm not able to go through "shopify login" command at the moment and want to revert back to a previous version of the CLI as that worked for most people.

## Specifications

- Operating System: Windows 11
- Shell: Git Bash
- Ruby version (ruby -v): ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- CLI Version: 2.9.0

**Comment by filipz** [comment]
You can revert to the previous version by using

`gem install shopify-cli -v '< 2.9.0'`

Restart terminal/console.

**Comment by lesterdefreitas** [comment]
> You can revert to the previous version by using
> 
> `gem install shopify-cli -v '< 2.9.0'`
> 
> Restart terminal/console.

@filipz I did this and it seemed to work, but even after restarting terminal it still seems to be on v2.9.0 when I check my version. Any ideas?

**Comment by filipz** [comment]
Perhaps removing 2.9.0 would help.

`gem uninstall shopify-cli -v 2.9.0`

**Comment by danniel917** [comment]
> 

You're the best, thank you a lot!!!

**Comment by danniel917** [comment]
> You can revert to the previous version by using
> 
> `gem install shopify-cli -v '< 2.9.0'`
> 
> Restart terminal/console.

You're the best, thank you a lot!!!

**Comment by DevSharpknife** [comment]
I am also having an issue with rolling back the Shopify CLI using Homebrew in MacOS. Does anyone know of a script that can be used to uninstall the current version and then install a specific older version of the Shopify CLI using Homebrew?
