### ISSUE TITLE
Shopify-cli login error

### ISSUE THREAD

**Issue by qamarabbasx** [Shopify/shopify-cli#1953]
shopify login --store theme-development-store-main.myshopify.com
X An unexpected error occured.
        To submit an issue include the stack trace.
        Please Help

**Comment by Elliottmeija** [comment]
Yep. I've been bugging the dev team incessantly since updating. This is triggered by
`shopify login --store=' '`
This is costing me 75% of my workflow and several thousand dollars of work. Someone please tell me that this is a priority fix!

**Comment by ettoredn** [comment]
Can be solved by downgrading to 2.8.0. See other issues.

N.B. If you work at ~$1k a day, I'm interested in working with you.

**Comment by danniel917** [comment]
With the command gem install shopify-cli -v '2.8.0' I could rever the version and it worked well.

**Comment by ettoredn** [comment]
see #1944
