### ISSUE TITLE
"shopify extension push" fails when there are a lot of JS files in asset folder.

### ISSUE THREAD

**Issue by zakariamofaddel** [Shopify/shopify-cli#1958]
# Issue summary
`shopify extension push` not working when there are a lot (79) JS files in asstes folder

Write a short description of the issue here ↓
I was doing some experiments and I wrote 79 script tags in a liquid file in the `/blocks` directory. The CLI fails to push when I have that many script tags.
Is there a limit for how many script tags one liquid file can have?
Or is there a limit for how many JS files can live in the `/assets` directory?

The CLI fails with `An unexpected error occurred on Shopify.`

# Stacktrace

![Screenshot 2022-01-23 011124](https://user-images.githubusercontent.com/66852346/150658376-3088922c-cae5-4e1f-b85a-258915c733e8.png)

- App type: Theme app extension
- Operating System: Windows 11
- Shell: Powershell
- Ruby version (ruby -v): ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by catlee** [comment]
This should be fixed now. Please let me know if you see it again!
