### ISSUE TITLE
Error with Shopify Version

### ISSUE THREAD

**Issue by Alfredo-Mendoza** [Shopify/shopify-cli#1960]
# Issue summary

I installed Shopify-CLI using the tutorial to [Install Shopify CLI](https://shopify.dev/themes/tools/cli/installation) and when I want to confirm the version installed y see the next error:

## Actual behavior
> shopify version
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/os.rb:15:in `current': Could not determine OS from platform x64-mingw-ucrt (RuntimeError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:13:in `<module:Spinner>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:6:in `<module:UI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:5:in `<module:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui/spinner.rb:4:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui.rb:19:in `<module:UI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui.rb:2:in `<module:CLI>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/vendor/deps/cli-ui/lib/cli/ui.rb:1:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/lib/shopify_cli.rb:24:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/shopify:9:in `require'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/load_shopify.rb:18:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/shopify:32:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.9.0/bin/shopify:32:in `<top (required)>'
        from C:/Ruby31-x64/bin/shopify:25:in `load'
        from C:/Ruby31-x64/bin/shopify:25:in `<main>'

## Steps to reproduce the problem

1. Open a terminal
2. Follow the steps to install Shopiy-CLI in the page [Install Shopify CLI](https://shopify.dev/themes/tools/cli/installation)
3. Run `shopify version` in the terminal

- Operating System:
          Edición:	Windows 11 Home Single Language
          Versión:	21H2
          Compilation del SO:  22000.434
- Ruby version (ruby -v): ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]

**Comment by abdullah-shah-5** [comment]
try to match the ruby devkit version with the version used in cli 
The current version of shopify cli is 2.9.0 and the ruby version used in it 2.7.5 (I guess you can make sure by visiting the releases page )

**Comment by puma1027** [comment]
Hello.
I have the same problem.
My ruby version is 3.1.0 and shopify cli version is 2.10.0.
Could you please help me.
Thanks.

**Comment by HeavenlyEntity** [comment]
Hi team this has been fixed with # # #1990
