### ISSUE TITLE
could not use shopify login command on windows 

### ISSUE THREAD

**Issue by yanjiechg** [Shopify/shopify-cli#1967]
# Issue summary

Tried "shopify login" on cmd, no web browser opens.
Tried "shopify login" on git bash, no web browser opens.
when I did ctrl+c, it showed up an url, after I pasted in the webbrowser I got 127.0 0.1 refused to connect.

**Comment by abdullah-shah-5** [comment]
did you try it with the correct flag and correct domain?
e.g : shopify login --store storename.myshopify.com/admin or shopify login --store storename.myshopify.com

**Comment by abdullah-shah-5** [comment]
after updating the shopify cli to 2.9.0 my default browser on windows got change automatically.
I have both firefox and chrome installed (Default one is chrome) but when I logged in from the cli it was opening firefox
So I went to default apps setting and changed it back to chrome and now it's working fine
