### ISSUE TITLE
ShopifyCLI::API::APIRequestForbiddenError: 403{"errors":"Unauthorized Access"}

### ISSUE THREAD

**Issue by akengandhi** [Shopify/shopify-cli#1968]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

> shopify theme pull

## Stacktrace

/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/api.rb:74:in `block in request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/api.rb:89:in `request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by amcaplan** [comment]
Hi @akengandhi, looks like you've run into [a known issue](https://github.com/Shopify/shopify-cli/issues/1694). I recommend looking at that thread for more information.
