### ISSUE TITLE
Font files error 500 after update to Shopify CLI v2.10.0

### ISSUE THREAD

**Issue by shahways** [Shopify/shopify-cli#1978]
# Issue summary

FontAwesome woff, woff2 and ttf files generate a 500 server error on the local development environment, saying "invalid byte sequence in UTF-8" after updating to shopify-cli v2.10.0. 

## Expected behavior

Font files should give status 200. 

## Actual behavior

We copied FontAwesome font files into the assets folder, and include them via the CSS file. After updating Shopify CLI to v2.10.0, the font files no longer work and now result in an error 500 in the browser on our development environment. They still however work fine on the live theme on Shopify.  The exact error is **invalid byte sequence in UTF-8**.

## Steps to reproduce the problem

1. Download FontAwesome and copy the various webfont files into your assets folder
2. Include the FontAwesome CSS (update the path to the webfonts folder to your assets folder)
3. Use an icon in your HTML

## Specifications

- App type: Chrome, Firefoxs
- Operating System: MacOS
- Shell: iTerm ZSH
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

![Screenshot 2022-01-27 at 18 48 53](https://user-images.githubusercontent.com/4831009/151415195-f2f9b435-f160-41ab-8644-57a0395a23af.png)

**Comment by corazzi** [comment]
Checking in as we also have this same issue. They break with the local URL but not with the myshopify.com URL.

**Comment by shahways** [comment]
Happy to confirm that the upgrade to 2.10.1 fixed the issue for us.
