### ISSUE TITLE
Login as a customer on localhost redirects to main store url

### ISSUE THREAD

**Issue by pinguluk** [Shopify/shopify-cli#1992]
# Issue summary

Write a short description of the issue here ↓
When I try to login as a customer on localhost and validate the recaptcha, I'm being redirect to the store url and I need to revalidate the recaptcha there too and I don't want to be redirected.

## Expected behavior

Don't redirect to store url when try to login as a customer and let you authenticate as a customer (to view customer details page, order history etc)

## Actual behavior

Same as issue summary.

## Steps to reproduce the problem

1. Try to login as a customer on localhost

## Specifications

- App type: -
- Operating System: Windows 10
- Shell: -
- Ruby version (ruby -v): ruby 3.0.3p157
- Shopify CLI version: v2.10.1

**Comment by pinguluk** [comment]
I confirm that disabling the recaptcha allows me to login as a customer on localhost. It seems that on the /challenge page, where you need to verify the recaptcha, the form submit url is the store url and localhost

**Comment by pinguluk** [comment]
It seems also that when I view the order history, the order number link goes again to store url and not localhost

**Comment by macournoyer** [comment]
Thanks for reporting @pinguluk ! The problem is indeed with recaptcha. Here's the issue to follow progress on this: #1636, and also a workaround.
