### ISSUE TITLE
Windows Support: Support Full CLI with local testing envoirement ect. for Windows

### ISSUE THREAD

**Issue by dtknepper** [Shopify/shopify-cli#2010]
### What type of project(s) will this request affect?

other

### What type of change do you want to see?

New feature

### Overview

As of this moment not all capibility's that are supported on MacOS devices are supported on Windows. As I am a Windows user I would love to see more support like for example local live testing server for shopify themes. This will increase productivity a lot. 

### Motivation

This feature request is posted after one of your colleagues from the Theme team pointed out I should do this. Since I would love to work on themes more efficient this feature would be really usefull.

**Comment by amcaplan** [comment]
Thanks @dtknepper for the suggestion. Do you know who it was on the Themes team who made the suggestion? Just so we can make sure they're aware of this issue.

**Comment by dtknepper** [comment]
If possible I would still like to see the option to use the serve command in the CLI for live testing on Windows.

**Comment by dtknepper** [comment]
Still active request

Kind regards,
Met vriendelijke groet,

Thom Knepper

Op do 4 aug. 2022 05:47 schreef github-actions[bot] <
***@***.***>:

**Comment by karreiro** [comment]
Hi @dtknepper,

Thank you for reporting this issue!

I've tried the `shopify theme serve` command this morning, and I could successfully use all features also available on macOS.

If you're still facing issues with the latest version of the CLI, could you please share more details? So, we can reproduce and fix it :)

Here are some details that help us reproduce the issue:
- Steps to reproduce
- Operating System version
- Shopify CLI version
- Ruby version
- Shell

Thanks again for reporting! 🚀

**Comment by karreiro** [comment]
Thanks a lot for checking, @dtknepper! We will stay tuned here for your future updates :)

Also, sorry I didn't express myself well in the other message 😅. What I meant was that I can successfully use on Windows all features that I also use on macOS :)

Thanks again, @dtknepper!
