### ISSUE TITLE
ShopifyCLI::Tunnel::NgrokError: The account \

### ISSUE THREAD

**Issue by SourabhSysquare** [Shopify/shopify-cli#2014]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/var/lib/gems/2.7.0/gems/shopify-cli-2.10.2/lib/shopify_cli/tunnel.rb:183:in `rescue in fetch_url'
/var/lib/gems/2.7.0/gems/shopify-cli-2.10.2/lib/shopify_cli/tunnel.rb:179:in `fetch_url'
/var/lib/gems/2.7.0/gems/shopify-cli-2.10.2/lib/shopify_cli/tunnel.rb:198:in `start_ngrok'
/var/lib/gems/2.7.0/gems/shopify-cli-2.10.2/lib/shopify_cli/tunnel.rb:70:in `start'
/usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by amcaplan** [comment]
Hi @SourabhSysquare, thanks for taking the time to open an issue!

Currently there isn't much information here, so we'll need a description of what you were trying to do and what you encountered, otherwise we really can't help much.

If we don't have this information in the next week, unfortunately we'll need to just close the issue.

**Comment by phylor** [comment]
For everyone ending up here using a search engine:

The shopify CLI does not show the whole error message from the log. Check the log file to find the full error. Usually found in the standard app data directory of your operating system (in Linux usually `~/.cache/shopify/sv/ngrok.log`).

The error I had in the log:

```
t=2022-05-12T08:54:56+0200 lvl=crit msg="command failed" err="The account \"myaccountname\" may not start an ngrok agent session until the admin's email address is verified. Verify your email at https://dashboard.ngrok.com/user/settings\r\n\r\nERR_NGROK_123\r\n"
The account "myaccountname" may not start an ngrok agent session until the admin's email address is verified. Verify your email at https://dashboard.ngrok.com/user/settings

ERR_NGROK_123
```

The error shown by the shopify CLI:

```
/home/myuser/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.16.1/lib/shopify_cli/tunnel.rb:184:in `rescue in fetch_url': The account \\ (ShopifyCLI::Tunnel::NgrokError)
```

@amcaplan It might make sense to improve your log parsing. Or maybe write the path of the logfile to stdout when an error occurs.

**Comment by Maljassim-alyasra** [comment]
THANK YOU @phylor 
I lost 2 days of my life for email verification!!!!
