### ISSUE TITLE
[Bug]: CLI App Creation Fails - 404s

### ISSUE THREAD

**Issue by inex0rable** [Shopify/shopify-cli#2046]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Some kind of initial app holding page as per the app dev instructions.

### Actual behavior

A series of usual Shopify errors in Shopify Admin ("This page can't be displayed") . App install page appears for a split second before being replaced with generic Shopify page errors. Firefox says ....

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.shopify.com/shopifycloud/web/assets/v1/latest/apprequestgrant-[...........].js. (Reason: CORS request did not succeed). Status code: (null).

ChunkLoadError: Loading chunk apprequestgrant failed.
(error: [https://cdn.shopify.com/shopifycloud/web/assets/v1/latest/[...........].js](https://cdn.shopify.com/shopifycloud/web/assets/v1/latest/apprequestgrant-[.....].js))

... eventually, after many many refreshes, a 404 error page appears instead of a default App holding page (after 5 minutes of refreshing the page).

Browser inspection suggests the request for https://shopify.github.io/shopify-cli/help/start-app/ is daft.... 

This is as a result of following Shopify app setup instructions - no coding undertaken.

Continuing with the setup instructions here:
https://shopify.dev/apps/getting-started/add-functionality
results in index.js code results (message about discounting products) "flashing up" for a split second before being replaced by the pretty 404 page.

Continuing with further page refreshes (nothing else) eventually results in a series of inconsistent cross-origin request errors from and to Shopify's own domain - followed by a complete SSL failure and apparantly permanent "Secure connection failed" browser errors. Following the Shopify app dev guide has bricked 2 of my dev stores - lol.

</eyeball roll>.

Message:
---------------------------------------

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

--------------------------------------------

### Reproduction steps

1. Follow the app dev instructions on the Shopify site (WIndows 10)
2. 
3.

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.11.1

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the delay, I'll have a look at this.

What type of app are you trying to build? It's failing in [this step](https://shopify.dev/apps/getting-started/create#step-4-install-your-app-on-your-development-store), right after running `shopify app serve`, right?

**Comment by stevenjmarmorstein** [comment]
@gonzaloriestra, yes, that's the issue I'm having on that step. Please help.

**Comment by skrispyb** [comment]
I am facing the same issue. Any solution yet?

![shopify app error](https://user-images.githubusercontent.com/76402998/160003671-11aa5c1b-2edb-4a34-b38c-5cf992ee7170.PNG)

**Comment by repzilon** [comment]
I experience the same problem as the original poster. I tried @themaximehardy solution, but still have the problem.

Also, when I go to http://localhost:8081 in a web browser , it tries to redirect me to https://undefined/admin/oauth/authorize?client_id=1f78cccba52990ef59c873bf295d0d4f&scope=write_products%2Cwrite_customers%2Cwrite_draft_orders&redirect_uri=https%3A%2F%2F618a-174-92-160-71.ngrok.io%2Fauth%2Fcallback&state=145073498289580&grant_options%5B%5D=per-user . The "undefined" as the host name in that URL seems really fishy.

**Comment by gonzaloriestra** [comment]
Hi, let me clarify a bit how it works, as it looks like there's a bit of confusion around this.

When you run `shopify app serve` it basically:
- Starts a local development server for your project
- Creates a public ngrok tunnel to your localhost
- Prompts to update your app URLs ([it will do it by default soon](https://github.com/Shopify/shopify-cli/pull/2188), by the way)

It's important to say `Yes` to the last question if you want to test your app embedded in your development store. That will update the URLs on the settings of your app:

![App setup - cli-node - Shopify Partners 2022-03-30 11-03-18](https://user-images.githubusercontent.com/14979109/160794347-9bde5905-f34f-426f-8114-35038b9395e6.png)

So you should see your current ngrok URL there.

Is anyone having this issue even when saying `Yes` to update the URLs?

**Comment by repzilon** [comment]
> Is anyone having this issue even when saying `Yes` to update the URLs?
I am having this issue even when saying Yes.

Where do I go to access the application URL settings as shown in the screenshot above?

**Comment by gonzaloriestra** [comment]
You can go to https://partners.shopify.com, find your app under Apps (left menu) and then click on `App setup`.

Could you please share the output of `SHOPIFY_CLI_STACKTRACE=1 shopify app serve`?

**Comment by gonzaloriestra** [comment]
We have changed a bit how this works (it's not prompting about updating URLs anymore) and fixed some related issues, so I'm closing here.

If anyone is still having issues with the latest version (2.15.6), please let me know!

**Comment by jhaastrup** [comment]
I am having this same issue, after i run shopify app serve i don't see my app UI on the page instead i get an error 404 page displayed.
