### ISSUE TITLE
Shopify-cli update  2.11.1  stop working with current ruby version (2.6 ), i updated  Ruby but still doesn't work

### ISSUE THREAD

**Issue by PedroCampana** [Shopify/shopify-cli#2048]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

pull / push / login features

### Actual behavior

Hello! i been working with shopify cli for a while making custom themes, i don't have any experience with ruby and backend in general. I  tried to figure it out but i'm in a dead end, hope you can help me. Thanks a lot. 

After the upgrade i got this

<img width="987" alt="Captura de Pantalla 2022-02-11 a la(s) 15 48 56" src="https://user-images.githubusercontent.com/86965463/153652336-dc52bb73-b59c-4900-bec9-19ce1fb0e7fe.png">

after upgraded my ruby version still getting the error.

<img width="677" alt="Captura de Pantalla 2022-02-11 a la(s) 15 49 19" src="https://user-images.githubusercontent.com/86965463/153652326-cc8da20f-7bb1-4418-9ff5-a7f8e749b74d.png">

### Reproduction steps

1. Upgrade shopify cli with brew
2. Pull theme to local 
3. Error, only shopify theme -h doesn't result in a error

### Operating System

MacOs Catalina 10.5.7

### CLI version (run `shopify version` if you're not sure)

2.1.1

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.0.0p0

**Comment by madomingos** [comment]
Install node, it did the trick for me.

ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

node -v
v16.14.0

hopify version
2.11.1

**Comment by PedroCampana** [comment]
Hey! I installed node and works fine. Thanks for the help @madomingos  and @gonzaloriestra  Se pasaron!

**Comment by Irrelon** [comment]
Hey folks, if you have node installed at version 16 etc, you likely need to update it to the latest to get this to work. The error speaks of the Ruby version but it's not correct. Installing the latest version of Node.js will solve this.
