### ISSUE TITLE
[Bug]: ngrok is causing restrictions and the free account is no more being served | Tested on two different IPs

### ISSUE THREAD

**Issue by jayantasamaddar** [Shopify/shopify-cli#2049]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Everything should have worked as it always does.

The node app actually does it's job. It's the ngrok connection that was supposed to connect to the app in the store that isn't connecting and throwing the error.

### Actual behavior

I noticed today morning (Feb 12, 2022, 11 AM GMT +0530), that there was an issue connecting the node app via ngrok to shopify.

Shopify serve works, updates the app url in the required areas but ngrok throws an error
![ngrok-error](https://user-images.githubusercontent.com/33408788/153705705-28273bf0-bd33-4336-8948-f1a854bd2eac.png)

So here is how we narrowed it down to ngrok causing the problems, from the possible problems listed below:

**List of possible issues:**
1) New Shopify CLI version 2.11.1 causing the issue.
2) It was a Region error, so maybe changing the ngrok region would help.
3) It is a ngrok problem only and shopify cli is not involved at all.
4) It is a ngrok http/https problem only. We will test with tcp to check. (Ngrok disabling it for free users etc)

**Tests**
1) Uninstalled and reinstalled shopify cli to an older version. Problem persists.
2) Added region as India (my country) `region: in` in the `ngrok.yml` file. Problem persists.
3) Asked a friend using a different PC, from a different ISP from another part of the country to install ngrok and run a http server using `ngrok http 1313` and share the link with me. We both get the same error. He just created a brand new ngrok account as well....so it is not even related to my account.
4) He tried with `ngrok tcp 1313` and it is working!

So our conclusion is ngrok has disabled http/https tunnelling for free users. 

Kindly provide us shopify app developers an alternative.

### Reproduction steps

1. `killall ngrok`
2. `shopify app serve` from the app folder after initial login and connecting the app.
3. Follow up the ngrok url

### Operating System

Ubuntu 20.04.3

### CLI version (run `shopify version` if you're not sure)

2.11.1

### Ruby version (run `ruby -v` if you're not sure)

2.7.0

### What language and version are you using in your application?

Node 16.13.2

**Comment by solamarpreet** [comment]
Can replicate the issue. I am from India region as well. I have written to NGROK asking them to confirm if they have indeed moved http tunnels to paid tier.

**Comment by gonzaloriestra** [comment]
It seems it was a ngrok issue, but they solved it. Could you try again? Let me know if it's still failing.

**Comment by solamarpreet** [comment]
> It seems it was a ngrok issue, but they solved it. Could you try again? Let me know if it's still failing.

Hi. Yes it seems to have been resolved. However ngrok asked for screenshots before telling me the restriction has been lifted for my account and that they have introduced this feature to combat abuse. If they are doing this on a case by case basis and not completely rolled back the update I would suggest to have a note in the documentation regarding this and advising new users to reach out to ngrok to get the restrictions lifted.

**Comment by jayantasamaddar** [comment]
I concur with @solamarpreet 
ngrok sent an email reply citing they have been restricting accounts for security reasons and asked me the purpose of using ngrok and any screenshots to demonstrate that, after which they allowed access again. It sounded excessive because I was a fairly new user.

**Comment by jaas1014** [comment]
![image](https://user-images.githubusercontent.com/89313920/181258967-17c58b3e-2e15-4404-8fb4-23c4b8ed766f.png)
i receive this bypass issue.or deceptive website when I use it for phishimg.can u help with the error please.

**Comment by gonzaloriestra** [comment]
That warning is shown by Ngrok, but it's normal and it should work if you click on "Visit site".

If someone can't get it to work, notice that the new CLI allows passing a custom URL, so you can use another provider like Cloudflare. Let me share some links:
- [How to migrate to CLI 3.x](https://shopify.dev/apps/tools/cli/migrate)
- [Flag to pass a custom URL](https://shopify.dev/apps/tools/cli/commands#flags) (--tunnel-url)
