### ISSUE TITLE
[Bug]: shopify extension push - An unexpected error occurred on Shopify.

### ISSUE THREAD

**Issue by ZPetrovich** [Shopify/shopify-cli#2050]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

extension should be pushed to Shopify successfully

### Actual behavior

It thinks near 1 minute and then shows error.

### Stack trace

```shell
% shopify extension push       
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┃ ✗ An unexpected error occurred on Shopify.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (115.14s) ━━
✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (You chose: Yes, send)
/usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/tasks/update_draft.rb:21:in `call': undefined method `dig' for nil:NilClass (NoMethodError)            
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/task.rb:8:in `call'                                                                                   
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/commands/push.rb:100:in `block in update_draft'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/commands/push.rb:95:in `with_waiting_text'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/commands/push.rb:99:in `update_draft'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/commands/push.rb:39:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/project_types/extension/commands/push.rb:38:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/command.rb:27:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/monorail.rb:30:in `log'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/bin/shopify:37:in `block (2 levels) in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/bin/shopify:36:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.11.1/gems/shopify-cli-2.11.1/bin/shopify:47:in `<top (required)>'
        from /usr/local/bin/shopify:7:in `load'
        from /usr/local/bin/shopify:7:in `<main>'
```

### Reproduction steps

1. cd theme-app-extension
2. shopify extension push 

### Operating System

Mac OS Catalina 10.15.7

### CLI version (run `shopify version` if you're not sure)

2.11.1

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.0p0

### What language and version are you using in your application?

Node v12.22.8

**Comment by TGIFelix** [comment]
Same issue

**Comment by muratozgul** [comment]
same issue

**Comment by TheApeMachine** [comment]
Same on Windows, and Ubuntu. I realize there is a warning about the version for me, but that one path update I don't think is the issue here. My gut tells me it is rate-limiting related, but who knows.

<details>
modules by path ../../node_modules/ 331 KiB
  ../../node_modules/big.js/big.js 22.8 KiB [built] [code generated]
  ../../node_modules/shopify-buy/index.js 308 KiB [built] [code generated]
webpack 5.69.1 compiled successfully in 514 ms
Your environment Ruby version, 3.1.1, is outside of the range supported by the CLI, 2.6.6..<3.1.0, and might cause incompatibility issues.
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┃ X An unexpected error occurred on Shopify.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (122.68s) ━━━
X An unexpected error occured.
        To submit an issue include the stack trace.

? Send an anonymized error report to Shopify? (You chose: No, don't send)
G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/tasks/update_draft.rb:21:in `call': undefined method `dig' for nil:NilClass (NoMethodError)

        response = ShopifyCLI::PartnersAPI.query(context, GRAPHQL_FILE, **input).dig(*RESPONSE_FIELD)
                                                                                ^^^^
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/task.rb:8:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/commands/push.rb:99:in `block in update_draft'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/commands/push.rb:94:in `with_waiting_text'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/commands/push.rb:98:in `update_draft'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/commands/push.rb:38:in `block in call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/project_types/extension/commands/push.rb:37:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/command.rb:27:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/executor.rb:15:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/bin/shopify:49:in `block in <top (required)>'
        from G:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.12.0/bin/shopify:60:in `<top (required)>'
        from G:/Ruby31-x64/bin/shopify:32:in `load'
        from G:/Ruby31-x64/bin/shopify:32:in `<main>'
</details>

**Comment by TheApeMachine** [comment]
Digging further, but for now noticing that organization_id is 0, which may have no impact, or it may have.

```
 #<Extension::ExtensionProject:0x0000024e4aaf7248 @directory="C:/Users/theapemachine/code/climate-neutral-checkout/climate-neutral-checkout-theme-extension", @env=#<ShopifyCLI::Resources::EnvFile:0x0000024e4aaaae48 @api_key="HIDDEN", @secret="HIDDEN", @extra={"EXTENSION_TITLE"=>"climate-neutral-checkout-theme-extension", "EXTENSION_ID"=>"4199805", "EXTENSION_UUID"=>"0f2db5a1-27bc-44a0-bc53-86932031d7da"}>, @config={"project_type"=>:extension, "organization_id"=>0, "EXTENSION_TYPE"=>"THEME_APP_EXTENSION"}>
```

**Comment by TheApeMachine** [comment]
I am hitting this line in lib\shopify_cli\api.rb. That and judging by something in older release notes, maybe this has to do with having either too many apps, or too many files to push?

```ruby
90 end.retry_after(APIRequestRetriableError, retries: 3) do |e|
91   sleep(1) if e.is_a?(APIRequestThrottledError)
92 end
```

**Comment by pepicrft** [comment]
👋🏼 First of all, apologies for the inconveniences this might have caused. To be able to debug the issue, I'd need some input from you. Please, run the same command but passing the `DEBUG=1` environment variable:

```bash
DEBUG=1 shopify extension push
```

That'll print more verbose logs. At the end of the logs you'll see a log that has the following structure:

```
DEBUG POST https://partners.shopify.com/api/cli/graphql with X-Request-Id: dca1a805-15d6-405b-b91e-xxxxx
```

Could you share that `X-Request-Id` with me?

**Comment by TheApeMachine** [comment]
Ok, so it seems check how big the assets size is, finally did a simple `shopify extension check` and the problem became pretty obvious: `blocks/app-block.liquid:1: suggestion: AssetSizeAppBlockJavaScript: JavaScript in Theme App Extension blocks exceeds compressed size threshold (10000 Bytes).`

Got rid of some things, built a production bundle, totally minified, now it seems to be working. Even though the final bundle is still 35kb, but oh well...
