### ISSUE TITLE
[Bug]: brew install shopify-cli error 

### ISSUE THREAD

**Issue by jyturley** [Shopify/shopify-cli#2057]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

other

### Expected behavior

```
brew tap shopify/shopify
brew install shopify-cli
```
successfully installs.

### Actual behavior

```
==> Fetching shopify-cli from gem source
Error: No such file or directory - /usr/local/opt/ruby@3.0/bin/gem
```

`/usr/local/opt/ruby@3.0/bin/gem` does exist in my system:
```
♤  ls /usr/local/opt/ruby\@3/bin/gem
/usr/local/opt/ruby@3/bin/gem*
```

Ruby v3
```
♤  ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin19]
```

### Reproduction steps

Follow steps laid out here: https://shopify.dev/themes/tools/cli/getting-started#macos-homebrew
1. brew update
2. brew tap shopify/shopify
3. brew install shopify-cli

### Operating System

macOS Catalina 10.15.7

### CLI version (run `shopify version` if you're not sure)

trying to install cli

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin19]

**Comment by danielbixel** [comment]
Same issue,
Thanks for already reporting

**Comment by lynnzc** [comment]
same issue.
```  
$ brew install shopify-cli
Running `brew update --preinstall`...
==> Fetching shopify-cli from gem source
==> Installing shopify-cli from shopify/shopify
==> Fetching shopify-cli from gem source
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/xxx/Library/Caches/Homebrew/shopify-cli-2.11.1.gem
```

**Comment by gonzaloriestra** [comment]
Not sure what's going on, but could you try running `brew install ruby@3.0` before?

@lynnzc your case seems different, 2.11.1 is not the latest version. You should run `brew update`.

**Comment by jyturley** [comment]
> Not sure what's going on, but could you try running `brew install ruby@3.0` before?

This fixed the issue for me as well.

**Comment by gonzaloriestra** [comment]
@lynnzc I'd try with:
```
brew uninstall shopify-cli 
brew cleanup shopify-cli 
brew install ruby@3.0
brew install shopify-cli
```

**Comment by pimoux** [comment]
I had the problem and I checked if the path exists but this was not the case because I had ruby@3.1.
For people who had the problem, I advise to check if the path exists and check if the version is the right one.

**Comment by Cam** [comment]
If you've already installed the ruby@3.0 gem and this still isn't working. Try running `brew install ruby` before running `brew install shopify-cli` again.

**Comment by maryambalogun** [comment]
hi im quite new to this, can i please ask what is the new brew formula for ruby 3.1.1 as I am still finding problems downloading shopify-cli

> The release [2.13.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.13.0) should fix this issue. It now supports Ruby 3.1 and the brew formula has changed. Please, let us know if you still have problems.



> The release [2.13.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.13.0) should fix this issue. It now supports Ruby 3.1 and the brew formula has changed. Please, let us know if you still have problems.

**Comment by Cam** [comment]
@gonzaloriestra I've _only_ had this issue with the [2.13.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.13.0) release, and the latest version of Homebrew. Sadly I believe it is still an active issue.

**Comment by pepicrft** [comment]
👋🏼 Pedro here from Shopify.
@cam would you mind updating the `shopify-cli.rb` formula with the content below and going through the installation again? Remember to uninstall the CLI and Ruby first from the Homebrew environment and do a cleanup. You can get the path to the formula by running: `echo $(brew --prefix)/Library/Taps/shopify/homebrew-shopify/shopify-cli.rb`

```
# frozen_string_literal: true
#
# The canonical copy of this file is hosted at
# https://github.com/Shopify/shopify-cli/blob/main/packaging/homebrew/shopify-cli.base.rb
# so please make all updates there.
#
# Modified from formula originally generated via `brew-gem` using
# `brew gem formula shopify-cli`

require "formula"
require "fileutils"

class ShopifyCli < Formula
  module RubyBin
    def ruby_bin
      Formula["ruby"].opt_bin
    end
  end

  class RubyGemsDownloadStrategy < AbstractDownloadStrategy
    include RubyBin

    def fetch(_timeout: nil, **_options)
      ohai("Fetching shopify-cli from gem source")
      cache.cd do
        ENV["GEM_SPEC_CACHE"] = "#{cache}/gem_spec_cache"

        _, err, status = Open3.capture3("gem", "fetch", "shopify-cli", "--version", gem_version)
        unless status.success?
          odie err
        end
      end
    end

    def cached_location
      Pathname.new("#{cache}/shopify-cli-#{gem_version}.gem")
    end

    def cache
      @cache ||= HOMEBREW_CACHE
    end

    def gem_version
      @version ||= @resource&.version if defined?(@resource)
      raise "Unable to determine version; did Homebrew change?" unless @version
      @version
    end

    def clear_cache
      cached_location.unlink if cached_location.exist?
    end
  end

  include RubyBin

  url "shopify-cli", using: RubyGemsDownloadStrategy
  version "2.13.0"
  sha256 "1da9e66ffb01b6725a62099c89195925d8787be66ba25c86bf56d018fe647219"
  depends_on "ruby"
  depends_on "git"

  def install
    # set GEM_HOME and GEM_PATH to make sure we package all the dependent gems
    # together without accidently picking up other gems on the gem path since
    # they might not be there if, say, we change to a different rvm gemset
    ENV["GEM_HOME"] = prefix.to_s
    ENV["GEM_PATH"] = prefix.to_s

    # Use /usr/local/bin at the front of the path instead of Homebrew shims,
    # which mess with Ruby's own compiler config when building native extensions
    if defined?(HOMEBREW_SHIMS_PATH)
      ENV["PATH"] = ENV["PATH"].sub(HOMEBREW_SHIMS_PATH.to_s, "/usr/local/bin")
    end

    system(
      "gem",
      "install",
      cached_download,
      "--no-document",
      "--no-wrapper",
      "--no-user-install",
      "--install-dir", prefix,
      "--bindir", bin,
      "--",
      "--skip-cli-build"
    )

    raise "gem install 'shopify-cli' failed with status #{$CHILD_STATUS.exitstatus}" unless $CHILD_STATUS.success?

    bin.rmtree if bin.exist?
    bin.mkpath

    brew_gem_prefix = "#{prefix}/gems/shopify-cli-#{version}"

    ruby_libs = Dir.glob("#{prefix}/gems/*/lib")
    exe = "shopify"
    file = Pathname.new("#{brew_gem_prefix}/bin/#{exe}")
    (bin + file.basename).open("w") do |f|
      f << <<~RUBY
        #!#{ruby_bin}/ruby --disable-gems
        ENV['GEM_HOME']="#{prefix}"
        ENV['GEM_PATH']="#{prefix}"
        ENV['RUBY_BINDIR']="#{ruby_bin}/"
        require 'rubygems'
        $:.unshift(#{ruby_libs.map(&:inspect).join(",")})
        load "#{file}"
      RUBY
    end
  end
end
```

**Comment by Cam** [comment]
Hey @pepicrft 👋

Boom! 🚀

```
==> Fetching shopify-cli from gem source
==> Installing shopify-cli from shopify/shopify
==> Installing dependencies for shopify/shopify/shopify-cli: ruby
==> Installing shopify/shopify/shopify-cli dependency: ruby
==> Pouring ruby--3.1.1.monterey.bottle.tar.gz
```
...etc 👍
