### ISSUE TITLE
shopify app tunnel auth <token> error

### ISSUE THREAD

**Issue by wishedy** [Shopify/shopify-cli#2058]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Successfully open my local Shopify development application

### Actual behavior

An exception is thrown after executing the ‘shopify app tunnel auth <token>’  command

### Stack trace

```shell
✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

### Reproduction steps

1.shopify app create node
2.npm install 
3.shopify app tunnel auth <token>

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

2.11.2

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.6.3

### What language and version are you using in your application?

ruby 2.6.3,node 14.15.4,npm 6.14.10

**Comment by wishedy** [comment]
An error is reported when starting locally，
HOST_NAME: process.env.HOST.replace(/https:\/\/|\/$/g, ""), /test_app/server/server.js:22:31)
But The corresponding host field is not configured in .env.   What should I do

**Comment by serkanalabas** [comment]
> Hi! In order to save your Ngrok token, you have to copy it from the [Ngrok dashboard](https://dashboard.ngrok.com/get-started/your-authtoken), and then run `shopify app tunnel auth YOUR-TOKEN`. Are you doing that? If everything works, it should save it in `/Users/wishedy/.ngrok2/ngrok.yml`.
> 
> If it's still failing, please run `SHOPIFY_CLI_STACKTRACE=1 shopify app tunnel auth YOUR-TOKEN` and share the stack trace here.
> 
> Regarding the HOST_NAME issue, the variable is set with the Ngrok URL when `shopify app serve` creates the tunnel. If the tunnel is not working, I guess is normal that it's empty.

I did the same steps and I get the following error;

`✗ An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (Choose with ↑ ↓ ⏎, filter with 'f')
> 1. Yes, send
  2. No, don't send
/opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:256:in `wait_for_user_input': Interrupt (Interrupt)
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:246:in `process_input_until_redraw_required'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:74:in `call'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt/interactive_options.rb:27:in `call'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:230:in `interactive_prompt'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:203:in `ask_interactive'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/lib/shopify_cli/exception_reporter.rb:68:in `report_error?'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/lib/shopify_cli/exception_reporter.rb:57:in `report?'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/lib/shopify_cli/exception_reporter.rb:26:in `report'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:31:in `handle_exception'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:71:in `block in install!'`

**Comment by serkanalabas** [comment]
Hey,

I found the sub-source of the problem. I am using Macbook Pro. It gives such a problem as it cannot access ngrok. It got better when I access it. Thank you :)


`/opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `spawn': Permission denied - /Users/serkomen/.cache/shopify/ngrok (Errno::EACCES)
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:126:in `system'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/lib/shopify_cli/context.rb:494:in `system'
        from /opt/homebrew/Cellar/shopify-cli/2.16.1/gems/shopify-cli-2.16.1/lib/shopify_cli/tunnel.rb:86:in `auth'
        from /opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `auth'`

**Comment by serkanalabas** [comment]
I share one more piece of information, maybe it will be useful for you. You said that you would put the file '/Users/wishedy/.ngrok2/ngrok.yml' in this path, but I got it '/var/root/.ngrok2/ngrok.yml'. I moved it to the right path and the problem was solved :)

```
serkomen@Serkans-MacBook-Pro sekomentest1 %  sudo shopify app tunnel auth XXXXXXXXX
Authtoken saved to configuration file: /var/root/.ngrok2/ngrok.yml
```
