### ISSUE TITLE
[Bug]: <Failed to process webhook: Error: Could not validate request for topic>

### ISSUE THREAD

**Issue by danielbixel** [Shopify/shopify-cli#2067]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

I am setting up a super basic app that should receive a webhook test notification and console log it.
I havent really changend anything in the code just added: 

 /* Register webhook for cart create */
        const registrationCartCreate = await Shopify.Webhooks.Registry.register({
          shop,
          accessToken,
          path: '/webhooks',
          topic: 'CARTS_CREATE',
          webhookHandler: (_topic, shop, body) => {
            console.log('received cart created webhook: ');
            const obj = JSON.parse(body);
            console.log(obj);
          },
        });
        if (registrationCartCreate.success) {
          console.log('Successfully registered cart create webhook!');
        } else {
          console.log('Failed to register cart create webhook', registrationCartCreate.result);
        }

Webhook payload is received with beeceptor without any issues.

Am I overseeing sth super-basic here?
As far as I am concerned cart webhooks don't need their scope added.

What I also find a bit strange is that chrome accuses me of phishing when I open the app in the Admin.
ngrok seems to work fine though.

Hope you guys can push me in the right direction.

Thanks a lot

### Actual behavior

Error message in console ( I console logged the ctx.)

`router.post("/webhooks", async (ctx) => {
    console.log(ctx)
    try {
      await Shopify.Webhooks.Registry.process(ctx.req, ctx.res);
      console.log(`Webhook processed, returned status code 200`);
    } catch (error) {
      console.log(`Failed to process webhook: ${error}`);
    }
  });`

...
response: {
     status: 404,
     message: 'Not Found',
     header: [Object: null prototype] {}
   },
...
Failed to process webhook: Error: Could not validate request for topic xxx.

### Stack trace

Failed to process webhook: Error: Could not validate request for topic carts/create

### Reproduction steps

1. shopify app create node

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

2.11.2

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by danielbixel** [comment]
When starting the app I get the following console message:

message: 'https://shopify.dev/api/usage/versioning#deprecation-practices',
path: 'https://stickvogel-test-store01.myshopify.com/admin/api/2020-10/graphql.json'

What is going on here? These old API versions arent supported anymore?

I am really confused about the shopify-cli as it seems that even the simplest tasks dont seem to work. Like setting up a webhook subscription.

Really looking forward to some guidance here. 
Thanks

**Comment by danielbixel** [comment]
console.log('webhookRegistry ' + JSON.stringify(Shopify.Webhooks.Registry.webhookRegistry))
ourput: webhookRegistry []

after deleting and reinstalling the app the webhookRegistery contains the registered webhooks:

webhookRegistry [{"path":"/webhooks","topic":"APP_UNINSTALLED"},{"path":"/webhooks","topic":"ORDERS_CREATE"},{"path":"/webhooks","topic":"PRODUCTS_CREATE"},{"path":"/webhooks","topic":"PRODUCTS_UPDATE"}]

**Comment by razanor** [comment]
@gonzaloriestra Hey! Any progress with the issue? I'm currently facing it as well.
`Failed to process webhook: Error: Could not validate request for topic products/update`

**Comment by mariusa** [comment]
still relevant! But not for Shopify :(

**Comment by gonzaloriestra** [comment]
@mariusa sorry for the delay. I'm closing here since it's not related to the CLI, but will ping the appropriated Shopify team.
