### ISSUE TITLE
[Bug]: Shopify login: timed out

### ISSUE THREAD

**Issue by stressed-pet-owner** [Shopify/shopify-cli#2082]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I'll be logged into the store like in the tutorial

### Actual behavior

It didn't work. It didn't prompt anything. I'm just new to Shopify and would like to try developing a theme by following this [tutorial ](https://www.youtube.com/watch?v=0EUSvAqxFEA).

### Reproduction steps

1. Install latest Ruby with Devkit
2. Install latest Shopify CLI
3. Login using shopify login[](url
![Capture](https://user-images.githubusercontent.com/78886814/155307536-36f908b4-d0c5-485d-af0a-7a3b2e2a2a4d.PNG)
)

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

Git Bash

### Ruby version (run `ruby -v` if you're not sure)

3.1.1p18

### What language and version are you using in your application?

Not sure what to use as I'm a beginner

**Comment by gonzaloriestra** [comment]
The `shopify login` command should open a new browser window, is that happening? If not, I think the problem is Git Bash, which may not be fully compatible. Could you try with PowerShell or CMD?

**Comment by FazalJarral** [comment]
> The `shopify login` command should open a new browser window, is that happening? If not, I think the problem is Git Bash, which may not be fully compatible. Could you try with PowerShell or CMD?

I have tried both CMD and PowerShell - a new window opens and displays the following text `✔ Logged in.`
Displays the following error `(Blocking operation timed out!) (IO::TimeoutError)`

Current Shopify CLI version: 3.45.0
OS: Windows 10
