### ISSUE TITLE
[Bug]: shopify extension register throwing "Unable to parse response from Partners Dashboard." error

### ISSUE THREAD

**Issue by sutjin** [Shopify/shopify-cli#2091]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

running `shopify extension register` should continue to register the extension. If an error occurred, should explain why it has failed

### Actual behavior

It only responded with "Unable to parse response from Partners Dashboard."

I have tried to add `SHOPIFY_CLI_STACKTRACE=1` to the environment and try to run it with `SHOPIFY_CLI_STACKTRACE=1 shopify extension` and is still not showing the straktrace

### Stack trace

```shell
✗ Unable to parse response from Partners Dashboard.
```

### Reproduction steps

1. Create an extension
2. Verified its working when running local (via ngork)
3. Register extension using `shopify extension register`

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205 

### What language and version are you using in your application?

14.17.0

**Comment by tyzion** [comment]
Have you tried to check if the extension is present in Shopify?
Try running `shopify extension connect`, and see if it is listed
My problem was that it didn't exist

**Comment by sisrio** [comment]
what's wrong with shopify development team? Like no one cares. Why they can't release just one stable version and make it run for several years, instead trying to overwhelm developers with constant version update, cli update, api update, bla bla bla. This issue is still happening on windows machines.

**Comment by jonniedarko** [comment]
I too am seeing this now suddenly and didn't a couple of days ago
