### ISSUE TITLE
ShopifyCLI::API::APIRequestForbiddenError: 403{"errors":"Unauthorized Access"}

### ISSUE THREAD

**Issue by The-Kelvin** [Shopify/shopify-cli#2098]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/api.rb:74:in `block in request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/api.rb:89:in `request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
/var/lib/gems/2.7.0/gems/shopify-cli-2.9.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):
https://www.loom.com/share/2cea025a8e3b48f89512c80d3e157c2a
https://www.loom.com/share/a2b3351cdbfd4e60945dad76b02b4d26

**Comment by amcaplan** [comment]
Hi @The-Kelvin, thanks for opening this issue. From the videos I can see this happened during a `theme pull` on 2.9.0.

Are you still experiencing this issue? Have you tried upgrading to the latest CLI version? 2.9.0 is [known to have some authentication bugs](https://github.com/Shopify/shopify-cli/issues/1944#issuecomment-1020343943) that were fixed in 2.10.0.

**Comment by The-Kelvin** [comment]
Hi Ariel. I figured it out.
However, the error is not caused by any version issues.
It's a bug related to how the normal shopify account and the partner
accounts under the same person integrate.
Development stores created on the partners account do not always
synchronize with the normal account. Only the stores listed on both
accounts offer a smooth usage with shopify-cli.
It took me some time to figure that out, and to then manage to fix it.
I will share you the link to what helped me fix the error at the end of
this email. Perhaps your team could figure out a way to fix it so that
stores created on partners accounts synchronize automatically with the
normal shopify account without hick-ups.

https://github.com/Shopify/shopify-cli/issues/1361#issuecomment-879426041

**Comment by The-Kelvin** [comment]
Hi Ariel. I figured it out.
However, the error is not caused by any version issues.
It's a bug related to how the normal shopify account and the partner
accounts under the same person integrate.
Development stores created on the partners account do not always
synchronize with the normal account. Only the stores listed on both
accounts offer a smooth usage with shopify-cli.
It took me some time to figure that out, and to then manage to fix it.
I will share you the link to what helped me fix the error at the end of
this email. Perhaps your team could figure out a way to fix it so that
stores created on partners accounts synchronize automatically with the
normal shopify account without hick-ups.

https://analytics.twitter.com/mob_idsync_click?slug=LSNONWG9dw&idb=AAAAEICAqxhPP_pp947TSoX1HMMzGCcOamCih6CxUIHX-3EvjOWu6wD072-osireBhg909CBU1UrcXfD9NYapwMpv3PhdrZflBbJ64bzaO3nGWWENb2V6T7-ECIz81_bBhgSP-LyAoK9K8Uq7H3kwItniGHoHH5STS6a1AlaD2b0tPvAoCnpa-QCVyneXCvhQR-nttR5CGHnU6-1_kcZeq8sjPGbaUQVj3DVd_dlGsJdHxYK6E0JVB3-E3tSUz6CpFee9uEA4aS9BCwZqGTlPobFQA&tailored_ads=false&ad_tracking=true

**Comment by The-Kelvin** [comment]
Please ignore my first reply

**Comment by pepicrft** [comment]
We are aware of this limitation of the platform and the team will soon work on improving the experience. Until then, we recommend following the workaround proposed [in this comment](https://github.com/Shopify/shopify-cli/issues/1309#issuecomment-1112351597). I'll close the issue to continue the discussion in that other issue that reports this same bug.
