### ISSUE TITLE
[Enhancement]: Document how to build and run a development version

### ISSUE THREAD

**Issue by kumar303** [Shopify/shopify-cli#2100]
### What type of project(s) will this request affect?

all of them

### Overview

As a contributor, I'd like to know how to build and run a development version of `shopify-cli`. This is not documented.

### Motivation

I would like to link to a document for my teammates to make them fully self sufficient. I think this is how to do it:

```
dev up
$HOME/src/github.com/Shopify/shopify-cli/bin/shopify --version
```

**Comment by amcaplan** [comment]
@kumar303 that mostly sounds right, but note that it's `shopify version` not `shopify --version`.

Also note this is a public project and that won't work for non-Shopifolk. In that case, I believe you'd want to:

1. Clone the repo
2. In the repo directory, `gem install`
3. `bin/shopify version`

I suppose you could alias something to the absolute path of `bin/shopify` but I'm not sure how to express that clearly in instructions.

**Comment by kumar303** [comment]
Thanks @amcaplan 

Running `gem install` gives an error. However, `bundle install` seemed to work.

**Comment by amcaplan** [comment]
Yes @kumar303, my careless mistake 🤦‍♂️

**Comment by kumar303** [comment]
It would be really helpful to get some documentation on how to develop `shopify-cli`. I also discovered `DEBUG=1` and I wish I knew about this earlier!
