### ISSUE TITLE
[Bug]: `shopify extension reigster` should support `--api-key` option, or not claim to in the documentation

### ISSUE THREAD

**Issue by msmithstubbs** [Shopify/shopify-cli#2106]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

The shopify CLI help suggests the `--api-key` option is supported:

```
$ shopify extension register --help
Register your local extension to a Shopify app
    Usage: shopify extension register
    Options:
      --api-key=API_KEY The API key used to register an app with the extension. This can be found on the app page on Partners Dashboard.
```

I expect the `shopify extension register` command to support specifying an API key with the `--api-key` option.

### Actual behavior

The command claims not to support the option.

```
$  shopify extension register --api-key
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ The option --api-key is not supported.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Either the help docs are wrong, or the command is wrong.

### Reproduction steps

1. Run `shopify extension register --help`
2. Observe the shopify cli claims to support the `--api-key` option
3. Run `shopify extension register --api-key=TESTING`
4. Observe the shopify cli rejects the `--api-key` option

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

2.12.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]

**Comment by stephszeto** [comment]
Thanks for raising, Matt!

This definitely predates me - I suspect it's the latter, but at this point with the refactor, I'm opting to just update the docs and CLI help text to make it consistent with the current behavior. 

@amcaplan - can you help update the CLI and @shainaraskas - can you update the extension docs to reflect this? Thanks y'all!
