### ISSUE TITLE
[Enhancement]: override graphql API version

### ISSUE THREAD

**Issue by gadieichhorn** [Shopify/shopify-cli#2123]
### What type of project(s) will this request affect?

app

### Overview

I would like to change the graph QL API version from code.

the default CLI generate an older API version (2021-10) that doesn't support some product elements I need (latest) 

there is a bit of a code that looks like it is related but it is not hooked into the app.js file

client.js
```  return new ApolloClient({
    uri: `https://${shop}/admin/api/2022-01/graphql.json`,
```
How do I dynamically set this to the right shop (public app) for all my graphql queries?

### Motivation

support graphql version API from code

**Comment by jamesjiadongwu** [comment]
+1
