### ISSUE TITLE
Store login fails with "An unexpected error occured" 

### ISSUE THREAD

**Issue by 2hari** [Shopify/shopify-cli#2124]
# Issue summary

can't log in. added stacktrace env to obtain below stack. In general all shopify cli command seem very slow. Even cloning the git repository, My network speed is fine.  

I have cross checked with #1865 - I don't have any syntax errors in my cli command. 
I have tried the same on cmd and powershell

## Stacktrace

raceback (most recent call last):
        34: from /usr/local/bin/shopify:23:in `<main>'
        33: from /usr/local/bin/shopify:23:in `load'
        32: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:59:in `<top (required)>'
        31: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:49:in `block in <top (required)>'
        30: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        29: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        28: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
        27: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
        26: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/monorail.rb:30:in `log'
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:15:in `call'
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/command.rb:35:in `call'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/commands/login.rb:18:in `call'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/commands/login.rb:45:in `validate_shop'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-2.13.0/lib/shopify_cli/commands/login.rb:61:in `shop_to_permanent_domain'
         7: from /usr/lib/ruby/2.7.0/net/http.rb:606:in `start'
         6: from /usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
         5: from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         4: from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
         3: from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
         2: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
         1: from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': execution expired (Net::OpenTimeout)

## Specifications

- App type: 2.13.0
- Operating System: Elementary OS 6.1 Jolnir
- Shell: bash
- Ruby version (ruby -v): ruby 2.7.0p0

**Comment by cbychen** [comment]
> 

did you solved it ?
