### ISSUE TITLE
[Bug]: Cannot change the store which Shopify-cli displays in install output

### ISSUE THREAD

**Issue by seanonthenet** [Shopify/shopify-cli#2139]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

On switching store in Shopify CLI with `shopify switch [--store=newStore]`  it should output the new store default install url on next serve:

```
⭑ To install and start using your app, open this URL in your browser:
https://sdlkfjlasdjk.ngrok.io/auth?shop=newStore.myshopify.com
```

### Actual behavior

Even when logging out and logging in again the install app on store output of the cli will not change:

```
⭑ To install and start using your app, open this URL in your browser:
https://sdlkfjlasdjk.ngrok.io/auth?shop=oldURL.myshopify.com
```

### Reproduction steps

1. `shopify switch --store=newStore` => success
2. `shopify app serve` (app hasn't been installed anywhere yet)
3.  output: 
```
⭑ To install and start using your app, open this URL in your browser:
https://sdlkfjlasdjk.ngrok.io/auth?shop=**oldURL**.myshopify.com
```

### Operating System

macOS Monterey

### CLI version (run `shopify version` if you're not sure)

2.13.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205

### What language and version are you using in your application?

ruby 2.6.8p205

**Comment by amcaplan** [comment]
Looks like `switch` changes the value set in `DB` (our `PStore` instance): https://github.com/Shopify/shopify-cli/blob/93f56a2d75e44ba4b9cb508d314c1a9e7dbfbb85/lib/shopify_cli/commands/switch.rb#L28

However, we use the value of the shop from `project.env.shop` when displaying that URL. https://github.com/Shopify/shopify-cli/blob/93f56a2d75e44ba4b9cb508d314c1a9e7dbfbb85/lib/shopify_cli/services/app/serve/rails_service.rb#L28

I need to look deeper and see which one is correct.

**Comment by amcaplan** [comment]
Here's my brief analysis.

It seems like `DB` is the correct source of truth for store login information. And it's not even clear why a store would be fundamentally associated with a project's env, as it's supposed to be able to be changed by logging into a different store.

Still, grepping around shows many times we're checking the project's `.env` instead of the `DB`:

```
lib/project_types/extension/extension_project.rb:20:          shop: current.env.shop,
lib/project_types/extension/features/argo_serve.rb:87:          options << "--store=#{project.env.shop}" if argo_runtime.supports?(:shop)
lib/project_types/extension/tasks/ensure_resource_url.rb:21:          .rescue { specification_handler.build_resource_url(shop: project.env.shop, context: context) }
lib/project_types/extension/tasks/ensure_resource_url.rb:26:              context.warn(context.message("warnings.resource_url_auto_generation_failed", project.env.shop))
lib/project_types/extension/tasks/merge_server_config.rb:30:          store: project.env.shop || "",
lib/shopify_cli/services/app/open_service.rb:14:          context.open_url!("#{project.env.host}/login?shop=#{project.env.shop}")
lib/shopify_cli/services/app/serve/node_service.rb:27:            if project.env.shop
lib/shopify_cli/services/app/serve/node_service.rb:28:              project_url = "#{project.env.host}/auth?shop=#{project.env.shop}"
lib/shopify_cli/services/app/serve/php_service.rb:27:            if project.env.shop
lib/shopify_cli/services/app/serve/php_service.rb:28:              project_url = "#{project.env.host}/login?shop=#{project.env.shop}"
lib/shopify_cli/services/app/serve/rails_service.rb:27:            if project.env.shop
lib/shopify_cli/services/app/serve/rails_service.rb:28:              project_url = "#{project.env.host}/login?shop=#{project.env.shop}"
lib/shopify_cli/tasks/ensure_dev_store.rb:9:          "core.tasks.ensure_dev_store.could_not_verify_store", project.env.shop
lib/shopify_cli/tasks/ensure_dev_store.rb:13:          ctx.message("core.tasks.ensure_dev_store.convert_to_dev_store", project.env.shop)
lib/shopify_cli/tasks/ensure_dev_store.rb:19:        ctx.puts(ctx.message("core.tasks.ensure_dev_store.transfer_disabled", project.env.shop))
lib/shopify_cli/tasks/ensure_dev_store.rb:30:          current_domain = project.env.shop
test/project_types/extension/extension_project_test.rb:66:      assert_equal("johndoe.myshopify.com", ExtensionProject.current.env.shop)
```

In fact, it seems like the only time we actually `get` the value from `DB` is for [`whoami`](https://github.com/Shopify/shopify-cli/blob/93f56a2d75e44ba4b9cb508d314c1a9e7dbfbb85/lib/shopify_cli/commands/whoami.rb#L7) and for [admin API](https://github.com/Shopify/shopify-cli/blob/93f56a2d75e44ba4b9cb508d314c1a9e7dbfbb85/lib/shopify_cli/admin_api.rb#L104) access.

I'm guessing that we should be changing all these to `ShopifyCLI::DB.get(:shop)`, I'm wondering if there's any reason to leave as is or there's something I'm missing? Because it seems like 1 big mistake that's been perpetuated across many areas of the code but isn't actually something you'd want to do.

The only caveat I can think of is for apps that are specific to.1 store, in that case maybe we should just refuse to serve if you're logged into another store. But in most cases I'd expect that the store is a mutable property of the environment and not an immutable property of the app itself.

**Comment by amcaplan** [comment]
I spoke with @pepicrft and now I understand a bit better. It seems that we have 2 ways of storing the store you're connected to:

1. Per-app/extension/etc.
2. Globally

Global state is intended for actions that don't depend on the current project, so `shopify populate` would be a good example. That state is stored in a global location, `DB`.

Per-app etc. is intended to make sure that what you're doing in your project remains constant until you change it deliberately, so it's stored in `.env` and doesn't change through a simple login. Instead, you'll need to run `shopify app connect` and along the way you'll be prompted to select a store. You get a scary warning message but it shouldn't be a problem if your app is in development; anyway the command just updates your local `.env` file.

I agree it's a confusing system, and we'll certainly take your experience into consideration as we continue to evolve the CLI. /cc @stephszeto

@seanonthenet please confirm this works for you!

**Comment by ronnycoding** [comment]
> I spoke with @pepicrft and now I understand a bit better. It seems that we have 2 ways of storing the store you're connected to:
> 
> 1. Per-app/extension/etc.
> 2. Globally
> 
> Global state is intended for actions that don't depend on the current project, so `shopify populate` would be a good example. That state is stored in a global location, `DB`.
> 
> Per-app etc. is intended to make sure that what you're doing in your project remains constant until you change it deliberately, so it's stored in `.env` and doesn't change through a simple login. Instead, you'll need to run `shopify app connect` and along the way you'll be prompted to select a store. You get a scary warning message but it shouldn't be a problem if your app is in development; anyway the command just updates your local `.env` file.
> 
> I agree it's a confusing system, and we'll certainly take your experience into consideration as we continue to evolve the CLI. /cc @stephszeto
> 
> @seanonthenet please confirm this works for you!

this works for me 
```shell
npx @shopify/cli@latest auth logout
```
