### ISSUE TITLE
[Bug]: <X An unexpected error occured.>

### ISSUE THREAD

**Issue by SamuvelRamesh** [Shopify/shopify-cli#2140]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When I try to run this comments on CMD I got this error : Let me know How can I fixed this?

### Actual behavior

C:\Users\user>shopify help
X An unexpected error occured.
        To ←]8;;https://github.com/Shopify/shopify-cli/issues/new?title=%5BBug%5
D%3A+Errno%3A%3AENOENT%3A+No+such+file+or+directory+-+break+%26%26+ruby+-e+%22pu
ts+RUBY_VERSION%22&labels=type%3Abug&template=bug_report.yaml&stack_trace=C%3A%2
FRuby27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A213%3Ain+%60spawn%27%0AC%3A%2FRuby
27-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A213%3Ain+%60popen_run%27%0AC%3A%2FRuby2
7-x64%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A101%3Ain+%60popen3%27%0AC%3A%2FRuby27-x6
4%2Flib%2Fruby%2F2.7.0%2Fopen3.rb%3A281%3Ain+%60capture3%27%0AC%3A%2FRuby27-x64%
2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fshopify-cli-2.13.0%2Fvendor%2Fdeps%2Fcli-ki
t%2Flib%2Fcli%2Fkit%2Fsystem.rb%3A199%3Ain+%60delegate_open3%27&os=x64-mingw32&c
li_version=2.13.0&ruby_version=2.7.5p203&shell←\submit an issue←]8;;←\ include t
he stack trace.

Traceback (most recent call last):
        32: from C:/Ruby27-x64/bin/shopify:23:in `<main>'
        31: from C:/Ruby27-x64/bin/shopify:23:in `load'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/s
hopify:59:in `<top (required)>'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/s
hopify:49:in `block in <top (required)>'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/bin/s
hopify:50:in `block (2 levels) in <top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/entry_point.rb:23:in `call'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/monorail.rb:30:in `log'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/entry_point.rb:24:in `block in call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/executor.rb:15:in `call'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/executor.rb:16:in `block in call'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/core/executor.rb:17:in `block (2 levels) in call'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/command.rb:32:in `call'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/command.rb:82:in `check_ruby_version'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/environment.rb:15:in `ruby_version'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/lib/s
hopify_cli/context.rb:557:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-2.13.0/vendo
r/deps/cli-kit/lib/cli/kit/system.rb:199:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory
- break && ruby -e "puts RUBY_VERSION" (Errno::ENOENT)

C:\Users\user>

### Reproduction steps

1.Windows 7  64 bit
2.ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32]
3. shopfiy help

### Operating System

Windows 7  64 bit

### CLI version (run `shopify version` if you're not sure)

New version 

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32]

**Comment by amcaplan** [comment]
Hi @SamuvelRamesh, thanks for reporting this issue. When you run `break` on the command line (which [should be a no-op](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/break)), what happens?
