### ISSUE TITLE
[Bug]: ngrok problem with shopify app serve

### ISSUE THREAD

**Issue by mdj-uk** [Shopify/shopify-cli#2141]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Running `shopify app serve` should launch an ngrok tunnel to local server. Navigating to url given in output should install app.

### Actual behavior

I run `shopify app serve` . Output seems fine:

```
✓ ngrok tunnel running at https://fe5c...big_string....ngrok.io, with account myemailaddress@gmail.com
✓ .env saved to project root
✓ Whitelist URLS updated in Partners Dashboard

⭑ To install and start using your app, open this URL in your browser:
https://fe5c...big_string....ngrok.io/auth?shop=mystorename.myshopify.com

┏━━ Running server… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 
┃ > shopify-app-node@1.0.0 dev
┃ > cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
┃ 
┃ [nodemon] 2.0.15
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching path(s): server/index.js
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node ./server/index.js`
┃ info  - Loaded env from /Users/jay/shopify_apps/new_app_1/.env
┃ event - compiled client and server successfully in 1606 ms (1222 modules)
┃ > Ready on http://localhost:8081
```

But on navigating to `https://fe5c...big_string....ngrok.io/auth?shop=mystorename.myshopify.com` in browser, I just see this:

> Not Found
> Tunnel fe5c...big_string....ngrok.io not found
> 
> ERR_NGROK_3200 

Until yesterday morning everything worked absolutely fine.

My understanding is that `shopify app serve` calls ngrok under the hood. But it looks like here that isn’t happening, or isn’t working properly.

I’ve noticed the following, but I don’t know if these observations are new, or whether it was always like this even when working properly:

1. According to my operating system (i.e. according to Activity Monitor in macOS Catalina 10.15.7) ngrok is not running. 
2. According to https://dashboard.ngrok.com/cloud-edge/status I don’t have any tunnels running.

If I run ngrok manually, e.g. with `ngrok http 8081`, then Activity Monitor and the ngrok dashboard both report that it’s running successfully.

### Reproduction steps

1. `shopify app create node -n new_app`
2. `cd new_app`
3. `shopify app serve`

### Operating System

Mac OS Catalina

### CLI version (run `shopify version` if you're not sure)

affects 2.13.0 and 2.7.4

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin19]

### What language and version are you using in your application?

node v16.14.0

**Comment by amcaplan** [comment]
Hi @mdj-uk, thanks for letting us know about your experience! It seems like the CLI is shelling out to ngrok quite directly inside the code, so I'm not sure why this issue is coming up. Might be a bug in ngrok, or some issue with your local dev environment. But you did say that running ngrok directly works, so I'm not 100% confident.

In such situations, I'd usually recommend trying `shopify app tunnel stop` then `shopify app tunnel start` and seeing what happens. Perhaps it'll fix the problem, or some more helpful error message will appear. You can also run `watch -n 0.5 'ps aux | grep ngrok | grep -v grep'` in another terminal window to see if the service is starting and stopping, or never starting at all.

**Comment by amcaplan** [comment]
Interesting. We do have [logic](https://github.com/Shopify/shopify-cli/blob/5ee313a6bcca239b3b9cb072c764ebc4ea49af23/lib/shopify_cli/process_supervision.rb#L61-L62) that checks whether ngrok is running and restarts it if needed. I tried the steps you described and the CLI was able to detect ngrok isn't running and restarted. So something is clearly different in our environments.

Unfortunately there isn't much more I can do without being able to reproduce. Are you able to get this error again reliably?

**Comment by hdas2012** [comment]
I am facing exactly same issue. This has something to do with Windows I think. Works fine on my Mac.

**Comment by joshtru** [comment]
@hdas2012 thanks for that

Incase anyone gets this error on mac after running `shopify app tunnel stop` 
`
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`
Trying the `killall -9 ngrok` won't do the job. Rather adding `sudo` before the commands does

`sudo shopify tunnel stop`
Result:
`x ngrok tunnel stopped`
then 
`shopify app serve` will work

**Comment by msrinathr** [comment]
Thanks @amcaplan your solution to stop and start the tunnel worked.
