### ISSUE TITLE
Shopify login ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by klausvennik** [Shopify/shopify-cli#2148]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Login in the browser to my shopify partner account and connects with my IDE and then can use the command to create new app in rails. 

### Actual behavior

After using the command shopify login i obtain an url to login. I put my user and password of shopify and then i see a page  http://127.0.0.1/ with: ERR_CONNECTION_REFUSED.

* I think this could be related with the url to preview in IDE Cloud9, that url always its like (https://12a34567b8cd9012345ef67abcd890e1.vfs.cloud9.us-east-2.amazonaws.com), because i saw the redirect uri to 127.0.01 inside the url after the shopify login.

### Reproduction steps

1. Configure Cloud 9 (AWS, ubuntu, rails 7, ruby 3.1) with Shopify Cli.
2. Use the command shopify login 
3. Try to login
4. You will have the 

### Operating System

Ubuntu 18.04.6 LTS

### CLI version (run `shopify version` if you're not sure)

2.14.0

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]

### What language and version are you using in your application?

Rails 7.0.2.3

**Comment by amcaplan** [comment]
Hi @klausvennik, thanks for opening this issue.

Currently we support an OAuth-based login flow where you need to be able to have the CLI launch a server and then have the flow redirect to the CLI server's URL. Unfortunately this seems to be complex to configure in cloud environments, and we actually have [another recent report](https://github.com/Shopify/shopify-cli/issues/2151) of a similar issue.

We are in the process of building support for a token-based authentication flow, which I think should be sufficient to support these environments. We'll of course announce when this feature is released. Unfortunately, until then, I don't think we'll be able to make the current system work easily for a cloud-based IDE.

**Comment by valorloff** [comment]
thanks for the clarifications
