### ISSUE TITLE
Login from Linux Terminal

### ISSUE THREAD

**Issue by valorloff** [Shopify/shopify-cli#2151]
Hi!
## Expected behavior
I really want to use the Cloud Ide for developing/ support Shopify App and login to Shopify store from terminal
## Actual behavior
but shopify login need user graphic browser window for authorization, based on 127.0.0.1:3456
# Issue summary
Cloud Shell IDE have terminal window and web-preview with host like https://3456-cs-71844-default.cs-west4-bhnf.cloudshell.dev/. 
1. I tried replace 127.0.0.1:3456 in long oauth link by web-preview host -  it didn't work by reason "redirect_uri mismatch".
2. I unsuccessfully tried setup elinks terminal browser with JS support. It don't understand all JS from shopify login(choose account) window 

Has anyone already encountered this task?

## Specifications
- App type: Public/ Embedd/ NextJS/ Express
- Operating System: Debian
- Shell: Google Cloud Shell
- NodeJs: 12>

**Comment by amcaplan** [comment]
Hi @valorloff, thanks for opening this issue.

Currently we support an OAuth-based login flow where you need to be able to have the CLI launch a server and then have the flow redirect to the CLI server's URL. Unfortunately this seems to be complex to configure in cloud environments, and we actually have [another recent report](https://github.com/Shopify/shopify-cli/issues/2148) of a similar issue.

We are in the process of building support for a token-based authentication flow, which I think should be sufficient to support these environments. We'll of course announce when this feature is released. Unfortunately, until then, I don't think we'll be able to make the current system work easily for a cloud-based IDE.

**Comment by coreytbacon** [comment]
Hey @amcaplan,
I was just wondering if there had been any update on this being released? 
I am looking to setup Bitbucket pipelines to handle theme deployment for our partners accounts. With the browser based login, this is not currently possible. 

Thanks :)
Corey

**Comment by Alonski** [comment]
@amcaplan Can you please give an update on this?
I am in the same boat :(

**Comment by jbwyme** [comment]
bump

**Comment by amcaplan** [comment]
@coreytbacon, have you had a look at CLI 3 for themes, which supports CI/CD pipelines? See [this doc](https://shopify.dev/themes/tools/cli/ci-cd).
