### ISSUE TITLE
[Bug]: Can't add app extension storefront locale without schema locale

### ISSUE THREAD

**Issue by mklopets** [Shopify/shopify-cli#2156]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

App extensions should support storefront locale files even when you don't have a schema locale file.

### Actual behavior

You can only add an app extension storefront locale file if you also have a schema locale file.

Pushing an extension update when adding just a storefront locale file (and no schema locale file) errors with the message:
```
Extension must have only one default schema locale file
```

Adding a schema locale file alongside it (`en.default.schema.json`) satisfies the validator and finishes the push operation.

(by the way: the docs [here](https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework#file-structure) mistakenly suggest that the file name for schema locales should be `en.schema.default.json` while it seems like it actually needs to be `en.default.schema.json`)

### Reproduction steps

1. With nothing else under `locales`, create a valid (default) locale file for an app extension, e.g. `locales/en.default.json`:
2. Run `shopify extension push`

### Operating System

macOS Monterey

### CLI version (run `shopify version` if you're not sure)

2.14.0

**Comment by huycuongdao** [comment]
> any workarounds in nodejs? I cannot add localization to my theme-app-extension. en.default.schema.json does not work too.
I work around this bug by adding 2 files `en.default.json` and `en.default.schema.json` with the same content. I don't know if it is the right way or not but it works for me.
![image](https://user-images.githubusercontent.com/13644506/176084026-e6f6f1aa-ec12-46bb-8ac1-172ba5b595c9.png)

**Comment by mklopets** [comment]
@umutsesen for me, adding `en.default.json` (that has actual contents) and an `en.default.schema.json` whose content is `{}` worked as a workaround
