### ISSUE TITLE
Login message typo

### ISSUE THREAD

**Issue by Rupert-com** [Shopify/shopify-cli#2159]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

other

### Expected behavior

https://shopify.dev/apps/tools/cli/core-commands#optional-parameters

use login like `shopify login --store STORE`

### Actual behavior

![image](https://user-images.githubusercontent.com/47078678/159296399-777aa011-a815-4125-a0a4-aa900eb9bf82.png)

the message is like `shopify login --store=STORE`

### Reproduction steps

```
shopify logout
shopify whoami
```

### Operating System

Windows 11

### CLI version (run `shopify version` if you're not sure)

2.14.0

**Comment by Rupert-com** [comment]
Hi @amcaplan I see that it worked else too. But using a uniform way is better because it's less irritated. If a query isn't working you get held by looking if it is `--store` or `--store=` but actually you're looking for issus in the wrong place by looking up the correct variant of the command.

**Comment by stephszeto** [comment]
Personally I prefer with the =, but curious if there's a more clearly obvious preference out there in the wild - @isaacroldan, what have you seen in your experience?

**Comment by stephszeto** [comment]
Let's go forward without spaces - @amcaplan, can we update the copy here to not include the =?
