### ISSUE TITLE
[Question] How to generate a valid SHOPIFY_CLI_AUTH_TOKEN

### ISSUE THREAD

**Issue by qw-in** [Shopify/shopify-cli#2163]
# Issue summary

I would like to use a github action to automate running `shopify extension push` for a theme app extension. However it is not clear how to generate the `SHOPIFY_CLI_AUTH_TOKEN` referenced in [the official action](https://github.com/Shopify/shopify-cli-action). It appears to be used here in the code https://github.com/Shopify/shopify-cli/blob/c0c6a8eec8c3c9257d7650f9a6b8bf915c3b2e64/lib/shopify_cli/identity_auth.rb#L72-L77

I have tried using a valid Shopify Partners token (from `https://partners.shopify.com/<id>/settings/partner_api_clients`) but no success

**Comment by stephszeto** [comment]
Hi Quinn! That feature is actually still in closed beta for now - we're just about to release it. If you fill out your info in [this form](https://forms.gle/Cg26edAMDkW5Mk1B9), I can get you added so you can take a sneak peek.
