### ISSUE TITLE
ShopifyCLI::IdentityAuth::Error: Invalid 'subject_token' value: invalid

### ISSUE THREAD

**Issue by liu0418sky** [Shopify/shopify-cli#2164]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.10.0/lib/shopify_cli/identity_auth.rb:244:in `post_request'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.10.0/lib/shopify_cli/identity_auth.rb:225:in `post_token_request'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.10.0/lib/shopify_cli/identity_auth.rb:219:in `request_exchange_token'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.10.0/lib/shopify_cli/identity_auth.rb:198:in `block in request_exchange_tokens'
/Library/Ruby/Gems/2.6.0/gems/shopify-cli-2.10.0/lib/shopify_cli/identity_auth.rb:197:in `each'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by amcaplan** [comment]
Hi @liu0418sky, thanks for opening an issue! Unfortunately I don't have much context, and I also see you're using CLI version 2.10.0.

Can you please try updating to the current CLI version [![Gem Version](https://badge.fury.io/rb/shopify-cli.svg)](https://badge.fury.io/rb/shopify-cli) and seeing if it solves your problem?

If that doesn't do the trick, it would be great to hear more about your use case and what you were trying to do.
