### ISSUE TITLE
.shopifyignore does not affect extensions

### ISSUE THREAD

**Issue by fandy** [Shopify/shopify-cli#2171]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

.shopifyignore should ignore files 
```
assets/product-reviews.tsx
**/*.tsx
```

### Actual behavior

Not ignoring files. I looked into the source of shopify-cli and couldn't find ignore logic.

```
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.01s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ Invalid filename: assets/product-reviews.tsx; .tsx is not supported
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
➜  theme-app-extension git:(main) ✗ 
```

### Reproduction steps

1. Create a .shopifyignore in the root dir of your `theme-app-extension` folder.
2. Add an ignore path like above
3. Push extension

### Operating System

12.2.1 (21D62)

### CLI version (run `shopify version` if you're not sure)

2.11.2

**Comment by amcaplan** [comment]
Hi @fandy, thanks for submitting this issue.

I'm curious where you got the impression that `.shopifyignore` is supported for extensions. It is [supported for themes](https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli) but I'm not aware of anywhere it's claimed to be supported for extensions.

By the way, the latest CLI version is 2.15.0 but you seem to be using 2.11.2. I don't think it should affect your issue, but we do request as a rule that users should test on the latest version to ensure that a bugfix hasn't already been issued.

**Comment by fandy** [comment]
> I'm curious where you got the impression that .shopifyignore is supported for extensions. It is [supported for themes](https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli) but I'm not aware of anywhere it's claimed to be supported for extensions.

Ah I see, I assumed it would be similar since `.shopifyignore` seemed like a common solution for both app and theme dev. I'm developing an extension, but find it hard to compile `.ts` or `.scss` files to the Shopify accepted filetypes (in the same folders, to keep them organized).

Is there a recommended solution you're aware of, or would I have to have the source of the files be outside the shopify root dir?

> we do request as a rule that users should test on the latest version to ensure that a bugfix hasn't already been issued.

It's happening on the latest too.

**Comment by daviareias** [comment]
Any solution for this? Developing extensions is currently complicated, because you have to create a bunch of separate folders to compile TS and CSS for production

**Comment by kubicle** [comment]
@amcaplan "I'm curious where you got the impression that .shopifyignore is supported for extensions."
Such a nice and coherent addition it would be however! :)
I am working on MacOS; each time my machine creates .DS_Store files into the asset folder I have to delete these. Of course I can add an "rm" command to delete these in my build command, but this is the perfect use case for ".shopifyignore" (just like .gitignore, etc.)

**Comment by amcaplan** [comment]
@kubicle this is a great point, and I've fixed here: https://github.com/Shopify/cli/pull/1640

No need to define a `.shopifyignore`, just generic ignore-system-files functionality. Hopefully this helps!

Should be available in the next prerelease and minor release versions.

**Comment by teckim** [comment]
> Any solution for this? Developing extensions is currently complicated, because you have to create a bunch of separate folders to compile TS and CSS for production

Same issue here, trying to create a React app for my extension and then use the build output in liquid and ignore React app source, but I cannot find a way to do so.

Any luck @daviareias?
