### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by thiscodes4u** [Shopify/shopify-cli#2186]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

After installing the latest `2.15.2` the expected behavior should result in the local version of the site rendering properly. 

### Actual behavior

Getting:

Internal Server Error
Is a directory @ io_fillbuf - fd:19 node_modules/libphonenumber-js/exports/examples.mobile.json
WEBrick/1.7.0 (Ruby/3.1.1/2022-02-18) at 127.0.0.1:9292****

### Reproduction steps

1. Install to latest
2. Run command `shopify theme serve`
3. Error on screen

### Operating System

Mac OS Monterrey

### CLI version (run `shopify version` if you're not sure)

2.15.2

### Shell

iTerm2 

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by thiscodes4u** [comment]
I'm going to investigate if this is something on my end first. Weird that this wasn't an issue until I updated.

**Comment by thiscodes4u** [comment]
Checked all dependencies and everything looks good on that front. Is anyone else having this issue with the latest version?

**Comment by thiscodes4u** [comment]
I had to uninstall my homebrew installed version of the shopify-cli @ version `2.15.2` and instead installed the gem version @ version `2.15.1` and it's working just fine for me now.

**Comment by amcaplan** [comment]
[Bugsnag](https://app.bugsnag.com/shopify/shopify-cli/errors/61f4f693044f70000ae077e6?filters[event.since]=30d&filters[error.status]=open&filters[search]=is%20a%20directory) for the full stack trace
