### ISSUE TITLE
Add POS UI Extension into Shopify Cli

### ISSUE THREAD

**Issue by samiulmonir06** [Shopify/shopify-cli#2195]
### What type of project(s) will this request affect?

extension

### What type of change do you want to see?

Substantial change to existing feature

### Overview

We want to have `point_of_sale` surface area available along with `checkout` and `admin`. 

### Motivation

We are building a retail ui library which third party developer will be available to install via shopify-cli. Running `shopify extension create` will then provide four options (checkout, post-checkout, subscription-management, and retail pos ui extension).

**Comment by stephszeto** [comment]
Few follow-up questions: 
- Was this only added to the existing 2.0 CLI? 
- If you use the `--type` parameter for the `extension create` command, what's the term that you'd use to generate a POS extension? `retail-pos-ui-extension`? If so, is there a way to make that pithier (e.g. `pos-ui`)?  
- Is this being made available to everyone or is this being gated somehow to a beta audience?

**Comment by stephszeto** [comment]
@samiulmonir06 - can you remind me again if you plan on having this added to the CLI 3.0 launching at June Edition and whether your team was planning on handling the port over or whether you wanted our team to handle it?

**Comment by samiulmonir06** [comment]
Hi @stephszeto: Yes, We are planning to add this into 3.0 launch (June Edition). We are hoping to complete our end to end test by next week. And, also we definitely need help to port it into the next edition. Please let me know if we can be any help to smooth the process.

**Comment by stephszeto** [comment]
When we port it over, will access to the extension type need to be gated somehow? 

Also - when you dev / serve your extension, what should that experience look like? We show the preview URL and then they click on it, land on the app page and access the QR Code via the Dev Console?

**Comment by samiulmonir06** [comment]
@stephszeto : Hey, I apologize for replying back so late. It's been crazy ween. 

This will be hidden under a beta flag `POS UI Extensions`. is this what you mean by gated or it's a completely different process? For the landing experience, when they serve, from the dev-console, they will have a QR code which will open the POS app and an `argo` tile will be render at the end of the SmartGrid. We will not have any web url. It will be focusing on mobile platforms. Please let me know if that makes sense. If not, I can schedule something for us to discuss.
