### ISSUE TITLE
[Bug]: "System call failed: npm run dev" when Shopify app serve

### ISSUE THREAD

**Issue by cnscorpions** [Shopify/shopify-cli#2201]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

1. cd my_test_app_01
2. run `Shopify app serve`
3. server is running well

### Actual behavior

1. run `Shopify app serve`
2. throw an error, ` X System call failed: npm run dev`

I use **nvm-for-windows** to manage node and npm versions, and doubt whether it breaks cli tool.

### Stack trace

```shell
PS F:\shopify-dev\my_test_app_01> shopify app serve
√ ngrok tunnel running at https://d84d-115-194-41-203.ngrok.io, with account Gavin Chan
√ .env saved to project root
? Do you want to update your application url? (You chose: yes)
√ Whitelist URLS updated in Partners Dashboard

* To install and start using your app, open this URL in your browser:
https://d84d-115-194-41-203.ngrok.io/auth?shop=gavin-development-store.myshopify.com
PS F:\shopify-dev\my_test_app_01> shopify app serve
√ ngrok tunnel running at https://d84d-115-194-41-203.ngrok.io, with account Gavin Chan
√ .env saved to project root
√ Whitelist URLS updated in Partners Dashboard

* To install and start using your app, open this URL in your browser:
https://d84d-115-194-41-203.ngrok.io/auth?shop=gavin-development-store.myshopify.com

┏━━ Running server… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 'npm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
┃ ���������ļ���
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.03s) ━━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ X System call failed: npm run dev
```

### Reproduction steps

In win10 pro,
1, cd project directory
2. run `Shopify app serve`

### Operating System

Win10 Pro

### CLI version (run `shopify version` if you're not sure)

2.15.2

### Shell

powershell with Windows Terminal

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]

### What language and version are you using in your application?

Node v16.14.0, Npm 8.3.1, Nvm 1.1.9

**Comment by MarcoDo99** [comment]
I run into the same issue. (Using macOs)
Have you found a solution?

**Comment by middlefive** [comment]
This worked for me on macOS:

1. npm cache clear --force
2. Delete node_modules and package-lock.json in your Shopify project files
3. npm install

**Comment by kali-kb** [comment]
I struggled with this error for hours just to find out that npm hasn't installed all the required packages successfully, it worked for me once I have uninstalled and reinstalled all the packages.
