### ISSUE TITLE
[Feature]: Support shopify extension serve for theme app extensions

### ISSUE THREAD

**Issue by staadecker** [Shopify/shopify-cli#2202]
### What type of project(s) will this request affect?

extension

### What type of change do you want to see?

New feature

### Overview

It would be amazing if there were support for `shopify extension serve` for theme app extensions.

### Motivation

Currently, the workflow when developing theme app extensions is to run `shopify extension push` and then refresh your browser page multiple times until the new theme app extensions is loaded (sometimes this takes several minutes). This makes testing changes incredibly painful and slow.

**Comment by Nikita240** [comment]
It's indeed absolutely awful at the moment. +1 this change is needed, or at least some way to bust the CDN cache when a push is performed.

**Comment by staadecker** [comment]
Afaik this is still relevant although I haven't checked super recently

**Comment by staadecker** [comment]
Afaik this is still relevant although I haven't checked super recently
