### ISSUE TITLE
[Bug]: NoMethodError: undefined method `shop' for nil:NilClass

### ISSUE THREAD

**Issue by dmaisano** [Shopify/shopify-cli#2206]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I installed a fresh copy of ruby in my wsl2 instance on my windows machine, along with other required deps like nodejs, npm, etc. expected the serve command to spin up a dev server for the default custom dawn theme

### Actual behavior

errors get logged to the console

### Stack trace

```shell
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:95:in `rescue in start'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:30:in `start'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
```

### Reproduction steps

1. `shopify login`
2. ` shopify login --store name_of_store`
3. `shopify theme serve` or `shopify theme serve --poll`

### Operating System

x86_64-linux-gnu

### CLI version (run `shopify version` if you're not sure)

2.15.2

### Shell

/usr/bin/fish

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

### What language and version are you using in your application?

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu], node v16.14.0, PHP 7.4.3

**Comment by dmaisano** [comment]
```shell
➜ shopify theme serve --poll > error.log
Traceback (most recent call last):
        37: from /usr/local/bin/shopify:23:in `<main>'
        36: from /usr/local/bin/shopify:23:in `load'
        35: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
        34: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
        33: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        32: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        31: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
        30: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
        29: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
        28: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        27: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
        26: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:32:in `start'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:71:in `find_or_create!'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme.rb:108:in `create'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:22:in `post'
         6: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:36:in `rest_request'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:95:in `rest_request'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:89:in `request'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
        27: from /usr/local/bin/shopify:23:in `<main>'
        26: from /usr/local/bin/shopify:23:in `load'
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         6: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:30:in `start'
/var/lib/gems/2.7.0/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:95:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)
```

**Comment by dmaisano** [comment]
I noticed the 403 error in the stack trace. Seems like some kind of auth error? Not exactly sure how that could be the case since I logged in and authenticated with the shopify cli

**Comment by maxackerman** [comment]
similar issue here.

Shopify CLI installed via homebrew: Version 2.15.2
Operating system: Mac OS 12.3
Runtime: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
Shell: zsh (mac default)

Steps to replicate:
Starting with  the dawn theme via:
- `shopify theme init`
- `shopify login` is successfull and `shopify whoami` works

The Issue:
running `shopify theme serve` returns: `✗ An unexpected error occured.`

Here is the output of the stacktrace:
<details>
  <summary>Click to expand</summary>
<pre>
/usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:95:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)                                                                           
        from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:30:in `start'                                                                                                                                  
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:7:in `load'
	from /usr/local/bin/shopify:7:in `<main>'
/usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:89:in `request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:95:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:36:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:22:in `post'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme.rb:108:in `create'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:71:in `find_or_create!'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:32:in `start'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:7:in `load'
	from /usr/local/bin/shopify:7:in `<main>'

</pre>
</details>

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the late response.

In version 2.15.3 we have improved the message shown in this situation, so it should say that there's a permission error. Could you try to upgrade the CLI and try again?

Are you sure you have edit permission?

**Comment by shauns** [comment]
Going to close due to inactivity -- feel free to reach out if still an issue. Thanks!
