### ISSUE TITLE
[Bug]: Impossible to create new php app on windows wsl

### ISSUE THREAD

**Issue by alexcaselli** [Shopify/shopify-cli#2207]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

The `shopify app create php` command should create a new app without errors

### Actual behavior

In a fresh new environment on wsl (Ubuntu), after installing PHP, npm, Composer and ruby-dev when trying to create a new PHP application the installation of composer dependencies fails with error: ` Your lock file does not contain a compatible set of packages. Please run composer update.`

PHP and npm versions are visible in the image

![image](https://user-images.githubusercontent.com/38326283/161421382-e22d9b92-5744-46c8-8d92-1926c1345024.png)

### Reproduction steps

1. Install wsl on windows with Ubuntu image
2. sudo apt install php7.4-cli
3. sudo apt install npm
4. sudo apt install ruby-dev
5. php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
6. php composer-setup.php
7. sudo mv composer.phar /usr/local/bin/composer
8. php -r "unlink('composer-setup.php');"
9. sudo apt install build-essential
10. sudo gem install shopify-cli
11. shopify app create php

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.15.2

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

### What language and version are you using in your application?

PHP 7.4

**Comment by Plansol** [comment]
hi Alecaselli, 
i also had same issue, in my case i had not installed the fileinfo extension of php, could you give it a try?

**Comment by alexcaselli** [comment]
> hi Alexcaselli, i also had same issue, in my case i had not installed the fileinfo extension of php, could you give it a try?

Hello, unfortunately, it's already installed on my system

**Comment by alexcaselli** [comment]
> Hi @alexcaselli
> 
> I fixed this issue by installing:
> 
> * `php7.4-xml`
> * `php7.4-dev`
> * `php7.4-curl`
> * `php7.4-sqlite3`
> 
> (I'm on WSL v2 + Debian 11)
> 
> Hope this will help 😃

This solves the problem!! Thank you!

How did you find out? i thought I had anything I needed with the build-essentials

**Comment by antho-girard** [comment]
You're welcome!

When I ran a `composer install` I had one time errors suggesting that I was missing the `xml` & `curl` extensions
Then I had a Laravel error about the database and the command `php artisan migrate` was not working so I took my chance with the `sqlite3` extension 😄
