### ISSUE TITLE
Getting an error message when using shopify theme serve

### ISSUE THREAD

**Issue by darkbugan** [Shopify/shopify-cli#2208]
hi friends! I need help with enabling the development store in shopify.. I'm getting an error message that says " 

![image](https://user-images.githubusercontent.com/102896828/161424613-6cef214d-244f-403a-9380-476b99325167.png)

**Comment by maxackerman** [comment]
similar issue here.

Shopify CLI installed via homebrew: Version 2.15.2
Operating system: Mac OS 12.3
Runtime: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
Shell: zsh (mac default)

Steps to replicate:
Starting with  the dawn theme via:
- `shopify theme init`
- `shopify login` is successfull and `shopify whoami` works

The Issue:
running `shopify theme serve` returns: `✗ An unexpected error occured.`

Here is the output of the stacktrace:
<details>
  <summary>Click to expand</summary>
<pre>
/usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:95:in `rescue in start': undefined method `shop' for nil:NilClass (NoMethodError)                                                                           
        from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:30:in `start'                                                                                                                                  
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:7:in `load'
	from /usr/local/bin/shopify:7:in `<main>'
/usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:74:in `block in request': 403 (ShopifyCLI::API::APIRequestForbiddenError)
{"errors":"Unauthorized Access"}
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/api.rb:89:in `request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/admin_api.rb:95:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:36:in `rest_request'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme_admin_api.rb:22:in `post'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/theme.rb:108:in `create'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:37:in `ensure_exists!'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/development_theme.rb:71:in `find_or_create!'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/theme/dev_server.rb:32:in `start'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/project_types/theme/commands/serve.rb:26:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command/sub_command.rb:16:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/command.rb:27:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:16:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/monorail.rb:26:in `log'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/lib/shopify_cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:50:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:49:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.15.2/gems/shopify-cli-2.15.2/bin/shopify:59:in `<top (required)>'
	from /usr/local/bin/shopify:7:in `load'
	from /usr/local/bin/shopify:7:in `<main>'

</pre>
</details>

**Comment by dillonlara115** [comment]
Getting this as well.  Fresh install on a macbook pro
