### ISSUE TITLE
[Bug]: System call failed: unzip -u, BusyBox unzip has no -u flag

### ISSUE THREAD

**Issue by ianjosephwilson** [Shopify/shopify-cli#2213]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

ngrok.zip should download and then be unzipped without error

### Actual behavior

unzip fails because there is no -u command

```
unzip -u /home/zing/.cache/shopify/ngrok.zip
unzip: unrecognized option: u
BusyBox v1.34.1 (2022-02-02 18:21:20 UTC) multi-call binary.

Usage: unzip [-lnojpq] FILE[.zip] [FILE]... [-x FILE]... [-d DIR]

Extract FILEs from ZIP archive

	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-j	Do not restore paths
	-p	Write to stdout
	-t	Test
	-q	Quiet
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
```

### Stack trace

```shell
shopify app tunnel start 
✓ curl @ /usr/bin/curl
✓ unzip @ /usr/bin/unzip
⠋ Installing ngrok…
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ System call failed: unzip -u /home/zing/.cache/shopify/ngrok.zip
```
```


### Reproduction steps

1. install docker image
2. use shopify login to connect to shop
3. try `shopify auth tunnel auth MY_TOKEN` when following https://shopify.dev/apps/getting-started/create#step-3-start-a-local-development-server

### Operating System

alpine linux

### CLI version (run `shopify version` if you're not sure)

2.15.2

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.1p18

### What language and version are you using in your application?

NA

**Comment by ianjosephwilson** [comment]
I was able to work around this bug by going into cache directory and unzipping the file without any options to unzip.

**Comment by ianjosephwilson** [comment]
I'm using busybox because I'm running the CLI in a container mentioned by a user in #1282.  The docker container is    [zingstudios/shopify-cli](https://hub.docker.com/r/zingstudios/shopify-cli).

**Comment by HarmonyCode7** [comment]
> 

Thank you very much @ianjosephwilson this worked for me.

**Comment by ianjosephwilson** [comment]
I got it working but my conclusion after difficulties was to just not use `shopify-cli`.  Glad I could help some people though.  Not sure if this bug ever even got fixed.
