### ISSUE TITLE
[Bug]: `shopify theme serve` does not sync liquid files at all without a rebuild for latest Mac M1 laptops

### ISSUE THREAD

**Issue by harryluo91** [Shopify/shopify-cli#2239]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

After running `shopify theme serve`, any `.liquid`, `.css`, `.js` file changes under `/sections` or `/assets` should trigger either a hot reload or full page reload on the local development URL with the updated changes

### Actual behavior

- changes in `.liquid` files will not get updated at all unless exit the current process and run `shopify theme serve` again.
- changes in `.css` or `.js` files will only take effect after the page is refreshed

Notes:
- tested on the default Dawn theme
- no errors are present in the terminal:

### Reproduction steps

1. run `shopify theme serve` 
2. change any mentioned files

### Operating System

Mac OS 12.1 on Apple M1 Pro

### CLI version (run `shopify version` if you're not sure)

2.15.5

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

**Comment by VatoGamtsemlidze** [comment]
Did you find the solution yet? I'm having the same problem but on windows

**Comment by harryluo91** [comment]
> 

No, but Windows 11 works as expected for me, I can only reproduce this on my new Mac M1 pro laptop

**Comment by gonzaloriestra** [comment]
Hi! Thanks for opening this issue.

It should be fixed in version 2.15.6, could you try upgrading the CLI?

**Comment by VatoGamtsemlidze** [comment]
I've tried lots of versions. But only 2.10.4 seems to be working (perfectly) on my device.

**Comment by brenr** [comment]
Also have this issue as of October 17th, 2022. Also on an M1 Pro.

**Comment by javierecr** [comment]
I'm having this issue as well.
