### ISSUE TITLE
[Bug]: <When I use the shopify app serve the serve start to run but the app doen't load on the browser>

### ISSUE THREAD

**Issue by Julio-Cardenas** [Shopify/shopify-cli#2240]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

I followed the app create guide (https://shopify.dev/apps/tools/cli/getting-started#how-it-works) , and y expect to see the welcome page to continue the tutorial.

### Actual behavior

The page doent charge. I see a black screen and i see nothing. The ngrok connection charge correctly and any error appears.
![image](https://user-images.githubusercontent.com/60556095/162770526-d4e42b90-db95-431e-9e97-04b4d0f40230.png)
![image](https://user-images.githubusercontent.com/60556095/162770653-e525cfda-80c2-42d4-a11a-f968538d6126.png)

### Stack trace

```shell
I have see other bugs and similar error, Y have seen the tunnel.rb file to change the port number and it doesn't work. In the index.js i have change the port number and it doesn´t work. I use the flag --port = {port number} and it doen't work. I have seen if the port is already used but any other program use it. I have re-installed the ruby packages, the shopify-cli program, the ngrok program and he issue continues.
```

### Reproduction steps

1. Change the port number on the file tunnel.rb
2. Use the flag --port = {port number}.

I have restart the port before running the app serve

### Operating System

Windows 11

### CLI version (run `shopify version` if you're not sure)

2.15.5

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]

### What language and version are you using in your application?

node v : v16.14.0 , npm : v16.14.0

**Comment by gonzaloriestra** [comment]
Buenas, Julio!

Not sure if it's the same problem, but we have fixed a similar issue with `app serve` in version 2.15.6. Could you check if it works with that version?

**Comment by EpsilonOrionis** [comment]
I have this problem. Suddenldy it stopped working as in the screenshot. Can anyone help me, please?
