### ISSUE TITLE
shopify theme push ignores checkout.liquid

### ISSUE THREAD

**Issue by sarhov** [Shopify/shopify-cli#2244]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I do `shopify theme push` and then expect that all local files will be pushed into chosen theme.

### Actual behavior

It pushes everything except the `checkout.liquid` file.

### Reproduction steps

1. run `shopify theme push`
2. choose the theme to push into
3. check the updated theme.

### Operating System

mac OS monterey

### CLI version (run `shopify version` if you're not sure)

last

### Shell

zsh

**Comment by gonzaloriestra** [comment]
Hi! I'm sorry you are experiencing this issue.

Have you checked if that file could be ignored because of any rule in your [.shopifyignore ](https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli)file?

**Comment by gonzaloriestra** [comment]
Then it should be pushed as the rest of the files. But I'm not able to reproduce the issue. What version of the CLI are you using?

**Comment by sarhov** [comment]
It seems it is already fixed, I can't reproduce this issue anymore.
