### ISSUE TITLE
[Bug]: shopify extension push - very slow (several minutes)

### ISSUE THREAD

**Issue by awd** [Shopify/shopify-cli#2256]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

Running `shopify extension push` should complete quickly, within a few seconds.

### Actual behavior

Running `shopify extension push` hangs for several minutes, before sometimes completing.

### Reproduction steps

1. Use latest shopify-cli
2. `shopify extension connect` - responds quickly enough
3. `shopify extension push` - hangs for undetermined amount of time

### Operating System

Mac OS Big Sur

### CLI version (run `shopify version` if you're not sure)

2.15.6

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.7.5p203

### What language and version are you using in your application?

ruby 2.7.5p203

**Comment by gonzaloriestra** [comment]
Hi! I'm sorry you are experiencing this problem. Some questions:
- Is it the first time you are pushing it? Or was it faster at some point?
- What type of extension are you working on?
- Is it showing any kind of warning or error?
- Does it have many files or heavy assets?
- Could you share your Extension UUID (you can find it in the `.env` file)? That way I can try to find what's happening in the server logs

**Comment by awd** [comment]
Hello, it seems to be resolved now, working on a theme app extension, no error just very slow (sometimes 2minutes) to respond. Small number of files, 1 JS / 1 CSS asset.

UUID - adf37ac8-4f55-4eb4-abdf-147f836b7908

**Comment by vivekrc** [comment]
So, the JS attached in an app embed is not updating for quite a while after the "shopify extension push". Could be a caching issue. The servers sending caching pages with the old scripts attached.

**Comment by pepicrft** [comment]
👋🏼 Apologies for the inconveniences that this might have caused. Would you mind sharing the type that you are trying to push? Also, does the terminal just hang when you run the `push` command?

**Comment by mfik** [comment]
Yes, +1 here. It's the theme app extension push. In my case a liquid file with a js file. Just showing the changes after push takes a lot of time. The console doesn't hang, the push itself is a couple of seconds. Changes can take up to minutes to show

**Comment by gonzaloriestra** [comment]
In case you missed, there's a revamped CLI (3.x) that might help with this issue. You can find a migration guide here: https://shopify.dev/apps/tools/cli/migrate

**Comment by Koala-afurubayashi** [comment]
Same for CLI 3.x. The command is "npm run deploy"
Reflection after deployment is very slow. not be developed.

**Comment by shauns** [comment]
For theme app extensions you can now run `dev`. That's pretty quick and offers good hot-reloading support so should speed things up quite a bit.
