### ISSUE TITLE
[Feature]: sub command to only update your app's URL without starting the app

### ISSUE THREAD

**Issue by tolgap** [Shopify/shopify-cli#2260]
### What type of project(s) will this request affect?

app

### What type of change do you want to see?

Substantial change to existing feature

### Overview

I don't use the `npm run dev` command when developing my apps. I choose to run the app using my own task executors. The only thing that I would want is to update the ngrok tunnel URL in my Shopify app every now and then.

I would love to see a subcommand just for ensuring that ngrok is started, and updating the ngrok URL in my App partner dashboard. Something like `shopify app tunnel update`.

### Motivation

Right now, to update the ngrok URL, I have to fallback to `shopify app serve`. But the command eventually fails as I don't use `npm or yarn` to run my projects.

**Comment by stephszeto** [comment]
@tolgap - I am sort of curious though, how do you run your app with your own task executors instead and how do you connect it to your Ngrok link?
