### ISSUE TITLE
[Feature]: Shopify CLI and Continuous Integration for themes

### ISSUE THREAD

**Issue by gazjones00** [Shopify/shopify-cli#2266]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

Currently, CI is only supported for Shopify App extensions. It would be really useful to see this implementation for themes. At this moment in time, it's difficult to migrate entirely away from theme kit, which is frustrating since Shopify CLI definitely helps to streamline things from a local development perspective.

### Motivation

We're currently having to use both Theme Kit and Shopify CLI, which isn't an ideal situation on the basis we want to migrate entirely away from Shopify CLI.

**Comment by AdamDemirel** [comment]
I managed to find a workaround for this by digging through the source code. Your password gets passed down with the `shopify login --store=$SHOPIFY_STORE --password=$SHOPIFY_PASSWORD` command IF the CI=true flag is set.

See https://github.com/Shopify/shopify-cli/blob/faca41c299320ea622c21f7c7dc85ebde938347f/lib/shopify_cli/commands/login.rb#L30 and https://github.com/Shopify/shopify-cli/blob/faca41c299320ea622c21f7c7dc85ebde938347f/lib/shopify_cli/context.rb#L172

**Comment by rahulpatidar0191** [comment]
> I managed to find a workaround for this by digging through the source code. Your password gets passed down with the `shopify login --store=$SHOPIFY_STORE --password=$SHOPIFY_PASSWORD` command IF the CI=true flag is set.
> 
> See
> 
> https://github.com/Shopify/shopify-cli/blob/faca41c299320ea622c21f7c7dc85ebde938347f/lib/shopify_cli/commands/login.rb#L30
> 
> and
> https://github.com/Shopify/shopify-cli/blob/faca41c299320ea622c21f7c7dc85ebde938347f/lib/shopify_cli/context.rb#L172

Hey @AdamDemirel, where do you set the CI flag to true?
