### ISSUE TITLE
[Feature]: Shopify CLI command to check theme's existence, and get a Theme ID

### ISSUE THREAD

**Issue by AdamDemirel** [Shopify/shopify-cli#2268]
Hi, it would be quite useful to be able to check a theme's existence and get theme IDs programmatically without using `shopify theme list` and grepping it or doing string manipulation.

**Comment by gonzaloriestra** [comment]
Hi! Thanks for the suggestion. Could you elaborate a bit more about the use case?

**Comment by AdamDemirel** [comment]
Hi @gonzaloriestra the use case is that we have various npm scripts which pull/deploy to various themes, and they create a fresh preview theme if it doesn't already exist. Right now the way we are checking if it exists is via the `shopify theme list` command and grepping it, which is a bit hacky and error prone since a string can potentially match multiple store names. Ideally we'd be able to do something like `shopify theme exists {id | exact string}` which returns a boolean

**Comment by gonzaloriestra** [comment]
Thanks a lot for the explanation.

To be honest, it doesn't look like a very common use case and you have a working workaround, so I'm afraid this won't have a high priority.

However, let me ping @stephszeto for her consideration.
