### ISSUE TITLE
[Bug]: You are not authorized to edit themes (but I am....)

### ISSUE THREAD

**Issue by sebszocinski** [Shopify/shopify-cli#2271]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Allow me to edit / serve themes.

### Actual behavior

`You are not authorized to edit themes on xxxx.myshopify.com`
`Check if your user is activated, has permission to edit themes at the store, and try to re-login.`

### Reproduction steps

1. Logout of CLI AND Shopify store account AND partner account
2. Login via CLI
3. Auth successful
4. Run `shopify theme serve`
5. Error

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.15.6

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the inconvenience.

Could anybody share their details to investigate? Partners account, store, theme... You can send them to gonzalo.riestra@shopify.com if you prefer.

Also, what are the "old tricks" you mention?

**Comment by jd1310** [comment]
Same problem and I can't logout with `shopify logout `command

**Comment by algorismu** [comment]
I am encountering the same exact bug as a store owner role too!
Why owners cannot use theme operations (pull, serve, etc..) on development stores via shopify-cli?
Seems like a counter-intuitive bug in managing permissions logic.

**Comment by pepicrft** [comment]
Hi @algorismu & @sebszocinski. Could you let me know if [`2.16.1`](https://github.com/Shopify/shopify-cli/issues/2208#issuecomment-1110670801) fixes the issue for you?

**Comment by pepicrft** [comment]
👋🏼 Let's move the discussion to [this other issue](https://github.com/Shopify/shopify-cli/issues/1309) that reports the same bug. Note [this comment](https://github.com/Shopify/shopify-cli/issues/1309#issuecomment-1112351597) that summarizes the current situation and provides a workaround.
