### ISSUE TITLE
[Bug]: shopify extension push consistently fails

### ISSUE THREAD

**Issue by dmhenry** [Shopify/shopify-cli#2275]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

`shopify extension push` should complete normally

### Actual behavior

┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.3s) ━━
┏━━ Error━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ Something went wrong while running script. error Command failed with exit code 1.
┃ .
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

### Reproduction steps

1. Run `shopify extension create` normally
2. `cd` into the extension directory
3. Run `shopify extension push`, responding to prompts
4. Observe the failure (above)

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.15.6

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.0

**Comment by gonzaloriestra** [comment]
Hi! I'm sorry you are facing issues.

I'm not able to reproduce it, could you give me more details?
- What type of extension are you creating?
- Does the selected app have any other extension? 
- Is it showing a stacktrace? Could you try with `SHOPIFY_CLI_STACKTRACE=1 shopify extension push`?

**Comment by dmhenry** [comment]
Resolved as of https://github.com/Shopify/shopify-cli/pull/2274
