### ISSUE TITLE
[Bug]: Error Code ELIFECYCLE When Trying To Run The Tutorial

### ISSUE THREAD

**Issue by nemnemnemy** [Shopify/shopify-cli#2283]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

I'm trying to finish the tutorial below.
https://shopify.dev/apps/getting-started/create

"shopify app serve" should have returned a URL of ngrok.

### Actual behavior

When I run "shopify app serve", I got ELIFECYCLE error.

 

### Stack trace

```shell
✓ ngrok tunnel running at https://***.ngrok.io, with account ***
✓ .env saved to project root

 To install and start using your app, open this URL in your browser:
https://***.ngrok.io/login?shop=***.com

┏━━ Running server… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃
┃ > shopify-app-node@ dev /home/***
┃ > cross-env NODE_ENV=development nodemon server/index.js --watch ./server
┃
┃ events.js:377
┃       throw er; // Unhandled 'error' event
┃       ^
┃
┃ Error: spawn nodemon ENOENT
┃     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
┃     at onErrorNT (internal/child_process.js:469:16)
┃     at processTicksAndRejections (internal/process/task_queues.js:82:21)
┃ Emitted 'error' event on ChildProcess instance at:
┃     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
┃     at onErrorNT (internal/child_process.js:469:16)
┃     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
┃   errno: -2,
┃   code: 'ENOENT',
┃   syscall: 'spawn nodemon',
┃   path: 'nodemon',
┃   spawnargs: [ 'server/index.js', '--watch', './server' ]
┃ }
┃ npm ERR! code ELIFECYCLE
┃ npm ERR! errno 1
┃ npm ERR! shopify-app-node@ dev: `cross-env NODE_ENV=development nodemon server/index.js --watch ./server`
┃ npm ERR! Exit status 1
┃ npm ERR!
┃ npm ERR! Failed at the shopify-app-node@ dev script.
┃ npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
┃ npm WARN Local package.json exists, but node_modules missing, did you mean to install?
┃
┃ npm ERR! A complete log of this run can be found in:
┃ npm ERR!     /home/***
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.35s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ System call failed: npm run dev
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

1. Connect linux server with, ssh -i ***.pem -L 8081:localhost:8081 ***@**.**.**.**
2. Follow the tutorial https://shopify.dev/apps/getting-started/create
3. In Step 3.2, shopify app serve

### Operating System

Debian GNU/Linux 10 (buster)

### CLI version (run `shopify version` if you're not sure)

2.16.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.6p219

### What language and version are you using in your application?

See the tutorial

**Comment by gonzaloriestra** [comment]
Hi, I'm sorry you are having issues.

It looks like a problem with you npm environment, what version of Node do you have (`node -v`)?

I would try with any of the solutions provided [here](https://stackoverflow.com/questions/59766839/error-code-elifecycle-npm-err-errno-134) or [here](https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle).
