### ISSUE TITLE
[BUG] Confusing error message about unknown extension type, despite using a valid type

### ISSUE THREAD

**Issue by ecbrodie** [Shopify/shopify-cli#2293]
# Issue summary

I reproduced this weird issue while testing out pushing a Checkout Extension to `shopify-cli` against our internal servers (ie, via `shopify extension push`). Check out the below screenshot:

![image](https://user-images.githubusercontent.com/1844664/165631552-0840e57c-8660-4a0d-a66e-a16934d1b320.png)

As you can see, it is complaining about me using an invalid extension type `CHECKOUT_UI_EXTENSION`. However, that value does appear in the list. Seems like the wrong error message might have been used for another class of error.

I roughly got this error when trying to push the extension to an organization that didn't have an app that supported Checkout Extensions. Unfortunately, I had some trouble reproducing this same error message further. Regardless, I still think we have something we could dig into and improve.

## Specifications

- App type: Checkout Extension
- Operating System: Mac OS 12.3.1
- Shell: ZSH
- Ruby version (ruby -v): `3.1.0` (note that I was using the latest version of the `shopify-cli` repo on my local machine)

**Comment by jeremie-qlf** [comment]
Got similar issue in our CI today:

```
Unknown extension type THEME_APP_EXTENSION. Valid extension types include: CHECKOUT_POST_PURCHASE, CHECKOUT_UI_EXTENSION, THEME_APP_EXTENSION, and PRODUCT_SUBSCRIPTION.
```

By searching a bit we also found this comment (https://github.com/Shopify/shopify-cli/pull/1825#issuecomment-994838973) which helped us to identify that we did not configure the api key properly in the CI env variables... This is definitely confusing as hell 🤯

**Comment by shauns** [comment]
Hi both -- tidying up and going to close this one. Your issues should have been resolved since the launch of Shopify Editions -- for instance Checkout UI extensions are now available outside of any preview programs. Do follow up if still having a problem.
