### ISSUE TITLE
[Bug]: --theme-editor-sync flag not seeing new templates

### ISSUE THREAD

**Issue by lesterdefreitas** [Shopify/shopify-cli#2304]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

The `--theme-editor-sync` flag should have fetched the new template that was created in the development theme and tracked any subsequent changes made to it.

### Actual behavior

The `--theme-editor-sync` flag did not fetch the new template created in the development theme nor did it fetch any subsequent changes made to it. Instead we have to stop the theme serve, manually pull the development theme, and then re-serve the theme, after which further changes to the new template were picked up.

### Reproduction steps

1. `shopify theme serve --theme-editor-sync`
2. open development theme editor
3. create a new template within the theme
4. check terminal for `get` update from cli, it won't be there

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.16.1

### Shell

$bash

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

**Comment by tpage99** [comment]
Similar issue here where it was just pulling the previous version, but wasn't catching any updates if running `--theme-editor-sync`. 

Fixed the issues when stopped and just ran `shopify theme serve` without the flag. Seems to be inconsistent at the moment as far as catching that when trying to sync local version files.

Thought it was an issue with 2.16.0 so I upgraded to 2.16.1 and same behavior.
