### ISSUE TITLE
[Bug]: Setting `--host=0.0.0.0` on passworded store redirects incorrectly

### ISSUE THREAD

**Issue by pm-zr** [Shopify/shopify-cli#2308]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

running `shopify theme serve --host=0.0.0.0` would expose the development server on the local network. When prompted for password, this should redirect to `<host IP>:<port>/password?_fd=0`.

### Actual behavior

The redirect seems to always go to `127.0.0.1:<port>/password?_fd=0`.

This works fine when accessing the site from the device that is running the development server, but when attempting to access the dev instance from another device on the local network this redirect fails. This is a useful feature when testing mobile features, to be able to quickly access the dev instance from a separate device.

### Reproduction steps

1. Spin up a dev server connected to a passworded storefront with `shopify theme serve --host=0.0.0.0`
2. Click the link that is provided from the CLI to access the dev theme (`0.0.0.0:9292` using default port)
3. Observe password redirect is at the IP `127.0.0.1`
4. Attempt to access the development instance using `<host IP>:9292` rather than `0.0.0.0`
5. Observe the password redirect is `127.0.0.1`
6. Attempt to access the dev instance from another device on the network using `<host IP>:9292`
7. Observe same problem.

### Operating System

Mac OS montery

### CLI version (run `shopify version` if you're not sure)

2.16.1

### Shell

Zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

### What language and version are you using in your application?

NA

**Comment by pinguluk** [comment]
Yeah, I changed the port to anything else and it redirected me to initial port (9292). I had to add "/password?_fd=0" to enter the password, then it redirected me again on port 9292 and I had to change it back again to my port
