### ISSUE TITLE
[Bug]: shopify app serve error : "  import { Shopify } from "@shopify/shopify-api"; ┃ ^^^^^^^ ┃ SyntaxError: The requested module '@shopify/shopify-api' is expected to be of type CommonJS, which does not support named exports."

### ISSUE THREAD

**Issue by luke-ichpekov** [Shopify/shopify-cli#2311]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

The app should start up.

### Actual behavior

The following error is thrown after inputting shopify app serve : 
" > dev
┃ > cross-env NODE_ENV=development nodemon server/index.js --watch ./server
┃
┃ [nodemon] 2.0.15
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching path(s): server\**\*
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node server/index.js`
┃ file:///C:/Users/lukei/shopifyProjs/firstapp/server/middleware/auth.js:1
┃ import { Shopify } from "@shopify/shopify-api";
┃ ^^^^^^^
┃ SyntaxError: The requested module '@shopify/shopify-api' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
┃ For example:
┃ import pkg from '@shopify/shopify-api';
┃ const { Shopify } = pkg;
┃ at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
┃ at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
┃ at async Loader.import (internal/modules/esm/loader.js:162:24)
┃ [nodemon] app crashed - waiting for file changes before starting..."

All other steps leading up to this point should be correct, latest version of shopify installed, app created, auth tunnel is up.

### Stack trace

```shell
> dev
┃ > cross-env NODE_ENV=development nodemon server/index.js --watch ./server
┃
┃ [nodemon] 2.0.15
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching path(s): server\**\*
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node server/index.js`
┃ file:///C:/Users/lukei/shopifyProjs/firstapp/server/middleware/auth.js:1
┃ import { Shopify } from "@shopify/shopify-api";
┃ ^^^^^^^
┃ SyntaxError: The requested module '@shopify/shopify-api' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
┃ For example:
┃ import pkg from '@shopify/shopify-api';
┃ const { Shopify } = pkg;
┃ at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
┃ at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
┃ at async Loader.import (internal/modules/esm/loader.js:162:24)
┃ [nodemon] app crashed - waiting for file changes before starting...
```

### Reproduction steps

1. input Shopify app serve

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.16.1

### Shell

CMD

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Node v16.15.0

**Comment by amcaplan** [comment]
Based on [this article](https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/) and the error message itself, I suspect this workaround might suffice:

```js
import shopifyApi from "@shopify/shopify-api";
const { Shopify } = shopifyApi;
```

**Comment by amcaplan** [comment]
@luke-ichpekov, are you still experiencing this error? If not, I'd like to close the issue.
