### ISSUE TITLE
[Bug]: "shopify theme serve" shows published theme on 127.0.0.1:9292

### ISSUE THREAD

**Issue by bantros** [Shopify/shopify-cli#2315]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When running `shopify theme serve` I expect the current development theme to **always** be shown when viewing `127.0.0.1:9292`. Any other theme available on the store should never be served

### Actual behavior

Typically this has been working as expected - run the serve command, files are synced and page hot reloads whilst working on a theme. Never ran into any problems doing this before.

However today I have run into the issue of the published theme being shown when viewing `127.0.0.1:9292`.

It was quite obvious the local development theme was not being served as the default Dawn theme appeared after a refresh of the page and I am building a custom theme from scratch. Unfortunately I cannot stop this from happening and it's been around an hour now.

There are no errors with any of the theme files reported by the CLI.

I have tried the following:

- Restarting the CLI serve command
- Logging out of the CLI and back in again
- Clearing browser tab cache
- Visiting `127.0.0.1:9292` in a private tab

None of the above work. I can manually push changes to an unpublished theme as a workaround in the meantime but this defeats the whole purpose of development using the CLI

_Edit: Forgot to mention that the Theme Editor link for the development theme works fine. I can still make content changes and any file changes are also reflected_

### Reproduction steps

1. Run `shopify theme serve`
2. Visit `127.0.0.1:9292`
3. Development theme should be displayed

I'm sure this is a rare occurrence as I cannot find any other tickets where the published theme was served

### Operating System

Mac OS Big Sur 11.6.3

### CLI version (run `shopify version` if you're not sure)

2.16.1

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.6

### What language and version are you using in your application?

Liquid, CSS, JS

**Comment by nathanhartallen-ca** [comment]
I'm experiencing the exact same bug. Any update?

**Comment by Luke-Markham** [comment]
I'm experiencing this too, I'll maybe do 1-3 changes/saves & hot reloads then suddenly I'll get the currently published theme served to 9292

**Comment by Luke-Markham** [comment]
@nathanhartallen-ca In my current position we do not integrate with Github in any way. For me it has been intermittent over the last two days with no regular pattern, I just came to look at the issues now as I can't even do one change without having to stop theme serve then run it again atm.

Currently awaiting replies from my co workers if they're being affected the same way I am :(

Be interesting to see if the deletion fixes it long term / why - I wonder if it is something to do with the Id of the Theme

**Comment by nathanhartallen-ca** [comment]
@Luke-Markham That's an interesting theory on the ID. Let me know if it fixes your issue too when you delete and replace.

**Comment by heikergil** [comment]
I'm experiencing the exact same bug but for me, it happens after running some automated tests, then `shopify theme serve` starts serving the published theme, and restarting `shopy theme serve` solves the issue, however, this does not work as a solution for me. It looks to me like the automated tests make more requests than the local dev environment can handle and reverts to the published theme.

**Comment by ItsGageH** [comment]
Experiencing the same issue. Unfortunately, restarting the `serve` command does not resolve the issue. Live reload does trigger but does not show the changes. Theme Customiser is showing a broken version of the theme with some CSS files not loading,

**Comment by claykelly** [comment]
I am having the same issue with CLI 3.44.1, opened another ticket for that here: https://github.com/Shopify/cli/issues/1642
