### ISSUE TITLE
[Bug]: ArgumentError: insufficient options

### ISSUE THREAD

**Issue by hurrypot** [Shopify/shopify-cli#2327]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

it should have worked

### Actual behavior

It didn't work

### Stack trace

```shell
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:192:in `ask_interactive'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/project_types/theme/forms/select.rb:12:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/form.rb:13:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/project_types/theme/commands/publish.rb:17:in `call'
```

### Reproduction steps

1. push success
2. publish failure

### Operating System

x86_64-linux

### CLI version (run `shopify version` if you're not sure)

2.17.0

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

### What language and version are you using in your application?

Ruby 3.1.2, Node 17.9, PHP 8.1.2

**Comment by amcaplan** [comment]
Hi @hurrypot, thanks for opening an issue.

I'm guessing these lines are excluding all available themes: https://github.com/Shopify/shopify-cli/blob/f0fa2f813ddb285a4115fb84a0855cf18c88df6e/lib/project_types/theme/forms/select.rb#L16-L17

Perhaps @macournoyer could speak to why that might be happening. If it's a valid case, perhaps we can handle the error more gracefully.
