### ISSUE TITLE
[Bug]: ShopifyCLI::Tunnel::NgrokError: The account \

### ISSUE THREAD

**Issue by x-Tom** [Shopify/shopify-cli#2328]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

Shopify App Serve to work

### Actual behavior

Didnt work, unexpected error
![Capture](https://user-images.githubusercontent.com/35583347/168466605-9a4d388e-3e0b-4cda-91b6-25be31b2adb5.PNG)

### Stack trace

```shell
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/tunnel.rb:184:in `rescue in fetch_url'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/tunnel.rb:174:in `fetch_url'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/tunnel.rb:202:in `start_ngrok'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/tunnel.rb:70:in `start'
C:/Ruby31-x64/lib/ruby/3.1.0/forwardable.rb:238:in `start'
```

### Reproduction steps

1.shopify app serve
![Capture](https://user-images.githubusercontent.com/35583347/168466543-c67826fd-31e8-454e-8c52-a9fb58b2da6d.PNG)

### Operating System

Windows 10 x64-mingw-ucrt

### CLI version (run `shopify version` if you're not sure)

2.17.0

### Shell

Command Prompt

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Ruby 3.1.2, Node v16.15.0

**Comment by amcaplan** [comment]
Hi @x-Tom, please have a look at [this issue](https://github.com/Shopify/shopify-cli/issues/2014). Chances are your ngrok accounts needs email verification or some such.
