### ISSUE TITLE
[Bug]: Errno::ENOENT: No such file or directory - node

### ISSUE THREAD

**Issue by Delvify** [Shopify/shopify-cli#2351]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

node app should have created

### Actual behavior

```
$ shopify app create node
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.
```

### Stack trace

```shell
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn'
/usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/usr/lib/ruby/2.7.0/open3.rb:208:in `popen2e'
/usr/lib/ruby/2.7.0/open3.rb:390:in `capture2e'
/var/lib/gems/2.7.0/gems/shopify-cli-2.17.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:199:in `delegate_open3'
```

### Reproduction steps

1. shopify version
2.17.0
2.shopify login
✓ Initiating authentication
✓ Loading available partner organizations
Logged into store
3.shopify app create node
✗ An unexpected error occured.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

### Operating System

x86_64-linux-gnu

### CLI version (run `shopify version` if you're not sure)

2.17.0

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

### What language and version are you using in your application?

node

**Comment by alytangalin1999** [comment]
Support

**Comment by rafadpedrosa** [comment]
I've added the `SHOPIFY_CLI_STACKTRACE=1.` and It shows me the error. I had the wrong key for the `ngrok` to connect.

**Comment by sergei-sss** [comment]
After installation these versions the node was created successfully for me:

```
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
```

See https://github.com/nodesource/distributions/blob/master/README.md#debinstall
