### ISSUE TITLE
[Feature]: Allow theme push without confirmation for CI purposes

### ISSUE THREAD

**Issue by MAA-Novicell** [Shopify/shopify-cli#2365]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

Hi there, 

I was wondering if there is any possibility to skip the confirmation steps at the moment?

When I do pass this command in our CI tool, it hangs - I bet its because it hits the confirmation step
`shopify theme push -l -n`

Would it be a solution to add a optional flag like 
`shopify theme push -l -n --sk`

### Motivation

Cant deploy using Azure CI/CD tool as it hangs.

**Comment by karreiro** [comment]
Hi @MAA-Novicell, you may run `shopify theme push -l -a`. Please, let me know if that works in your context :)
