### ISSUE TITLE
[Feature]: Login/Authenticate via CLI

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/shopify-cli#2366]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Currently, running `shopify login --store=STORE.myshopify.com` will a browser during the `Initiating authentication` phase. 

It would be really nice to directly pass in email/password credentials e.g. `shopify login --store=STORE.myshopify.com --email='' --password=''`.

### Motivation

The use-case would be for CI where a github action would be able to automate store login and theme creation.

**Comment by sdepablos** [comment]
@amcaplan @Jay-Plumb taking a look to the code of this tool I realised you can actually do it:
```
shopify login --store=<store>.myshopify.com --password=<password>
```

**Comment by curiouscrusher** [comment]
Just a heads up for those who land here looking for a solution, the above has been broken for many releases. The feature was [briefly available](https://github.com/Shopify/shopify-cli/commit/9aad86c88690a86bc2325854d384921f42ab637f) and then [reverted unexpectedly](https://github.com/Shopify/shopify-cli/commit/385ba38c27bbee66fe23a98fcce7cd4fa72e81c1). If you're hoping for proper CI/CD integration we're still up a creek for the meantime..
