### ISSUE TITLE
[Bug]: Shopify theme check fails with error

### ISSUE THREAD

**Issue by Lucania001** [Shopify/shopify-cli#2367]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Theme check completes as expected

### Actual behavior

Theme check fails with error

### Stack trace

```shell
━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ /usr/local/Cellar/shopify-cli/2.18.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:197:in `check': ThemeCheck::Cli::Abort
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/theme-check-1.10.2/lib/theme_check/cli.rb:123:in `run!'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/command.rb:27:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/bin/shopify:49:in `block in <top (required)>'
┃       from /usr/local/Cellar/shopify-cli/2.18.0/gems/shopify-cli-2.18.0/bin/shopify:59:in `<top (required)>'
┃       from /usr/local/bin/shopify:8:in `load'
┃       from /usr/local/bin/shopify:8:in `<main>'
```

### Reproduction steps

1. run SHOPIFY_CLI_STACKTRACE=1 shopify theme check
2. View error

### Operating System

macOS Catalina

### CLI version (run `shopify version` if you're not sure)

2.18.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.2p20

**Comment by spccbve** [comment]
C:\theme\Dawn>shopify version
2.20.1

C:\theme\Dawn>ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]

Windows 10

`Checking SHOPIFY_CLI_STACKTRACE=1 ...
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:188:in `check': No theme files found. (ThemeCheck::Cli::Abort)
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/project_types/theme/commands/check.rb:27:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/command.rb:27:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/executor.rb:15:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/monorail.rb:26:in `log'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/bin/shopify:49:in `block in <top (required)>'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.20.1/bin/shopify:59:in `<top (required)>'
┃       from C:/Ruby31-x64/bin/shopify:32:in `load'
┃       from C:/Ruby31-x64/bin/shopify:32:in `<main>'`

**Comment by eballeste** [comment]
```terminal
╭─[devbox] as eballeste in ~/Documents/projects/shopify-theme using node v18.7.0 on (finish-home)✘✘✘
  ─(ﾉ˚Д˚)ﾉ  SHOPIFY_CLI_STACKTRACE=1 shopify theme check
Checking . ...
sections/global-footer.liquid:9: error: TranslationKeyExists: 'general.mailing_list.success' does not have a matching entry in 'locales/en.default.json'.
        <div class="footer__newsletter-message">{{ 'general.mailing_list.success' | t }}</div>
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

104 files inspected, 1 offenses detected, 1 offenses auto-correctable
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Theme check failed with error:
┃ /opt/homebrew/Cellar/shopify-cli/2.21.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:197:in `check': ThemeCheck::Cli::Abort
┃       from /opt/homebrew/Cellar/shopify-cli/2.21.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃       ...
┃       this whole stack trace is unnecessary
┃       ...
┃       ...
┃       ...
┃       ...
```
