### ISSUE TITLE
[Feature]: Create Dummy Order From CLI

### ISSUE THREAD

**Issue by justinhenricks** [Shopify/shopify-cli#2370]
### What type of project(s) will this request affect?

app

### What type of change do you want to see?

New feature

### Overview

When testing the order placed webhook it's very time consuming and annoying to have to go through the checkout with dummy payment info in order to properly test the order create webhook. It would be amazing if there is a CLI command to quickly and easily generate a dummy order.

### Motivation

Developing an application the depends on the order placed web hook.

**Comment by Elliottmeija** [comment]
This would be absolutely amazing. +1 for this feature

**Comment by Elliottmeija** [comment]
It's only inactive because shopify doesn't do anything about feature requests
