### ISSUE TITLE
[Bug]: Unable to view stores on partner account?

### ISSUE THREAD

**Issue by nbsimmons** [Shopify/shopify-cli#2380]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I should be able to see a list of stores within my Partner account.

### Actual behavior

I get the error:

```
✓ Initiating authentication
✓ Finalizing authentication
✓ Loading available partner organizations
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.
```
![Recording 2022-06-06 at 16 32 43](https://user-images.githubusercontent.com/74195121/172193785-cc7f1b4d-7c59-412b-b4d9-8bc233af5c79.gif)

I've tried logging out, clearing my browser's cookies etc.

### Reproduction steps

1. Open terminal
2. Run 'shopify login'

### Operating System

macOS 12.4

### CLI version (run `shopify version` if you're not sure)

2.18.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by mateusvahl** [comment]
Same. Already tried logout+login multiple times using password or google authenticator, but seems that the CLI is unable to detect my partner organization account.

-  I've installed via home-brew.
-  The same does not happen on `2.11.2`
-  I also tried to rollback to a previous version by using `brew install shopify-cli@2.11.2 `, but that was not valid cmd.

This is currently a blocker on our team.


### Reproduction steps

```shell
$ DEBUG=1 shopify login
$ ✓ Initiating authentication
$ ✓ Loading available partner organizations
$ It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.
$ 
$ If trying to log into a store staff account, please use shopify login --store STORE to log in.
```

### CLI version (run shopify version if you're not sure)
2.18.1

### Shell
zsh

### Ruby version
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
