### ISSUE TITLE
[Bug]: Calling depends_on :macos => :yosimite is deprecated!

### ISSUE THREAD

**Issue by TimmJensen** [Shopify/shopify-cli#2383]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

other

### Expected behavior

Running the `brew update` command should update, without _warnings_ from the **Shopify/shopify tap**.

### Actual behavior

Running the brew update command returns a warning about a depends_on-call, that is deprecated and should be reported to shopify/shopify tap.

### Stack trace

```shell
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the shopify/shopify tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/shopify/homebrew-shopify/bazel@10.rb:19
```

### Reproduction steps

1. Run the command `brew update` in your terminal on a macos-machine
2. Receives the message about the warning.

### Operating System

macOS Monterey V12.4

### CLI version (run `shopify version` if you're not sure)

2.18.0

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by amcaplan** [comment]
Hey, thanks for bringing this up! This isn't an issue with the CLI, but rather with another formula in Shopify's homebrew tap. [This issue](https://github.com/Shopify/homebrew-shopify/issues/380) exists to track it, I recommend following there if you're interested. But this shouldn't affect CLI installs in any way.

Closing as there isn't much to do on the CLI itself.

**Comment by SnoW-Wei** [comment]
you can uninstall homebrew-shopify 。 like `brew untap homebrew/shopify`
