### ISSUE TITLE
[Bug]: `pull --only` with wildcards are not pulling files

### ISSUE THREAD

**Issue by Maybach91** [Shopify/shopify-cli#2386]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Pulling me all files from Shopify Store matching the wildcard `/templates/*.json` (e.g. `page.test.json` for a new page template added in the Shopify store)

### Actual behavior

It does not pull anything new/created from the Store.   
Only explicit pulling the file is working. Like `shopify theme pull --only templates/page.test.json` is working. But `shopify theme pull --only templates/*.json`or `shopify theme pull --only templates/page*.json` is not working.

### Reproduction steps

1. Create a new file named `page.test.json` in the `templates` folder of the currently published theme in the Shopify Admin
2. Try to full the created file with a CLI command with wildcard: `shopify theme pull --only templates/*.json`
3. It says pulled successfully, but didn’t pulled  the just created `page.test.json` file.

### Operating System

macOS Montery 12.1 (21C52)

### CLI version (run `shopify version` if you're not sure)

2.18.1

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

`ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
same with the following version:  
`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]`

### What language and version are you using in your application?

Just a theme, but: Node 18.3.0

**Comment by karreiro** [comment]
Thank you for reporting this, @Maybach91. I believe you may workaround this issue by using quotes:

```
shopify theme pull --only "templates/*.json"
```

**Comment by Maybach91** [comment]
> Thank you for reporting this, @Maybach91. I believe you may workaround this issue by using quotes:
> 
> ```
> shopify theme pull --only "templates/*.json"
> ```

Wow, that works, thanks for the hint!

**Comment by Maybach91** [comment]
Still an issue, bot.

**Comment by Poitrin** [comment]
I think I was able to reproduce the issue.

Commands running in the current working directory …

* `shopify theme pull --only="templates/*.json" --path="./…"` for CLI 3,
* `shopify theme pull --only "templates/*.json"` and `shopify theme pull . --only "templates/*.json"` for CLI 2

… are working.

However, when I `mkdir` a new folder (e.g. `2386`) and execute `shopify theme pull ./2386 --only "templates/*.json"`, no file was pulled (even though UI ran without irregularities).

`shopify theme pull --path="./2386" --only="templates/*.json"` with CLI 3, and using an _absolute_ path with CLI 2, was working though.

@Maybach91 – If you pull into your current working directory, or if you use an absolute path, does the error still appear?

**Comment by Poitrin** [comment]
Some additional info before closing this issue:
* [The issue I mentioned with the _relative_ vs. _absolute_ path](https://github.com/Shopify/shopify-cli/issues/2386#issuecomment-1475851140) is not appearing in CLI3 and will not be fixed for CLI2
* [The issue with using quotes or not](https://github.com/Shopify/shopify-cli/issues/2386#issuecomment-1237834711) (e.g. `--only "templates/*.json"`) depends on the shell: `zsh` needs quotes (and returns `zsh: no matches found: templates/*.json` otherwise), whereas `bash` is fine with both variants. You can read more [in this article](https://www.bartbusschots.ie/s/2019/06/12/bash-to-zsh-file-globbing-and-no-matches-found-errors/), which also includes a solution if you want to keep using the non-quotes version in `zsh`.
