### ISSUE TITLE
[Bug]: Invalid schema: setting link_list type can only be inserted once in the settings.

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/shopify-cli#2388]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Limiting a section to one "link_list" setting seems really restrictive, what if e.g. you want a separate menu for mobile and desktop? It's only an issue with the CLI, Themekit and the Online Editor accepts this fine. 

### Actual behavior

The CLI throws an error and prevents the file being uploaded. 

09:52:35 ERROR  » update sections/layout-header.liquid:
  Invalid schema: setting link_list type can only be inserted once in the settings.
  

### Reproduction steps

1. Create a section e.g. "layout-header.liquid"
2. Give it a Schema with two or more "link_list" type settings. 
```

{% schema %}
    {
        "name": "Header",
        "class": "shopify-section-layout-header",
        "settings": [
            {
                "type": "header",
                "content": "Navigation (Desktop)"
            },
            {
                "type": "link_list",
                "id": "main_menu_link",
                "label": "Main Menu"
            },
            {
                "type": "header",
                "content": "Navigation (Mobile)"
            },
            {
                "type": "link_list",
                "id": "mobile_menu_link",
                "label": "Mobile Menu"
            }
        ]
    }
{% endschema %}
```

3. Run "shopify theme serve" and watch the file fail to upload

### Operating System

Windows 11

### CLI version (run `shopify version` if you're not sure)

2.18.1

### Shell

Git Bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.3p183

### What language and version are you using in your application?

N/A

**Comment by ceri-waterscreative** [comment]
Turns out this is an issue and limitation when "App Blocks" are present within a seciton. 
https://shopify.dev/themes/architecture/sections/app-blocks#app-blocks-and-section-settings

**Comment by MaxDesignFR** [comment]
I have the same issue with "page" attribute in schema settings. It seems "link_list" as well. It may not have been fixed after all?

**Comment by mccarthykp** [comment]
This issue should still be open. I am currently trying to create a two-menu header with the following code and receiving the same error:

```
{
"type": "link_list",
"id": "menu",
"default": "main-menu",
"label": "Menu left"
},
{
"type": "link_list",
"id": "menu_2",
"default": "main-menu",
"label": "Menu right"
},
```

**Comment by notrealdev** [comment]
same issue here

**Comment by conflictxinside** [comment]
Having the same issue here, as well.

**Comment by marcdomancie** [comment]
Same issue here

**Comment by notrealdev** [comment]
I created a new issue here [1965](https://github.com/Shopify/cli/issues/1965)
