### ISSUE TITLE
💡Add new `theme update` command

### ISSUE THREAD

**Issue by karreiro** [Shopify/shopify-cli#2397]

**Comment by lesterdefreitas** [comment]
Interesting, what's the idea here? Pull the latest version of the theme code from Shopify theme store? 🤔

**Comment by karreiro** [comment]
Hey @lesterdefreitas,

Yes, that's the idea. But we still need to explore how that fits into developers' workflows and polish some corner cases.

Please, feel free to leave your thoughts and comments about that :)

**Comment by karreiro** [comment]
@lesterdefreitas, actually, this command would mimic the update button the theme library.

But, this idea of using other themes as a reference than just Dawn is pretty interesting as well :) when you say any theme, do you mean any GitHub repository or any theme in the theme library?

**Comment by karreiro** [comment]
That's right! Thank you for the clarification, @lesterdefreitas!

**Comment by lesterdefreitas** [comment]
@karreiro this is awesome. Thank you so much for everything you are doing to improve the cli for themes. 👏🏻
