### ISSUE TITLE
[Enhancement]: <A link to session storage is broken>

### ISSUE THREAD

**Issue by haxn3x9** [Shopify/shopify-cli#2431]
### What type of project(s) will this request affect?

app

### Overview

I was configuring CLI 3, I was trying to setup sessionStroage with mysql using Readme, but there was a [link](https://github.com/Shopify/shopify-api-node/tree/main/src/auth/session/storage) attached for session storage which is broken.

### Motivation

I was facing problem with connection of session storage. I couldn't find any documents for connection with mysql/mongodb.

**Comment by amcaplan** [comment]
Hi @haxn3x9, thanks for getting in touch!

I know it's a bit confusing, but CLI 3.0 is in a different repository: https://github.com/Shopify/cli so if it's specifically related to CLI 3.0, then I recommend closing this issue and opening an issue there.

I'm a bit hazy on the details of what you were looking at. What README are you referring to? Where does this link appear? If I have a bit more context, I can try and correct it.

**Comment by haxn3x9** [comment]
Hi @amcaplan , Issue is not with cli 3.0, Issue is with nodejs template cli 3 uses. Link attached in that readme is broken.

**Comment by amcaplan** [comment]
I suspect it was a repo that was formerly private. I just tried, and the link works now.
