### ISSUE TITLE
[Bug]: shopify --theme-serve "Keep the remote version" deletes files on new development theme

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/shopify-cli#2433]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When doing "shopify theme serve" anew (No development theme uploaded yet) it says that all .json files are out of sync. "is different from the remote version in the development theme", choosing "Keep the remote version" actually results in all of your .json files being deleted! 

It shouldn't say any files are out of sync because they don't yet exist on the development theme.. 

### Actual behavior

All of my .json files were deleted

### Reproduction steps

1. Login to a Shopify Store. (shopify login --store [store-a.myshopify.com](http://store-a.myshopify.com/))
2. Login to a different Shopify Store ((shopify login --store [store-b.myshopify.com](http://store-b.myshopify.com/)))
3. Run "shopify theme serve --theme-editor-sync"
4. Wait for message "xx is different from the remote version in the development theme"
5. Choose number 1 (Keep the remote version)
6. Watch as all of your .json files get deleted! 

### Operating System

Windows 11

### CLI version (run `shopify version` if you're not sure)

2.19.0

### Shell

Git Bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.3p183

### What language and version are you using in your application?

N/A

**Comment by vfonic** [comment]
I've encountered this issue several times. For both new development theme as well as existing one (but I logged in/out of a different Partner organization).

This is a huge issue. Shopify CLI should _never_ delete local files. I have `email_templates` directory locally and it's constantly getting deleted...but that's a separate issue.

This issue with fantom conflicting or non-existing files is a bug and the given options are confusing and at this point I'm just guessing which option I can choose to cause the least amount of work, reverting back to how everything was before I was offered the list of possible solutions to proceed...

**Comment by vfonic** [comment]
Possible duplicate: https://github.com/Shopify/shopify-cli/issues/2424

**Comment by mikez93** [comment]
I have the same issue.

**Comment by mikez93** [comment]
Same issue.

**Comment by vfonic** [comment]
Can someone please have a look at this issue?

I'm working on several stores and one of them is an old theme with lots of files and it takes almost 2 minutes to completely start `shopify theme serve` and sync all the files, with **no file changes** between live theme and local development theme.

2 minutes is an eternity and is annoying to have to do this every time I switch store with `shopify login ...`

**Comment by karreiro** [comment]
Thank you for reporting and sharing those, @vfonic. They help us towards a proper fix for this issue.

The initial decision of keeping the remote or the local version just **impacts the setup of the development theme** (which happens when the progress bar is loading) - the other 2-way sync features of `shopify theme serve` are not affected by this initial decision.

As a temporary workaround, when you run `shopify theme serve`, if your development theme doesn't exist (due to a re-login), you may select the option to keep your local files. Then, the development theme will be created using your local files as the reference, and nothing will be deleted.

But, as I mentioned, that's a temporary workaround, and the team is already working on a proper fix for this issue.
