### ISSUE TITLE
"No Organization found", cannot run commands after logging in

### ISSUE THREAD

**Issue by CraigTrs** [Shopify/shopify-cli#2436]
I have been given the opportunity to learn Shopify at my workplace, so this is new to me however I'm running into a problem out the gates.

After installing the latest version of the CLI, being set up on their partner dashboard and creating a dev store, then creating a staff account on my development store, I've ran:
`shopify login --store=store-name`

This has logged me in, however I can't run any commands as it is not detecting an organisation. Other devs at my workplace have done the same thing to my test store and got in fine. 

There error is shown below:
`Logged into store storename.myshopify.com as staff (no partner organizations available for this login)`

## Expected behavior

I should be able to choose the organisation and start developing my app.

## Actual behavior

I receive this error: 

    No Organization found

    Stack trace:
    at NoOrgError                 …/node_modules/@shopify/app/src/cli/services/dev/fetch.ts:23  
    at fetchOrganizations         …/node_modules/@shopify/app/src/cli/services/dev/fetch.ts:59  
    at processTicksAndRejection…  node:internal/process/task_queues:96                          
    at selectOrg                  …de_modules/@shopify/app/src/cli/services/environment.ts:324  
    at ensureDevEnvironment       …ode_modules/@shopify/app/src/cli/services/environment.ts:87  
    at dev                        …nt-trs/node_modules/@shopify/app/src/cli/services/dev.ts:49  
    at run   

## Steps to reproduce the problem

1. Create store
2. Create staff account
3. Log in on CLI to staff account / or partner account. Both do the same.

## Specifications

- App type: Node
- Operating System: OSX
- Shell: ZSH
- Ruby version (ruby -v): ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

**Comment by amcaplan** [comment]
Hi @CraigTrs, it seems you've installed 2 different CLIs:

* `shopify login` is Ruby-based CLI 2.0, represented by this repository, which was our primary CLI until just a couple of weeks ago.
* From your stack trace, I that when it comes time to develop, you're running Node-based CLI 3.0 when trying to `dev` the app. In CLI 3.0, you run things as part of your dependency manager, e.g. `npm run shopify version`

The 2 CLIs aren't intended to work together and aren't sharing information. In fact, they work quite differently, as 2.0 is global while 3.0 is managed as a direct dependency of your project. They also store information like login credentials in different places on your system.

You can read more [about CLI 3.0](https://shopify.dev/apps/tools/cli) but for your purposes I'll say it sounds like you're using 3.0 in your app, so if that's the case, you should uninstall the Ruby CLI and just work with CLI 3.0.

CLI 3.0 should prompt you to log in when it needs credentials (e.g. to `dev` your app), so if it's failing to do so, I'd recommend opening a new issue on the CLI 3.0 repository.

Hopefully this is enough information to solve your problem, so I'm closing this issue. If you continue to face surprising bugs:

* If you verify you're on a 3.0 app, [open an issue here](https://github.com/Shopify/cli/issues/new/choose).
* If you're on a 2.0 app, you can [open another issue](https://github.com/Shopify/shopify-cli/issues/new/choose) with more details.

**Comment by amcaplan** [comment]
Hi @CraigTrs, quick update. I mentioned your issue to a colleague, who noted that you seem to be logging in using a store staff account without access to a partner organization. You need to invite the account to the partners organization too, or else you'll continue to receive this error.

**Comment by alanrodriguezdotme** [comment]
I'm seeing a similar problem when I first run `npm run dev` after creating an app. I get the prompt to click any key to login, which I do with my partner account, then I get this error:

```
No Organization found

    What to try:
    · Have you created a Shopify Partners organization?
    · Have you confirmed your accounts from the emails you received?
    · Need to connect to a different App or organization? Run the command again with --reset
```

I've tried logging out and running `npm run dev --reset` but I get the same error. I've also uninstalled CLI 2.0 and restarted my machine.

**Comment by amcaplan** [comment]
Hi @alanrodriguezdotme, as above - does the logged-in account have access to a partner organization? Or is it just a store staff account?

**Comment by xyakim** [comment]
> > Hi @alanrodriguezdotme, as above - does the logged-in account have access to a partner organization? Or is it just a store staff account?
> 
> The logged in account is a partner account with a test store. No staff accounts at all.

Hi, I have the same problem, have you been fixed it?  I create an app from my store, it gives me a auth token, but i can't find where to use it.
Also, I run the command `npm run dev -- --reset`, It still tells me ` No Organization found`

**Comment by alanrodriguezdotme** [comment]
> > > Hi @alanrodriguezdotme, as above - does the logged-in account have access to a partner organization? Or is it just a store staff account?
> > 
> > 
> > The logged in account is a partner account with a test store. No staff accounts at all.
> 
> Hi, @alanrodriguezdotme I have the same problem, have you been fixed it? I create an app from my store, it gives me a auth token, but i can't find where to use it. Also, I run the command `npm run dev -- --reset`, It still tells me ` No Organization found`

I logged out, and logged in with my @shopify.com email, which I didn't think we were allowed to do. That seemed to fix it, not sure why though. Possibly because I have a store set up and running on that account, whereas my personal email does not? I'm not really sure what tit means by "organization", so I could be way off.

**Comment by cennis-ck** [comment]
> npm run dev -- --reset

WOW this is so dumb i tried all morning to reset to no avail using the command specified, not this monstrosity. thank you

**Comment by rehancse** [comment]
Just use the **Shopify auth logout** and then **npm run dev**. You will be prompted to login again with your partner account. Login and go back to your terminal your problem will be solved.
