### ISSUE TITLE
Request: Add the ability to provide your own scaffold repo

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/shopify-cli#244]
# Summary
The [shopify-app-node](https://github.com/Shopify/shopify-app-node) is a great starting point but for regular app building having an extended version of this with extra features like a database, etc. would be a necessity.

Having the ability to pass your own repo to scaffold would be awesome.

**Comment by katiedavis** [comment]
Hey @dan-gamble thanks for the request! I'll bring it up with the team. I should note though, that we totally welcome contributions from the community. So if you create an app that you think the CLI should create, you can open a pull request to add it to the CLI as an option :)
