### ISSUE TITLE
[Bug]: shopify theme push/serve "Section type 'my-section' does not refer to an existing section file"

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/shopify-cli#2450]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

No error when deploying a functional new theme.

### Actual behavior

Since version 2.20.0 we are getting an error "Section type 'my-section' does not refer to an existing section file" when pushing a new theme or new development theme. The section definitely exists. The sections that fails seems to be changing each time.

It's not that much of an issue for the development environment as it works when we do a second `serve` but we are also using shopify cli in our CI environment to create a backup theme when we launch a deployment and the backup creation fails because of that. Forcing version 2.19.0 fixes the issue.

I'm guessing this would be related to the performance enhancements added to push and serve in version 2.20.0: https://github.com/Shopify/shopify-cli/pull/2368

### Reproduction steps

1. Delete your development theme
2. run `shopify theme serve`

### Operating System

windows 10

### CLI version (run `shopify version` if you're not sure)

2.20.0

**Comment by karreiro** [comment]
Thank you for reporting, @tommypepsi!

You don’t need to install the CLI 2.19; instead, you may continue in the latest version and rely on the `--stable` flag (`shopify theme serve --stable`/`shopify theme push --stable`).

We needed to introduce many critical changes to speed up the upload process in the CLI (which is 6x faster now). However, we were expecting some corner cases, so we’ve introduced the `--stable` flag to help during that transition.

Could you please share the **`x-requed-id`** header? (it appears when you run `shopify theme serve`) With that information, I can debug and fix the issue you're facing :) here's how to get it:

<img width="1463" alt="request_id" src="https://user-images.githubusercontent.com/1079279/178477183-b83ad1cc-ea75-4cc1-b5f9-46e42fd00f0b.png">

Thanks again for reporting it!

**Comment by jessetuglu** [comment]
Hello @tommypepsi , the latest release v2.20.1 should address the above issues. I will close this, but please feel free to reopen if you see any further issues 🙏 – thanks!
