### ISSUE TITLE
[Enhancement]: Recommendations needed for using `shopify theme serve` and Github integration

### ISSUE THREAD

**Issue by jordantomax** [Shopify/shopify-cli#2452]
### What type of project(s) will this request affect?

theme

### Overview

I use the `shopify theme serve` command to work locally when developing themes. I also use the Shopify Github integration to keep themes up to date with Github. I like the integration, because without it, there isn't an explicit connection to source control and I have sometimes forgotten to keep source control up to date.

However, this setup has one major shortcoming. Because Shopify pushes every change to Github, every time I save a file, Shopify pushes. This causes issues when I want to push my local changes to Github, namely that many or all of my changes have already been pushed, and my named commit no longer has any meaning. It's been consumed by tens or even hundreds of unnamed commits pushed automatically by Shopify. A further problem is that using Github Actions to run code on push for tools like lighthouse, as recommended by Shopify, becomes untenable with this workflow as it runs the workflow way too many times and often causes errors like "A shop may only have 100 development themes".

I'm guessing that Shopify wouldn't recommend using this setup, because if they were doing this themselves, they would no doubt be as frustrated as I am. So I'd like to ask what does Shopify suggest to get around this problem? Is there a development workflow that allows me to use the Github integration and still review changes locally?

### Motivation

As described in my outline, my issue is motivated by:
1. Conflicts when pulling new changes from Github
2. Inability to have a clean history of named commits on Github
3. Inability to use CI correctly on `push`
4. Unclear what is Shopify's recommended workflow for using the Github integration and also viewing changes locally

**Comment by explorier** [comment]
> I'm also puzzling over this issue - it seems like a major shortcoming of the plugin and is likely going to prevent me from using it, even though I'd really like a simple way to keep my client's edits to the templates in sync with the repository. Committing a change every time I make a local edit while running `shopify theme serve` make this approach dead in the water unfortunately. Are there any recommended solutions to this issue?

After writing this & during the development process of a new theme, I realized that not using the Github plugin and instead just running `shopify theme serve --theme-editor-sync` meets most of my workflow needs for the time being - any changes theme customizations made by client are pulled locally and I can commit them to the repo.

**Comment by jordantomax** [comment]
@explorier I've also found that's the most viable alternative, but it's not without problems, the most obvious being that you now have 2 unlinked workflows (Shopify and Github). Using that setup I have forgotten to push my latest code to Github. I think having a single source of truth (ideally the source code in Github) is the most correct solution. I'd love to know what Shopify thinks about this and if they have any recommendations about the correct usage cc @karreiro.

**Comment by karreiro** [comment]
👋 Hey folks,

The post is ready, but after we read it, we notice it would be better to leave that content in a more permanent place (instead of documentation or the blog post). We're working in that place.

Still, I'm sharing the draft of the post here, so you may access that content:
https://gist.github.com/karreiro/9a887fe9861ff1d247820a99924c6b7a

Feel free to leave feedback there as Gist comments -- I'd really appreciate that :)

Thank you.
