### ISSUE TITLE
[Bug]: `--ignore` flag doesn't do anything

### ISSUE THREAD

**Issue by diegovogel** [Shopify/shopify-cli#2454]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When I run `shopify theme push --ignore config/settings_data.json` it should push everything except `settings_data.json`.

### Actual behavior

It pushes everything including `settings_data.json`.

### Reproduction steps

1. Use Shopify CLI to `pull` a theme.
2. In the Shopify dashboard, find the theme you just pulled _from_ (not your dev theme), click Customize and update some content.
3. Go back to Shopify CLI, run `shopify theme push --ignore config/settings_data.json`, select the theme from step 2. The content you just updated will be overwritten by whatever is in your local copy of `settings_data.json`.

I have tried `--ignore config/settings_data.json` with and without quotations and it makes no difference.

### Operating System

macOS Monterey v12.4

### CLI version (run `shopify version` if you're not sure)

2.20.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

**Comment by zhixiangyao** [comment]
I have the same problem🥹

Operating System
macOS Monterey v12.4

CLI version (run shopify version if you're not sure)
2.20.0

Shell
zsh

Ruby version (run ruby -v if you're not sure)
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

**Comment by zhixiangyao** [comment]
I have a temporary solution to downgrade `shopify-cli` version (2.19.0).
Copy the contents of this [link](https://raw.githubusercontent.com/Shopify/homebrew-shopify/eefed22d3fb4f8a1a3d071baef6fa83f131d4373/shopify-cli.rb) into `shopify-cli.rb` and then:

```shell
# You must uninstall it first
brew uninstall shopify-cli
brew install ./Desktop/shopify-cli.rb
```

**Comment by diegovogel** [comment]
Thanks @zhixiangyao. Good to know that downgrading resolves the problem. That seems to indicate it's a CLI issue. 

This issue led me down the path of finding a better deployment workflow. I ended up writing a script that pulls live content, commits it to the repo as a backup, then pushes everything live. In my case this solves a number of other issues as well and the whole process is a lot more streamlined. It used to take a handful of terminal commands and some manual work to deploy theme updates, now it's a single command. So I guess there's a silver lining.

**Comment by diegovogel** [comment]
Thanks @jessetuglu
