### ISSUE TITLE
[Enhancement]: please separate content (`settings_data.json`) from code

### ISSUE THREAD

**Issue by diegovogel** [Shopify/shopify-cli#2455]
### What type of project(s) will this request affect?

theme

### Overview

This issue is probably bigger than the CLI. If there's somewhere else this should be posted I'd be happy to do so. I'll speak with anyone who will listen. 😅 

A lot of page content is stored in the theme via `settings_data.json`. This is a problem for a number of reasons.

- It's very easy to overwrite content without knowing it. Example: a dev pulls a theme to work on it, meanwhile the store owner updates some content, the dev finishes his work and pushes, the updated content reverts back to what it was before.
- If a dev is frequently working on a theme, it's annoying to have to pull the theme just in case someone changed something.
- If a theme is used on multiple stores with different content, deploying code updates is kind of a nightmare.

I know there is the `--ignore` flag for the `push` command, but that's not very robust. I just discovered that this flag mysteriously stopped working for me a while back. There was no warning and I have no way of knowing when it stopped, so I don't even know what content is now outdated without combing through the site.

Maybe I'm missing something, and if someone can explain why things were set up this way that would be great. But it just seems like separating content from code would solve a lot of problems here.

### Motivation

- It's very easy to overwrite content without knowing it. Example: a dev pulls a theme to work on it, meanwhile the store owner updates some content, the dev finishes his work and pushes, the updated content reverts back to what it was before.
- If a dev is frequently working on a theme, it's annoying to have to pull the theme just in case someone changed something.
- If a theme is used on multiple stores with different content, deploying code updates is kind of a nightmare.

I know there is the `--ignore` flag for the `push` command, but that's not very robust. I just discovered that this flag mysteriously stopped working for me a while back. There was no warning and I have no way of knowing when it stopped, so I don't even know what content is now outdated without combing through the site.

**Comment by diegovogel** [comment]
Just want to add that overall I love Shopify CLI. It's a huge improvement over Slate / Theme Kit. And in my experience as a developer in the Shopify ecosystem has been generally delightful. But this `settings_data.json` thing and the problems it causes are ruining Shopify's otherwise excellent DX for me.

**Comment by karreiro** [comment]
Thank you for all the details you've provided, @diegovogel.

I believe this feature is related to this: https://github.com/Shopify/slate/issues/749. Also, I'm reopening this issue so we don't lose track of it. Still, I don't think it's something at the CLI level.

I'll get feedback from other folks, and as soon as I have an update about this, I will leave a comment here.

Thanks again for raising this topic! :)

**Comment by karreiro** [comment]
Hi @diegovogel. You've posted the feature request in the correct place :) as it relates to themes DX and tools.

Thanks again for raising this :)

**Comment by lesterdefreitas** [comment]
@diegovogel just to add here, the way we deal with this is to use the [Shopify x Github integration](https://shopify.dev/themes/tools/github). The integration keeps our codebase in sync with changes made to the theme. That way when we merge a dev branch back to our `main` branch (which is synced with the Shopify theme) our work can merge with updates made to the theme on Shopify. Now and then there can be conflicts to deal with, which are a pain, but at least this way we know we are not having to manually pull updates all the time.

**Comment by diegovogel** [comment]
@lesterdefreitas thanks for the tip. How do you handle the differences between the source code and live code? For example, we're using SCSS in the source code, but only the compiled CSS gets deployed. So our source code directory structure is slightly different than what gets deployed to Shopify. Because of this, we have two repos: one for source code and one for live code. We are already using the Shopify x Github integration but we have it connected to the repo for live code, and it's basically just a way to capture changes made via the Shopify editors so we can backfill to the source code more easily. Have you found a way to connect the Github integration to the source code even if the directory structure isn't exactly what gets deployed?

**Comment by lesterdefreitas** [comment]
@diegovogel oh, no, that is a more complex problem. And it is because of that, that we do not use a compilation pipeline in our development workflow. We work with the standard theme directory only.

How do you backfill changes to the live code? Manually?

**Comment by diegovogel** [comment]
@octipus thanks for the tip. Good to know Shopify will ignore the /styles directory. Is that true of any directory that's not part of the standard theme structure?

**Comment by karreiro** [comment]
I will keep the link to this thread for future reference, but I am closing this issue due to changes in `Shopify/shopify-cli`.

**Comment by diegovogel** [comment]
@karreiro thanks for the heads up. What changes are you referring to?

**Comment by diegovogel** [comment]
@karreiro sorry I'm not sure I follow. We have been using Shopify CLI 3.x for quite some time and this is still a problem. We're currently on 3.45.1. How is the sunsetting of 2.x relevant? Am I missing something?
