### ISSUE TITLE
[Bug]: could not run shopify theme serve which blocked 40%

### ISSUE THREAD

**Issue by zhangzhaohong** [Shopify/shopify-cli#2456]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Edit theme loacal

### Actual behavior

it is block in 40% and not continue.
<img width="2007" alt="image" src="https://user-images.githubusercontent.com/54138238/178644002-64f322c7-a016-477f-b3c0-3a1ea14bf714.png">

### Reproduction steps

1.
2.
3.

### Operating System

macOs 13

### CLI version (run `shopify version` if you're not sure)

2.20.0

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

**Comment by labzy88** [comment]
> I've got the same issue except I get stuck at 99%. The logout/login suggestion above doesn't work. Been happening since updating to 2.20.0

So it also is a bit hit and miss for me... I forgot to mention that you may have to try a few times, I hope it works for you until they implement a fix!

**Comment by mattsterp** [comment]
I have the same issue.  Every time there is a CLI update Shopify theme development is broken.

**Comment by adictonator** [comment]
I am facing this issue as well.  What I have noticed so far is that the files `package.json` and `package-lock.json` are causing the `shopify theme serve` to stall. When I delete these files from the root, the command works fine. But a fix would be really appreciated here.

**Comment by meltinbit** [comment]
Same here since 2.20.0 update. Command shopify theme serve get stuck at a random percentage. Logout/login does not solve the problem, neither to change store.

**Comment by lucylounge** [comment]
> 

This worked for me and now back up and running - thanks for the tip @meltinbit

**Comment by karreiro** [comment]
Hey everyone, thank you for reporting.

You don’t need to install the CLI 2.19; instead, you may continue in the latest version and rely on the `--stable` flag (`shopify theme serve --stable`/`shopify theme push --stable`).

We needed to introduce many critical changes to speed up the upload process in the CLI (which is 6x faster now). However, we were expecting some corner cases could happen, so we’ve introduced the `--stable` flag to help during that transition.

Could you please share the **`x-request-id`** header? (it appears when you run `shopify theme serve`)
With that information, I can debug and fix the issue you're facing :) here's how to get it:

<img width="1463" alt="request_id" src="https://user-images.githubusercontent.com/1079279/178477183-b83ad1cc-ea75-4cc1-b5f9-46e42fd00f0b.png">

Thanks again for reporting it.

**Comment by jessetuglu** [comment]
Hello everyone, the latest release `v2.20.1` should address the above issues. I will close this, but please feel free to reopen if you see any further issues 🙏 – thanks!
