### ISSUE TITLE
[Bug]: Stuck on theme sync (shopify theme serve)

### ISSUE THREAD

**Issue by lspoor** [Shopify/shopify-cli#2465]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

CLI to upload the theme to Shopify as a development theme

### Actual behavior

Stuck on sync at 57%

### Reproduction steps

1. Create empty folder and run `shopify theme init` to create a theme
2. Run `shopify theme serve`
3. Stuck on 57%

<img width="682" alt="Screenshot 2022-07-15 at 15 42 15" src="https://user-images.githubusercontent.com/1685176/179246798-cddc18f3-2669-451f-9fe6-1878b807e63e.png">

### Operating System

macOS Montery (M2 Chip)

### CLI version (run `shopify version` if you're not sure)

2.20.0

### Ruby version (run `ruby -v` if you're not sure)

3.0.

**Comment by noah-haub** [comment]
I have the same issue. Have you found a solution yet?

**Comment by punkstar** [comment]
@lspoor Hey, I'm running into this issue - it's only started happening recently. Out of curiosity, did you do anything to get this working again?

**Comment by lspoor** [comment]
I managed to get past this using the `--stable` flag as mentioned here https://github.com/Shopify/shopify-cli/issues/2456#issuecomment-1184473600 but now ran into this issue https://github.com/Shopify/shopify-cli/issues/2457 so the latest version of the CLI just isn't usable for me and unable to go to an earlier version.

**Comment by punkstar** [comment]
Thanks @lspoor. For anyone else reading, it was just a `package.json` in my repo that caused the issue here. Tracked this down with [`DEBUG=1`](https://github.com/Shopify/shopify-cli/blob/7bcc63802bd0597de7766573251745cd37a26af4/bin/shopify#L32) and then adding `package.json` to [`.shopifyignore`](https://shopify.dev/themes/tools/cli#excluding-files-from-shopify-cli).

**Comment by jessetuglu** [comment]
Hi @punkstar, are you on the latest version of the CLI? `v2.20.1` should fix the issue you have mentioned above.
