### ISSUE TITLE
[Bug]: config/settings_data.json overwritten on theme push (shopify-cli v2.20.0)

### ISSUE THREAD

**Issue by muriloshimizu** [Shopify/shopify-cli#2467]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When `config/settings_data.json` is added to the `.shopifyignore` file, shopify-cli should ignore that file and do not push to the theme. This actually works when using shopify-cli v2.19.0.

### Actual behavior

When using shopify-cli v2.20.0, even if the `config/settings_data.json` has been added to `.shopifyignore`, it will be overwritten on `shopify theme push` command.

Oddly enough, not everything in the `config/settings_data.json` file may be overwritten. However, I did find that some theme settings that I changed were indeed overwritten (eg: App embed settings, static sections, fonts, custom settings).

### Reproduction steps

1. Using dawn (live theme), change the heading font in theme settings
2. Make sure that `config/settings_data.json` is present on `.shopifyignore`
3. Using cli v2.20.0 `shopify theme push --theme=THEMEID -n` to push the theme (replace THEMEID with the actual theme id).
4. Check the settings_data.json and find the heading font – it should be reverted back to the previous option
5. Repeat the same steps using `shopify-cli` v2.19.0 - the new font selected should still be there (not overwritten)

### Operating System

MacOS Monterey 12.4

### CLI version (run `shopify version` if you're not sure)

2.20.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

2.6.8p205

**Comment by karreiro** [comment]
Thank you for reporting, @muriloshimizu.

This issue was resolved by [#2459](https://github.com/Shopify/shopify-cli/pull/2459), and the fix will be included in the next CLI release.
