### ISSUE TITLE
[Feature]: Official Shopify Docker Image

### ISSUE THREAD

**Issue by ademers** [Shopify/shopify-cli#2472]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

It would be useful if Shopify provided an official Docker image from which we could run the Shopify CLI in a Docker container.

### Motivation

Useful for devs who prefer not to install Homebrew or Ruby directly on macOS.

Thanks for your consideration.

**Comment by shauns** [comment]
Hi @ademers -- we're looking into how we distribute the CLI, particularly for theme developers. If you follow app development (or storefronts via Hydrogen) you may be aware a new version of the CLI has arrived (https://www.youtube.com/watch?v=8bfr5Twpfhc). For now, theme development is unchanged, but perhaps once migrated to this new platform, docker distribution may make sense.

**Comment by ademers** [comment]
HI @shauns! Thanks for the reply. So if I understand correctly, theme development will eventually be migrated to CLI 3.0? If so, where can I learn more about this via a roadmap, for example.  I'd like to know if the reference theme (Dawn, or other) will eventually ship with Tailwind CSS like Hydrogen does.

**Comment by shauns** [comment]
@ademers -- Themes are available via CLI 3.0 https://www.shopify.com/uk/partners/blog/november-2022-whats-new#:~:text=Introducing%20support%20for%20themes%20with%20the%20latest%20update%20to%20Shopify%20CLI%203.20
