### ISSUE TITLE
[Feature]: Reloading all matching CSS files on change and not just the first

### ISSUE THREAD

**Issue by we5** [Shopify/shopify-cli#2488]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

Only the first matching CSS file is being "hot-reloaded" if the local file has been changed.

### Motivation

While developing sections I realized, that referencing CSS files in sections makes the hot-reload experience a bit awkward and I found myself manually reloading the page because only the first link reference will be updated. This leads to conflicting stages.

I already changed the reloading part locally and it works without any problems.

**Comment by karreiro** [comment]
Thank you, @we5!
