### ISSUE TITLE
[Bug]: Not able to Run Shopify Command

### ISSUE THREAD

**Issue by meenakhipanigrahy** [Shopify/shopify-cli#2491]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Run Shopify

### Actual behavior

Not able to Run Shopify Command 

### Stack trace

```shell
D:/Ruby30-x64/lib/ruby/3.0.0/pstore.rb:484:in `load': dump format error(0x0) (ArgumentError)
        from D:/Ruby30-x64/lib/ruby/3.0.0/pstore.rb:484:in `load'
        from D:/Ruby30-x64/lib/ruby/3.0.0/pstore.rb:404:in `load_data'
        from D:/Ruby30-x64/lib/ruby/3.0.0/pstore.rb:330:in `transaction'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/db.rb:86:in `get'
        from D:/Ruby30-x64/lib/ruby/3.0.0/forwardable.rb:238:in `get'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/migrator.rb:28:in `last_migration_date'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli/migrator.rb:11:in `migrate'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli.rb:189:in `<module:ShopifyCLI>'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/lib/shopify_cli.rb:42:in `<top (required)>'
        from <internal:D:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:D:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:9:in `require'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/load_shopify.rb:18:in `<top (required)>'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:45:in `require_relative'
        from D:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.20.1/bin/shopify:45:in `<top (required)>'
        from D:/Ruby30-x64/bin/shopify:25:in `load'
        from D:/Ruby30-x64/bin/shopify:25:in `<main>'
```

### Reproduction steps

1. Installed Ruby
2. Install Shopify CLI
3. Run Shopify command in terminal.

### Operating System

Window 10

### CLI version (run `shopify version` if you're not sure)

2.20.1

### Shell

git bash

### Ruby version (run `ruby -v` if you're not sure)

3.0.4p208

**Comment by amcaplan** [comment]
Hi @meenakhipanigrahy, thanks for reaching out. I see this issue has been sitting for some time, so hopefully you figured this out on your own, but in case not...

The problem seems to be that your local Shopify DB file is corrupted. This isn't a big deal, as the CLI will repopulate it with any necessary information as-needed. But it'll prevent the CLI from running as long as that file exists.

You can print the location of that file with the 1-liner `ruby -r shopify_cli -e "puts ShopifyCLI::DB.new.db.path"`. Then just delete the file and you should be good to go!

Please let me know if this solves the problem for you.
