### ISSUE TITLE
[Bug]: `shopify app serve` leaves `ngrok` running when it exits

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify-cli#2517]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

After running `shopify app serve` I hit Ctl-C to stop the process. At that point I would expect the `ngrok` process to also be stopped. Currently I have to kill it by hand in order to start it for a different project.

### Actual behavior

I have an `ngrok` process still running.

### Stack trace

```shell
N/A
```

### Reproduction steps

1. `shopify app serve`
2. Ctl-C
3. See that an `ngrok` process is still running.

### Operating System

MacOS 12.3

### CLI version (run `shopify version` if you're not sure)

2.21.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.3

### What language and version are you using in your application?

Ruby 2.7.3

**Comment by isaacroldan** [comment]
Hi @jagthedrummer ! 

This is the intended behaviour of the CLI, we keep the tunnel open in case you run `app serve` again, that way you'll reuse the same tunnel and won't need to open a new URL to see your app.

I can bring this problem to the team but just to better understand your use case, are you encountering issues running multiple CLI apps? or incompatibilities with other tools?

**Comment by isaacroldan** [comment]
Hi @jagthedrummer, I discussed this issue with the team and this behaviour is the intended one and won't change in CLI 2.x
However, in CLI 3.x, tunnels works differently and they'll be stopped when you stop the CLI.

My recommendation then would be to [migrate to CLI3](https://shopify.dev/apps/tools/cli/migrate) if possible or to
run `shopify app tunnel stop` to manually stop the tunnel.
