### ISSUE TITLE
[Enhancement] TAE: Use the actual app ID on `Theme::Extension::DevServer`

### ISSUE THREAD

**Issue by karreiro** [Shopify/shopify-cli#2521]
The goal of this task is using the actual app ID at the `Theme::Extension::DevServer` class.

We might have it at the `lib/project_types/` level, so (at the lib/shopify_cli/theme/extension/dev_server.rb level), we may receive the app ID as `DevServer#start` parameter.

**Comment by jessetuglu** [comment]
We are not handling concurrent TAE in this first release.
