### ISSUE TITLE
[Bug]: -o flag regex doesn't work properly.

### ISSUE THREAD

**Issue by peepers-rick** [Shopify/shopify-cli#2531]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

A file named "snippets/json-swatch.liquid" should NOT be pulled when running `shopify theme pull -o /\.json/` since it doesn't have ".json" anywhere in the filename.

### Actual behavior

A file named "snippets/json-swatch.liquid" WAS pulled when running `shopify theme pull -o /\.json/`

### Reproduction steps

1. Create a file that has "json" in it but does NOT have ".json" in it
2. Run `shopify theme pull -o /\.json/`
3. Observe that the file that contains "json" but not ".json" is pulled anyway

### Operating System

Ubuntu 20.04 (via WSL)

### CLI version (run `shopify version` if you're not sure)

2.22.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.1p64

### What language and version are you using in your application?

Liquid

**Comment by amcaplan** [comment]
Please confirm this solved your problem 😁

**Comment by peepers-rick** [comment]
Hi @amcaplan ,
That works, thank you! However, I'd recommend updating the docs on [Theme commands -> pull](https://shopify.dev/themes/tools/cli/theme-commands) because the examples show a single escape for the `-o` flag like `/\.jpe?g$/`

**Comment by amcaplan** [comment]
/cc @shainaraskas

Note this affects `push` as well.

I'm not sure what the correct answer is here, as the regex itself is correct, it just needs to be escaped an extra time due to the shell itself doing escaping. How do we communicate that? Maybe leave the regex as is, but note they may need to escape an extra time due to the shell escaping arguments?
