### ISSUE TITLE
[Enhancement] TAE: Show "Synced" messages with the timestamp

### ISSUE THREAD

**Issue by karreiro** [Shopify/shopify-cli#2554]
The goal of this task is showing the success message following the same standard we have for themes:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/1079279/183892123-b5ca41bd-e7af-4755-b684-a79613e7a74c.png">

**Stretch goal**: it would be awesome if we could also list the updated files, as the following snippet shows. However, we would need to implement an extra mechanism to monitor assets, because (IIUC) never get in the  `Syncer#@pending_updates` array (so, showing the files is really a stretch goal for this task). 

```
09:55:05 Pushed » 'theme-app-extension' to a draft
   - blocks/rockets.liquid
   - assets/base.css
09:55:28 Pushed » 'theme-app-extension' to a draft
   - blocks/rockets.liquid
```

**Comment by amcaplan** [comment]
@karreiro @jessetuglu can I close this?

**Comment by karreiro** [comment]
Yes, @amcaplan. Thank you!
