### ISSUE TITLE
[Enhancement]: Add a shorthand for `--theme-editor-sync` 

### ISSUE THREAD

**Issue by charlespwd** [Shopify/shopify-cli#2587]
### What type of project(s) will this request affect?

theme

### Overview

Partner would like a short flag for `--theme-editor-sync`. `-s` or something.

### Motivation

I have to google CLI Theme Commands everytime because “--theme-editor-sync” is hard to remember.

**Comment by octipus** [comment]
> Thanks for opening this issue @charlespwd 👍
> 
> "shopify theme serve" is something we use daily as well as --theme-editor-sync, but I personally always forget the correct word order. A shorthand would be really handy.

You can use Zsh and add custom commands in your prompt with aliases.
here is a useful link to get you started 
https://linuxhint.com/configure-use-aliases-zsh/
