### ISSUE TITLE
[Bug]: windows security giving threat warning on update to 2.24.0 version

### ISSUE THREAD

**Issue by prem1835** [Shopify/shopify-cli#2595]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

It should not have given security threat warning on windows security app.

### Actual behavior

It gave security threat warning on windows security app.

![image](https://user-images.githubusercontent.com/54386867/187873150-d66ca863-55a0-4363-b4eb-1b5de842a0e1.png)

### Reproduction steps

Just updating the Shopify CLI to 2.24.0 version will produce the error in the windows security app.

### Operating System

Windows 11

### CLI version (run `shopify version` if you're not sure)

2.24.0

### Shell

ConEmu (cmd)

### Ruby version (run `ruby -v` if you're not sure)

3.1.0p0

**Comment by amcaplan** [comment]
Hi @prem1835, thanks for reporting this issue! We certainly need to make sure the CLI isn't labeled as malware.

While we look into this, I should just note I don't think this should impact you personally if your focus is themes. Does it prevent the CLI from running in any noticeable way for you while working on themes?

**Comment by prem1835** [comment]
Hi @amcaplan 
You're right, this issue didn't impacted my workflow and I restored the file deleted by the windows security app. 
I wanted to make this issue just for the information purpose!
