### ISSUE TITLE
[Enhancement]: Option to ignore the "data" files from a theme

### ISSUE THREAD

**Issue by octipus** [Shopify/shopify-cli#2596]
### What type of project(s) will this request affect?

theme

### Overview

First of all congrats for all the hard work you guys put in Shopify CLI!
I am using it for over a year now and i'm thrilled to see how far it came.

We are using the Shopify x Github integration to manage a multinational/multistore architecture from the same codebase.
In other words, there are 5 regional stores that use the same repository, each assigned to it's own branch.
When developing new features, some go to all stores some go to a select few stores.

### Motivation

The problem that we have is that every time we introduce new features, we have to deal with hundreds of merge conflicts - most of which are - you guessed - the json data files + settings_data.json etc.
The problem here is that each time json files are updated by marketing team in the customizer, this creates a difference in branches and when we do a pull request Github is mad confused.

I know this ties more into github and yes, we tried adding the .json files to .gitignore file but in effect that wouldnot allow us to preview on local machines when we branch since the json files are ignored. This might not be a Shopify CLI issue - i'm just throwing this here in the hope that someone has used this type or architecture before and can suggest a solution of some sort. 

Any help would be highly appreciated 
Many thanks
Octo

**Comment by octipus** [comment]
@ADTC thank you so much for your response!

> Would the `--ignore` option in `theme push` help?

We tried using the `--ignore` flag but that does not work unless we use shopify CLI to push but that means logging in and out of 5 stores every time we push something to production

> Unfortunately you may have to unlink from GitHub I suppose, and manually manage your GitHub repository. Besides, you don't need to integrate with GitHub if you have a lot of stores sharing a single theme repository. It would only be a one-way sync (from GitHub to Shopify), not the other way (from Shopify to GitHub).

Unlinking from Github is not an option as we need to have a centralized point of control from where we push the features to each store. We don't want to develop the same feature 5 times. 

So i guess the endgoal is to have 1 repository with multiple branches(each connected to 1 store) - using the [gitflow branching model](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).
This will allow us to have new features developed locally and push to 5 stores. Currently what blocks us from doing this, are the json files that are different from each store and get updated in a new commit when any change is done in shopify theme customiser.

**Comment by lvl99** [comment]
@octipus we have the same issue, but we're thinking of moving back to the `shopify theme push` method (aka manual deployments). There are other issues to manage with that methodology, which I'm trying to solve in this PR #2551 as well.

I think to add a +1 to your request and elucidate more on the primary struggle, our issue is to do with managing versions of any app or theme managed file (`config/settings_data.json`, `locales/*.json`, `templates/page.custom.json`, etc.). When they can diverge between stores, it makes it tricky to merge and combine into a single repo. We had thought of doing separate branches per store, but again there are merge issues which need to be manually actioned by a developer, and it can be an intense process.

I think there needs to be some kind of disconnect or separation between theme structure (code) vs theme content (data) at the platform level. There will be a blend between structure & content in some cases (especially with regards to locales and JSON page templates).

Another really hard thing to merge is the differences between text elements within sections and blocks and their translations. Sections/blocks have unique IDs assigned to them per store, and even if the same stores have the same textual content, they'll have different IDs and it would mean that there is duplicate content when merging data in `config/settings_data.json` and `locales/*.json` -- so hard to reconcile into a "single source of truth" for all stores to reference. In that case, I think there is a limit to how much the Shopify CLI can mitigate the issue when perhaps it is a platform architectural issue.

**Comment by ADTC** [comment]
@octipus I think the Git branching model will help your use case. Consider having a separate branch for each store, then merge your developed changes to each and every one of these branches as a "deployment step":

![image](https://user-images.githubusercontent.com/6047296/191046215-fb9da97a-3011-4828-9f9e-294c23972cba.png)
[_(Browse this repository here.)_](https://github.com/ADTC/multi-branch-test/branches)

As you can see, different version of the common code can be deployed to different stores, but the `main` branch will never have any of the store-specific JSON fles. If Shopify's Git integration creates a commit in a store branch, it will not affect the `main` branch. **Just make sure you'll never merge a store branch back to `main`.**

Once you get the hang of this, you can automate the merges (from `main` to a lot of store branches) and pushes (from local to remote) using some scripts.

**Note:** The Git integration for each store should be linked to the correct store branch, not to the `main` branch.

**PS:** You can initialize a new store branch from _any_ point in the `main` branch. The use of first commit above is for illustration only.

If ever you need to get a non-JSON commit from a store branch, you must use `git cherry-pick` to import it into the `main` branch.

Also, for testing your changes to `main` branch, have a test store with its own branch and JSON files. Merging changes from `main` branch to the test store's branch will help test those changes.

**Comment by ADTC** [comment]
@lvl99 

> Sections/blocks have unique IDs assigned to them per store, and even if the same stores have the same textual content, they'll have different IDs

Actually you can simply change the IDs of the same text block in every store to be the same ID. The IDs only need to be unique within one theme, but can be reused in another theme or store.

**Comment by ross-nama** [comment]
That's super interesting @ADTC
How would you go about developing new features with this strategy? Checking out a new branch from main, using the Shopify CLI to work on your changes and then cherry picking the commits made to non JSON files into each store branch?

**Comment by ADTC** [comment]
@ross-nama 

> How would you go about developing new features with this strategy?

That's what the test store / test branch is for. But if you don't have one, you can simply branch off any store you have, and develop your features on the store branch's **copy**. Then cherry-pick the non-JSON commits to the `main` branch. Then merge the new main branch to all the store branches.

Note that you can't develop on the `main` branch since it doesn't contain any JSON files which could be different across different stores.
