### ISSUE TITLE
[Bug]:  Shopify Cli Error For Every Action on Mac Air M2

### ISSUE THREAD

**Issue by clairegll** [Shopify/shopify-cli#2598]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Don't know at all ... 
A beugue with Shopify Cli because i'm on new env and still not working 

### Actual behavior

An unexpected error occured.
	To submit an issue include the stack trace.

<img width="1458" alt="Capture d’écran 2022-09-02 à 10 40 32" src="https://user-images.githubusercontent.com/68912730/188155768-a2041d3b-c05e-4225-b226-9972c52a4e0f.png">
<img width="1091" alt="Capture d’écran 2022-09-02 à 10 40 17" src="https://user-images.githubusercontent.com/68912730/188155783-14fefa9e-120c-478a-a0dc-56e52687db01.png">

### Reproduction steps

Shopify theme serve, Shopify theme pull ...
each command of shopify don't work even on my Mac Monterer or Mac Mojave ! 

### Operating System

Mac OS Montery v12.5

### CLI version (run `shopify version` if you're not sure)

2.24.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.0.0

### What language and version are you using in your application?

ruby

**Comment by amcaplan** [comment]
Hi @clairegll, it looks like you're trying to serve a theme from your home directory (`~`). This will search your entire home directory for theme files, which probably isn't what you want. Aside from the permissions issue (as it's trying to access directories that should be closed off to the CLI), it will try to upload your documents, downloads, movies, music, etc. as part of the theme.

Instead, create your theme in a subdirectory, and make sure that is your current working directory when serving. (Alternatively, you can run `shopify theme serve ./my-theme-subdirectory` substituting the actual name of your theme's directory.)
