### ISSUE TITLE
SystemExit: abnormal termination status: 2

### ISSUE THREAD

**Issue by findoc2021** [Shopify/shopify-cli#2610]
# Issue summary

Write a short description of the issue here ↓

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Stacktrace

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:137:in `exit'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:137:in `rescue in run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/theme-check-1.9.2/lib/theme_check/cli.rb:126:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.0/lib/project_types/theme/commands/check.rb:25:in `call'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/shopify-cli-2.10.0/lib/shopify_cli/command/sub_command.rb:14:in `call'

## Specifications

- App type:
- Operating System:
- Shell:
- Ruby version (ruby -v):

**Comment by amcaplan** [comment]
Hi @findoc2021, thanks for opening an issue!

Unfortunately I don't have much context here outside of an extremely generic error message. Per [this code](https://github.com/Shopify/theme-check/blob/9ce4565ff18b6d88b567bf9f31c8828298677a33/lib/theme_check/bug.rb), the error should print detailed information about its contents and context, but I don't see that information here, and I can't do much for you without it.

I'm closing as this isn't technically the correct place for this issue. If you are still experiencing the error, I'd strongly encourage you to open an issue with full details [on the theme-check repo](https://github.com/Shopify/theme-check/issues), and the relevant team will be delighted to have a look.
