### ISSUE TITLE
[Bug]: Sync doesnt start on theme serve

### ISSUE THREAD

**Issue by lspoor** [Shopify/shopify-cli#2615]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

CLI to begin the sync process then provide the theme URLs

### Actual behavior

Says "Syncing..." but doesn't show the progress bar and goes no further.

<img width="1278" alt="Screenshot 2022-09-12 at 17 44 17" src="https://user-images.githubusercontent.com/1685176/189710413-7a861894-0209-4fd2-8cd8-f6fafdf708eb.png">

If I `ctrl + c` to exit, I get the following:

<img width="1262" alt="Screenshot 2022-09-12 at 17 45 52" src="https://user-images.githubusercontent.com/1685176/189710591-c09563b7-facb-4fe7-832b-d14ceba66615.png">

### Reproduction steps

1. Run shopify theme serve

### Operating System

Mac OS Monterey 12.5.1

### CLI version (run `shopify version` if you're not sure)

2.24.0

**Comment by panama86** [comment]
I'm having the exact same issue over here.
