### ISSUE TITLE
Allow users to use custom ngrok subdomain

### ISSUE THREAD

**Issue by carlosreyes** [Shopify/shopify-cli#262]
Users with paid ngrok accounts should be able to use custom subdomains. Having to update your app URL is a pain since they expire every 8 hours.

As a stopgap, I've just modified [this line](https://github.com/Shopify/shopify-app-cli/blob/master/lib/shopify-cli/tasks/tunnel.rb#L95) to include the `--subdomain=xxxxxxxx` and `--region=xx` flags hardcoded with my settings, but this should be available without modifying the source.

I should be able to have this live in env variables, a config file, or pass similar flags to what ngrok accepts to `shopify tunnel start`

**Comment by katiedavis** [comment]
Thanks for opening this @carlosreyes! I'm going to add an enhancement label and bring it up with the team :)

**Comment by Mindgames** [comment]
@carlosreyes +1  

To be noted is that it's still possible to run `shopify serve` and then run ngrok as normal like `ngrok http 8081 -region eu -subdomain=ingrid` instead of using `shopify tunnel`  

**However**
This will only allow for a good developer experience for those that have a paid ngrok.

**solutions** 
- CLI grabs the ngrok url and on the fly update app URL.

**Comment by markdavies** [comment]
It would be great to have a feature where `shopify serve` could skip the question `Do you want to update your application url?` with some kind of configurable setting. When we are using a custom subdomain using a paid ngrok account, it's too easy to accidentally choose the default option of "Yes", and have to go back in and change your settings back again.

**Comment by itsniper** [comment]
This would be very helpful! For now, this is what I've been doing:
1) Setup my ngrok config file (`~/.ngrok2/ngrok.yml`) with a named tunnel
2) Start ngrok tunnel
3) Run `shopify serve --host=https://<reserved ngrok domain>`

For this to work you also need to update `config/environments/development.rb` to support non-regex `config.host`. I'm using a reserved ngrok subdomain so it looks like this (replace `<reserved ngrok subdomain>`):
`config.hosts = (config.hosts rescue []) << /(\h+|<reserved ngrok subdomain>).ngrok.io/`
