### ISSUE TITLE
[Bug]: updating CLI and it stops working

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-cli#2638]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

shopify extension serve should open an ngrok tunnel to my local machine and let me develop against my code

### Actual behavior

it worked for 2.24 but when I updated to 2.25 that command stopped working and could no longer open a tunnel

### Stack trace

```shell
/usr/local/Cellar/shopify-cli/2.25.0/gems/shopify-cli-2.25.0/lib/project_types/extension/models/specification_handlers/default.rb:55:in `serve': unknown keywords: :theme, :api_key, :api_secret, :registration_id, :project (ArgumentError)
	from /usr/local/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/delegate.rb:87:in `method_missing'
	from /usr/local/Cellar/shopify-cli/2.25.0/gems/shopify-cli-2.25.0/lib/project_types/extension/commands/serve.rb:135:in `serve'
```

### Reproduction steps

1. update CLI to 2.25
2. shopify extension serve
3. error

### Operating System

MacOS

### CLI version (run `shopify version` if you're not sure)

2.25

### Shell

warp

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

### What language and version are you using in your application?

ruby, JS

**Comment by isaacroldan** [comment]
Hi @resistorsoftware !
This has been fixed and will be included in the next release
