### ISSUE TITLE
[Bug]: Local changes not being shown

### ISSUE THREAD

**Issue by toma-ohhdeer** [Shopify/shopify-cli#2639]
### Please confirm that you:

- [x] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When I update the code the local version should reflect these changes

### Actual behavior

When I save a change in the code the command prompt says its synced and the webpage refreshes however the changes made are never actually present on the site

### Reproduction steps

1. Run shopify theme serve
2. Make changes to the code
3. Save changes
4. Watch as the local version (127.0.0.1:9292) doesn't update 

### Operating System

Windows 11 Pro

### CLI version (run `shopify version` if you're not sure)

2.25.0

### Shell

Command Prompt

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20L

### What language and version are you using in your application?

Liquid

**Comment by karreiro** [comment]
Thank you for reporting this, @toma-ohhdeer! I've tried to reproduce this problem, but I've had no success.

Could you please share a screenshot of the Google Chrome console and the terminal after a file change?
(that would provide more context about where the issue lives, so we may reproduce and fix it)

Thanks again for reporting this!

**Comment by toma-ohhdeer** [comment]
> 

Heres a picture from Google Chrome console and a screenshot of the terminal, also not sure if its related but the link it gives me to "Share this them preview" never works either however the theme editor link does.
Chrome Console:
![console](https://user-images.githubusercontent.com/114403200/193214205-097dd4fb-2132-428f-bd19-264c73bd96de.png)
Terminal:
![terminal](https://user-images.githubusercontent.com/114403200/193212729-1f569429-fcad-4106-92ee-25b2ea4182e4.png)

**Comment by karreiro** [comment]
Thank you for sharing these screenshots, @toma-ohhdeer! They are really helpful for us to proceed with the investigation.

Regarding the _"missing one of these required files"_-issue, I'd need a bit more context to help with that. Could you please share your `.shopifyignore` file and the **x-request-id** header? (it appears when you run `shopify theme serve`). Here's how to get it:

![image](https://user-images.githubusercontent.com/1079279/193777716-af77ecda-3e0e-49c7-817d-658178b52c68.png)

**Comment by rhianna-ohhdeer** [comment]
I am now also having this problem - that is now all of our web team with this issue - making this very urgent.
We are unable to develop locally.

**Comment by toma-ohhdeer** [comment]
Hi, the issue was caused by us, after deleting a small amount of code a rogue comma remained however no errors were ever coming up when running `shopify theme serve`

**Comment by aidantjones** [comment]
I had this issue as well. Deleting my dev theme and regenerating it fixed it for me.

**Comment by aidantjones** [comment]
I had the same issue. Deleting my development theme and regenerating fixed it for me.
