### ISSUE TITLE
[Bug]: Shopify theme serve - preview theme: 404 Not Found

### ISSUE THREAD

**Issue by MaxDesignFR** [Shopify/shopify-cli#2641]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

It should open the preview theme.

### Actual behavior

It doesn't work. Url structure: https://domain.com/en/services/access_tokens/create_sharing/123391672398?return_to=%2F

![image](https://user-images.githubusercontent.com/46461193/193263490-e958cbdf-67bb-4eb4-8886-94669993946c.png)

### Reproduction steps

1. shopify login --store=https://www.domain.com/
2. shopify theme serve --theme-editor-sync
3. Click on "Share this theme preview" link

### Operating System

Linux on Windows 11 with WSL

### CLI version (run `shopify version` if you're not sure)

2.25.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]

**Comment by karreiro** [comment]
Thank you for reporting this, @MaxDesignFR.

Could you please share your the **x-request-id** of the localhost request? Here's how to get it:

![image](https://user-images.githubusercontent.com/1079279/193777716-af77ecda-3e0e-49c7-817d-658178b52c68.png)

(I understand the issue happens at the preview URL, but the localhost request ID would provide some extra information for us)

Thank you! :)

**Comment by MaxDesignFR** [comment]
I've had this issue for a couple of days until I report it, but very odd, it is working today... If it comes from my environement, I have not changed a thing recently, so I wonder. The **x-request-id** I have now is 937ebb3a-354d-4dfa-bb16-4d1cf779be22 , but as I said it's now working so it's possible there is no bug after all.
