### ISSUE TITLE
[Bug]: Could not login by the newest version

### ISSUE THREAD

**Issue by zhangzhaohong** [Shopify/shopify-cli#2655]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

login the account and enable to use shopify theme serve.

### Actual behavior

It did not work.
![image](https://user-images.githubusercontent.com/54138238/194981175-6ba843c2-4e13-4c8a-9bdc-40c1194bddf0.png)

### Reproduction steps

1.shopify login
2.
3.

### Operating System

macOs 13

### CLI version (run `shopify version` if you're not sure)

2.27.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

### What language and version are you using in your application?

liquid

**Comment by gonzaloriestra** [comment]
@Chenjiujiu do you still have that issue? Have you tried running `shopify logout` first? Could you share the stacktrace? Thanks!

**Comment by Chenjiujiu** [comment]
Thank you for your reply. The problem is getting better, but it will still come up, like this afternoon
