### ISSUE TITLE
The project cannot be opened locally, and the shopify theme serve command failed

### ISSUE THREAD

**Issue by ysz18520** [Shopify/shopify-cli#2663]
大家好，我是一名shopify模板开发人员，就在这个周一，我回来工作的时候发现shopify的本地脚手架无法正常运行了，开始提示的信息是shopify-cli的脚手架版本过低，于是我进行了更新，更新后依旧无法正常启动脚手架，在我输入shopify theme serve 命令行的时候，会弹出一个进行验证登录网址，我进行验证登录后，cmd命令处也没有任何响应，如error_mes.jpg图片所示内容，一直卡死在这个页面，直到报错发送邮件，有时候会出现error.jpg图示的错误，我非常有印象，以前进行shopify theme serve命令的时候很少会出现验证登录的网址弹出，在进行登录命令shopify login --store https://nomadbasic.com/会出现三个”√“符号，目前只有图error.jpg所示的一个，我一个同样开发shopify模板的师傅，也遇到和我一样的问题，我们尽可能排除自身原因，排除了主题模板以及Ruby gem 和shopify-cli版本问题等部分原因，由于没法快速找到问题的所在，所以向大家发送了求助信息，希望能够得到解答，非常感谢！

Hello, I am a developer of shopify template. On this Monday, when I came back to work, I found that the local scaffold of shopify could not run normally. The message I started to prompt was that the scaffold version of shopify cli was too low, so I updated it. After the update, the scaffold could not be started normally. When I entered the shopify theme serve command line, a login website for verification would pop up, After I log in through authentication, there is no response from the cmd command, such as error_ mes. The content shown in the jpg image is stuck on this page until an error is reported and the email is sent. Sometimes an error occurs I was very impressed by the error in the jpg diagram. Before, when I used the shopify theme serve command, the URL for verification login rarely popped up. When I used the shopify login -- store command https://nomadbasic.com/ There will be three "√" symbols. At present, there is only one as shown in the figure error.jpg. I, a teacher who also developed the shopify template, also encountered the same problems as me. We tried our best to eliminate our own reasons and some reasons such as the theme template, Ruby gem and shopify cli version problems. Since we couldn't find the problem quickly, we sent a help message to everyone, hoping to get answers. Thank you very much!

Sorry, I don't know how to upload the picture, I will display the picture content in text。

error_mes.jpg:

C:\UsersAdministrator\Desktop \{myfile_name}>shopify theme serve
一viewing theme…--------------------------------------------------------

error.jpg

C: \[Users\Administrator\Desktop\{myfile_name}>shopify theme serve
一viewing theme…--------------------------------------------------------
----------------------------------------------------------------------0.01s-
X No store found. P1ease run shopify 1ogin --store/-s STORE to login to a specific store
C:;Users\Administrator\Desktop\{myfile_name}>shopify 1ogin --store {my_store}
X An unexpected error occured.
                To submit an issue include the stack trace.
?Send an anonymized error report to Shopify7?(Navigate up with 'r’and down with ' j'，press Enter to select, ilter with 'f’)
1. yes, send
2. No,’don't send

**Comment by Ing233** [comment]
Hello, I also encountered this problem on Monday, and my online store at that time could not be accessed.  I fed this problem back to shopify online help center, they  flushed my front end cache, and now I can use it.  Maybe you should try email to customer service.
