### ISSUE TITLE
[Bug]: Shopify CLI 2.29.0 homebrew requires Xcode 14.1 but 14.1 is not out yet

### ISSUE THREAD

**Issue by kevindees** [Shopify/shopify-cli#2671]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Expected Xcode 14.0.1 to work when running `brew upgrade` on macOS 13.0 as Xcode 14.1 is still in RC only.

This error also removed my access to the `shopify` shell command.

### Actual behavior

```
==> Upgrading shopify/shopify/shopify-cli
  2.22.0 -> 2.29.0

Error: Your Xcode (14.0.1) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.
```

### Reproduction steps

1. Open a terminal and run `brew upgrade` with Shopify CLI already installed.
2. Errors.

### Operating System

macOS 13.0

### CLI version (run `shopify version` if you're not sure)

2.22.0

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.10p210

**Comment by shivanraptor** [comment]
Same issue here. Xcode 14.1 official build does not even release yet. The `shopify` command cannot be used now. Annoyed.

**Comment by gonzaloriestra** [comment]
I'm closing, since it's not related to the CLI. Remember you can also install it with `gem install shopify-cli`, or even better, move to the new CLI 3.x that now supports themes as well 🙂.
