### ISSUE TITLE
[Bug]: brew install shopify-cli@2

### ISSUE THREAD

**Issue by philipaxelsson94** [Shopify/shopify-cli#2675]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

brew tap shopify/shopify
brew install shopify-cli@2
shopify-version

Output 2.30

### Actual behavior

![Screenshot 2022-11-03 at 15 34 52](https://user-images.githubusercontent.com/59344629/199750011-7d1c6ee8-3597-4e12-8f9e-0cf50427641f.png)

### Stack trace

```shell
It says that shopify-cli version 2.30 is installed but when I run shopify-version the command is not found.
```

### Reproduction steps

1. Uninstall brew and reinstall
2. reinstall shopify-cli@2
3.

### Operating System

Mac OS Monterey version 12.6

### CLI version (run `shopify version` if you're not sure)

2.30

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p20

### What language and version are you using in your application?

ruby 2.6.8p20

**Comment by maximedaraize** [comment]
I have the same issue with different specs

### Operating System
Mac OS Ventura 13.0 (22A380)

### CLI version
2.30

### Shell
zsh

### Ruby version
ruby 3.0.3p157

**Comment by philipaxelsson94** [comment]
Do you have any suggestions?

**Comment by niklasjk** [comment]
I'm also experiencing this, pretty much the same configuration!

**Comment by niklasjk** [comment]
While looking for a fix to this issue I found out (https://github.com/Shopify/shopify-cli/issues/2671#issuecomment-1294714054) that you can now work on themes on version 3.x as well!

**Comment by cfxd** [comment]
@philipaxelsson94 per the docs:

> After Shopify CLI 2.x is reinstalled, you can run Shopify CLI 3.x commands using the shopify program name, and **run Shopify CLI 2.x commands using the _shopify2_** program name.

**Comment by ShawLocke** [comment]
@philipaxelsson94 I also encountered the same issue after I upgrade homebrew to the latest version `3.6.11` on macOS 12.5.1 MacBookAir M1. `shopify` command works when I  was in old homebrew version (can't remember the exact version number).

I fount it is not easy to downgrade homebrew.  My solution is:
1. use `brew` to uninstall shopify cli.
2. use `asdf` to install ruby 2.7.6 or newer version, and set global ruby as 2.7.6, keep macOS pre-installed ruby 2.6.8 untouched.
3. use gem to install shopify cli: `gem install shopify-cli`.

Note: if you install ruby under 2.7.6, e.g. 2.7.2, you will get a warning message after you start your project.
`Your environment Ruby version, 2.7.2, is outside of the range supported by the CLI, 2.7.5..<3.2.0, and might cause incompatibility issues.`
