### ISSUE TITLE
[Bug]: ShopifyCLI::API::APIRequestServerError: 500{"errors":"Internal Server Error"}

### ISSUE THREAD

**Issue by cmarc-novatize** [Shopify/shopify-cli#2691]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Should start my projet

### Actual behavior

just does nothing and fails

### Stack trace

```shell
/usr/local/Cellar/shopify-cli/2.29.0/gems/shopify-cli-2.29.0/lib/shopify_cli/api.rb:82:in `block in request'
/usr/local/Cellar/shopify-cli/2.29.0/gems/shopify-cli-2.29.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
/usr/local/Cellar/shopify-cli/2.29.0/gems/shopify-cli-2.29.0/lib/shopify_cli/api.rb:89:in `request'
/usr/local/Cellar/shopify-cli/2.29.0/gems/shopify-cli-2.29.0/lib/shopify_cli/admin_api.rb:92:in `block in rest_request'
/usr/local/Cellar/shopify-cli/2.29.0/gems/shopify-cli-2.29.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
```

### Reproduction steps

1. shopify login
2. shopify theme serve
3. then it fails

### Operating System

x86_64-darwin21

### CLI version (run `shopify version` if you're not sure)

2.29.0

### Shell

/bin/zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

**Comment by TomJacobsUK** [comment]
I have same issue, think it's server-side issue.

**Comment by Feniks212** [comment]
It already seems to be working
