### ISSUE TITLE
[Bug]: Theme Serve Not Working

### ISSUE THREAD

**Issue by machancock** [Shopify/shopify-cli#2702]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

'shopify theme serve', I should get three URLs.

One with an IP address.

One for my development theme that opens the editor, and the second is a direct preview to the development theme.

I am getting both the URL's but they will not allow me to preview my Development or local theme, it is only previewing the live theme with none of my local changes.

### Actual behavior

The preview for the development theme editor is working and it shows i'm previewing my Development theme in the top left. When I try and preview the theme from inside the editor, it takes me to the live site and isn't showing any of the changes I made inside of the editor or on my development theme.

The direct link to preview my development theme isn't working either, It just takes me to the live theme with none of the local changes I have made.

I have had several of my coworkers test on their end and they have the same behavior.

### Reproduction steps

1. Log in / out of Shopify
2. Clear all cache and cookies
3. Logged out from the inside the Shopify CLI
4. Ran 'shopify theme serve' and pasted both URL's in my browser.
5. Tested inside of incognito mode.
6. Had several other developers try as well and they all have the same issue.
7. Attempted all the above steps with other stores I work with, same issue.
8. I also attempted to update Shopify CLI but there were no updates

### Operating System

macOS Ventura 13.0.1

### CLI version (run `shopify version` if you're not sure)

2.32.1

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Ruby

**Comment by gonzaloriestra** [comment]
@Shopify/theme-developer-tools any idea of why could this be happening? I'm not able to reproduce it.

**Comment by karreiro** [comment]
Thank you for reporting this, @machancock.

Which browser are you using? Currently, `shopify theme serve` is compatible with Google Chrome only (still, we're working on supporting it on other browsers)

Also, you could you please run the command with the DEBUG flag (`DEBUG=1 shopify-dev theme serve`) and share a screenshot here? Then, we may get more information and context to solve this.

Thanks again for reporting that issue!
