### ISSUE TITLE
[Bug]: Checkout UI type is missing while create shopify extension using CLI Command

### ISSUE THREAD

**Issue by kmajay978** [Shopify/shopify-cli#2707]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

I want to create the **checkout UI extension** using this command:- **shopify extension create**
but it doesn't include **checkout ui extension type**. Kindly help me out. This extension isn't available in a list.

I am getting on these options, After running this command: **shopify extension create**. Kindly check the following screenshot for more details.

![Extension create](https://user-images.githubusercontent.com/75435942/210950883-a16d25d8-d75b-4215-96f3-7c746e9a9329.png)

### Actual behavior

It should include the checkout UI extension type in a list. so that we developer can create or select the extension type.

### Reproduction steps

1. Shopify CLI should be installed 
2.  Just simply run the following command :- **shopify extension create**

### Operating System

Window 10

### CLI version (run `shopify version` if you're not sure)

2.22.0

### Shell

Git Bach, VScode

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

PHP 7.4 (Laravel + React)

**Comment by amcaplan** [comment]
Hi @kmajay978, thanks for opening an issue.

Actually, we don't support the creation of checkout UI extensions in CLI 2. You need a CLI 3 project for that.

If you need to create a new app, you can follow the [instructions here](https://shopify.dev/apps/tools/cli#getting-started). If migrating an existing app, I'd recommend checking out our [migration guide](https://shopify.dev/apps/tools/cli/migrate).

Once you have a CLI 3 app, you can use [this command](https://shopify.dev/apps/tools/cli/commands#generate-extension) to generate the extension.

Note that CLI 2 will no longer be supported starting in 3 months' time, per the [announcement](https://shopify.dev/changelog/cli-2-0-to-be-sunset-on-may-31-2023). So it's best to migrate your apps ASAP anyway.
