### ISSUE TITLE
[Bug]: Shopify CLI Requires Javscript to work

### ISSUE THREAD

**Issue by lukecharle** [Shopify/shopify-cli#2709]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Produce the response (which would be a webpage) as I'm making a fetch request

### Actual behavior

I get the following in the response and not the webpage

<img width="627" alt="Screenshot 2023-01-06 at 09 43 09" src="https://user-images.githubusercontent.com/115987937/210975628-85260e3c-feae-4b8d-ae33-9c71278f63f7.png">

### Reproduction steps

1. Fetch a webpage within the same store
2. Check response tab

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

2.28.0 (has happened across multiple versions)

**Comment by lukecharle** [comment]
Hi @karreiro , I don't have Javascript disabled in my browser so it should be working?

**Comment by karreiro** [comment]
@lukecharle yes, it should be working. Could you please share which browser you're using?

Also, could share a screenshot of your browser console (or equivalent)? That would be great and it would provide much more context about this issue:

![console](https://user-images.githubusercontent.com/1079279/212894418-c79f1086-cbd2-4f7c-9ffa-44fbd985b29e.png)

Thanks a lot for reporting this.

**Comment by SzuJanLin** [comment]
Is there any update on this issue? I'm having the same problem on app block extension

**Comment by karreiro** [comment]
Thank you for reporting this, @SzuJanLin.

If you don't mind, could you let us know which browser you're currently using? In case you're using a browser other than Google Chrome, would you be able to give it a try on Chrome and let us know if the issue persists?

Also, if it's possible for you to share a screenshot of your browser console (or equivalent), that would help us get a better understanding of the problem and work towards a solution. Thanks a lot!

**Comment by mihrich** [comment]
Check your theme.liquid

So, for example, I put <style></style> instead of {% style %} and {% endstyle %} and got the same error
