### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by george-arnold-88** [Shopify/shopify-cli#2711]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

CLI commands should function normally

### Actual behavior

I have been developing for a client for several months with no issues.  Out of nowhere,  CLI commands stopped working for me.  They do work for my fellow collaborators under the SAME login. Just for some reason, on my machine, when theme commands are run (ALL commands, theme pull, push, serve/dev etc) AND On both Shopify CLI 2 and Shopify CLI 3 I get the error message: 
`You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.`

This only happens on this one client, I went to General support. They sent me to partner support. I went to partner support and they sent me here with the following message: 

From Shopify Partners: 
**After reaching out to my team about this they advised that unexpected CLI behavior isn't something our team supports. While we appreciate you taking the time to contact us regarding some potentially unexpected behavior while working with the Shopify CLI, if you are facing an issue or have a concern about the functionality of this development tool, the best first stop would be our official [Github repository - Shopify CLI](https://github.com/Shopify/shopify-cli) to search for related GitHub issues.
If you can't find anything related to your concern specifically, please consider creating a new issue and be sure to include as much detail as possible. Our suggestion would be to include any images, the OS you're running, versioning and dependencies, as well as specific examples of errors returned by the command line.
While Shopify supports the CLI, our Partner Support team doesn't quite support unexpected behaviors when working with the CLI. We have a dedicated team that triages and supports CLI issues through the Github repo I linked above.**

### Reproduction steps

1. Run any commands at all for the store at batchusa.com
2.
3.

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

2 and 3.31.1

### Shell

all

### Ruby version (run `ruby -v` if you're not sure)

2.6.10p210

**Comment by amcaplan** [comment]
Hi @george-arnold-88, thanks for opening an issue.

This is surprising. It's possible the error message doesn't reflect the situation correctly.

Can you please try running on CLI 3 with `--verbose` and let us know the request ID as well as any request/error details you see? That may help us debug what's going on.

**Comment by matteodepalo** [comment]
Closing this, but feel free to open a new issue if you're still facing this.
