### ISSUE TITLE
[Bug]: Losing edits in Theme Customizer

### ISSUE THREAD

**Issue by surfwoodroad** [Shopify/shopify-cli#2720]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I shouldn't lose work. If 'shopify theme dev' has to stop running, ok. But it shouldn't restart and overwrite the edits I was making in the theme customizer. It should just display a message that it has stopped and I may need to pull changes before running again. I've lost work every day for over a week (sob emoji). (I probably have 20 edits on 10 pages that I have to find and make again.)

### Actual behavior

While running 'shopify theme dev' sometimes it just stops, then restarts and pushed my local files again without warning.

### Stack trace

```shell
Here's something from the console - note that I didn't do any commands:

16:31:30 Synced » update snippets/card-product.liquid
16:32:22 Synced » update snippets/card-product.liquid
16:33:29 Synced » update snippets/card-product.liquid
Stopping…
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ * Syncing theme #136512798951 on tea-drops-staging-3-0.myshopify.com
┃                                                                                                                        100%
┃ 
┃ Serving .
┃ 
┃ Please open this URL in your browser:
┃ http://127.0.0.1:9292
┃ 
┃ Customize this theme in the Theme Editor, and use 'theme pull' to get the changes:
┃ https://tea-drops-staging-3-0.myshopify.com/admin/themes/136512798951/editor
┃ 
┃ Share this theme preview:
┃ https://tea-drops-staging-3-0.myshopify.com/?preview_theme_id=136512798951
┃ 
┃ (Use Ctrl-C to stop)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (5.97s) ━━
```

### Reproduction steps

1. run 'shopify theme dev' 
2. do a mix of editing files and making changes in the theme customizer
3. at some unpredictable point, this happens every day.

### Operating System

Mac OS

### CLI version (run `shopify version` if you're not sure)

3.36.1

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.6.3p62

### What language and version are you using in your application?

it's a website, so liquid

**Comment by mrobit** [comment]
Are you ignoring `config/settings_data.json` and `templates/*.json` files via `.shopifyignore`?

**Comment by surfwoodroad** [comment]
@mrobit no, I'm not. If I did that, wouldn't that mean that I couldn't pull my edits down from my dev theme to push out to a staging theme (without changing my .shopifyignore file every time)? I'm often doing a mix of content and code edits.

**Comment by taksh108** [comment]
@surfwoodroad Try using `--theme-editor-sync` with shopify theme dev. that way all changes in theme editor are synced in real time
