### ISSUE TITLE
[Feature]: --force flag for theme push live theme

### ISSUE THREAD

**Issue by hedgehog90** [Shopify/shopify-cli#2722]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

Currently there appears to be no way to push my theme update without a manual user input to confirm.
`shopify theme push --live --json`
always returns:
`Are you sure you want to push to your live theme?`

### Motivation

I want to have a batch script to run the command.

**Comment by anders-christiansen** [comment]
@hedgehog90 
You can actually use --force :) Don't know why it is not in the docs

**Comment by karreiro** [comment]
Closing as this feature is currently implemented by the `--allow-live` flag.
