### ISSUE TITLE
[Bug]: Shopify theme dev - Page not found

### ISSUE THREAD

**Issue by gabrieleciolinosv** [Shopify/shopify-cli#2725]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

It should open the preview theme to allow local development.

### Actual behavior

Hi, I can't get "shopify theme dev" to work. The command returns no error but when I try to reach the urls it provides (localhost or the share link) it keeps giving me a Not Found page. The online theme works perfectly but with this problem you can no longer develop new features because you can't work from local. No error in console. 
If it is helpful the X-Request-Id is 5a5ab9da-5728-4868-910e-c0612eb9d219
The problem seems pretty similar to issue https://github.com/Shopify/shopify-cli/issues/2641

Note that I specified 3 as the cli version but even with 2 it was giving the same problem so I don't think it's a version problem.

### Reproduction steps

1. Logged in
2. Launch shopify theme dev
3. Click on share preview or localhost link

### Operating System

MacOs Monterey

### CLI version (run `shopify version` if you're not sure)

3.39.0

**Comment by taksh108** [comment]
Please check if you have templates with extension .json.liquid.
If so, you might face this issue.

**Comment by taksh108** [comment]
> Closing following @taksh108 comment.
@karreiro 

I suppose there could be better handling of this issue - as I've seen a few people face this. Having multiple templates - with .json and .liquid doesn't upload at all
