### ISSUE TITLE
[Bug]: Running `yarn dev` results in a 502

### ISSUE THREAD

**Issue by galexw** [Shopify/shopify-cli#2743]
### Please confirm that you:

- [x] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

It should start my app locally.
Point an ngrok address to my dev app.

### Actual behavior

```
$ shopify app dev
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  The introspection endpoint returned a 502:                                  │
│  https://accounts.shopify.com/oauth/introspection                            │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

I am using this app template https://github.com/Shopify/shopify-app-template-ruby
Run `yarn dev` in the project root.

### Operating System

Ubuntu

### CLI version (run `shopify version` if you're not sure)

3.44.1

**Comment by wolff95** [comment]
Same! 3.44.1 Shopify CLI, no upgrades available... and no apparent reason, I suppose this goes beyond my powers.

**Comment by deepahir** [comment]
Can anyone find solution , I have same problem.

**Comment by MikkoHeikkila** [comment]
Same here

**Comment by alejuu** [comment]
same here

**Comment by deepahir** [comment]
Currently any solution or not?

**Comment by rmoylan** [comment]
Same here
`
Shopify CLI    3.44.1
`

**Comment by lmd808** [comment]
Same here, has anyone had any luck resolving it?

**Comment by Chetv17** [comment]
Same here

**Comment by lmd808** [comment]
If anyone is still looking for help on this I was able to solve it by logging out and logging back in 
run: 

`shopify auth logout`

Then try logging back in. It worked for me and I hope it works for everyone else as well. 


Link to shopify CLI command docs [here](https://shopify.dev/docs/themes/tools/cli/commands) ...in case anyone needs it for reference.

**Comment by galexw** [comment]
> If anyone is still looking for help on this- I was able to solve it by logging out and logging back in:
> 
> 1. run:  `shopify auth logout`
> 2. Then try logging back in. It worked for me and I hope it works for everyone else as well.
> 
> Link to shopify CLI command docs [here](https://shopify.dev/docs/themes/tools/cli/commands) ...in case anyone needs it for reference.

This worked for me!

**Comment by dawoodidrees** [comment]
shopify auth logout
login back will work just fine

**Comment by JorenRothman** [comment]
> Can anyone find solution , I have same problem.

Legend Thanks!

**Comment by PyCreatorr** [comment]
shopify logout does not help, quite a pity ;((
Shopify make something on his platform, wait a while...

**Comment by ADCREW-LLC** [comment]
> If anyone is still looking for help on this- I was able to solve it by logging out and logging back in:
> 
> 1. run:  `shopify auth logout`
> 2. Then try logging back in. It worked for me and I hope it works for everyone else as well.
> 
> Link to shopify CLI command docs [here](https://shopify.dev/docs/themes/tools/cli/commands) ...in case anyone needs it for reference.

You've saved my life!

**Comment by github-arkub** [comment]
After logout also it is not working

**Comment by blanklob** [comment]
For this to work you can pass env vars to theme command instead of flags, here is an example:

1. Create a `.env` file

```bash
# Shopify Theme CLI
SHOPIFY_FLAG_STORE=example-store.myshopify.com
SHOPIFY_CLI_THEME_TOKEN=shpka_e2d495....
```

Then install [env-cmd](https://www.npmjs.com/package/env-cmd) package to load the vars in the file before each command, like so:

```json
{
  "private": true,
  "scripts": {
    "dev": "env-cmd shopify theme dev",
    "push": "env-cmd shopify theme push -u"
  },
  "devDependencies": {
    "env-cmd": "latest",
  }
}
```

**Comment by srhtkemal** [comment]
> I got into my app folder then on terminal ran: npm run shopify auth logout
> 
> received the message: ✅ Success! Logged out from Shopify.
> 
> then I proceeded to run: npm run dev
> 
> Then you should receive To run this command, log in to Shopify Partners. 👉 Press any key to open the login page on your browser
> 
> (via the browser accept the login)
> 
> ✔ Logged in.
> 
> i am using react hope this helps someone

It worked, thank you so much

**Comment by alvaro-shopify** [comment]
Issue solved and related with https://github.com/Shopify/cli/issues/1701
