### ISSUE TITLE
TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by inklingsofreality** [Shopify/shopify-cli#333]
# Issue summary

With the latest update, there appears to be a couple of breaking issues, one of which was solved by changing SHOPIFY_API_SECRET_KEY  to SHOPIFY_API_SECRET in the .env file. Now there is another issue with getting a TypeError (see what happens)

## Expected behavior

App should load in my store

## Actual behavior

What actually happens?

<details>TypeError: Key must be a buffer
┃       at new Hmac (crypto.js:117:16)
┃       at Object.createHmac (crypto.js:643:10)
┃       at Object.validateHmac [as default] (/mnt/c/projects/recipes_app/node_modules/@shopify/koa-shopify-auth/dist/auth/validate-hmac.js:17:10)
┃       at /mnt/c/projects/recipes_app/node_modules/@shopify/koa-shopify-auth/dist/auth/create-oauth-callback.js:24:52
┃       at step (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:133:27)
┃       at Object.next (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:114:57)
┃       at /mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:107:75
┃       at new Promise (<anonymous>)
┃       at Object.__awaiter (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:103:16)
┃       at oAuthCallback (/mnt/c/projects/recipes_app/node_modules/@shopify/koa-shopify-auth/dist/auth/create-oauth-callback.js:9:24)
┃       at /mnt/c/projects/recipes_app/node_modules/@shopify/koa-shopify-auth/dist/auth/index.js:58:46
┃       at step (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:133:27)
┃       at Object.next (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:114:57)
┃       at /mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:107:75
┃       at new Promise (<anonymous>)
┃       at Object.__awaiter (/mnt/c/projects/recipes_app/node_modules/tslib/tslib.js:103:16)
</details>

Also, here is my sample .env file with details removed
```
SHOPIFY_API_KEY=somekey
SHOPIFY_API_SECRET=somesecret
HOST=somengrokhost
SHOP=someshop.myshopify.com
SCOPES=myscopes
```

## Steps to reproduce the problem

1. Shopify Serve
2. Load app in store
3. Get Internal Server error
4. See error in console

## Specifications

- App type: Unlisted Public App using React
- Operating System: Windows
- Shell: WSL Ubuntu
- Ruby version (ruby -v): 2.5.1p57

**Comment by katiedavis** [comment]
Hi @inklingsofreality, you'll need to go into your `server.js` file and change the instances of `SHOPIFY_APP_SECRET_KEY` to `SHOPIFY_APP_SECRET`:
https://github.com/Shopify/shopify-app-node/commit/7c2cf72336d205e72c615604db4200dae0425598#diff-ea75b530d74f94670cea053feb8b961b

Sorry about the issue! Let me know how that goes

**Comment by inklingsofreality** [comment]
@katiedavis Thank you. I just did a search and replace. That seemed to fix that issue.
