### ISSUE TITLE
Setup System Call test boundaries.

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify-cli#352]
For testing in the CLI we really have 3 boundaries
- Network call to Shopify
- Filesystem call to create/write/delete files
- System call to integrate with the operating system.

Currently we already have appropriate test boundaries around 2 of those.
- Network is blocked by webmock
- Filesystem is blocked by FakeFS

We need a similar boundary that should raise an error if a system call is invoked from a test.

**Comment by andyw8** [comment]
We could start by wrapping all the existing systems calls in an adapter, and raising an exception if that is ever called during the tests. We can add a custom RuboCop rule to ensure that we always use the adapter and don't make system calls directly, e.g. through `system` or with the backtick notation
