### ISSUE TITLE
Update App Proxy with ngrok URL

### ISSUE THREAD

**Issue by dunckr** [Shopify/shopify-cli#440]
# Issue summary

Update the App Proxy url as part of updating the whitelisted URLs setup

## Expected behavior

The App proxy URL (https://partners.shopify.com/******/apps/********/manage_extensions/online_store/app_proxy) should be updated with the ngrok URL

## Actual behavior

It is not changed when the app uses a different ngrok URL

## Steps to reproduce the problem

1. `shopify serve`
1. View https://partners.shopify.com/******/apps/********/manage_extensions/online_store/app_proxy

Thanks for making this tool it's x10 better workflow than before 👍

**Comment by tanema** [comment]
Thanks, this is a great suggestion. It may take us a while though considering we have to check a bunch of criteria to see if you have app proxies enabled and relay that back to the CLI but I will look into this for future work..

**Comment by dunckr** [comment]
Thanks @tanema for the speedy reply. I think I'll just cough up for ngrok for now as it's so nicely integrated 😀
