### ISSUE TITLE
Unhelpful errors when Partners request fails

### ISSUE THREAD

**Issue by jacobsteves** [Shopify/shopify-cli#480]
# Issue summary

If something goes wrong in the Partners side, we print the response body. However, this body can be full of html so the user wont know what actually happened or how to fix it.

Im not sure if returning the response body is intentional right now, but I think a simple fix (and I dont mind putting up a PR if you agree) could be just changing the raised error message to send the response message rather than the body [in all our api errors here](https://github.com/Shopify/shopify-app-cli/blob/f7f77fc9b797b10aed7a5f1e6b4929906922951d/lib/shopify-cli/api.rb#L63). Ie, 

```ruby
raise APISomeError, "#{response.code}\n#{response.message}"
```

## Expected behavior

The user should see an error message or something to inform them on what to do.

## Actual behavior

We print the exception code + body. In my case, it filled my terminal scrollback buffer so I couldn't see what the error code was. 

![image](https://user-images.githubusercontent.com/28009669/77082768-f0124800-69d2-11ea-8cb0-fca02b7e95c0.png)

## Steps to reproduce the problem

1. Make Partners fail
    - In my case I had to sign out of my account and log back in to fix it, so maybe I was getting a 401?
    - But the same issue will occur if you raise an exception in partners during the GraphQL execution 
2. Run some command that sends a request to partners

## Specifications

- App type: Node
- Operating System: macOS Catalina 10.15.2
- Shell: zsh
- Ruby version (ruby -v): 2.6.3

**Comment by tanema** [comment]
Where is response.message coming from? I am happy with the change if you want to make it however I just worry about it hiding issues. On the other exceptions, the response is just a text message so it is easy to display, but clearly not all are. I am willing to try out your approach and see if it hides anything.

**Comment by jacobsteves** [comment]
Hmm okay looks like `response.message` wont work then. It just returns the text status of the error (ie 404 => Not found).

I just played around with the AdminAPI and PartnersAPI and found a few inconsistencies between the response body:

<details>
<summary>Hitting anything in Partners that returns a status other than 200</summary>
<br>
Ends up returning the HTML for the relevant error page. Ex: a 500 error will return the "something went wrong" html. Looks like it just doesn't support json error responses.
</details>

<details>
<summary>Hitting a 404 in the Admin API</summary>
<br>
<pre>
This command ran with ID: 81992
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	37: from shopify-app-cli/bin/shopify:36:in `<main>'
	36: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	35: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	34: from shopify-app-cli/bin/shopify:37:in `block in <main>'
	33: from shopify-app-cli/lib/shopify-cli/entry_point.rb:20:in `call'
	32: from shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	31: from shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	30: from shopify-app-cli/lib/shopify-cli/entry_point.rb:21:in `block in call'
	29: from shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	28: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	27: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	26: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	25: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	24: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	23: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	22: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	21: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	20: from shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	19: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	18: from shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	17: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	16: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	15: from shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	14: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:18:in `call'
	13: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:47:in `call'
	12: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:78:in `populate'
	11: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:78:in `times'
	10: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:79:in `block in populate'
	 9: from shopify-app-cli/lib/shopify-cli/commands/populate/resource.rb:105:in `run_mutation'
	 8: from shopify-app-cli/lib/shopify-cli/helpers/admin_api.rb:9:in `query'
	 7: from shopify-app-cli/lib/shopify-cli/helpers/admin_api.rb:17:in `authenticated_req'
	 6: from shopify-app-cli/lib/shopify-cli/helpers/admin_api.rb:10:in `block in query'
	 5: from shopify-app-cli/lib/shopify-cli/helpers/admin_api.rb:28:in `api_client'
	 4: from shopify-app-cli/lib/shopify-cli/helpers/admin_api.rb:40:in `fetch_api_version'
	 3: from shopify-app-cli/lib/shopify-cli/api.rb:28:in `query'
	 2: from shopify-app-cli/lib/shopify-cli/api.rb:75:in `request'
	 1: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
shopify-app-cli/lib/shopify-cli/api.rb:65:in `block in request': 404 (ShopifyCli::API::APIRequestNotFoundError)
{"errors":"Not Found"}
</pre>
</details>

<details>
<summary>Hitting Admin API locally when the server isn't running</summary>
<br>
<pre>
? What type of app project would you like to create? (You chose: node embedded app)
This command ran with ID: 30072
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	36: from shopify-app-cli/bin/shopify:36:in `<main>'
	35: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	34: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	33: from shopify-app-cli/bin/shopify:37:in `block in <main>'
	32: from shopify-app-cli/lib/shopify-cli/entry_point.rb:20:in `call'
	31: from shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	30: from shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	29: from shopify-app-cli/lib/shopify-cli/entry_point.rb:21:in `block in call'
	28: from shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	27: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	26: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	25: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	24: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	23: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	22: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	21: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	20: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	19: from shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	18: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	17: from shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	16: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	15: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	14: from shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	13: from shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	12: from shopify-app-cli/lib/shopify-cli/commands/create/app.rb:15:in `call'
	11: from shopify-app-cli/lib/shopify-cli/forms.rb:17:in `ask'
	10: from shopify-app-cli/lib/shopify-cli/forms/create_app.rb:14:in `ask'
	 9: from shopify-app-cli/lib/shopify-cli/forms/create_app.rb:51:in `ask_shop_domain'
	 8: from shopify-app-cli/lib/shopify-cli/forms/create_app.rb:42:in `organization'
	 7: from shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:14:in `fetch'
	 6: from shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
	 5: from shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:46:in `authenticated_req'
	 4: from shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
	 3: from shopify-app-cli/lib/shopify-cli/api.rb:28:in `query'
	 2: from shopify-app-cli/lib/shopify-cli/api.rb:75:in `request'
	 1: from shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
shopify-app-cli/lib/shopify-cli/api.rb:71:in `block in request': 502 (ShopifyCli::API::APIRequestServerError)
Nothing is running at port xxx on your host. For this to work, you need to check you're in the relevant project and start the corresponding server on macOS.
</pre>
</details>

So it seems like a bigger problem than I thought, but still low priority since these things shouldn't happen too often
