### ISSUE TITLE
Spin off a branch for Svelte/Sapper

### ISSUE THREAD

**Issue by lgs** [Shopify/shopify-cli#525]
# Issue summary

[Svelte](https://svelte.dev/) and [Sapper](https://sapper.svelte.dev/) are quickly growing ecosystem in reactive js field. 

It would be great having a branch for scaffolding 

> Node.js and Svelte

other then just 

> Node.js and React

> Ruby

**Comment by jerriclynsjohn** [comment]
I would absolutely love to contribute to this, let me know where we should start!
