### ISSUE TITLE
Shopify Serve fail - gettaddr: nodename nor servname provided

### ISSUE THREAD

**Issue by lemonadecreative** [Shopify/shopify-cli#532]
# Issue summary

Write a short description of the issue here ↓
Installed APP CLI and created project, all worked fine. Ran `shopify serve` to bring the app up, but failed with 

```
~/Sites/[app-name](master) » shopify serve
✓ ngrok tunnel running at https://789204.ngrok.io
✓ writing .env file...
✓ Whitelist URLS updated in Partners Dashboard
⭑ Press  Control-T to open this project in [storename].myshopify.com
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ => Booting Puma
┃ => Rails 5.2.4.2 application starting in development
┃ => Run `rails server -h` for more startup options
┃ Puma starting in single mode...
┃ * Version 3.12.4 (ruby 2.6.3-p62), codename: Llamas in Pajamas
┃ * Min threads: 5, max threads: 5
┃ * Environment: development
┃ Exiting
┃ /Users/[username]/.rvm/gems/ruby-2.6.3/gems/puma-3.12.4/lib/puma/binder.rb:273:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
┃ 	from /Users/[username]]/.rvm/gems/ruby-2.6.3/gems/puma-3.12.4/lib/puma/binder.rb:273:in `new'

```

## Expected behavior

What do you think should happen?
The app should run and I should be able to view the app in the Shopify store admin. 

## Actual behavior

What actually happens?
Running the `shopify serve` command fails. When visiting the app in the store I selected to install it, the page displays an Ngrok error stating it failed to complete tunnel connection.

![image](https://user-images.githubusercontent.com/20567992/79927182-90112600-8404-11ea-8b42-24f457d5e1ce.png)

## Steps to reproduce the problem

1. Install shopify app cli
2. Create new app using `shopify create rails [app name]`
3. Run `shopify serve`

## Specifications

- App type: Rails
- Operating System: Mac OSX 10.15.4
- Shell: iTerm with zsh (ohmyzsh)
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

**Comment by tanema** [comment]
This looks like a configuration issue with your puma setup.
