### ISSUE TITLE
Show current context with command not found error

### ISSUE THREAD

**Issue by attaboy** [Shopify/shopify-cli#585]
# Issue summary

Building on #565, the CLI should remind the user what context/project they're in (or if they're not in one) if they try to run a command that isn't found.

For example, if you type `shopify serve`:

Current experience:
```console
$ shopify serve
┏━━ Command not found ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify serve was not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Suggested experience outside of a project:
```console
$ shopify serve
┏━━ Command not found ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify serve was not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

No project found. Type shopify help to see available core commands.
```

Suggested experience inside a project (if serve isn't a valid command):
```console
$ shopify serve
┏━━ Command not found ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ shopify serve was not found
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Project: my-shopify-cli-app (Ruby on Rails App)
Type shopify help to see available commands for Ruby on Rails App projects.
```

/cc @gfscott @andyw8

**Comment by andyw8** [comment]
👍 

Should `shopify help` be in quotes, or maybe a different colour?

**Comment by attaboy** [comment]
Yes, I would follow the same patterns we have elsewhere, where command text is shown in cyan.

**Comment by gfscott** [comment]
This is a good opportunity to start building consistency in the verb we use to direct people to run commands. Today I see three words in use:

- **Use**: `Use shopify help to display detailed information...`
- **Type**: `Type shopify help to see available commands...`
- **Run**: Arg I can't find my example right now, but I _swear_ I've seen it

I very slightly prefer the more action-oriented `use` or `run`; to me, `type` feels like a more passive action.

But whatever we choose, it would be great to standardize and always use consistently!
