### ISSUE TITLE
Convert command names to lowercase before being added to CommandRegistry

### ISSUE THREAD

**Issue by mkevinosullivan** [Shopify/shopify-cli#600]
# Issue summary

Currently, there is nothing preventing the CLI being extended with two commands with the same name if they only differ by case, e.g., `logout` and `Logout` would be treated as separate commands.

## Expected behavior

All commands should be one case (preferably lowercase) and any command name should be converted to lowercase before being added to the Registry.

## Actual behavior

Currently, there is no such case conversion during command registration.

**Comment by andyw8** [comment]
Should this a issue for cli-kit?

I think it would just mean changing

https://github.com/Shopify/cli-kit/blob/0122d37670088bd0fa995a59630e6e3a0717cb47/lib/cli/kit/command_registry.rb#L35-L37

to

`commands[name.downcase] = const`

**Comment by tanema** [comment]
We now register our commands in a central place, I want to touch cli-kit and cli-ui as little as possible
