### ISSUE TITLE
Expand Connect command to each project type

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify-cli#614]
# Issue summary
Currently the connect command is only useful for rails and node apps to re-hydrate the .env file however there are a couple of problems with this. Other project types do not follow this convention so in some cases they do not persist an API or even need a .env file. The other being that this only works for projects with a `.shopify-cli.yml` file

What we need to do is change the connect command to follow similar patterns as the create command. This means that we need to
- Prompt for app type or accept the app type from a list of available app types. Hidden project types can be called as subcommands
- Call the subcommand connects

## Things to be considered
Can we re-use connect functionality? For instance, on create could we call connect first and then create for the project types?

**Comment by ErinRenNumber1** [comment]
Just a few questions.  Are you suggesting this `connect` command becomes another command to exist in the root directory?  So, `shopify connect --app_type=script` for example?  

My 2 cents, and as always feel free to ignore.  I think we need this `connect` functionality in Scripts project as well to `deploy` to a particular app for example.  The way Tyler explained to me was that `connect` was a convenience command, which you can call it explicitly or being called by other commands implicitly when app information needs to be prompt.  I always thought this `connect` functionality was something other projects would all benefit from.  For now, we implemented our own `connect` to an app or a dev store, but this functionality can be abstracted and shared.
