### ISSUE TITLE
run_cmd test helper issues external HTTP request

### ISSUE THREAD

**Issue by NatMorcos** [Shopify/shopify-cli#696]
# Issue summary

Write a short description of the issue here ↓
When using the `run_cmd` to test `build` or `serve` commands within the extension project, we see CI failing because it tried to make external HTTP requests.

## Expected behavior

No external HTTP requests are issues. Test helpers run smoothly in CI.

## Actual behavior

Please see the first build failure here:
https://travis-ci.com/github/Shopify/shopify-app-cli/jobs/351508394

Notably,  this only happens _most of the times. It's reproducible but somehow this build, which was running on the same changes, passed:
https://github.com/Shopify/shopify-app-cli/pull/695/checks?check_run_id=788811992

## Steps to reproduce the problem

see: https://github.com/Shopify/shopify-app-cli/pull/695

## Specifications
reproducible on ruby 2.5.1 (unreliably)

eg.  2.5.1 locally:

![image](https://user-images.githubusercontent.com/3375286/85161020-30c96980-b22d-11ea-9a37-48a3aff82e89.png)

it also passes from time to time

**Comment by tanema** [comment]
Again this might be because your project type not be properly loaded. This request is expected in the other project types in the serve commands but not yours so you may accidentally be calling the wrong serve command. I suggest calling your command class directly.

**Comment by NatMorcos** [comment]
cc. @fredriculrich
