### ISSUE TITLE
run_cmd test helper failing for hidden command

### ISSUE THREAD

**Issue by NatMorcos** [Shopify/shopify-cli#697]
# Issue summary

In the extension project, we have a hidden command:
https://github.com/Shopify/shopify-app-cli/blob/master/lib/project_types/extension/commands/build.rb#L7

The `run_cmd` test helper cannot find the hidden command (sometimes)

## Expected behavior

The hidden command should be executable from within the extension context. 
eg: 
![image](https://user-images.githubusercontent.com/3375286/85161778-4ab77c00-b22e-11ea-9399-a67fd7eef616.png)
- first call here is from outside the extension project context
- second call is from within the extension project context

## Actual behavior
- The run_cmd helper cannot find the command even when it is issued from within the project namespace. The run then Silently aborts
- the test failure is outputted in the test run, where we would normally expect an `F`, not an error message. The error message is missing from the actual test failure

![image](https://user-images.githubusercontent.com/3375286/85161952-85b9af80-b22e-11ea-9b4e-6c91e61eaed4.png)

![image](https://user-images.githubusercontent.com/3375286/85161976-90744480-b22e-11ea-9032-5779988d8352.png)

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem
Please see https://github.com/Shopify/shopify-app-cli/pull/695

## Specifications

reproducible sometimes locally on ruby 2.5.1
similarly on CI: https://travis-ci.com/github/Shopify/shopify-app-cli/jobs/351508394

Note that it passes _sometimes_

**Comment by tanema** [comment]
You most likely need to load your project type, this is very unlikely an issue with `run_cmd` Try calling the command by the class name and see what happens. I would recommend moving toward using the class name instead at this point anyways.

**Comment by NatMorcos** [comment]
cc. @fredriculrich

**Comment by fredriculrich** [comment]
> You most likely need to load your project type
This was my first suspect too but we checked and were indeed loading type within the `setup` step of our test.

> I  would recommend moving toward using the class name instead at this point anyways.
I was pretty sure this was the recommendation at this point too so this is the route we took to get the tests passing. I think most of our command tests are now setting the `context` and running the command directly.
