### ISSUE TITLE
shopify help shows connect even when unavailable

### ISSUE THREAD

**Issue by NatMorcos** [Shopify/shopify-cli#701]
# Issue summary

the shopify connect command is not implemented in the extensions project yet `shopify help` from within the project context shows it anyway

## Expected behavior

the connect command should not show in the help output for a project type where it is not defined

## Actual behavior
it shows
![image](https://user-images.githubusercontent.com/3375286/85182632-405da800-b257-11ea-8715-e5e00d0a0819.png)

## Steps to reproduce the problem

1. `shopify create extension` choose any option
1. `cd` into newly created directory
1. `shopify help`

**Comment by tanema** [comment]
Connect is a global command and is very similar to create. It would not need to be implemented by you

**Comment by NatMorcos** [comment]
@tanema  We understand that the reason it shows up is because right now, it's a global command. However I'm not sure it makes sense as a global command, because what connect does doesn't work for all project types. It would need a project type specific implementation in order to make sense for us.

Should we make it a non-global command, or make it a required command for each project type to implement? I see your edit and it sounds like we're maybe saying the same thing. It sounds like it doesn't make sense as a global command right now?

**Comment by tanema** [comment]
The current implementation is not idea for every project type right now correct, we will however be changing to allow for every project to implement their own
