### ISSUE TITLE
Shopify serve command failing/stopping with no error.

### ISSUE THREAD

**Issue by SirCameron** [Shopify/shopify-cli#785]
# Issue summary

the shopify serve command is failing. ngrok tunnel is created, but whatever is in the receiving end at port 8081 is dead.
Out put is simply:
```
✓ ngrok tunnel running at https://93fe383ffe7c.ngrok.io
✓ .env saved to project root
? Do you want to update your application url? (You chose: yes)
✓ Whitelist URLS updated in Partners Dashboard
⭑ Press  Control-T to open this project in sircameron-test.myshopify.com
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.27s) ━━
```

So, the running server part simply ends with no output.
I've tried to see if there is something blocking on port 8081, but there isn't. I've tried using a different port, but that's not possible (and would be a nice addition).

## Expected behavior

Shopify serve serves the app correctly, as expected.

## Actual behavior

What actually happens?

No error message, serve simply stops. 
Visiting the ngrok url, this is the result:
![Screenshot 2020-07-28 at 15 42 05](https://user-images.githubusercontent.com/74608/88673493-f8009800-d0e8-11ea-910a-033c40c21614.png)

## Steps to reproduce the problem

1. run: shopify serve
2. see process end.

## Specifications

- App type: node
- Operating System: mac os
- Shell: iTerm
- Ruby version (ruby -v): 2.6.3p62

**Comment by mkevinosullivan** [comment]
Hi, can you run `shopify system all` from inside the app directory, please, and share the results here (it displays a variety of system/configuration/environment information to aid debugging).

Also, is this a newly created node app or a node app that's been around for a while, that is, it existed before the recent shopify-app-cli upgrade?

Regards,
Kevin.

**Comment by SirCameron** [comment]
hi @mkevinosullivan 

I tried with both: one older app and one newly created app. Neither work.

```
Environment
  TERM              = xterm-256color
  SHELL             = /bin/zsh
  PATH              = /anaconda3/bin:/usr/local/sbin:/Developer/NVIDIA/CUDA-9.2/bin:/usr/local/miniconda3/bin:/Developer/NVIDIA/CUDA-10.2/bin:/usr/local/sbin:/Developer/NVIDIA/CUDA-9.2/bin:/usr/local/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/sircameron/Library/Android/sdk/tools:/Users/sircameron/Library/Android/sdk/tools/bin:/Users/sircameron/Library/Android/sdk/platform-tools:/Users/sircameron/development/flutter/bin:/usr/local/opt/dart/libexec:/Users/sircameron/Library/Android/sdk/tools:/Users/sircameron/Library/Android/sdk/tools/bin:/Users/sircameron/Library/Android/sdk/platform-tools:/Users/sircameron/development/flutter/bin:/usr/local/opt/dart/libexec:/Users/sircameron/.golang/bin

Shopify App CLI
               ROOT = /usr/local/Cellar/shopify-cli/1.0.2/src
  PROJECT_TYPES_DIR = /usr/local/Cellar/shopify-cli/1.0.2/src/lib/project_types
           TEMP_DIR = /usr/local/Cellar/shopify-cli/1.0.2/src/.tmp
          CACHE_DIR = /Users/sircameron/.cache/shopify
   TOOL_CONFIG_PATH = /Users/sircameron/.config/shopify
           LOG_FILE = /Users/sircameron/.config/shopify/logs/log.log
     DEBUG_LOG_FILE = /Users/sircameron/.config/shopify/logs/debug.log

Ruby (via RbConfig)
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  x86_64-apple-darwin19     - RbConfig["host"]
  ruby-2.6.0                - RbConfig["RUBY_VERSION_NAME"]

Commands
  ✓ git, /usr/local/bin/git
  ✓ curl, /usr/bin/curl
  ✓ tar, /usr/bin/tar
  ✓ unzip, /usr/bin/unzip

In a Node.js project directory
  ✓ npm, /usr/local/bin/npm, version 6.14.7
  ✓ node, /usr/local/bin/node, version 14.6.0
  ✓ yarn, /usr/local/bin/yarn, version 1.22.4
  ✓ ngrok, /Users/sircameron/.cache/shopify/ngrok

  Project environment
  SHOPIFY_API_KEY    = ********
  SHOPIFY_API_SECRET = ********
  SHOP               = sircameron-test.myshopify.com
  SCOPES             = write_products,write_customers,write_draft_orders
  HOST               = https://afe2a02f325e.ngrok.io
```

**Comment by tanema** [comment]
What is the ouput if you simply run `npm run dev` in your project directory?

**Comment by SirCameron** [comment]
we're using yarn... running yarn dev has the correct result of compiling and creating the dev server.
If I run ngrok and yarn dev separately, I can continue dev.
Is there a verbose option on the shopify cli to see possible errors?

**Comment by tanema** [comment]
Not currently, usually if there is an error that would end a server like this, it is outputted. The strange thing about this is that there is no error, it just ends. 

We will have to try it ourselves and make sure to force it to use yarn, maybe there is something wrong with the yarn functionality.
