### ISSUE TITLE
Development Environment issue

### ISSUE THREAD

**Issue by tejasamandaliya** [Shopify/shopify-cli#878]
# Issue summary
 [ event ] build page: /
┃ [ wait ]  compiling ...
┃ Hello World--------
┃ [ event ] disposing inactive page(s): /
┃ [ event ] build page: /
┃ [ wait ]  compiling ...
┃ Hello World--------
┃ [ wait ]  compiling ...
┃ [ wait ]  compiling ...
┃ Hello World--------  [Function: Date]
┃ emptyState--- true
┃ [ wait ]  compiling ...
┃ [ wait ]  compiling ...
┃ [ wait ]  compiling ...
┃ [ wait ]  compiling ...
┃ [ wait ]  compiling ...
┃ Hello World--------  1600327359963
┃ [ wait ]  compiling ...
┃ Hello World--------  2020-09-17T07:24:34.656Z
┃ Hello World--------  2020-09-17T07:24:42.725Z
┃ [ wait ]  compiling ... **Some change in code**
┃ [ wait ]  compiling ... **Some change in code**
**Wait for 5-10 min it's still showing compiling...**

![Screenshot 2020-09-17 at 12 57 46 PM](https://user-images.githubusercontent.com/26873822/93434162-67268b80-f8e5-11ea-8f3a-971531348bf5.png)

Write a short description of the issue here ↓
When I try to change anything in the codebase taking too much time to compile code.
during compilation, it shows errors in console **attached screenshot **

<img width="690" alt="Screenshot 2020-09-17 at 12 45 24 PM" src="https://user-images.githubusercontent.com/26873822/93432818-ab189100-f8e3-11ea-9d08-aeedde4004bd.png">

## Expected behavior
Without the Shopify app cli it takes normally 2-3 second to **compile and hot reload** 
it should show an error if any.

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. start the application using `Shopify serve`
2. Change anything in code  
3. wait for compilation on console

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Node React
- Operating System: macOS Catalina(version 10.15.5)

**Comment by l-portet** [comment]
Just got the same issue without doing anything special, now I can't use my app in dev mode anymore.
@tejasamandaliya Did you find a solution?
