### ISSUE TITLE
SHOPIFY CLI issue: ngrok gateway error 

### ISSUE THREAD

**Issue by bilal7446** [Shopify/shopify-cli#890]
i created an application for first time using Shopify cli in windows and everything worked fine at first. application was installed and worked as well. but on second day when i tried to start app using Shopify serve command and when i open app in a store it shows message of "ngrok gateway error" . i even tried creating new app through Shopify cli and after installation on store when i open, its showing same error. i cannot seem to be able to figure out what is the issue. everything worked fine at first but now its not working even if i create a fresh new node app.

**Comment by paulomarg** [comment]
Hi @bilal7446, can you please provide a bit more detail on the error message you're seeing? Either a screenshot or the exact text of the error would be really helpful!

One possible cause that comes to mind is that ngrok could be returning an HTTP `502 Bad Gateway` error, which would indicate that your app is failing when handling the request. If that is the case, you should check your app logs to see what the error is.

**Comment by bilal7446** [comment]
i cannot understand  the issue. everything was working fine at first and than i started to have that issue.this is screenshot
![er](https://user-images.githubusercontent.com/50451073/94676295-8afdbe80-0334-11eb-8915-bd360d37f37a.png)

and these are i guess errors that appear in cli
 [nodemon] starting `node ./server/index.js`
┃ > Ready on http://localhost:8081
┃ [ event ] build page: /
┃ [ wait ]  compiling ...
┃ [ event ] disposing inactive page(s): /
┃ (node:11376) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'B:\nod2\rm\.next\static\development\pages\index.js'
┃     at Object.realpathSync (fs.js:1621:7)
┃     at deleteCache (B:\nod2\rm\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:6:35)
┃     at B:\nod2\rm\node_modules\next\dist\build\webpack\plugins\nextjs-require-cache-hot-reloader.js:30:25
┃     at _next0 (eval at create (B:\nod2\rm\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
┃     at eval (eval at create (B:\nod2\rm\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
┃     at B:\nod2\rm\node_modules\next\dist\build\webpack\plugins\unlink-removed-pages-plugin.js:32:29
┃ (node:11376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
┃ (node:11376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
┃ [ event ] client pings, but there's no entry for page: /
┃ [ event ] build page: /
┃ [ event ] build page: /

**Comment by paulomarg** [comment]
Thanks for the information, it helps a lot. We will look into this!

**Comment by paulomarg** [comment]
Actually, looking at the error message a bit more deeply, it doesn't seem to be related to our code. It seems you're getting a permission error when accessing your `index.js` file.

Could you please confirm that this still fails if you run your terminal as administrator and then try to run the app?

**Comment by bilal7446** [comment]
@paulomarg

**Comment by bilal7446** [comment]
@paulomarg 
Yes the problem still exists even in terminal running as  administrator 
![image](https://user-images.githubusercontent.com/50451073/94714224-49393c00-0365-11eb-8e4a-00bac3e28262.png)

i didnot knew it was related accessing index.js file
i will also try to look into it from my end
thnx

**Comment by MarcelJurtz** [comment]
Any Update on this? I have the same problem after following [this tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify). The connection seems to be established tough, since ngrok logs the requests with a 502. Tried running server and app as sudo too, same result.
