### ISSUE TITLE
Add ngrok troubleshooting docs page

### ISSUE THREAD

**Issue by paulomarg** [Shopify/shopify-cli#896]
We've been receiving a fair amount of issues on ngrok set up and execution, and they are usually related to file permissions or `sudo`.

We should provide a list of steps for developers to run if they have problems to rule out the most common issues without needing maintainer support.

This would also serve as a reference checklist for issues that do arise, which would make it easier to surface actual needs and bugs in the code.

**Comment by andyw8** [comment]
(perhaps as a follow-up piece of work, the CLI could 'self-diagnose' some common issues).

**Comment by Roaldkamman** [comment]
Yes please, I'm currently having issues with ngrok. full issue here: https://community.shopify.com/c/Shopify-APIs-SDKs/Tunnel-bf256c0ea7e2-ngrok-io-not-found/m-p/922663#M57741
