### ISSUE TITLE
`spawn': No such file or directory - git (Shopify App / Win 10 / Ruby / RubyGems / Rails)

### ISSUE THREAD

**Issue by kkMatt** [Shopify/shopify-cli#981]
# Issue summary

Write a short description of the issue here ↓

I followed all official Shopify manuals for RubyInstall, RubyGems for Windows 10 and install for Rails. And I got error that is not described in the official manual

## Expected behavior

App should have been installed.

## Actual behavior

What actually happens?
```
PS C:\rubygems> shopify create rails
? App name
> ewp1
? What type of app are you building? (You chose: Custom: An app custom built for a single client.)
i Authentication required. Login to the URL below with your Shopify Partners account credentials to continue.
Please open this URL in your browser:
https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=*****&response_type=code&code_challenge=****&code_challenge_method=S256
This command ran with ID: 31084
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        47: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:32:in `<main>'
        46: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        45: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        44: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/bin/shopify:33:in `block in <main>'
        43: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:42:in `call'
        42: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/monorail.rb:20:in `log'
        41: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/core/executor.rb:15:in `call'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/commands/create.rb:8:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/command.rb:19:in `call'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/sub_command.rb:12:in `call'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/rails/commands/create.rb:27:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/form.rb:13:in `ask'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/project_types/rails/forms/create.rb:25:in `ask'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/task.rb:7:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:11:in `call'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:38:in `get_organization'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/tasks/select_org_and_shop.rb:27:in `organizations'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:48:in `query'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/partners_api.rb:49:in `block in query'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/api.rb:29:in `query'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/api.rb:93:in `default_headers'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/api.rb:88:in `current_sha'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/git.rb:24:in `sha'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/git.rb:112:in `exec'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/lib/shopify-cli/context.rb:400:in `capture3'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.4.1/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)
PS C:\rubygems> 09
```

## Steps to reproduce the problem

1. Follow official Shopify manuals for RubyInstall, RubyGems for Windows 10 and install for Rails

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: rails custom app
- Operating System: Win 10 x64
- Shell: Powershell
- Ruby version (ruby -v): 2.7.0

**Comment by paulomarg** [comment]
Hey @KestutisIT, thanks for reporting this!

I believe this error is being triggered because you don't have git installed on your machine, or it cannot be run by the current user by running `git` on your terminal. Could you please make sure you have git installed and executable, and retry?

Please let us know if that solves the problem, but in any case the CLI should detect this and return a proper error message instead of throwing an error.

**Comment by SongofDiomede** [comment]
Same issue here while trying to install it for Node.js, with almost the exact same error report.
I tried @paulomarg solution, which worked. THANK YOU

**Comment by jfroome** [comment]
Same problem here.  Windows 10, trying to create a node app. Git and node are both installed and executable from command line and still not working.

**Comment by Sdrapak** [comment]
THIS! Thank you for pointing out Git is required.  In hindsight it's somewhat obvious but no one mentions it in the Shopify videos.
Also you need to update your path to point to: C:\Program Files\Git\bin\git.exe

**Comment by amitpatil321** [comment]
I am still getting this error, Already tried uninstalling git twice and also set path variable

> D:\Projects\shopify>shopify create
? What type of project would you like to create? (Navigate up with 'k' and down with 'j', press Enter to select, filter
? What type of project would you like to create? (You chose: Node.js App)
? App name
> banner
? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
This command ran with ID: 14721
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        51: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:32:in `<main>'
        50: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        49: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        48: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/bin/shopify:33:in `block in <main>'
        47: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        46: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        45: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        44: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/core/executor.rb:15:in `call'
        43: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        42: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        41: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        40: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        39: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        38: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        37: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        36: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        35: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        34: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        33: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        32: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        31: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        30: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/commands/create.rb:8:in `call'
        29: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/command.rb:25:in `call'
        28: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/commands/create.rb:25:in `call'
        27: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/sub_command.rb:12:in `call'
        26: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/commands/create.rb:18:in `call'
        25: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/form.rb:13:in `ask'
        24: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/project_types/node/forms/create.rb:13:in `ask'
        23: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/task.rb:7:in `call'
        22: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:14:in `call'
        21: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:42:in `get_organization'
        20: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/tasks/select_org_and_shop.rb:31:in `organizations'
        19: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api/organizations.rb:6:in `fetch_all'
        18: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:48:in `query'
        17: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:63:in `authenticated_req'
        16: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
        15: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:26:in `query'
        14: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:69:in `request'
        13: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        12: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:46:in `block in request'
        11: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:96:in `default_headers'
        10: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/api.rb:91:in `current_sha'
         9: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:24:in `sha'
         8: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:118:in `rev_parse'
         7: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/git.rb:112:in `exec'
         6: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/lib/shopify-cli/context.rb:404:in `capture3'
         5: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:90:in `capture3'
         4: from E:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.8.0/vendor/deps/cli-kit/lib/cli/kit/system.rb:194:in `delegate_open3'
         3: from E:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from E:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from E:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
E:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - git (Errno::ENOENT)

**Comment by Siddharth712** [comment]
Hello. I installed all these stuffs, still I m getting same issues in my machine

**Comment by MBWJoel** [comment]
sdrapak says "THIS! Thank you for pointing out Git is required. In hindsight it's somewhat obvious but no one mentions it in the Shopify videos.
Also you need to update your path to point to: C:\Program Files\Git\bin\git.exe"

Where do we update this path?
